### ISSUE TITLE
Disable directory bolding/truncation

### ISSUE THREAD

**Issue by awgymer** [romkatv/powerlevel10k#1007]
Is there any way to disable the bolding/highlighting and shortening that gets applied to the current working directory?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find parameters that control the appearance of `dir` segment: https://github.com/romkatv/powerlevel10k/blob/54d40b924c491a6510c44391dccac05fe78a7310/config/p10k-lean.zsh#L199-L324

- To disable bolding of "anchor" directories, change the value of `POWERLEVEL9K_DIR_ANCHOR_BOLD` from `true` to `false`.
- To disable special coloring of "anchor" directories, set `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND` to the same value as `POWERLEVEL9K_DIR_FOREGROUND`.
- To disable special coloring of shortened directories, set `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND` to the same value as `POWERLEVEL9K_DIR_FOREGROUND`.

You can disable shortening by removing `POWERLEVEL9K_SHORTEN_DIR_LENGTH` and `POWERLEVEL9K_SHORTEN_STRATEGY`. I wouldn't recommend it. Instead, you can set `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0`, `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0` and `POWERLEVEL9K_DIR_MAX_LENGTH=""` (empty string). This will shorten current working directory only if otherwise it would overlap right prompt or overflow to the next line. Overlapping or overflowing prompt is almost always worse than a shortened directory. Also note that shortening is lossless -- each directory is shortened to a unique prefix.

**Comment by awgymer** [comment]
Hmm. Ok thanks I'll take that recommendation. I'm only using a left-prompt so I assumed overflow wouldn't be too bad. I also couldn't find a way to disable the icons for dirs. For some other things like time I just set the custom icon equal to `""`, which I assume is the correct method?

**Comment by romkatv** [comment]
> I'm only using a left-prompt so I assumed overflow wouldn't be too bad.

It's almost always worse than shortening the current directory.

> I also couldn't find a way to disable the icons for dirs.

The easiest way is to run `p10k configure` and select "Few Icons" instead of "Many Icons". The extra icons you get with "Many Icons" are primarily decorative. They convey very little information.

You can also manually disable dir icons by uncommenting this line in `~/.p10k.zsh`:

```zsh
# typeset -g POWERLEVEL9K_DIR_CLASSES=()
```

**Comment by awgymer** [comment]
Ok thanks! Is there documentation for the difference between few and many options?

**Comment by romkatv** [comment]
There is no documentation for it. However, what I wrote above is true. "Many Icons" adds decorative icons. Informative icons (e.g., an icon to let you know you have background jobs) are displayed either way.

**Comment by awgymer** [comment]
Ok. I'm going to stick with selectively disabling them as I quite like a few of the decorative ones (python/git etc). Thanks.

**Comment by romkatv** [comment]
> Ok. I'm going to stick with selectively disabling them as I quite like a few of the decorative ones (python/git etc).

Python is displayed either way because otherwise it may not be obvious what the following text means. Git icons are indeed displayed only with the "Many Icons" option. No one so far has been confused by what "master" means even if there is no icon next to it.

**Comment by awgymer** [comment]
Ha. I have `time > dir > variable segments` and I find a symbol helps me more quickly locate the variable bit I'm looking for sometimes.
