### ISSUE TITLE
Font rendering bug (top cut off)

### ISSUE THREAD

**Issue by JPUnD** [romkatv/powerlevel10k#101]
**Describe the bug**
With the oh my zsh update today (3-7) the powerlevel10k running the latest build on Manjaro linux has its "top cut out".
If i change shell to bash, by typing bash in termite, that isn't themed, the prompt acts as expected.

**Screenshots**
[Picture of my terminal here](https://imgur.com/3JHTOTR)

**System:**
 OS: Manjaro
 Zsh version: Latest
 Terminal emulator: Termite

I updated my system right after i updated oh my zsh, that's when i noticed this behaviour.

**Comment by romkatv** [comment]
Here's how Powerlevel10k and every other powerline-inspired theme renders its prompt. Try copy-pasting this code block into your ZSH:

```zsh
{
  space=' '
  triangle=$'\uE0B0'
  blue_space="%K{blue}$space%k"
  blue_triangle="%F{blue}$triangle%f"

  print -P "triangle      $triangle"
  print -P "blue_space    $blue_space"
  print -P "blue_triangle $blue_triangle"
  print -P "powerline     $blue_space$blue_triangle"
}
```

Different fonts have slightly different glyphs for `U+E0B0`, different line spacing and so on. Thus, the output may look better or worst depending on the font your terminal uses. If the powerline doesn't look to your satisfaction, you have several options.

1. Try a different font, different terminal or tweak your terminal settings.
2. Override `POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR` to use some other symbol instead of the default triangle (`$'\uE0B0'`).
3. Live with the imperfect powerline rendering.
4. Use a different -- non-powerline -- prompt style.

The last option is my personal choice. Powerline-styled prompt requires a lot of time spent on fine-tuning what in the end is a prompt designed for posting screenshots to [/r/unixporn](https://www.reddit.com/r/unixporn/) rather than getting things done. For a practical alternative, try [Pure Power](https://github.com/romkatv/dotfiles-public/blob/master/.purepower). It'll give you a fast and functional prompt that works with any font. To install, remove all `POWERLEVEL9K` options from your `~/.zshrc` and type this:

```zsh
curl -fsSL -o ~/.purepower https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower
echo 'source ~/.purepower' >>! ~/.zshrc
```

To customize your prompt, edit `~/.purepower`.

Closing the issues as it's a problem with the combination of font × terminal × terminal settings. Choose your poison among the options 1-4 listed above.
