### ISSUE TITLE
(END) after some commands

### ISSUE THREAD

**Issue by erdincozden** [romkatv/powerlevel10k#1016]
<img width="1410" alt="Screen Shot 2020-09-18 at 21 59 38" src="https://user-images.githubusercontent.com/6343486/93635039-41d77180-f9fa-11ea-9a32-4a92801e2f56.png">

Hi Team,
This page opens after some commands. how can i prevent it?
Thanks

**Comment by romkatv** [comment]
This looks like pager to me. It has nothing to do with powerlevel10k.

**Comment by erdincozden** [comment]
@romkatv  It was not like  powerlevel9k version. I wanted to ask if maybe it was about settings.

**Comment by romkatv** [comment]
I’m positive this is not caused by powerlevel10k.

**Comment by ZekeLu** [comment]
This is the output of a pager. I have seen the same behavior before, and have configured the pager to avoid this.

According to the [AWS CLI doc](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside):

> AWS CLI version 2 provides the use of a client-side pager program for output. By default, this feature returns all output through your operating system’s default pager program.

And it states that on Linux and macOS:

> If you do not specify otherwise, the pager AWS CLI version 2 uses by default is `less`. If you don't have the `LESS` environment variable set, the AWS CLI version 2 uses the `FRX` flags.

According to the [less doc](http://manpages.org/less/1#options):

> -F or --quit-if-one-screen
    Causes less to automatically exit if the entire file can be displayed on the first screen.
> -R or --RAW-CONTROL-CHARS
>    Like -r, but tries to keep track of the screen appearance where possible.
> -X or --no-init
>    Disables sending the termcap initialization and deinitialization strings to the terminal. This is sometimes desirable if the deinitialization string does something unnecessary, like clearing the screen.

Maybe the `LESS` environment variable is set somewhere. For example, [oh-my-zsh executes less with -R flag](https://stackoverflow.com/a/49267711/1369400).
You can unset `LESS` to fallback to the default behavior or set a new value to specify your expected behavior:

```sh
# unset the environment variable
unset LESS
# or overwrite it
export LESS='-FRX'
```

**Comment by erdincozden** [comment]
Thank you @ZekeLu . It works!
