### ISSUE TITLE
Ligatures not showing on MacOS 11 BigSur beta/iTerm2

### ISSUE THREAD

**Issue by bamapookie** [romkatv/powerlevel10k#1037]
Had to manually enable ligatures in the iTerm2 preferences after installing the font.  Custom icons would not show otherwise.

**Comment by romkatv** [comment]
Please clarify what you do, what happens when you do it, and what you expect to happen.

**Comment by bamapookie** [comment]
I installed the font using the configure script, but it would not show the special characters, like the diamond and lock.  I went through the readme, and it mentioned setting the font in iTerm2's preferences.  The font was already set correctly, but the use ligatures box was not checked.  I checked the box and restarted iTerm2.  I then went back through the configure script and the special characters worked.

<img width="989" alt="Screen Shot 2020-10-04 at 11 27 41 AM" src="https://user-images.githubusercontent.com/1924926/95019667-b2a29e80-0634-11eb-98c6-c677d0d06b3c.png">

**Comment by bamapookie** [comment]
macOS Big Sur Version 11.0 Beta (20A5384c)
iTerm2 Build 3.3.12

**Comment by romkatv** [comment]
These symbols are not ligatures. In addition, this font doesn't have any ligatures, so this checkbox has no effect.

Here's what I think happened. Please let me know if this matches your recollection.

When the configuration wizard ran for the first time, it asked you whether to install the recommended font. You agreed (good choice). After installing the font, wizard presented you with this screen:

![image](https://user-images.githubusercontent.com/1282067/73163916-2f1dce80-40f1-11ea-8d32-0b01219bd302.png)

There is no way to exit this screen other than by pressing `Y`. If you press any other key, it'll say "It's important to restart iTerm2 for the changes to take effect" and ask for confirmation once again.

![image](https://user-images.githubusercontent.com/1282067/73163967-46f55280-40f1-11ea-8f03-2e4aafeff4ba.png)

In the past, the wizard would simply print "Please restart iTerm2 for the changes to take effect" and exit, but so many users were missing this message that I added essentially a non-dismissible modal dialog. This has cut down on the number of issues similar to this by a lot. If you exit this dialog and then run `p10k configure` *without restarting iTerm2*, the wizard will not offer to install the font because it will see that the font is already installed. However, iTerm2 is still using the old font, so you won't see custom glyphs such as the diamond, the lock, etc. Once you tell the wizard that glyphs don't render properly, it won't offer prompt styles that use them. If it did, you would end up with broken prompt.

If you open iTerm2 preferences and change anything, it'll have the same effect as restarting iTerm2. That is, iTerm2 will start using the new font.

Does this sound like what happened?

**Comment by bamapookie** [comment]
I don't think so.  I used it in the state without icons for a few days.  I did restart iTerm2 at least twice in that time. (One time rebooting to install an OS update.). It is possible that I may have exited iTerm2 without properly exiting the shell.  Maybe that did it?

**Comment by bamapookie** [comment]
I tried disabling the ligatures checkbox and rerunning the configure script.  It does still show the diamond.
Restarted iTerm2 and reran configure script.  Still shows the diamond.  Maybe I didn't exit properly.

**Comment by bamapookie** [comment]
Thanks for your help, and great plugin!
