### ISSUE TITLE
Instant prompt warning still shows up with POWERLEVEL9K_INSTANT_PROMPT=quiet

### ISSUE THREAD

**Issue by scalp42** [romkatv/powerlevel10k#1048]
Hi @romkatv 

Thank you for the wonderful project.

I've set the variable to quiet the instant prompt warning but it's still showing up:

```
03:24:27 🔥  ~
❯ typeset POWERLEVEL9K_INSTANT_PROMPT
POWERLEVEL9K_INSTANT_PROMPT=quiet
03:24:27 🔥  ~
❯ echo $POWERLEVEL9K_INSTANT_PROMPT
quiet
```

<details>
  <summary markdown="span">Full output</summary>

```
Last login: Thu Oct  8 03:24:21 on ttys000
anthowo%
[ERROR]: When using instant prompt, Powerlevel10k must be loaded before the first prompt.

You can:

  - Recommended: Change the way Powerlevel10k is loaded from ~/.zshrc.
    See https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation.

    * You will not see this error message again.
    * Zsh will start quickly.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start slowly.

03:24:24 🔥  ~
❯ typeset POWERLEVEL9K_INSTANT_PROMPT
POWERLEVEL9K_INSTANT_PROMPT=quiet
03:24:27 🔥  ~
❯ echo $POWERLEVEL9K_INSTANT_PROMPT
quiet
03:25:22 🔥  ~
❯
```

</details>

Any ideas?

Thanks in advance 🙏

**Comment by romkatv** [comment]
Please read the error message you've posted and do what it suggests.

**Comment by scalp42** [comment]
I got the part that you can turn off the instant prompt but I was wondering if there was a way to just turn off this message all together?

It's already loaded at the top, I'm just trying to figure how to make it work with `zinit`.

This will work fine:

```
zinit ice depth=1;
zinit light romkatv/powerlevel10k
```

But the following will trigger the output (even though it loads faster):

```
zinit ice depth=1 silent wait'!' lucid atload"source $ZSH_CONF/.p10k.zsh; _p9k_precmd" nocd
zinit light romkatv/powerlevel10k
```

**Comment by romkatv** [comment]
> I got the part that you can turn off the instant prompt but I was wondering if there was a way to just turn off this message all together?

Have you noticed the first solution suggested by the error message you've quoted above?

**Comment by scalp42** [comment]
Yes I have and it doesn't fix the issue.

**Comment by romkatv** [comment]
You must be mistaken. From the error message:

>  - Recommended: Change the way Powerlevel10k is loaded from ~/.zshrc.
>    See https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation.

Clicking on the link you can see:

> ### Zinit
>
> Add `zinit ice depth=1; zinit light romkatv/powerlevel10k` to `~/.zshrc`.
> 
> The use of `depth=1` ice is optional. Other types of ice are neither recommended nor officially
> supported by Powerlevel10k.

You wrote:

> This will work fine:
> 
> ```zsh
> zinit ice depth=1;
> zinit light romkatv/powerlevel10k
> ```

Which confirms that the documented installation instructions do indeed work and that the error message no longer appears if you follow them.

Does this make sense?

**Comment by scalp42** [comment]
It sounds like you don't want to help regarding `zinit` which is fine but I'm not even asking for any support regarding `zinit` directly.

My question was related to the output in general but you seem to give me the runaround and it's pretty toxic but nothing unsurprising judging by some threads like https://github.com/zdharma/zinit/issues/268#issuecomment-592151609 and dozen others.

I'll just fork and unset `__p9k_instant_prompt_erased`.

Thanks for your work anyway.

**Comment by romkatv** [comment]
When using instant prompt, Powerlevel10k must be loaded before the first prompt. If this requirement is violated, the error message you've quoted above is displayed. In order to get rid of the error message you either need to fix your zshrc so that Powerlevel10k is loaded before the first prompt, or disable instant prompt. The former is recommended. How exactly this can be done is described in https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation.

The error message triggers in your case because you are using ice `wait` when loading powerlevel10k with zinit. This ice is pointless at best when instant prompt is enabled. It doesn't make zsh startup faster, not even a little bit. The only effect it has is prompt flickering (powerlevel10k prompt => another prompt => powerlevel10k prompt once again). Hence the error message to tell you that you need to change your configuration to something that makes sense.

P.S.

Please refrain from bad faith accusations. It's unbecoming.

**Comment by scalp42** [comment]
If anyone comes across this thread:

https://github.com/scalp42/powerlevel10k/commit/b391ff572826be2f21571c70a8a0fe9843e9a9e2

Hust set `PS1=` before and it'll flicker once but load way faster.

**Comment by romkatv** [comment]
> [...] it'll flicker once but load way faster.

This is not true.

When you correctly load Powerlevel10k with enabled Instant Prompt, here's what happens on zsh startup:

1. A limited version of Powerlevel10k prompt is printed out. This happens within a dozen or so milliseconds after you start Zsh, and after this step you can start typing commands. The prompt is limited in a sense that it's missing some types of information. For example, it always displays the current directory, username and current time but never displays Git status or the number of entries in command history.
2. Powerlevel10k gets fully initialized and replaces the limited prompt with a full-fledged version that contains all information. If you type `zsh` when your current directory is a Git repository, you'll notice this step taking place because the name of the checked out Git branch will appear in prompt.

When you load Powerlevel10k via `zinit` with `wait` ice, an extra step is added in between:

1.5. The limited Powerlevel10k is replaced by a different prompt (specified via `PS1`).

This step causes prompt flicker on startup but doesn't make other steps faster nor slower. If you think about it, it cannot possibly speed up Powerlevel10k initialization that follows. The middle step just prints something on the screen.

When Powerlevel10k detects prompt flicker, it prints a message explaining how it can be removed. If you prefer the `PS1` prompt over the limited Powerlevel10k prompt on zsh startup, disable Instant Prompt. If you prefer the limited Powerlevel10k prompt over the custom `PS1`, remove the `wait` ice. Both of these solutions will remove the flicker and will result in better user experience. They will not make anything slower.

**Comment by scalp42** [comment]
Without ice and with instant prompt:

```
zinit ice depth=1 silent atload"source $ZSH_CONF/.p10k.zsh"
zinit light scalp42/powerlevel10k
```

```
❯ avg-time
0.066000000000000017
```

With ice and instant prompt (flicker once):

```
# NOTE: my fork turns off the warning about instant prompt
zinit ice depth=1 silent atload"source $ZSH_CONF/.p10k.zsh; _p9k_precmd" nocd wait'!' lucid
zinit light scalp42/powerlevel10k
```

```
❯ avg-time
0.044399999999999988
```

**Comment by romkatv** [comment]
Run meaningless benchmarks, get meaningless results.

Do you understand my previous comment? Do you see that it’s impossible to make Powerlevel10k initialize faster simply by printing something?

**Comment by romkatv** [comment]
To clarify, I don’t meant that `wait` ice on Powerlevel10k with Instant Prompt produces *small* Zsh startup speedup. It produces *no* speedup and this cannot possibly be otherwise. It does have an effect on benchmarks that measure some part of zsh initialization simply because a different part gets slower. From the users point of view, both parts must complete before you notice anything useful being done.

**Comment by romkatv** [comment]
Going back to https://github.com/romkatv/powerlevel10k/issues/1048#issuecomment-705722342, when you run `avg-time` with correctly loaded Powerlevel10k with Instant Prompt, it measures how long it takes for steps 1 and 2 to execute. But if you use `wait` ice with `zinit` to load Powerlevel10k, it measures only the steps 1 and 1.5. Step 1.5 doesn't do anything useful at all but you *think* it's useful because it affects the benchmark you are using. This is an indication that the benchmark is broken. A good benchmark wouldn't show a lower number when you add an extra step in the initialization process.
