### ISSUE TITLE
Color of the element

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#1058]
Can you please tell me how i can change the color of this element? It merges with the background of my terminal.

![image](https://user-images.githubusercontent.com/35394377/96333437-99591380-1072-11eb-9dae-5f7032b2177b.png)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find this block: https://github.com/romkatv/powerlevel10k/blob/54d40b924c491a6510c44391dccac05fe78a7310/config/p10k-rainbow.zsh#L466-L505

Uncomment and edit `BACKGROUND` parameters as you like.

A better solution is to configure your terminal so that color 0 is not identical to the background color.
