### ISSUE TITLE
Some icons stoppred rendering properly.

### ISSUE THREAD

**Issue by DERPSQUID9** [romkatv/powerlevel10k#1068]
Some icons, like the home icon in the current working directory segment, have recently stopped rendering properly. I have not recently changed anything in my .zshrc or .p10k.zsh files.

zsh version: zsh 5.8 (x86_64-pc-linux-gnu)
font: Nerd Fonts Fira Code

Please let me know if any more information would be helpful.

**Comment by romkatv** [comment]
Please do the following:

1. Post a screenshot of your prompt.
2. Explain what is unexpected/wrong on the screenshot.
3. Attach your `~/.zshrc` and `~/.p10k.zsh` to this issue.
4. Run `print '\uF015'` and post a screenshot.

**Comment by DERPSQUID9** [comment]
Here's a screenshot of my prompt after running `print '\uF015'`
![image](https://user-images.githubusercontent.com/29845794/97121228-fe57dd80-16f2-11eb-8d7a-91bb74029042.png)

The segment that displays the current directory (medium blue, left side) and the segment that displays the time (pink, right side) should each have an icon, but all of it except for the very top is cut off.

Here are my .zshrc and .p10k.zsh files: (I had to remove the period at the beginning and add .txt in order for it to be accepted as an attachment)
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/5436097/zshrc.txt)
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/5436098/p10k.zsh.txt)

**Comment by romkatv** [comment]
> Here's a screenshot of my prompt after running `print '\uF015'`

U+F015 is the home glyph in nerd fonts. The font used by your terminal doesn't have this glyph. To fix this issue you need to install a font with this glyph and configure your terminal to use this font. This problem is not specific to Powerlevel10k, zsh or anything else that you run within the terminal. It cannot be solved by tweaking Powerlevel10k or zsh configs. The only way to fix the problem is on the level of the OS (install an appropriate font) and the terminal (configure it to use the right font).

If you cannot find a font that has the font icon at U+F015, try [the recommended font](https://github.com/romkatv/powerlevel10k#manual-font-installation).

**Comment by subnut** [comment]
@DERPSQUID9 Most modern terminals in linux (gnome-terminal, kitty, alacritty, termite, QTerminal, etc.) (but not xterm, st, etc) Should pick up the missing glyph from another Nerd Font if installed. I personally use Fira Code (the original one, not patched) in all my terminals, and also have MesloLGS NF (provided by @romkatv) installed. In all of the above-mentioned terminals, I have mentioned only a single font, Fira Code. But all of them correctly detect and show the nerd-font-icons from MesloLGS NF automatically.

**Comment by romkatv** [comment]
@subnut The font used by the OP has a glyph at U+F015.

In general, font fallbacks are unreliable when using glyphs from the unicode private use area. There is no shared meaning of U+F015. Every font is free to display anything whatsoever.

When you use a font without U+F015 and attempt to print this character, the fallback mechanism will work fine as long as there is only one font with this glyph, or if you've manually specified which font this glyph should be pulled from. Otherwise the results are unpredictable.

For this reason I very much prefer adding glyphs to fonts directly rather than relying on fallbacks.

This is just a tangent though and it's unlikely to help the OP. What they need is to install a font with nerd font glyphs and to configure their terminal to us it.

**Comment by DERPSQUID9** [comment]
I closed this because it was determined that it was not caused by powerlevel10k, but I have now found a solution and figure that I may as well post it in case anyone else is having a similar issue: I changed the font's name in my terminal config file from `Fira Code` to `Fira Code Nerd Font` and now everything's perfectly fine.

**Comment by romkatv** [comment]
@DERPSQUID9 Thanks for the update.
