### ISSUE TITLE
Wrong escaping in prompt?

### ISSUE THREAD

**Issue by wazum** [romkatv/powerlevel10k#107]
I tried to use powerlevel10k with https://github.com/Valiev/almostontop which results in 
`almostontop_preexec:7: bad math expression: operand expected at %F{000+27'`

It works without a problem with Powerlevel9k.

The _problematic_ line here is
`print -n -P "$prompt$fg[$ALMOSTONTOP_COLOR]"`

When I print the prompt I get the line with different escapings
`%K\{004\\\}%F\{000\\\}\~%b%K\{004\}%F\{000\}%b%K\{004\}`
so I guess the problem lies here somewhere.

Could you take a look at this?
Tia

**Comment by romkatv** [comment]
That's a bug in almostontop. It's difficult to even call it a bug because almostontop is a simplistic plugin that works only with very simple prompts. When used with non-trivial prompts, it can results in errors just like you've seen, in loss of information when only a part of the prompt is displayed, and in incorrect prompt when it shows you not what your prompt would normally show. The documentation doesn't mention this but almostontop doesn't work with most themes.

You can get the proper behavior of almostontop by adding the following snippet to the _top_ of your `~/.zshrc`. It must run before powerlevel10k is sourced.

```zsh
function clear-screen() { clear -x }
autoload -Uz add-zsh-hook
add-zsh-hook precmd clear-screen
```
