### ISSUE TITLE
Rainbow with "No frame" does not show exit code

### ISSUE THREAD

**Issue by yanzhang0219** [romkatv/powerlevel10k#1079]
![image](https://user-images.githubusercontent.com/11582667/97523976-c8b82c00-1960-11eb-8618-0d781fb2365a.png)
I double-checked that `status` is on in `.p10k.zsh`. 
If I change "No frame" to "Full", the exit code part will be shown.
![image](https://user-images.githubusercontent.com/11582667/97524101-103eb800-1961-11eb-81f8-b833d6c12dab.png)

Thank you.

**Comment by romkatv** [comment]
It doesn't show the "boring" exit codes because the red `❯` is usually enough in practice. "Interesting" error codes are still shown. For example, type `sleep 10` and hit <kbd>Ctrl+C</kbd> and you'll see `INT` to tell you the process was interrupted. Or try `echo hello | grep goodbye` and you'll see `0|1` to tell you that the first job in the pipeline has finished successfully but the second failed with error code 1.

If you want to always see error code, open `~/.p10k.zsh` and find this block: https://github.com/romkatv/powerlevel10k/blob/54d40b924c491a6510c44391dccac05fe78a7310/config/p10k-lean.zsh#L487-L491

Flip `false` to `true`. You can do the same for other conditions if you like. For example, `POWERLEVEL9K_STATUS_OK=true` to show the green checkmark (rather useless given the green `❯`).

**Comment by yanzhang0219** [comment]
I see. Thank you so much for your instant response and detailed explanation.
