### ISSUE TITLE
Pop!_OS Logo doesn't exist

### ISSUE THREAD

**Issue by nonforgettable** [romkatv/powerlevel10k#1082]
![image](https://user-images.githubusercontent.com/68202470/97697843-f03b0000-1aea-11eb-83ae-48dfda8a5f26.png)

**Comment by romkatv** [comment]
As far as I know, there are no fonts with the Pop!_OS logo. You can either create a font like that yourself or induce someone to create it for you.

By the way, the text on your screenshot looks italicized. This is unexpected. This is usually caused by a failure to install all 4 font faces or by explicitly selecting the italicized font face in the terminal settings.

**Comment by nonforgettable** [comment]
> As far as I know, there are no fonts with the Pop!_OS logo. You can either create a font like that yourself or induce someone to create it for you.
> 
> By the way, the text on your screenshot looks italicized. This is unexpected. This is usually caused by a failure to install all 4 font faces or by explicitly selecting the italicized font face in the terminal settings.

Heh, it's some sort of bug caused by Pop!_OS and MATE terminal mixture. On Gnome Terminal it works fine.
