### ISSUE TITLE
Question about  POWERLEVEL9K_STATUS_ERROR

### ISSUE THREAD

**Issue by zenmaster24** [romkatv/powerlevel10k#1089]
Hi,

I was wondering if there was a way to get the prompt to **only** display a colour (red) when the last command was in error?
Currently it displays the exit code, like 1 or 127 which I dont want - I have been able to get it to just display the colour when the command succeeds by have a space in **POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION**, but this does not seem to work for **POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION**.

I also dont want a **prompt_char** - just a blank coloured square with seperator will do.

Thanks!

**Comment by romkatv** [comment]
> [...] but this does not seem to work for POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION.

By default, when a command fails with the error code `1`, you'll see an icon (usually a red cross) and content (literally "1"). If you set `POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION=""`, you are replacing the icon with an empty string. If you set `POWERLEVEL9K_STATUS_ERROR_CONTENT_EXPANSION=""`, you are replacing the content with an empty string.

---

Type `echo "hello world" | grep hello | grep goodbye`. You'll see `0|0|1` to let you know that the first two commands in the pipeline have succeeded but the last has failed with error code one. Do I understand it correctly that you want just a red icon instead of this?

Type `sleep 60` and press <kbd>Ctrl+C</kbd> to interrupt it. You'll see `INT` to let you know that the command has been killed with the `INT` signal.  Do I understand it correctly that you want just a red icon instead of this?

**Comment by zenmaster24** [comment]
Hi - ideally I want just a red coloured space - no icon/character/symbol/integer.

**Comment by romkatv** [comment]
> Type `echo "hello world" | grep hello | grep goodbye`. You'll see `0|0|1` to let you know that the first two commands in the pipeline have succeeded but the last has failed with error code one. Do I understand it correctly that you want just a red icon instead of this?

I'm assuming the answer is Yes.

> Type `sleep 60` and press Ctrl+C to interrupt it. You'll see `INT` to let you know that the command has been killed with the `INT` signal. Do I understand it correctly that you want just a red icon instead of this?

I'm assuming the answer is Yes.

> Hi - ideally I want just a red coloured space - no icon/character/symbol/integer.

Remove all existing `POWERLEVEL9K_STATUS_*` parameters and add these:

```zsh
# Do not show status on success.
typeset -g POWERLEVEL9K_STATUS_OK=false
# Do not show an icon for status.
typeset -g POWERLEVEL9K_STATUS_VISUAL_IDENTIFIER_EXPANSION=
# Display a red-colored space as status.
typeset -g POWERLEVEL9K_STATUS_CONTENT_EXPANSION='%K{1} %k'
```

**Comment by zenmaster24** [comment]
hi - thanks for the help, i got it to work how i want with the below:

```
  typeset -g POWERLEVEL9K_STATUS_OK=true
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION=' '
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=70

  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION=' '
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=70

  # Do not show an icon for status.
  typeset -g POWERLEVEL9K_STATUS_VISUAL_IDENTIFIER_EXPANSION=
  # Display a red-colored space as status.
  typeset -g POWERLEVEL9K_STATUS_ERROR_CONTENT_EXPANSION='%K{1} %k'
```
