### ISSUE TITLE
Feature request: Show both branch and tag if available in git

### ISSUE THREAD

**Issue by marekdedic** [romkatv/powerlevel10k#1169]
Hi,
I'd like to show both the branch and the tag in the git repository, if I'm at a point where both are applicable.

I tried modifying the config, but it doesn't really seem to be made for this.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status and https://github.com/romkatv/powerlevel10k/issues/391#issuecomment-612702692.

**Comment by romkatv** [comment]
I've updated the templates for `~/.p10k.zsh` so that it's easier to make this change: https://github.com/romkatv/powerlevel10k/commit/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45. If you update powerlevel10k and run `p10k configure`, you'll have the following piece of code in `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45/config/p10k-lean.zsh#L387-L389

**Comment by marekdedic** [comment]
Oh, I just pulled and it's really easy! Thanks.
