### ISSUE TITLE
Show submodule dirty option not respected

### ISSUE THREAD

**Issue by heylookltsme** [romkatv/powerlevel10k#118]
I've set the `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY` to true in my `.zshrc` file, but it doesn't seem to be respected. 

I've disabled all plugins and any custom configuration other than what comes out of the box with Oh My Zsh.  

I installed both powerlevel10k and powerlevel9k to see if the setting works in the latter and it does.  [Here's a screencast](https://www.dropbox.com/s/1ufvmdfeebu1z17/dirty-submodule.mp4?dl=0) of the dirty status not showing in powerlevel10k and then showing up when I switch to powerlevel9k.

I'm very new (like, as of yesterday 🙃) to zsh so it's very possible there's just something funky going on in my environment, but I've been banging my head on this for a while and I strongly suspect it's a genuine issue. I can elaborate on what I've done so far to debug, if it's helpful. 

Thanks!

**Comment by romkatv** [comment]
> I've set the `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY` to true in my `.zshrc` file, but it doesn't seem to be respected.

Indeed, it's not respected. You are the first person to ask for it. Are you sure you want it?

**Comment by romkatv** [comment]
To clarify, with `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false` you'll still get the dirty indicator if the submodule is checked out to a commit different from what's recorded in the superrepo. This is what most people want as it's uncommon to do development in the submodules directly. What `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true` does is to recursively call `git status` in each submodule and to aggregate the results.

**Comment by heylookltsme** [comment]
> To clarify, with POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false you'll still get the dirty indicator if the submodule is checked out to a commit different from what's recorded in the superrepo. 

Ahh ok that is indeed my main concern. I just tested that and, sure thing, it works. 👍🎉

> Are you sure you want it?

It is kind of confusing that the setting would work differently in powerline9k vs powerline10k. And I guess I don't really see the benefit of obscuring local changes in a submodule from the superrepo status. But I also don't feel super strongly about it.  /shrug 

Thanks for the help and quick response!

**Comment by romkatv** [comment]
I think it's the last option in Powerlevel9k that isn't implemented in Powerlevel10k. I'll get to implementing it once I'm done with a few large things I'm working on.

By the way, your prompt in the screencast looks close to what you get by default. The defaults are super old and ave to be kept unchanged so that users' configs don't break, but they are really suboptimal. I'm yet to see anyone who wants that history counter in their prompt. I'm working on two new configs that Powerlevel10k will recommend to new users to base their configs on -- lean and classic -- and the first is already usable. It's also the config I use, so it's been tested. If you are willing to try a new prompt look, try https://github.com/romkatv/powerlevel10k/blob/master/config/lean.zsh. It's meant to be copied and modified. E.g., you could copy it to `~/p10k.zsh` and source it from `~/.zshrc`. Don't source it from powerlevel10k directly. It works well out of the box. You can try uncommenting a few things in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and maybe change `POWERLEVEL9K_PROMPT_ADD_NEWLINE` and `POWERLEVEL9K_SHOW_RULER` and see if you like it better. If you have a few free minutes, read the comments that I sprinkled through the file.

Eventually I'll add all available options for all prompts in that config so that whenever you want to change the appearance of your prompt, you can just look in your config file for what's available and read nearby comments as documentation. Lean config doesn't use backgrounds or uninformative icons, and it works with standard fonts. Classic config will be in powerline style (similar to what you have right now) and will require a Powerline font.

**Comment by heylookltsme** [comment]
> By the way, your prompt in the screencast looks close to what you get by default.

Oh yeah it totally was. I turned off any customization so I could just use the defaults for testing. I've been using purepower so far and it's really great. I'll check out lean as well 👍 

Thanks very much for all the info! 

> I think it's the last option in Powerlevel9k that isn't implemented in Powerlevel10k. I'll get to implementing it once I'm done with a few large things I'm working on.

Ah ok awesome. Since you're planning on doing that, I'll reopen this. 👍

**Comment by romkatv** [comment]
> Oh yeah it totally was. I turned off any customization so I could just use the defaults for testing. I've been using purepower so far and it's really great. I'll check out lean as well 👍

Phew :-) It pains me every time I see someone using Powerlevel10k with the default settings. And I feel guilty because it's my job to make the theme work well out of the box. I'm glad you weren't stuck in this trap.

Lean config is basically Pure Power v2. Same basic style but more streamlined. There is slightly better Git prompt, status and context. Most changes are related to code quality. The config is much easier to understand and edit than the original Pure Power. It also showcases several advanced features that I've recently added that give you a lot of control over the content of segments.

> Ah ok awesome. Since you're planning on doing that, I'll reopen this. 👍

Sounds good!

**Comment by romkatv** [comment]
Closing as I'm unlikely to work on it. If users request this feature, I'll reconsider.

**Comment by ddarbyson** [comment]
Hey guys... I recently switched to powerlevel10k and found that the `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY` is not working like powerlevel9k... With powerlevel9k I was able to see when I had a dirty submodule that needed to be committed. 

The reason is why this is important for our workflows is the submodule is always committed on a particular commit and the parent that is using the submodule must use the commit specified and not master, or anything on a previous commit or else the parent code will break.

So we consider the submodule as part of the core code. A commit on the submodule means the parent must also commit the new reference to the submodule, hence why it is very important to see that the submodule is dirty so the commit isn't forgotten.

Thanks for listening, hope to see this improvement in the future.

**Comment by ddarbyson** [comment]
I do want to note, that if I make a commit in the submodule then the parent shows as dirty.

I think what I'm used to is the parent showing dirty if the submodule is dirty as well as the submodule have a latest commit

**Comment by romkatv** [comment]
> Hey guys... I recently switched to powerlevel10k and found that the `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY` is not working like powerlevel9k...

Correct. This is mentioned in the [FAQ](https://github.com/romkatv/powerlevel10k#does-powerlevel10k-always-render-exactly-the-same-prompt-as-powerlevel9k-given-the-same-config):

> Powerlevel10k doesn't support `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true`.

I'm unlikely to ever implement this.

**Comment by ddarbyson** [comment]
I hear you... Well, I really appreciate the effort you have given this project so far. I found my new prompt – you really figured out what mattered toome. Speed, simplicity, and nice UI (like Pure).

Here's hoping you get bored one day and implement `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY` :)
