### ISSUE TITLE
strange newline seperator

### ISSUE THREAD

**Issue by kyeotic** [romkatv/powerlevel10k#120]
There is a thin line joining the two lines of a multiline prompt. Even when using some popular pre-built prompts that dont show this line, it shows up. 

<img width="353" alt="Screen Shot 2019-07-15 at 1 17 15 PM" src="https://user-images.githubusercontent.com/1187432/61246074-e1b4b380-a702-11e9-9b48-5caf0e4d9081.png">

its the thin line to the left of the checkmark. Does anyone know where this comes form or how to remove it?

**Comment by romkatv** [comment]
It does looks awful. Powerlevel10k, like all other themes, cannot do pixel-level drawing. It can only print characters that your font supports. If these two characters look the way they do in your prompt, they'll look that way in any ZSH theme, in Bash, etc. You have several options.

1. You can change these two symbols by defining `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX` and `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX`.

2. You can try another font.

3. You can try another terminal.

4. You can turn off these symbols and enable the multi-purpose `prompt_char`.

```zsh
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir vcs newline prompt_char)
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
POWERLEVEL9K_PROMPT_CHAR_LEFT_SEGMENT_SEPARATOR=
POWERLEVEL9K_PROMPT_CHAR_WHITESPACE_BETWEEN_LEFT_SEGMENTS=
```

This will look better, save space and give you more information in the prompt. You can even remove `status` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` because your prompt symbol now shows whether the last command has succeeded or not (it also shows vi mode if you are using vi keymap).

This requires a recent version of Powerlevel10k.

**Comment by kyeotic** [comment]
That's much better, thank you. 

It looks like is all it takes to get rid of is
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir vcs newline prompt_char)
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
```

**Comment by romkatv** [comment]
If you are after the smallest change that will remove the prefixes, it's `POWERLEVEL9K_PROMPT_ON_NEWLINE=false`.
