### ISSUE TITLE
Poluting terminal window with prompt line elements after window resizing (GNOME terminal)

### ISSUE THREAD

**Issue by metacortexplus** [romkatv/powerlevel10k#1216]
This is how it looks like after intentional **multiple** resizing (just to emphasize the problem).
![Screenshot from 2021-01-12 15-23-44](https://user-images.githubusercontent.com/21023720/104320218-b9219b80-54ea-11eb-915e-e95c1e20f06c.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by eddyg** [comment]
Roman, based on the number of times people open issues without reading the README, I wonder if you should consider creating a [GitHub Issues Template](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository) for P10K that mentions this issue in particular. Something like:

---
I have read the Powerlevel10k README and this issue *(place an* `x` *between the brackets below)*:
- [ ] is *not* related to the [mess that occurs when resizing my terminal](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window)
- [ ] is *not* related to another item already addressed in the README
---

Half joking, half serious...

**Comment by romkatv** [comment]
That's a trade-off between my time and the time spent by everyone who opens good issues.

Right now I'm wasting a minute or so every time someone reports an issue related to resizing. If I add an issue template, I'll save that minute but at the cost of everyone else having to read the verbiage when they want to report an issue. That's not a good trade off.

P.S.

I don't really care about the time wasted by people reporting specifically *this* issue. They can help themselves by searching through issues instead of blindly filing a new one.
