### ISSUE TITLE
Transient prompt fails when line-finish hook gets added in precmd hook

### ISSUE THREAD

**Issue by marlonrichert** [romkatv/powerlevel10k#1238]
Given the following `.zshrc` file and Powerlevel10k configured with transient prompt, the transient prompt feature stops working:
```zsh
source /Users/marlon/git/powerlevel10k/powerlevel10k.zsh-theme
autoload -Uz add-zsh-hook-widget add-zle-hook-widget
add-line-finish() {
  no-op() {}
  add-zle-hook-widget line-finish no-op
}
add-zsh-hook precmd add-line-finish

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by romkatv** [comment]
Simplified test case:

```text
% zsh -f
% autoload -Uz add-zsh-hook-widget add-zle-hook-widget
% function foo() print -rl '' foo
% add-zle-hook-widget line-finish foo
% zle -A zle-line-finish orig-zle-line-finish
foo

% function bar() { zle orig-zle-line-finish; print bar; }
foo

% zle -N zle-line-finish bar
foo

% true
foo
bar

% add-zle-hook-widget line-finish foo
foo
bar

% true
foo
```

Note that on the last line only `foo` is printed but `bar` isn't. This is the underlying issue.

Ideally this should be fixed in `add-zle-hook-widget` but even then it'll take a while before users get the fix. In the meantime we'll need to add workarounds.

Is it feasible to avoid invoking `add-zle-hook-widget` multiple times in zsh-autocomplete? That is, the original snippet you've posted can be fixed by unhooking `add-line-finish`:

```diff
 add-line-finish() {
   no-op() {}
   add-zle-hook-widget line-finish no-op
+  add-zsh-hook -d precmd add-line-finish
 }
```

**Comment by marlonrichert** [comment]
> Is it feasible to avoid invoking `add-zle-hook-widget` multiple times in zsh-autocomplete? 

Ah, yes, definitely. That is, in fact, a bug. Thanks for spotting it. I will fix it.
