### ISSUE TITLE
Is there a theme based on starship?

### ISSUE THREAD

**Issue by Genora51** [romkatv/powerlevel10k#1260]
I noticed in the readme the gif in the ["Extremely Customisable"](https://github.com/romkatv/powerlevel10k#extremely-customizable) section features a theme named `p10k-starship.zsh`.

But I couldn't find this file anywhere. Does the theme shown in the gif exist, and if so, where can it be found?

**Comment by romkatv** [comment]
The text in the linked section answers your question.

**Comment by jvbs** [comment]
I'd like to open this section again because it's not clear enough how to get this theme. Which linked section?

**Comment by romkatv** [comment]
> Which linked section?

See the link in the issue description. Here's the content:

> [Pure](https://github.com/romkatv/powerlevel10k#pure-compatibility), [Powerlevel9k](https://github.com/romkatv/powerlevel10k#powerlevel9k-compatibility) and [robbyrussell](https://github.com/romkatv/powerlevel10k#how-to-make-powerlevel10k-look-like-robbyrussell-oh-my-zsh-theme) emulations are built-in. To emulate the appearance of other themes, you'll need to write a suitable configuration file. The best way to go about it is to run `p10k configure`, select the style that is the closest to your goal and then edit `~/.p10k.zsh`.

**Comment by danielhu19** [comment]
I've seen two issues like this, I think they **just** want the `p10k-starship.zsh` file you demonstrated in that [screencast](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/other-theme-emulation.gif).

**Comment by romkatv** [comment]
That file *just* doesn't exist.

**Comment by laertis** [comment]
Bumping this thread again even tho it's closed. I think there are people, like me, that really like starship but want to make the jump to powerlevel10k for the sake of the async speed or play around with something different 
* eg. https://www.reddit.com/r/zsh/comments/12tyfva/config_to_make_powerlevel10k_look_like_starship/

I believe having a config [preset](https://github.com/romkatv/powerlevel10k/tree/master/config) for starship will make jumping form starship to p10k more tangible and expand its audience

Having said that, In the [screencast](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/other-theme-emulation.gif) mentioned above there is a `p10k-spaceship.zsh` being sourced that I didn't manage to find through the project's git history.
If such a file exists, or existed at some point, you could upload that since starship is really similar to spaceship

**Comment by romkatv** [comment]
Lean style is quite close to Starship. Give it a try.
