### ISSUE TITLE
P10k lean config

### ISSUE THREAD

**Issue by mustaqimM** [romkatv/powerlevel10k#129]
Hi there, is the `p10k-lean.zsh` config able to use all p9k variables?
Because I'm unable to get
```zsh
status                  # exit code of the last command
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
typeset -g POWERLEVEL9K_HOME_ICON='  '
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
```

**Comment by romkatv** [comment]
> Hi there, is the `p10k-lean.zsh` config able to use all p9k variables?

`p10k-lean.zsh` is just a config. It has no code, it simply sets some `POWERLEVEL9K` variables. It doesn't _use_ variables. Powerlevel10k does.

> `status                  # exit code of the last command`

Imagine that I copied your existing p9k config. If you have some `POWERLEVEL9K_STATUS_*` variables in there, `status` segment will look differently from its default style. If I wanted to customize how `status` looks, I would need to replace your `POWERLEVEL9K_STATUS_*` variables with mine.

It's the same with this config. If you want to set your own style for `status`, search for `POWERLEVEL9K_STATUS` and replace all those parameters with yours. If you want the default style of `status`, simply delete those parameters.

> `typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true`

This is already set in `p10k-lean.zsh`.

> `typeset -g POWERLEVEL9K_HOME_ICON='  '`

This one is tricky because it requires reading comments in `p10k-lean.zsh`. The short version is that `p10k-lean.zsh` disables all segment icons by default. To enable them you need to remove `POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION` from the config.

I realize that people don't read comments so I'm working on a setup wizard that will ask during installation whether icons should be enabled or disabled by default.

I don't like icons that don't any information (such as `HOME_ICON` -- I already see that my current directory is `~`; same for `VCS_BRANCH_ICON` -- the prompt already unambiguously tells you when you are on a branch), so I turn them off. Many users like redundant icons, so it should be easy for them to decorate their prompt. Right now this requires a one-line config change, which is more work than it should be.

> `typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''`

This should work if you update powerlevel10k and `p10k-lean.zsh` to the latest version. The config has this line:

```zsh
# No branch icon. Set this parameter to '\uF126 ' for the popular Powerline branch icon.
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
```

You can set it to any value, of course.

P.S.

By the way, the recommended way to customize your prompt when using `p10k-lean.zsh` is to copy and edit it. It's not a good idea to source it unmodified and then define/redefine some variables. The latter method is bound to break when you update p10k.

**Comment by mustaqimM** [comment]
@romkatv I see, thanks for the in-depth explanation. I thought some of the variables don't have any implementation because it wasn't setting the git branch icon. I do copy it to my `zsh/` folder and `ln -sf` it to the p10k folder. So I can keep it under git:
```zsh
zpl ice lucid atclone"ln -sf $ZDOTDIR/p10k-lean.zsh config/p10k-lean.zsh" \
  atpull"%atclone" run-atpull src"config/p10k-lean.zsh" compile"{functions/*.zsh,gitstatus/*.zsh}"
zpl light romkatv/powerlevel10k
```

**Comment by romkatv** [comment]
> I thought some of the variables don't have any implementation because it wasn't setting the git branch icon.

Right. This config is generating the content of vcs segment from scratch, so the parameters that p10k uses to render vcs have no effect.

If you have some existing set of vcs parameters that you like, you can simply replace all vcs parameters in the config with yours.

> I do copy it to my `zsh/` folder [...] so I can keep it under git:

Good idea.

I don't know what those `zpl` commands do or why you `ln -sf` the config to p10k folder. But if it works, it works.

**Comment by mustaqimM** [comment]
@romkatv It's a shorthand alias for the zplugin manager. Thanks so much for your replies and awesome project!
