### ISSUE TITLE
Icon padding doesn't work in lean mode

### ISSUE THREAD

**Issue by coldspark29** [romkatv/powerlevel10k#1354]
This works when I choose the rainbow mode but not in lean mode. I have selected "moderate" in both cases.

![image](https://user-images.githubusercontent.com/19779511/114858625-02370380-9dea-11eb-82a3-7168c9fd5439.png)

As you can see, the branch and vim icons need more space.

**Comment by romkatv** [comment]
Which font are you using?

**Comment by coldspark29** [comment]
Powerline fonts I assume

**Comment by romkatv** [comment]
Have you tried the recommended font? What do you get with that one? (The recommended font doesn't need padding.)

Which terminal are you using? Have you tried it with a different terminal?

**Comment by coldspark29** [comment]
Yeah it works with that one. I had Source Code Pro before and you wrote that it works well with that. The Nerd Font is a little small for my case as I am far sighted.

**Comment by romkatv** [comment]
> I had Source Code Pro

This font doesn't have the icons that are visible on your screenshot. This means the icons come from elsewhere, via a fallback.

> Hmm somehow the icons are really small now and the don't get bigger again if I change the font back to Source Code Pro

Delete the new font and reboot. That should make the fallback work as before. Or you can manually reconfigure how fallbacks work.

My personal advice is to use the recommended font and to increase the font size so that it's easily readable. I would also suggest going with the "few icons" option in the wizard. It'll remove useless icons and leave the useful ones.

If you want, you can keep your current font with oversized icons and manually add/remove spaces where necessary. For example, there is too much whitespace after the github logo and too little after vim logo. These can be fixed like this:

```zsh
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uF113'
POWERLEVEL9K_VIM_ICON=$'\uE62B'
```

This is a lot of work for little gain.

These spaces aren't the default because every font with oversized icons has different relative icon sizes. Powerlevel10k has presets for the most common icon fonts but yours is not one of them. Sorry.

**Comment by coldspark29** [comment]
Yeah it is better like this. The font was actually okay. It were just the icons that were tiny. I could not even see them really. I have 2k resolution. Maybe that is why. I manually edited the icons now and this is how I wanted it to be.
