### ISSUE TITLE
prompt_ram:19: bad math expression: operand expected at `* 1024 '

### ISSUE THREAD

**Issue by rubendibattista** [romkatv/powerlevel10k#136]
I switched from `powerlevel9k` to `powerlevel10k`, and I'm using the ram prompt. But when loading up the shell I very often get the error in the title. I'm on CentOS 7.

This is my configuration: 
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_TIME_FOREGROUND='011'
POWERLEVEL9K_TIME_BACKGROUND='black'
POWERLEVEL9K_TIME_FORMAT="%D{%d.%m.%y \UF133  %H:%M}"
POWERLEVEL9K_RAM_BACKGROUND='024'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='202'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='214'
POWERLEVEL9K_PYENV_FOREGROUND='202'
POWERLEVEL9K_PYENV_BACKGROUND='214'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%f "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(pyenv virtualenv os_icon context dir vcs background_jobs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time ram)
```

**Comment by romkatv** [comment]
Thanks for the report.

I wasn't able to reproduce this but from the error message it appears that `/proc/meminfo` has something that isn't a number listed for `MemAvailable`. Powerlevel9k doesn't show `ram` in this case, so I've changed Powerlevel10k to use the same logic (although with a faster implementation). Please update and try again. Let me know whether the issue is fixed.

**Comment by rubendibattista** [comment]
Thanks for the prompt response. The update fix the error. 

(I actually don't know why `MemAvailable` should report a non-number. I also tried to `cat` it, but I always got a number. Maybe in some transient state? Don't know. Thank you for your help!)

**Comment by romkatv** [comment]
Thanks for the confirmation!
