### ISSUE TITLE
Unicode escapes are ignored in POWERLEVEL9K_*_VISUAL_IDENTIFIER_EXPANSION

### ISSUE THREAD

**Issue by unikitty37** [romkatv/powerlevel10k#1360]
The right segment separator is set using the line

```
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
```

However, if I use the same syntax for setting `POWERLEVEL9K_RBENV_VISUAL_IDENTIFIER_EXPANSION`, the escape sequence is not interpreted:

```
typeset -g POWERLEVEL9K_RBENV_VISUAL_IDENTIFIER_EXPANSION='\uF219'
```

![image](https://user-images.githubusercontent.com/139183/115018793-370d8e00-9eb0-11eb-96b0-bc8933f24c69.png)

Copying the literal character from a font viewer and pasting it into the config file works, but now the config file is unreadable in environments that don't have a nerd font installed:

```
typeset -g POWERLEVEL9K_RBENV_VISUAL_IDENTIFIER_EXPANSION=''
```

**Comment by romkatv** [comment]
Do this:

```zsh
typeset -g POWERLEVEL9K_RBENV_VISUAL_IDENTIFIER_EXPANSION=$'\uF219'
```

Note the dollar sign.

**Comment by unikitty37** [comment]
Thanks — that fixed it!

It's a bit confusing that it's required for some variables and not others, though — I take it that it won't hurt to always use it :)

**Comment by romkatv** [comment]
The expansion is applied automatically on `POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR` for backward compatibility. It's not a good thing that it's applied there. If I were starting a theme from scratch, I would remove all those implicit expansions because they require you to quote some characters and it's difficult to figure out what exactly you need to quote.
