### ISSUE TITLE
How can I know what does the segment means?

### ISSUE THREAD

**Issue by bruno-gurgel** [romkatv/powerlevel10k#1381]
I am using PowerLevel 10k with the Lean style, and sometimes appears a segment that I don't know the meaning.

For example: now is appearing a green engine and I have no idea of its meaning;

There is a list of all the segments with its icon or someplace I can refer to to get that information?

Thanks a lot!

The green engine:

<img width="148" alt="segment_p10k" src="https://user-images.githubusercontent.com/71857117/117504677-3c16a800-af59-11eb-9e22-f76952d9eb83.png">

**Comment by romkatv** [comment]
There is no list of all icons segments, unfortunately. Given the flexibility of configuration, it's not easy to provide it. A long time ago I've added a TODO to implement `p10k describe` command that would explain the current prompt, but there is slim chance I'll be working on it any time soon.

You can figure out what that green gear means with the following (admittedly convoluted) process. First, run this command to print IDs of all *prompt parts*:

```zsh
() { local -A reply; p10k display -a '*'; print -rC1 -- ${(ok)reply} }
```

You'll see something like this:

```text
1
1/gap
1/left
1/left/dir
1/left/vcs
1/left_frame
1/right
1/right/status
1/right/background_jobs
1/right/context
1/right/time
2
2/gap
2/left
2/left/prompt_char
2/left_frame
2/right
2/right_frame
empty_line
ruler
```

The format of these IDs is documented at `p10k help display`. Since we are trying to identify the green gear on the first line of right prompt, we should be looking at IDs of the form `1/right/*`. We can hide them one by one and see when the gear disappears. Let's hide the first one:

```zsh
p10k display '1/right/status'=hide
```

This won't have any visible effect because `status` isn't visible on your screenshot (but would be if you hit <kbd>Ctrl+C</kbd> or if you were to run `true | false`). Let's try the next segment:

```zsh
p10k display '1/right/background_jobs'=hide
```

Bingo! The gear is no longer visible. Now we know that the name of the segment is `background_jobs`. You can search for it on https://github.com/romkatv/powerlevel10k to see this description: "presence of background jobs". The same can be found in `~/.p10k.zsh`. You can see which jobs you have in the background by typing `jobs`.

`p10k display` changes the visibility of prompt parts only within the current shell. Restart zsh (with `exec zsh`) to have everything shown as before.

**Comment by bruno-gurgel** [comment]
Thanks so much! I understand that would be too hard!! Thanks for the comands, it will be very useful!!
