### ISSUE TITLE
weird behavior when left and right prompts overlap

### ISSUE THREAD

**Issue by mr-salty** [romkatv/powerlevel10k#140]
This started happening with 8300a1e363e7ef57b0c20da3f0855d6c8a7ede10

if my prompt gets long enough to overlap with the RPROMPT, I see a literal `\n` before the second-line prompt.  The first prompt visible here is at 5dd3ecab5ff636d06b5edd131f3fcc1a21990076 and the rest are at 8300a1e363e7ef57b0c20da3f0855d6c8a7ede10 which is the same as I see at HEAD. Note the RPROMPT disappears completely in both versions, unless the left prompt is short enough.

![rprompt](https://user-images.githubusercontent.com/7683836/62085498-be712480-b229-11e9-9600-c47c644d5306.png)

I have:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs newline background_jobs root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
```

In 9k the rprompt is always on the second line, regardless of whether I set whether I set `POWERLEVEL9K_RPROMPT_ON_NEWLINE` to `false` or `true` (ignore the messed up left indent):

![rprompt 9k](https://user-images.githubusercontent.com/7683836/62085769-5cfd8580-b22a-11e9-8a86-aa94044aa3a9.png)

Setting `POWERLEVEL9K_RPROMPT_ON_NEWLINE=true` in 10k does produce the same behavior as 9k, so I think that is a viable workaround for me... but the literal `\n` is weird regardless.

![rprompt 10k rprompt_on_newline](https://user-images.githubusercontent.com/7683836/62086071-3ee45500-b22b-11e9-8d4b-474e92283bcb.png)

**Comment by romkatv** [comment]
> weird behavior when left and right prompts overlap

A silly typo with such bad consequences, damn! Thanks for the report. This is fixed now.

> In 9k the rprompt is always on the second line, regardless of whether I set whether I set `POWERLEVEL9K_RPROMPT_ON_NEWLINE` to `false` or `true` (ignore the messed up left indent):

This is the reason I broke backward compatibility with p9k here. There is no way in p9k to move right prompt up unless you set `POWERLEVEL9K_PROMPT_ON_NEWLINE` (note `PROMPT` rather than `RPROMPT`) but that setting removes the ability to customize the last line of left prompt and adds ornaments on the left side of the prompt. My breaking compatibility means that for a small number of users prompt changes between p9k and p10k but as you noted consistency can be restored by defining `POWERLEVEL9K_RPROMPT_ON_NEWLINE=true`.

In p10k both of `ON_NEWLINE` parameters are best avoided as there is a consistent way of controlling the layout of left and right prompt. You can use `newline` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` the same way you do it with `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

```zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(newline status time)
```

You can define segments on both lines of right prompt if you like.

In addition, you can independently specify how empty prompt lines are rendered.

```zsh
POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='...'
POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='...'
```

For backward compatibility, the first setting defaults to the right-pointing triangle and the second defaults to empty. You can see the effect of both of these defaults in your prompt. You prompt has two lines on each side but empty lines are rendered differently on the left and right.

You can specify a more specific override for the last prompt line. Here's the algorithm that determines the end-of-line symbol on the last line of left prompt:

1. If the last visible segment is `foo` (e.g. `dir`):
1.1 If the segment is in state `BAR` (e.g., `dir` in state `NOT_WRITABLE`) and `POWERLEVEL9K_FOO_BAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` is set, use that.
1.2. If `POWERLEVEL9K_FOO_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` is set, use that.
2. If the line is empty (no last visible segment) and `POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` is set, use that.
3. If `POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` is set, use that.
4. If `POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR` is set, use that.
5. Use the default triangle.

Hopefully you can see the hierarchy of overrides. The algorithm is the same for many segment properties other than `LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL`.

By the way, the reason the bug has been left unnoticed for so long is that `dir` in my own prompt is enabled to automatically shorten when it doesn't fit on the screen. See https://asciinema.org/a/258376 for a demo and the description of the shortening algorithm. Since the directory is shortened only when necessary and that the original is uniquely identified by the shortened result, there is no good reason to _not_ enable this feature.

Lastly, I highly recommend running `p9k_configure`. It'll ask you a few questions and generate a good and well-commented config that you can edit further. Run it a few times to explore different styles. Once you find the one you like, apply manual edits to `~/.p10k.zsh`.
