### ISSUE TITLE
Mercurial Nerd Font bookmark icon is not spaced properly

### ISSUE THREAD

**Issue by ParceledTongue** [romkatv/powerlevel10k#1414]
Something is causing the extra space after the `\uF461` (NF bookmark icon) character to not display in the prompt before the name of the bookmark. Since the space is there to accommodate the double-width character, its omission causes the icon to overlap with the bookmark name. See this screenshot:

<img width="762" alt="Screen Shot 2021-05-26 at 9 54 03 AM" src="https://user-images.githubusercontent.com/5892626/119672104-50d3b680-be08-11eb-9d61-1ddd6dec1a7b.png">

(The screenshot is from iTerm2 using the default MesloLGS NF font, though I don't believe the issue is specific to the terminal or the font—the same thing occurs in Apple's default Terminal application and with the FiraCode Nerd Font, for example.)

The issue persists even if `VCS_BOOKMARK_ICON` is changed to use other double-width characters, for example the branch icon character `\uF126`—which works fine with `VCS_BRANCH_ICON`, where the extra width is accommodated in the same way (by adding a space after the unicode). This makes me think the issue is not with the spec in `internal/icons.zsh` but somewhere else in the logic to incorporate the bookmark info into the prompt. It also doesn't seem to matter how many spaces are placed after the unicode here; even if `\uF461` is followed by 10 spaces, the bookmark name still overlaps the icon. 

Interestingly, when the space after the icon character is specified via unicode (as in `'\uF461\u0020'`), the prompt correctly displays the space. This would be an acceptable workaround from my end-user perspective, though someone here can hopefully take that info and figure out what's actually going wrong instead 🙂

**Comment by romkatv** [comment]
I think spacing is correct but the glyph is too damn large. Ideally I would go and shrink it a bit but it's more work than I have the willpower for right now.

As a workaround I offer you this (should go into your config; do not edit anything in powerlevel10k):

```zsh
POWERLEVEL9K_VCS_BOOKMARK_ICON='\uF461 '
```

This syntax works for all icon overrides by the way.

P.S.

Your attempt to add spaces in`icons.zsh` didn't work as you expected because of this: https://github.com/romkatv/powerlevel10k/blob/9c034101fe3cec1e2edb8e07c32a3e6dba9afaee/internal/icons.zsh#L815

**Comment by romkatv** [comment]
Oh, that's a good point! Do you want to send a PR?

**Comment by ParceledTongue** [comment]
Coming through shortly 😁
