### ISSUE TITLE
Kubecontext always shows the same context

### ISSUE THREAD

**Issue by d0n03rkf1tz** [romkatv/powerlevel10k#1417]
No matter what context i set my config to for `kubectl` it always shows the same context when I type the command:
![image](https://user-images.githubusercontent.com/83191295/119700394-c778b000-be18-11eb-89e8-c38ee24868b4.png)

Is there a setting I need to change to get it to update?

**Comment by romkatv** [comment]
Is this `kubectl` actually `kubectl.exe`?

**Comment by d0n03rkf1tz** [comment]
it's kubectl.exe

**Comment by romkatv** [comment]
That must be why. Powerlevel10k assumes UNIX-like behavior from tools. It can work on Cygwin as long as you use tools that behave as if Cygwin was UNIX-like. `kubectl.exe` doesn't.

This is probably fixable but I don't want to spend time on Cygwin support. If you send a PR with clean code, I'll merge it.

By the way, why use Cygwin rather than WSL?

**Comment by d0n03rkf1tz** [comment]
Understood, thanks for the explanation!

Using Cygwin over WSL as I was experiencing some issues with WSL.  This is on a corporate laptop and there were some glitches. Maybe those have been fixed.  I'll have to give it another shot. 

Either way, appreciate it. Have a good one!

**Comment by romkatv** [comment]
WSL is really good nowadays. I used to use Cygwin and I can tell you it's like night and day. Highly recommended.

Closing as Won't Fix. Sorry I couldn't be more helpful.
