### ISSUE TITLE
icons are not showing correctly

### ISSUE THREAD

**Issue by shoaibsharif** [romkatv/powerlevel10k#143]

**Comment by romkatv** [comment]
> I am using MesloLGS Nerd font Complete and I can not get the correct font according to the screenshot when I set up. Can anybody tell me what was wrong? I am using iterm2.

I'm seeing 3 problems.

1. There is a question mark in your prompt. This is expected. This is how untracked git files are displayed. Type `git status` to see them. You can change this symbol by opening `~/.p10k.zsh`, searching for `?` and replacing it. Here's the relevant bit:

```zsh
# ?42 if have untracked files.
vcs+='${${VCS_STATUS_NUM_UNTRACKED:#0}:+ %39F?${VCS_STATUS_NUM_UNTRACKED}}'
```

2. There is `git` written in your prompt. This is expected. This icon depends on the URL of your remote. If it's github.com, you'll get GitHub icon. If it's gitlab.com, you'll get GitLab icon, etc. If it's something else, you'll get just `git`.

3. Blurry heads and tails look missized. After digging into this I realized it's an issue with Nerd Fonts. All fonts in the Nerd Fonts repository have incorrectly sized block glyphs. I went ahead and manually edited Meslo. You can pick up the working Meslo Nerd Font from my repo. See https://github.com/romkatv/powerlevel10k/#fonts. If you already have a font with the name of "MesloLGS NF", you need to replace it and then reboot for changes to have effect. I've checked that everything looks great with this font in iTerm. Highly recommended!

Tip: Slanted separators work very well with blurred heads. Try using them instead of angled separators.

**Comment by shoaibsharif** [comment]
Wow! that was fast. Thank you. I was using `Meslo Nerd Font` but realized that the `Meslo Nerd Font Mono` was actually giving me the accurate font. Thanks for the git icon problem, I have realized that just before your post. I am very happy with this theme.

**Comment by romkatv** [comment]
Please do try the patched Meslo from https://github.com/romkatv/powerlevel10k/#fonts. It's based on Meslo from Nerd Fonts but with extra fixes.
