### ISSUE TITLE
Percentage Sign and Two Prompts.

### ISSUE THREAD

**Issue by AyaanZaveri** [romkatv/powerlevel10k#1445]
<img width="249" alt="Screen Shot 2021-06-12 at 4 00 54 PM" src="https://user-images.githubusercontent.com/63752541/121787958-603c5900-cb97-11eb-87ac-a49903e91c6d.png">

I tried to add this line "unsetopt PROMPT_SP" in my .zshrc, and it the percentage sign went away, but when I installed PowerLevel10K, it showed up again. Also, it shows the starting prompt twice. 

Any fix?

Terminal: Hyper
OS: MacOS Big Sur

**Comment by romkatv** [comment]
Don't use `unsetopt PROMPT_SP`. It'll make your shell lie to you. Try it. Run `zsh -f` and then run these commands:

1. `unsetopt PROMPT_SP`
2. `printf hello >/tmp/hello`
3. `cat /tmp/hello`

Here's how it would look:

![image](https://user-images.githubusercontent.com/1282067/121790079-9aeec300-cb90-11eb-9629-0e419c69219e.png)

Note how the last command doesn't output "hello" as if the file was empty. So, don't run `unsetopt PROMPT_SP`.

That percent that you see when you open a terminal is caused by a bug in your terminal. I'm guessing you are using Hyper? Try another terminal (any terminal is better than a Hyper, so you won't lose anything).

**Comment by romkatv** [comment]
> See [lxqt/qterminal#778 (comment)](https://github.com/lxqt/qterminal/issues/778#issuecomment-857735806).

Thanks for the reference!

> I had this problem in the past using Hyper and now with Kitty (this is a quite advanced and well implemented terminal).

Many terminals are suffering from bugs related to incorrect terminal dimensions during a short period after the TTY is created. Here are the ones I'm aware of:

- All terminals based on VTE up to a certain version. This includes GNOME Terminal, Tilix, Termite and Guake.
- All terminals based on `term.js`. This includes Hyper and the integrated terminal in Visual Studio Code.
- All terminals when running under Sway and Wayland.
