### ISSUE TITLE
Python virtualenv indicator disappears after directory change

### ISSUE THREAD

**Issue by marcelned** [romkatv/powerlevel10k#1498]
The visual indicator disappears even though the environment is still activate

<img width="884" alt="Screenshot 2021-07-22 at 14 07 26" src="https://user-images.githubusercontent.com/82392567/126636745-40cd13c3-ac53-4014-bebd-fb048c74f5fd.png">

Big Sur, Venv used

**Comment by romkatv** [comment]
Please post the output of the following command in the first and the second directory:

```zsh
() {
  emulate -L zsh -o extended_glob
  typeset -pm 'VIRTUAL_ENV|CONDA_PREFIX|CONDA_ENV_PATH|PYENV_VERSION'
  print -rC1 -- ./(../)#(.python-version)(#qN) ./(../)#(.tool-versions)(#qN)
}
```

> Venv used

What does this mean?

**Comment by marcelned** [comment]
Hi @romkatv 

Upon trying to recreate the anomaly it seems to work now.
I will see if I can recreate the issue.

By Venv I meant https://docs.python.org/3/library/venv.html. Sorry for the ambiguous language.

**Comment by romkatv** [comment]
Closing as Not Reproducible for now.

If you figure out how to reproduce it, please either reopen this issue or file a new one. If you do, specify how you are using venv. I'll need the exact commands in order to be able to reproduce this myself. You've listed `cd chapter09` command -- this is great; I'll need the same level of specificity for the rest of the setup that is necessary to reproduce this.
