### ISSUE TITLE
Different prompt color if previous command was not sent

### ISSUE THREAD

**Issue by Kyuuhachi** [romkatv/powerlevel10k#1508]
If I write half a command but decide to throw it away with `^C`, the succeeding prompt is red just like if it was executed but failed. It would be nice if that prompt turned gray or something instead.

There are two different ways that could be done in, either graying out the not-sent prompt and retaining the color of the succeeding prompt, or graying out the succeeding prompt. The latter would be more in line with how the prompt color currently works, but I feel like the former might feel more natural nevertheless.

**Comment by romkatv** [comment]
Would `^U` work for you instead of `^C`?

**Comment by Kyuuhachi** [comment]
That seems to only clear the current line in multi-line commands. Also, years of muscle memory.

**Comment by romkatv** [comment]
You can clear the whole buffer with `kill-buffer` widget. It's bound to `^X^K` by default but you can rebind it. Using this widget seems like a better UX to me because scrollback won't contain the command that wasn't executed.

If you really want `^C` to do something different from what it does now, send a PR. I'll merge it if it's high quality and not very large.

**Comment by Kyuuhachi** [comment]
Okay, fair enough. Maybe I could just bind `^C` to `kill-buffer`.
