### ISSUE TITLE
How to properly share the configuration across devices?

### ISSUE THREAD

**Issue by diogenes1oliveira** [romkatv/powerlevel10k#1509]
I synchronize a Dropbox folder with my oh-my-zsh settings, so I thought that just symlinking the ~/.p10k.zsh would be enough. But the configuration wizard keeps on showing up and my settings are not applied. Also, this error keeps on showing up (it seems to be looking for gitstatus relative to the .p10k.zsh file):

```
_p9k_init_vcs:source:47: no such file or directory: /home/.../custom/zsh/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh                                                                                                    
```

Is there a guide on how to do this? What other files does powerlevel10k require?

**Comment by romkatv** [comment]
When you start zsh, it sources a bunch of rc files. See the full list here: https://zsh.sourceforge.io/Intro/intro_3.html. So if you want to have the same setup on several machines, you need to share the rc files. If any of the rc files source other files, you'll need to share them too.

In practical terms it means you need to share `~/.zshrc`, `~/.p10k.zsh` (because it's sourced by `~/.zshrc`) and the whole `powerlevel10k` directory (even though you can just clone it on every machine).

**Comment by romkatv** [comment]
> What other files does powerlevel10k require?

Powerlevel10k requires all files from its own repo (that is, you shouldn't delete anything after you clone it). It does not require anything else. The configuration produced by `p10k configure` is stored in `~/.p10k.zsh`. If you want to save the results of `p10k configure`, save `~/.p10k.zsh`. `p10k configure` also adds a few lines to `~/.zshrc` if they aren't there already. Hence you'll want to save `~/.zshrc` after you run `p10k configure`.

**Comment by diogenes1oliveira** [comment]
@romkatv Thanks for the prompt response! I realized that I had just done something like this in my `.zshrc`, instead of symlinking the file:

```
source ~/Dropbox/custom/.zshrc
```

So powerlevel10k edited this file directly, of course. So I edited and added manually those lines and it worked. Now my symlinks look like this:

```
.zshrc -> /home/worker/Dropbox/custom/zsh/profile.zsh
.p10k.zsh -> /home/worker/Dropbox/custom/zsh/themes/.p10k.zsh
```

I'm not sure if a new installation would follow the symlink, but for not it's working. Thanks!
