### ISSUE TITLE
Customize path?

### ISSUE THREAD

**Issue by avamsi** [romkatv/powerlevel10k#1518]
Part of my pre-powerlevel10k prompt config looks like this --

``` shell
path() {
  if [[ $PWD =~ '/long/useless/path/(.+)/repo_root(.*)' ]]; then
    print "/.../${match[1]}/repo_root${match[2]}"
  else
    print '%~'
  fi
}

PROMPT="...:[$(path)]..."
```

-- where, if the current working directory is `/long/useless/path/$branch/repo_root/potentially/useful/path`, it always gets truncated to `/.../$branch/repo_root/potentially/useful/path` on the prompt.

1. Can I do this with powerlevel10k?
2. I see that powerlevel10k has some logic to automatically truncate long paths -- is there a way I can tell it not truncate "$branch" in my working directory?

**Comment by romkatv** [comment]
Add this to `~/.zshrc`:

```zsh
hash -d p=/long/useless/path
```

This will establish a bidirectional mapping between `~p` and `/long/useless/path` which works just like the mapping between `~` and `$HOME`. You can type `cd ~p/my_project` and it'll just work. Tab completion will work, too (`cd ~p/<TAB>`). Prompt will look nicer, etc.

You can a different name instead of `p` and it's not limited to a single character. You can also create more than one mapping of this kind.

**Comment by avamsi** [comment]
Neat! I would still have preferred if there was a way to customize the prompt myself (if I could highlight $branch in a different color, for example) but this works for me, so feel free to close if you'd like. Thanks!
