### ISSUE TITLE
Newline appears before prompt

### ISSUE THREAD

**Issue by amirashabani** [romkatv/powerlevel10k#1525]
When I open a new terminal, sometimes, a newline is added before the prompt:

![powerlevel10k](https://user-images.githubusercontent.com/23696447/128634697-0e5d36a1-fc39-4ff8-8ada-a85f07ce30c0.png)

Shell: zsh 5.8
WM: bspwm
Terminal: alacritty

And it's already up to date.

**Comment by romkatv** [comment]
This is caused by a bug in the terminal you are using.

**Comment by romkatv** [comment]
More specifically, the terminal reports incorrect TTY dimensions for a short time after the TTY is created. This may be a bug in the WM rather than the terminal (the WM creates a terminal and then quickly resizes it). Either way there is nothing I can do about it. You should be able to reproduce this issue without powerlevel10k by adding the following at the top of `~/.zshrc`:

```zsh
PS1='> '
RPS1='<'
ZLE_RPROMPT_INDENT=0
return
```
