### ISSUE TITLE
powerlevel10k is WONDERFUL <3

### ISSUE THREAD

**Issue by ahillio** [romkatv/powerlevel10k#1529]
Wow.  I began using powerlevel9k solely because it was the only prompt I could find that was git-aware and had a vi-mode indicator.   I used it for a long time hating the distracting blobs of color the default config placed on my screen.  Finally I got around to customizing the colors and in doing so found that it's discontinued and powerlevel10k has taken its place...

This is definitely an order of magnitude beyond any other prompt I've seen.  The "transient" setting is sublime, and the segments that only appear when they're relevant to the command that's being typed is a similarly great addition.  Bravo.

And for my personal taste, the "lean" option in the config wizard results in a decently colored prompt that I don't have to customize at all.

(not to mention the fact that you then helped me get it working when I couldn't get the vi-mode to toggle)

THANK YOU!!!

**Comment by romkatv** [comment]
Thanks for the kind words 🤗 

Great choice w.r.t. transient prompt and lean style. These are my favorites. I can also highly recommend a two-line prompt because thanks to transient prompt you get all the benefits (commands start from fixed offset and more space for typing commands) without the downsides (scrollback is still as dense as before). Empty line before prompt (this is called "sparse" in the wizard) is also a good and for the same reason. Lastly, choose "few icons" rather than "many icons" to get rid of useless decorative icons while preserving the functional ones. I suppose you've already figured out that you don't need `vi_mode` when using lean style because `prompt_char` reflects the current keymap.

There is a bit more info w.r.t. productivity-focused configuration here: https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard

**Comment by ahillio** [comment]
Yes those were all the options I chose!  I'm very opinionated about this: this is how the prompt should be :D

For years, I don't know how many, I suffered from the distracting blobs of color that my old prompt smeared the terminal with, violating the #1 principle of design (emphasis and hierarchy).  

And now with p10k.zsh this out-of-the-box configuration (along with
#1539) I've got a perfect prompt.

Oh, let me not forget to praise the auto-truncating of paths where `~/code/web/clients/WPP/docroot/themes/custom/wpp_bootstrap/css` will be condensided to `~/code/web/c/WPP/d/t/cu/wpp_bootstrap/css` -- brilliant!

**Comment by romkatv** [comment]
I'm happy that you are happy 😄 

Closing as acknowledged and appreciated.
