### ISSUE TITLE
Prompt not working via ssh

### ISSUE THREAD

**Issue by fheusel** [romkatv/powerlevel10k#153]
Hi, I'm using powerlevel10k with oh-my-zsh on macOS 10.14.6 (zsh is version 5.7.1 from brew) with the `MesloLGS NF` font from your dotfiles-repo.
When connecting via ssh the prompt won't be rendered correctly and I get this error: `_p9k_get_icon:13: character not in range`
![screenshot](https://user-images.githubusercontent.com/1217774/62476502-6dbc7700-b7a7-11e9-94ab-f0c3dac8d399.png)

**Comment by romkatv** [comment]
The problem is that the locale in your SSH session isn't using utf-8 encoding. If you try to print a non-ascii character with `print '\u2B50'` or `echo $'\u2B50'`, you'll get "character not in range" error. It's not affecting just p10k but everything you run in the SSH session. To fix this problem you need to run `locale -a`, pick a locale that has `utf8`, `utf-8` or `UTF8` or `UTF-8` in its name, and export `LANG` from your `~/.zshrc` or `~/.zshenv` with the value set to the chosen locale.

For example:

```zsh
echo 'export LANG=C.UTF-8' >>! ~/.zshenv
```

Or:

```zsh
echo 'export LANG=en_US.UTF-8' >>! ~/.zshenv
```

I've update powerlevel10k so that it works when your terminal actually supports utf-8 but your locale says that it doesn't. If you update powerlevel10k and generate a new config with `p10k configure`, it'll work even with a misconfigured locale. However, you really need to fix your locale to avoid issues with all programs you'll run.

**Comment by fheusel** [comment]
Thank you very much for your quick and helpful response. I was not aware that my locale settings are not in effect in the SSH session.
