### ISSUE TITLE
Feature Request: prompt_char segment also sets PS2,PS3,etc.

### ISSUE THREAD

**Issue by iboyperson** [romkatv/powerlevel10k#154]
Right now to get a similar effect to this I am having to use:
```zsh
typeset -g {PS2,PS3}="%(?.%F{$__PASTEL_COLORS[blue]}$PASTEL_PROMPT_CHAR%f.%F{$__PASTEL_COLORS[red]}$PASTEL_PROMPT_CHAR%f) "
```
Note the vars are part of [p9k-theme-pastel](https://github.com/iboyperson/p9k-theme-pastel) a p9k/p10k theme I am making.
* $__PASTEL_COLORS: Array of color codes that changes based on a theme compatibility mode
* $PASTEL_PROMPT_CHAR: Displayed char in my case '❯'

This is able to partly replicate the functionality of prompt_char, however it lacks the setting of different VI mode chars. It would be nice if either prompt_char sets this or  there was a way to externally access the char prompt_char displays. I will include screenshots of the visual difference below.

**With:**
![Screenshot_20190805_191722](https://user-images.githubusercontent.com/10000914/62506467-a9f6d400-b7b5-11e9-84f9-0692ecbbdf9f.png)
![Screenshot_20190805_192106](https://user-images.githubusercontent.com/10000914/62506612-2e495700-b7b6-11e9-9b1f-6de7830e665b.png)

**Without:**
![Screenshot_20190805_191858](https://user-images.githubusercontent.com/10000914/62506546-e296ad80-b7b5-11e9-84f4-114639898067.png)
![Screenshot_20190805_192022](https://user-images.githubusercontent.com/10000914/62506596-1c67b400-b7b6-11e9-8b7d-0f3e82a01a31.png)

**Comment by romkatv** [comment]
I could set `P9K_PROMPT_CHAR` to `❯`, `❮` or `Ⅴ` but it would be too limiting as you wouldn't be able to use a different symbol in `PS2`. A more flexible solution would be to set `P9K_PROMPT_CHAR` to `OK_VIINS`, `ERROR_VICMD`, etc. Then you could use it to index into your own assoc array.

What do you think?

P.S.

A few aside notes.

"Without" screenshots look better to me as they show valuable information on every line. Knowing that I have an open quote, function or `for` loop is useful. "With" screenshots duplicate the same symbol on every line, which I already can see.

In the default p10k configs `dir` uses this shortening: https://asciinema.org/a/258376. The logic is explained in the description. The nice thing about it is that shortening becomes more aggressive when prompt doesn't fit, so you don't have to commit in advance to some cutoff. You can still specify that directory shouldn't take more than X columns even if there is enough screen space (`POWERLEVEL9K_DIR_MAX_LENGTH=80` in the default configs) but this limit can be relatively high because directory _will_ get shortened if it doesn't fit. This logic can in theory be implemented for many shortening strategies but for now it's only supported in `truncate_to_unique`, which is simply my personal favorite.

What's the point of supporting p9k? Anyone who finds your project will know that p10k exists. I think only people unaware of p10k (and p9k devs) use p9k. Supporting p9k increases the complexity of your project for no apparent benefit. Or am I missing something?

In p10k you can set background to empty to make it transparent. You can also set background for all segments with one parameter: `POWERLEVEL9K_BACKGROUND=''`.

Is there a reason to call functions such as `_pastel_config_vpn_ip` only if the corresponding segment is in use? Why not set all these parameters always, unconditionally? It'll simply code a great deal and will allow for hot config updates. Basically, in p10k you an change any parameter on the fly. E.g., you can add a segment by typing `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=vpn_ip`. With your approach this will display unstyled segment because you aren't applying styling options for segments that weren't in use during loading.

**Comment by romkatv** [comment]
> I could set `P9K_PROMPT_CHAR` to `❯`, `❮` or `Ⅴ` but it would be too limiting as you wouldn't be able to use a different symbol in `PS2`. A more flexible solution would be to set `P9K_PROMPT_CHAR` to `OK_VIINS`, `ERROR_VICMD`, etc. Then you could use it to index into your own assoc array.
> 
> What do you think?

Before I implement this feature I'd like to know whether it'll solve your problem.

**Comment by iboyperson** [comment]
Either implementation would likely solve my problem. 

P.S.
After reading your side notes I am working on changing the theme to fit your suggestions. Regarding the liking the "Without:" part, do you know if it would be possible to make PS2 appear as something like "dquote❯" in a quote and "for❯" in a for loop?

**Comment by romkatv** [comment]
> Either implementation would likely solve my problem.

OK, I'll implement it then.

> After reading your side notes I am working on changing the theme to fit your suggestions.

By the way, what do you think about taking `p10k-lean.zsh` and modifying it? Adding support for customizable pastel colors and replaceable symbols should be straightforward. You'll get the benefit of fine-tuned `dir`, `vcs` and a few other contexts that such out of the box but work great in the standard configs.

> do you know if it would be possible to make PS2 appear as something like "dquote❯" in a quote and "for❯" in a for loop?

You are looking for `%_`. This thing expands to `for`, `dquote`, etc.

FWIW, I like the default. Having a whole bunch of `❯` simultaneously flip to `❮` when I switch to command mode would be weird. What function could that serve?

**Comment by romkatv** [comment]
I added `P9K_PROMPT_CHAR_STATE`, which can take one of 6 values: `{OK,ERROR}_VI{INS,CMD,VIS}`. It's updated when `prompt_char` is rendered.

While testing it I noticed that `prompt_char` doesn't update when you change keymap while `PS2` is visible. It seems like it's not possible to reexpand prompt in that state. Not sure whether it's bad or good for you. If you create a new line with `esc-enter`, `prompt_char` changes as expected when keymap changes.

Let me know if you find a good use for `P9K_PROMPT_CHAR_STATE`. If not, I'll remove it.

**Comment by iboyperson** [comment]
I will defiantly let you know. I am currently experimenting with taking `p10k-lean.zsh` and modifying it. My only worry is modifying it correctly with the way you have it implemented (your zsh experience is far greater than mine) while keeping the features I valued in my theme like tty compatibility.

**Comment by iboyperson** [comment]
Thinking more about this with the fact that PS2 cant change its char after is is displayed anyway or if it can I am not skilled enough to make it do so, I would say it is probably safe to remove this feature if you so desire and I could go back to checking exit codes (Which I am in essence doing in the above function just with fancy P9K porcelain).

**Comment by romkatv** [comment]
Removed `P9K_PROMPT_CHAR_STATE`. It's not that it's difficult to maintain but, as you said, it doesn't seem useful.

**Comment by romkatv** [comment]
>  PS2 cant change its char after is is displayed

PS2 can change alright. It's just when you have PS2, you cannot change any prompt line other than the last. As a quick test, this works:

```zsh
PS2='${${${KEYMAP:-0}:#(vicmd|vivis|vivli)}:+❯}'
PS2='${'$p':-${${(M)${:-$KEYMAP$_p9k_region_active}:#vicmd0}:+❮}}'
PS2='${'$p':-Ⅴ}'
PS2="$p "
```

This will change `PS2` on the last line when keymap changes. It uses internal p10k parameters though, so please don't use it.

This makes your original request much more useful. Given that `prompt_char` does not change when keymap updates, but the last PS2 does, there is value is settings PS2. Without it you cannot see your current keymap.

I also noticed that `%_` is broken. If you hook zle widgets, `%_` will reflect the state of the hooks when they trigger. As a result, `%_` turns into `cmdand` when I change keymap. It might be possible to work around this problem by hooking even more zle widgets and using something lower-level in place of `%_`.

I'll reopen this issue and let it simmer.

**Comment by iboyperson** [comment]
My Zsh ability is not high enough to implement or understand a PS2 such as the above so I likely can't do much involving this

**Comment by romkatv** [comment]
I wasn't suggesting that you try to pursue this. I've reopened the issue to provide something in p10k that would make setting PS2 in this way easy.

**Comment by iboyperson** [comment]
Ah okay I misunderstood. Sorry

**Comment by romkatv** [comment]
`%_` is really finicky. When PS2 is visible, calling reset-prompt is ill-advised as it'll almost always substitute random garbage in place of `%_`. This makes it infeasible to implement the same kind of prompt char for PS2 as for PS1. By "the same kind" I mean reflecting vi mode.

Without the ability to display vi mode in PS2 there is little value in showing a custom prompt char there. I'm going to close this issue as I don't plan to pursue it further given this obstacle.
