### ISSUE TITLE
generate new line for each TAB action

### ISSUE THREAD

**Issue by CyrilTaylor** [romkatv/powerlevel10k#155]
Ubuntu Server 18.04.1 on Xshell SSH

- Issue 1: It will generate new line on the top of current prompt for each TAB action

- Issue 2:  overfill POWERLEVEL9K_RULER_CHAR to next line

![snipaste_20190806_184924](https://user-images.githubusercontent.com/12631466/62534284-59e24500-b87b-11e9-95ab-f6b30b2b03f7.png)

**It's only appear in SSH mode.**

**Comment by romkatv** [comment]
Seems like your terminal incorrectly displays some glyphs. More specifically, it renders some single-width glyphs as if they were double-width. Some terminals have a settings that causes this sort of badness. For example, if you tick "Treat ambiguous-width characters as double width" in iTerm, your prompt will break in exactly this way.

This issue is not specific to Powerlevel10k. You can see the same sort of brokenness by typing the following command:

```zsh
PROMPT="$(print_icon HOME_ICON) $(print_icon VCS_GITHUB_ICON) > " zsh -df
```

Once prompt appears, hit `Ctrl-R`. You'll see the cursor jump around. Also try typing `ls` and then hit TAB.

You need to fix your terminal to not fail in this test. Once you do, Powerlevel10k will work correctly.

**Comment by CyrilTaylor** [comment]
It's work fine with hit TAB in your command, so I think issue 1 & 2 is a bug of Powerlevel10k.

They appear only with **git dir in SSH mode**, maybe there is a bug with git status check.

![snipaste_20190807_103711](https://user-images.githubusercontent.com/12631466/62590662-aa9b8180-b8ff-11e9-8ace-eaf9cc4e0828.png)

![snipaste_20190807_104810](https://user-images.githubusercontent.com/12631466/62591029-dff49f00-b900-11e9-97f5-c9e5c4458f00.png)

**Comment by CyrilTaylor** [comment]
I login in with other ssh client, it's work fine, you are right, it's an issue of Xshell.

**Comment by romkatv** [comment]
> I login in with other ssh client, it's work fine, you are right, it's an issue of Xshell.

:+1: 

![screenshot](https://user-images.githubusercontent.com/12631466/62590662-aa9b8180-b8ff-11e9-8ace-eaf9cc4e0828.png)

There is missing space between `>` and `ls`. It disappeared when you pressed TAB. This is what I meant by cursor jumping around.

**Comment by CyrilTaylor** [comment]
update the solution for the user of xshell

Session Properties -> Terminal -> Treat ambiguously sized characters as wide, uncheck it.

![snipaste_20190809_115646](https://user-images.githubusercontent.com/12631466/62753178-fcc5d980-ba9c-11e9-8263-52f975b41156.png)
