### ISSUE TITLE
Does commenting out prompt elements speed up prompt?

### ISSUE THREAD

**Issue by trallnag** [romkatv/powerlevel10k#1580]
Even though p10k is really fast, does commenting out prompt elements speed up the prompt? Or are the changes visual only?

**Comment by romkatv** [comment]
> does commenting out prompt elements speed up the prompt?

Yes, it does. You can measure by how much with [zsh-prompt-benchmark](https://github.com/romkatv/zsh-prompt-benchmark).

**Comment by trallnag** [comment]
ok thanks for the info

**Comment by romkatv** [comment]
Without knowing by how much you can speed up prompt you cannot say whether it's worth doing it. For example, if you lift your computer a bit higher above the ground, it'll also speed up prompt because time runs faster for objects that are further away from earth. This is obviously not a practical way to speed up your zsh prompt.
