### ISSUE TITLE
Different colors and arrow

### ISSUE THREAD

**Issue by spacecat** [romkatv/powerlevel10k#1589]
Hi,

1. Is there a way to set the entire blue prompt bar to the exakt same shade of a color?
2. How to fix the arrow on the right side. I don't think it's supposed to look like that?
![Screenshot 2021-10-01 at 17 35 28](https://user-images.githubusercontent.com/866622/135649113-77decfbe-8add-41f7-b43e-3e339e2f9e1b.png)
Thanks!

**Comment by romkatv** [comment]
The issue on the left happens because your terminal renders foreground blue and background blue with different hues. Some terminals have a setting to disable this obnoxious behavior. Others don't.

The issue on the right happens because in your terminal the background black color is the same as the default background color. You can fix it by changing either of these colors in the terminal config. Alternatively, you can open `~/.p10k.zsh` and change all segments that use background color 0 to use some other color.

You can avoid all these issues and many more by running `p10k configure` and choosing *Lean* style instead of *Rainbow*.

**Comment by spacecat** [comment]
Thanks, I switched to iTerm2 and now it looks as it should!

**Comment by romkatv** [comment]
Great!
