### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by GrotenM** [romkatv/powerlevel10k#1633]
Hey,

im using powerlevel10k on a wsl ubuntu system. After upgrading to Windows 11 im getting the following error.

```
[ERROR]: gitstatus failed to initialize.


  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh
```

When i add the command to my zshrc i get the following error:

`(eval):1: command not found: Sleeping`

Cause everything i google for gitstatus failed to initialize is related to p10k i thought this is the right place.

Hope you can help - many thanks in advance!

```text
  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.13.1636661342.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 21 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 21 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                  17' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.13.1636661342.1.fifo
    (anon):sysopen:62: can't open file /tmp/gitstatus.POWERLEVEL9K.1000.13.1636661342.1.fifo: no such file or directory
    +(anon):62> return

  System information:

    zsh:      5.8
    uname -a: Linux MaiksPC 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by romkatv** [comment]
This looks pretty bad. I don't have access to Windows  11 and won't have it for at least a year. I don't think I can help you with this. Since this broke when you updated a microsoft product, you might have better luck asking microsoft people to help you. I wouldn't hold my breath though.

**Comment by romkatv** [comment]
If this is the full log, it means something has deleted files from `${TMPDIR:-/tmp}` while zsh was initializing. It might be something you invoke from `~/.zshrc` or other zsh startup files. Try disabling everything except powerlevel10k.

**Comment by GrotenM** [comment]
Hey, 
no problem. Thanks for your effort! For me it seems like a wiered timing / permission issue. When using bash im getting the following error.

`Sleeping for 1 second to let systemd settle`

But all of them just occure once after a restart or wsl --shutdown which of course is basically the same. So very confusing.

**Comment by romkatv** [comment]
Can you report this against https://github.com/microsoft/WSL? The fact that you are getting `(eval):1: command not found: Sleeping` means that the message `Sleeping for 1 second to let systemd settle` gets printed to stdout somewhere inappropriately. In addition, files in `/tmp` disappear for no reason when WSL is booting. This doesn't look good. I'd appreciate if you post a link to the issue against wsl.

**Comment by gaFregatto** [comment]
Hi @GrotenM, I had the exact same error when starting my wsl2 ubuntu 20.04 on windows 10 and the cause for was ubuntu-wsl2-systemd-script not installing everything properly. Since there is nothing indicating that your problem is solved, I think is worth taking a look here https://github.com/DamionGans/ubuntu-wsl2-systemd-script/issues/37#issuecomment-671267959

**Comment by VentusTWY** [comment]
VentusTWY commented now
[VentusTWY](https://github.com/VentusTWY)
[now](https://github.com/romkatv/powerlevel10k/issues/706#issuecomment-4098766758)
Hey I have got the same issue on my enterprise mac (with p10k on zsh). I believe its because earlier it got blocked by Santa when I was trying to enable Go binaries. Got Claude to do the fix for me:
The fix was doing codesign --sign - --force /path/to/gitstatus-darwin-arm64

This gives an adhoc signature to the binary telling it has been explicitly approved
