### ISSUE TITLE
python venv name not shown property

### ISSUE THREAD

**Issue by niguiecandy** [romkatv/powerlevel10k#1663]
Hi, 
powerlevel10k does not display python venv name properly.
In fact, it doesn't show the name at all.
It used to display correctly until recently, but unfortunately I'm not sure exactly when this started happening.

zsh 5.8 (x86_64-apple-darwin20.1.0)

If additional infos are required, please let me know.
Thank you!

**Comment by donaldgifford** [comment]
+1

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by niguiecandy** [comment]
![스크린샷 2021-12-10 오후 5 13 36](https://user-images.githubusercontent.com/39695857/145540236-afec2bbe-b844-47a3-8ecd-131640101fb0.png)

Above  : powerlevel10k 1.15.0
Below : eastwood

Note that (.venv) is not displayed on the upper panel.

**Comment by romkatv** [comment]
Do you want to see `.venv` instead of `test-git` when you activate a virtual environment in `test-git`? If so, you can do that as follows:

1. Open `~/.p10k.zsh`.
2. Add this (preferably somewhere next to other `POWERLEVEL9K_VIRTUALENV_*` parameters):
  ```zsh
  # When a virtual environment name is generic and meaningless (such as ".venv"),
  # Powerlevel10k by default shows the name of the parent directory. By setting
  # POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=() we disable this.
  typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()
   ```
3. Restart zsh with `exec zsh`.

Note that your prompt will be less informative: `.venv` doesn't tell you *which* environment you've activated while `test-git` does.

**Comment by niguiecandy** [comment]
Thank you for the quick reply!

> Do you want to see `.venv` instead of `test-git` when you activate a virtual environment in `test-git`? If so, you can do that as follows:

No, I want '.venv' be displyed next to pwd, as it used to be. powerlevel10k used to display (.venv) just like eastwood does above.

**Comment by romkatv** [comment]
Powerlevel10k never used to display `(.venv)` to the left of the current directory.

You can configure it this way if you want. Firstly, note that Powerlevel10k does display the name of the virtual environment. You can see it on the right hand side: "Py" says that you have an active python virtual environment, and "test-git" tells you the name of the virtual environment. As I mentioned above, you can configure Powerlevel10k to display ".venv" instead of "test-git" as the name of the environment. You will see less information (because ".venv" doesn't tell you *which* virtual environment is active) but you can do that nonetheless.

You can also move virtual environment from right to left. Like this:

1. Open `~/.p10k.zsh`.
2. Add `virtualenv` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` array.
3. Remove `virtualenv` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` array.
4. Restart zsh with `exec zsh`.

**Comment by niguiecandy** [comment]
huh, something has changed.
```
# Custom icon.
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='venv'
```
![스크린샷 2021-12-10 오후 5 36 08](https://user-images.githubusercontent.com/39695857/145543035-063dc9ff-b798-43ad-bad5-15fff3d92655.png)

Seems like some behavior has been changed, I guess? It used to display just like eastwood does, and i've never changed any settings myself before

**Comment by romkatv** [comment]
> Seems like some behavior has been changed, I guess?  It used to display just like eastwood does, and i've never changed any settings myself before

Nothing in Powerlevel10k has been changed w.r.t. python virtual environment. Powerlevel10k never displayed python virtual environment like eastwood.

**Comment by niguiecandy** [comment]
This is getting scary...  I can't trust my own memory!

Anyway, thank you for your kind reply! Have a great weekend!

**Comment by romkatv** [comment]
> This is getting scary... I can't trust my own memory!

It's a good thing that you don't have to. The full history of all powerlevel10k changes is public. You can checkout any commit from powerlevel10k and check how your prompt looks like.

> Anyway, thank you for your kind reply! Have a great weekend!

You are welcome. Have a great weekend yourself!
