### ISSUE TITLE
How to remove pesky newline in text output?

### ISSUE THREAD

**Issue by irahorecka** [romkatv/powerlevel10k#1680]
I recently configured powerlevel10k for MacOS (Catalina 10.15.7) and found pesky newline spaces between items in the terminal (image below):

<img width="414" alt="Screen Shot 2021-12-19 at 9 36 47 AM" src="https://user-images.githubusercontent.com/48743671/146685201-92667f5e-148e-4aa7-a88e-2fb38937c47b.png">

Is there any way to remove this?

**Comment by romkatv** [comment]
Firstly, see https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect. Powerlevel10k has no effect on the output of `ls`.

The problem you are experiencing is caused by a bad terminal or bad terminal settings. If your terminal has settings, you need to reduce spacing between lines. If your terminal does not have settings, try a different terminal.

**Comment by irahorecka** [comment]
@romkatv You are very right - thanks for the clarification. It was an iTerm2 issue.

**Comment by romkatv** [comment]
I'm glad you found the right setting. With the correct value the sharp end of prompt should attach cleanly to the rest of it. Like here:

![p10k](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png)
