### ISSUE TITLE
Symbols not showing with p10k configure

### ISSUE THREAD

**Issue by johnvanhienen** [romkatv/powerlevel10k#1720]
When running p10k configure it doesn't show any of the symbols. I've tried to check as many possibilities from different issues, so i've checked if zsh was the correct version and if it supported truecolor (according to https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard): 
![image](https://user-images.githubusercontent.com/7302372/149586800-93638476-e9a8-4d42-addd-cd5a810075e2.png)

Since `p10k configure` didn't prompt for the font, I've installed the 4 fonts manually (as suggested by https://github.com/romkatv/powerlevel10k#manual-font-installation):
![image](https://user-images.githubusercontent.com/7302372/149586996-7a702432-496c-4150-9602-83a0ce97aab3.png)

And configured it in iterm:
![image](https://user-images.githubusercontent.com/7302372/149587036-3c89992f-09fc-4e17-8728-c126b74ebafa.png)

I've restarted iterm numerous times and removed all config from .zshrc after trying different solutions (and the .p10k.zsh file). However, it still won't show any symbols:

![image](https://user-images.githubusercontent.com/7302372/149587261-0a7e2f2f-4c64-4130-af16-b1af5f90f6ff.png)

Any guidance or additional debugging steps that I can perform to fix this issue? Thank you in advance!

**Comment by romkatv** [comment]
> And configured it in iterm: ![image](https://user-images.githubusercontent.com/7302372/149587036-3c89992f-09fc-4e17-8728-c126b74ebafa.png)

The font on this screenshot is not Meslo. You can see it by comparing "r" and "i" between your screenshot and [this one](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png).

There is no need to modify any zsh configs. What you need to do is to convince your terminal to use MesloLGS NF font.

I would try the following:

1. Verify that a different terminal can successfully use MesloLGS NF on the same machine. For example, try it with Terminal.app.
2. If the previous step succeeds, you'll know that the problem is with iTerm. Try resetting its settings. To do that you'll need to quit iTerm (use <kbd>⌘Q</kbd>) and then run `defaults delete com.googlecode.iterm2` from Terminal.app.
3. After resetting iTerm settings, open iTerm and run `p10k configure`.

**Comment by johnvanhienen** [comment]
Good catch, I didn't notice that the font was being changed. The profile within iterm seemed to be corrupted. Creating a new profile and adjusting the font resolved the issue. Thank you.

**Comment by romkatv** [comment]
Glad you got it working.

One more thing. Your screenshot of iTerm settings has *Use built-in Powerline glyphs* unchecked. Check it. It's good.
