### ISSUE TITLE
Feature Request: Support for Hermit

### ISSUE THREAD

**Issue by damienrj** [romkatv/powerlevel10k#1813]
Hello,
Side note, I am a long time user of powerlevel10k and just wanted to say it has been great.

I have been using hermit as a way to manage isolated, self bootstrapping tools for different projects. 
https://cashapp.github.io/hermit/

However, when using a normal zsh shell when I activate I get the spiral shell emoji and I have not been able to replicate that with powerlevel10k.  Would the best course of action to be making a new segment?
```

~/project$ . ./bin/activate-hermit
Hermit environment /home/user/project activated
project🐚~/project$
```

**Comment by romkatv** [comment]
Try this:

```zsh
function prompt_my_hermit() {
  if [[ -n $HERMIT_ENV ]]; then
    p10k segment -b blue -f red -i '🐚' -t "${${HERMIT_ENV:t}//\%/%%}"
  fi
}
```

Add `my_hermit` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. Colors can be customized just like for other prompt segments. See `p10k help segment` for docs.

**Comment by damienrj** [comment]
Thank you for the quick reply. That seems to work great a couple of follow up questions.  If I understand correctly there doesn't appear to be a way to have the icon after the text. Is that correct? Second, would it be okay for me to make a PR to add support?

**Comment by romkatv** [comment]
> If I understand correctly there doesn't appear to be a way to have the icon after the text. Is that correct?

You can remove `-i '🐚'` and embed the icon directly in the value of `-t`.

Alternatively, you can define `POWERLEVEL9K_MY_HERMIT_ICON_BEFORE_CONTENT=false`. This generic parameter works for all prompt segments.

> Second, would it be okay for me to make a PR to add support?

If you want to. If you implement it so that I can merge it without any changes, I'll merge it. If it requires changes, there is a good chance I'll do nothing. I don't consider this high priority because you can trivially implement this as a custom segment.

Note that you would need to find a different icon. The default icons in powerlevel10k cannot be wide because there are many terminals out there with bugs that get triggered by wide unicode symbols.

**Comment by damienrj** [comment]
Ah, that worked perfectly.  That is a good point about the different icon, if the project owners want to suggest a different (not wide icon) I will make a PR since based on how simple this change is with your help I would be able to merge it. But for now I will just add the directions to their page.  
Thanks again.
