### ISSUE TITLE
Segments printing only escape codes don't seem to work

### ISSUE THREAD

**Issue by aaronjensen** [romkatv/powerlevel10k#1815]
I'm trying to set up [vterm shell configuration](https://github.com/akermu/emacs-libvterm#shell-side-configuration) and attempting to use a segment to do it:

```sh
vterm_printf(){
  if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ); then
    # Tell tmux to pass the escape sequences through
    printf "\ePtmux;\e\e]%s\007\e\\" "$1"
  elif [ "${TERM%%-*}" = "screen" ]; then
    # GNU screen (screen, screen-256color, screen-256color-bce)
    printf "\eP\e]%s\007\e\\" "$1"
  else
    printf "\e]%s\e\\" "$1"
  fi
}

vterm_prompt_end() {
  vterm_printf "51;A$(whoami)@$(hostname):$(pwd)";
}

function prompt_trackdir() {
  p10k segment -i 'x' -t "%{$(vterm_prompt_end)%}"
}
function instant_prompt_trackdir() {
  p10k segment -i 'x' -t "%{$(vterm_prompt_end)%}"
}
```

If I do not include the icon, the segment does not work. If I do, it prints an icon and it works. Is there something that's preventing segments printing only escape codes from printing?

Thanks!

**Comment by romkatv** [comment]
Zero-length prompt segments without icons don't get printed. Imagine how they would look like with powerline style.

The shell code in the emacs-libvterm is not very good. It's doing up to 4 forks for something that requires none. The design is either unclear or weird. Do they really have a single escape sequence for marking the end of prompt and for sending the current working directory? The current working directory doesn't change on every prompt, so why should it be sent?

Anyway, you can try this:

```zsh
function vterm-integration() {
  emulate -L zsh
  if (( ! $+_vterm_integration )); then
    typeset -gi _vterm_integration
    return
  fi
  [[ -t 1 ]] || return
  local msg=${(%):-'51;A%n@%m:%/'}
  if [[ -n $TMUX && $TERM == (tmux|screen)(|-*) ]]; then
    printf '\ePtmux;\e\e]%s\a\e\\' $msg
  elif [[ $TERM == screen(|-*) ]]; then
    printf '\eP\e]%s\a\e\\' $msg
  else
    printf '\e]%s\e\\' $msg
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd vterm-integration
vterm-integration
```

Add it at the very top of `~/.zshrc`, even above the instant prompt preamble if you have it there.

This prints the escape sequence before the prompt rather than after it but it's not obvious whether it'll be better or worse.

NOTE: I didn't test this code.

**Comment by aaronjensen** [comment]
Thanks, though a part of its integration is that it is how it determines where the actual prompt is in the buffer, so I *think* it needs to run immediately after the prompt. I'll try this out, but is there a way to do that in case it is necessary?

**Comment by romkatv** [comment]
What can vterm possibly do by knowing where prompt ends? One of the most useful features of other terminals with shell integration is that they allow you to select the output of the last (or any other) command, copy it to clipboard, see it in pager, etc. This requires knowing where commands start and end. A mark that's in the middle of zle seems rather useless. It's unfortunate that vterm invented its own protocol instead of implementing OSC 133 and OSC 7. If they did the latter, you could get full integration with `POWERLEVEL9K_TERM_SHELL_INTEGRATION=true`.

Anyway, here's how you can inject stuff at the end of left prompt. First, add this at the very top of `~/.zshrc`:

```zsh
function vterm-integration() {
  emulate -L zsh
  typeset -g _vterm_integration
  local msg=${(%):-'51;A%n@%m:%/'}
  if [[ -n $TMUX && $TERM == (tmux|screen)(|-*) ]]; then
    printf -v _vterm_integration '\ePtmux;\e\e]%s\a\e\\' $msg
  elif [[ $TERM == screen(|-*) ]]; then
    printf -v _vterm_integration '\eP\e]%s\a\e\\' $msg
  else
    printf -v _vterm_integration '\e]%s\e\\' $msg
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd vterm-integration
vterm-integration
```

Then add this to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=' %{$_vterm_integration%}'
```

Once again, this code is untested.

**Comment by aaronjensen** [comment]
Thank you. Vterm is used in editors, so one of the things that they do is return your editor cursor to the start of the prompt if you move it away. Similar to how tmux would when you exit copy mode, but because there are so many ways to move the cursor vterm can't just remember where it was before you started a movement.

**Comment by romkatv** [comment]
Moving the cursor to the start of prompt will break zsh. Zsh tracks where the cursor is, and if the cursor is not where zsh expects it to be, things will break. So when vterm give you cursor back, it *has* to be where it was previously.

**Comment by aaronjensen** [comment]
Yeah, what I said is inaccurate. I meant that it's possible to move the Emacs cursor to the beginning of the prompt (or just know where it is for various functions). If the emacs integration with vterm actually wants to change the cursor location within zsh, it does it by sending arrow keys. The zsh cursor stays where it is otherwise.

**Comment by romkatv** [comment]
It depends on why emacs would want to move cursor to the beginning of prompt. Perhaps moving it to the start of prompt would be just as useful or just as bad. Anyway, you can experiment and choose what works better for you.

Closing as fixed.

**Comment by aaronjensen** [comment]
Thank you, this works for me. I appreciate the help and p10k.
