### ISSUE TITLE
Who do I get IP without internet speed ?

### ISSUE THREAD

**Issue by ebanDev** [romkatv/powerlevel10k#1880]
Hi, in the "right prompt elements" i'd like to have the private ip of my machine, but without the internet speed, how could I do that ? 🤔

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, uncomment `ip` prompt segment within `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and then find this block: https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-lean.zsh#L1476-L1491

Read the comments and adjust parameter value(s) to your liking.

You can also use `vpn_ip` segment instead of `ip`. With `POWERLEVEL9K_VPN_IP_SHOW_ALL=true` you can see all ip addresses of network adapters of your choice.

**Comment by ebanDev** [comment]
Oooh ok thx !! :D

**Comment by romkatv** [comment]
Have you tried it? Does it do what you want?

**Comment by ebanDev** [comment]
Yeah it does ! Thank you ! :D

**Comment by romkatv** [comment]
You are welcome.
