### ISSUE TITLE
Feature request: support "nix shell" (flakes) for nix_shell segment

### ISSUE THREAD

**Issue by evilmav** [romkatv/powerlevel10k#1892]
Nix now supports new command style, using `nix shell` and `nix develop` commands with `flake.nix` in addition to `nix-shell`. See [Flakes](https://nixos.wiki/wiki/Flakes). The `nix_shell` segment does not seem to be currently activated under `nix shell`. This would be really helpful.

**Comment by SebTM** [comment]
Hey, I was looking for a solution as there is https://github.com/chisui/zsh-nix-shell now which set's the expected variable `IN_NIX_SHELL` to "pure" or "impure" also "NIX_SHELL_PACKAGES" and "name" is set set usage-section.

**Comment by romkatv** [comment]
@SebTM What seems to be the problem?

**Comment by SebTM** [comment]
Ah you are right, that pure/impure is working - I was wondering how I can change the prompt with powerline10k (like done in the example to show some extra infos like: https://gist.github.com/chisui/0d12bd51a5fd8e6bb52e6e6a43d31d5e) and tbh. assumed that it's not working (as the issue is open) and searching for a PR implementation to try it myself but very cool that the base-work is already done :)

**Comment by romkatv** [comment]
I've closed the issue to avoid this sort of confusion.

In general, I would highly recommend first trying things out before looking for open issues.
