### ISSUE TITLE
icons not shown correct.

### ISSUE THREAD

**Issue by gapplef** [romkatv/powerlevel10k#19]
zsh 5.4.2, Ubuntu 18.04

I set `POWERLEVEL9K_SHORTEN_DIR_LENGTH=2`
With `powerlevel9k` I have:
![Screenshot-9](https://user-images.githubusercontent.com/5604665/54338018-aaa69680-466b-11e9-9383-11212403300e.png)

While with `powerlevel10k`:
![Screenshot-10](https://user-images.githubusercontent.com/5604665/54338020-ab3f2d00-466b-11e9-9bdf-12f39ebd64cc.png)

**Comment by romkatv** [comment]
Ouch, this is embarrassing. Fixed.

Thanks for the report.

**Comment by mvcouwen** [comment]
I have a similar issue with custom custom git icons from a nerd font:
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uf408'
POWERLEVEL9K_VCS_BRANCH_ICON='\ue0a0'

<img width="206" alt="Schermafbeelding 2019-06-21 om 10 46 44" src="https://user-images.githubusercontent.com/44055511/59910343-fb1f5400-9411-11e9-949f-75b79c6a2139.png">

I can however manually fix it by inserting some spaces...

**Comment by romkatv** [comment]
> I can however manually fix it by inserting some spaces...

The problem is that `\uf408` is within a _Private Use Area_ Unicode range. Neither your terminal nor ZSH have any idea about properties of this character. For example, they cannot know how wide the character is. In some fonts this character is narrow, in others it's wide. When in doubt, your terminal assumes the character is narrow (takes as much space as a single letter such as `x`). In this case the character is in fact wide, taking the space of `xx`.

Adding a space after a wide character that your terminal thinks is narrow is the correct (and only) solution. You might want to add spaces after other icons, too. For example, your prompt might look better with a space after the folder icon, and another space after branch icon. Keep in mind that once you switch to another font, you may end up with too many spaces in your prompt, so you'll have to change icons in your theme config.
