### ISSUE TITLE
Remove the "kube" from kubecontext

### ISSUE THREAD

**Issue by mtavaresmedeiros** [romkatv/powerlevel10k#1929]
Hello, I would like to know if is possible to remove the" Kube" from the kubecontext.

(☸️ | **kube** clustername:namespace)

Thank you and nice work.

**Comment by romkatv** [comment]
Can you post a screenshot of your prompt that has "kube" in it?

**Comment by mtavaresmedeiros** [comment]
Sure.
![Screenshot 2022-07-06 at 17 47 01](https://user-images.githubusercontent.com/14811074/177591359-284ba577-957b-4158-bd4f-8b51b8d8d1e6.png)

Thank you.

**Comment by romkatv** [comment]
This doesn't look like prompt that can be produced by any of the stock configs. Can you attach your `~/.zshrc` and all files with powerlevel10k parameters (if they aren't in `~/.zshrc`)?

**Comment by mtavaresmedeiros** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/9057030/p10k.txt)
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/9057031/zshrc.txt)

Thank you.

**Comment by romkatv** [comment]
Thanks. Could you also post the output of the following command when you prompt is the same as on the screenshot above?

```zsh
typeset -pm 'P9K_KUBECONTEXT*'
```

**Comment by romkatv** [comment]
Thanks.

`kube` is the icon. Normally it would be a real icon but since you are using powerlevel10k in ASCII mode, the icon is literally "kube". You an remove it the same way as you can remove (or customize) all other icons. Search for `POWERLEVEL9K_KUBECONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION`, uncomment it and set its value to nothing.

By the way, instead of `%{$fg[blue]%}` you can use `%F{blue}` and instead of `%{$reset_color%}` you can use `%f`. This is the modern and recommended way in zsh.

**Comment by mtavaresmedeiros** [comment]
It is correct, thank you man.
