### ISSUE TITLE
VCS Branch Name Shorterning

### ISSUE THREAD

**Issue by sanathkumarbs** [romkatv/powerlevel10k#193]
Hello @romkatv, thanks for building powerlevel10k. Been loving this!

Branch names in several repositories which I work in are loooooong (longer than the one in the image at times)

![Screen Shot 2019-08-29 at 3 57 01 PM](https://user-images.githubusercontent.com/13061998/63981910-c5cc5d80-ca75-11e9-92aa-c0e6b16bc59c.png)

This eats up all my space on prompt. I see that `powerlevel9k` has a feature to truncate branch names. Is there similar feature in `powerlevel10k`?

https://github.com/Powerlevel9k/powerlevel9k/pull/798

I tried adding `powerlevel9k` shortening config to .zshrc and sourcing it, and, that doesn't seem to work. (Did this with the hope of `powerlevel10k` honoring `powerlevel9k` configs)

```
POWERLEVEL9K_VCS_SHORTEN_LENGTH=8

POWERLEVEL9K_VCS_SHORTEN_STRATEGY=truncate_middle
```

**Comment by romkatv** [comment]
In Powerlevel9k you need to define both `POWERLEVEL9K_VCS_SHORTEN_LENGTH` and `POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH` to enable branch shortening.

https://github.com/Powerlevel9k/powerlevel9k/blob/d1fbc1b889f63f6ea3e9672b7069133493ccab8a/functions/vcs.zsh#L54

This logic is identical in Powerlevel10k. If you have a working Powerlevel9k config that utilizes branch shortening, you'll get the same results with this config if you switch to Powerlevel10k.

However, since you are using a config generated by the configuration wizard, your Git prompt segment is assembled within your config and it doesn't honor `POWERLEVEL9K_VCS_SHORTEN_LENGTH` or `POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH`. To configure shortening, open `~/.p10k.zsh` and search for `32`. This is basically `POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH` and you can change it to something smaller. There is also `12` in a couple of places on the next line. That's the equivalent of `POWERLEVEL9K_VCS_SHORTEN_LENGTH`.

The advantage of `~/.p10k.zsh` is that you have a lot more freedom w.r.t. how you shorten your branches. If in your company branches follow certain rules, you can take advantage of them in order to shorten branches without too much information loss. For example, you can always drop the leading `IND-XXX-`, or the trailing `-POC`, or both. Or the other way around -- only leave those parts and drop the middle.

I can also highly recommend two-line prompt. Vertical space is cheap, and it's a good deal to get the full terminal width for typing your commands in exchange for one line per prompt. In addition, it's really nice when all your commands start from the same column. Makes it much easier to read your history or your current prompt. You can also spread your right prompt segments over two lines instead of cramming all of them on a single line.

Lastly, I see that you have an unusually high number of unstaged Git changes. Does that `!1495` match what you see in the output of `git status`? If it doesn't, this is likely a bug and I'd like to fix it if you could provide more info. If you indeed have locally modified or deleted 1495 files, you might want to search for `MAX_NUM` in `~/.p10k.zsh` and change the value to `99`. This will change your prompt so that it shows at most `!99`, which for practical purposes might be as good as the real number since both essentially mean "many". The benefit is that your prompt will be faster.

**Comment by sanathkumarbs** [comment]
Thank you for the detailed response, @romkatv. Appreciate it!

You're right, I had totally missed defining `POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH`. I modified my `~/.p10k.zsh` based on your feedback and it works like a charm. I also choose the two-line prompt, great tip!

Regarding the high number of unstaged Git changes, I had moved several directories around and that caused these many changes. It matches my `git status` too. I did update my `MAX_NUM` to be 99. Not sure if you've seen this feature on chrome on phones where after 99 tabs the counter just becomes `:D` - it's pretty funny and cool. 

Also, while modifying the max line length for branch, I had to manually adjust the shortened length. Might be cool to have a default way to identify the lengths? Or have the configure tool help you do it? Not sure if it is an overkill.

If `MAX_LEN=32`, `DEF_SHORT_LEN=round(MAX_LEN/2)`. 
And, strip ->  `[1, (DEF_SHORT_LEN/2)-2]` + `...` + `[(DEF_SHORT_LEN/2)-1, 1]`

Just throwing an idea out there.

**Comment by romkatv** [comment]
> Thank you for the detailed response, @romkatv. Appreciate it!
> 
> You're right, I had totally missed defining `POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH`. I modified my `~/.p10k.zsh` based on your feedback and it works like a charm. I also choose the two-line prompt, great tip!
> 
> Regarding the high number of unstaged Git changes, I had moved several directories around and that caused these many changes. It matches my `git status` too. I did update my `MAX_NUM` to be 99. Not sure if you've seen this feature on chrome on phones where after 99 tabs the counter just becomes `:D` - it's pretty funny and cool.
> 
> Also, while modifying the max line length for branch, I had to manually adjust the shortened length. Might be cool to have a default way to identify the lengths? Or have the configure tool help you do it? Not sure if it is an overkill.

Questions in the configuration wizard have high costs as all users will have to go through them. If the default works for 99% of the user base, I prefer not to ask for the preference and to let the 1% apply edits directly in `~/.p10k.zsh`. Comments in that file are supposed to make simple edits possible without having to understand the minutia details of ZSH scripting. I've committed https://github.com/romkatv/powerlevel10k/commit/9a5abe8185870df5e41e5506253fc9575d541dc9 to help with branch shortening edits.

> If `MAX_LEN=32`, `DEF_SHORT_LEN=round(MAX_LEN/2)`.
> And, strip -> `[1, (DEF_SHORT_LEN/2)-2]` + `...` + `[(DEF_SHORT_LEN/2)-1, 1]`
> 
> Just throwing an idea out there.

This might be more difficult to edit. Constants `-2` and `-1` in this implementation are tunable parameters but it's not obvious from the code how they will affect the results. It's also more difficult to see how to retain just the suffix (or prefix) and drop the rest.

The default config works as if the following parameters were defined:

```zsh
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=32
POWERLEVEL9K_VCS_SHORTEN_LENGTH=12
POWERLEVEL9K_VCS_SHORTEN_STRATEGY=truncate_middle
```

Note that `12` is quite a bit less than `32 / 2`. This is intended. Shortening just to save 1 or 2 characters is not a good trade-off, so by default shortening will happen only if it can save at least 8 characters. How much to leave from the prefix and the suffix is easy to configure, and the effect of `12` in both cases is obvious to the reader. I value these properties.

P.S.

Consider installing [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) and to running `p10k configure` again. With "lean" style and "few" icons you'll get prompt a little bit shorter than you have now, without any loss of information. For example, `Py` will become an icon, saving one character. It'll look a bit nicer, too.

**Comment by CeruttiMaicon** [comment]
Hi everyone,

I know that the discussion is closed, but I've come up with a neat solution here.

I wanted to share a small snippet I added to my `.zshrc` or `.zprofile` to dynamically control the branch name truncation behavior in Powerlevel10k. The code defines an environment variable `MY_BRANCH_SHORTEN_LENGTH` with a default value of 32 (which you can override). If set to 0, it comments out the line in `~/.p10k.zsh` that truncates the branch name —while ensuring the line starts with 6 spaces. Otherwise, it uncomments the line, enforces a 6-space indent, and replaces the default truncation value with the value of MY_BRANCH_SHORTEN_LENGTH.

This allows for a flexible configuration where you can decide whether to use truncation (and with what limit) or to display the full branch name.

Below is the complete code snippet:

```zsh
# Define the variable with a default value of 32 (can be overridden externally)
MY_BRANCH_SHORTEN_LENGTH=${MY_BRANCH_SHORTEN_LENGTH:-32}

if [[ -f ~/.p10k.zsh ]]; then
  if [[ "$MY_BRANCH_SHORTEN_LENGTH" -eq 0 ]]; then
    # If 0, comment out the line that contains the truncation and add 6 leading spaces
    sed -i.bak -E '/branch\[13,-13\]="…"/ {
      s/^[[:space:]]*//;
      s/^/      #/
    }' ~/.p10k.zsh
  else
    # If not 0, remove the comment, enforce 6 leading spaces, and replace the number with MY_BRANCH_SHORTEN_LENGTH
    sed -i.bak -E '/branch\[13,-13\]="…"/ {
      s/^[[:space:]]*#?[[:space:]]*//;
      s/^/      /;
      s/(\(\(\s*\$#branch\s*>\s*)[0-9]+(\s*\)\)\s*&&\s*branch\[13,-13\]="…")/\1'"${MY_BRANCH_SHORTEN_LENGTH}"'\2/
    }' ~/.p10k.zsh
  fi
fi
```

I hope this helps anyone looking for a similar customization!
