### ISSUE TITLE
os icon does not recognize OS

### ISSUE THREAD

**Issue by NeoFax75** [romkatv/powerlevel10k#1933]
For whatever reason the os icon shows only the tux penguin instead of either my OS Endeavour or Arch.

**Comment by romkatv** [comment]
Please run the following command on Arch and post a screenshot that contains the output and prompt:

```zsh
typeset -pm 'POWERLEVEL9K_MODE|_p9k_os*' && cat /etc/os-release
```

**Comment by NeoFax75** [comment]
https://i.imgur.com/qGyTXlW.png

❯ typeset -pm 'POWERLEVEL9K_MODE|_p9k_os*' && cat /etc/os-release
typeset _p9k_os=Linux
typeset _p9k_os_icon=
typeset POWERLEVEL9K_MODE=nerdfont-complete
───────┬─────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/os-release
───────┼─────────────────────────────────────────────────────────────────────────────────────────
   1   │ NAME=EndeavourOS
   2   │ PRETTY_NAME=EndeavourOS
   3   │ ID=endeavouros
   4   │ ID_LIKE=arch
   5   │ BUILD_ID=rolling
   6   │ ANSI_COLOR="38;2;23;147;209"
   7   │ HOME_URL='https://endeavouros.com'
   8   │ DOCUMENTATION_URL='https://discovery.endeavouros.com'
   9   │ SUPPORT_URL='https://forum.endeavouros.com'
  10   │ BUG_REPORT_URL='https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports
       │ '
  11   │ LOGO=endeavouros

**Comment by romkatv** [comment]
This doesn't look like Arch Linux. You mentioned earlier that you aren't getting the icon you expect on Arch Linux. Is that correct? If so, can you run the command on Arch Linux and post its output?

**Comment by romkatv** [comment]
I re-read the original issue description and I think I misunderstood. You aren't using Arch Linux, you are using EndeavourOS, correct?

If so, you are seeing the penguin because there is no EndeavourOS glyph in [nerd fonts](https://www.nerdfonts.com/cheat-sheet). If you were using Arch Linux, you would see Arch Linux logo because it does exist in nerd fonts.

**Comment by jenzuslongus** [comment]
@NeoFax75 I've just read the thread because I have the question as you had. I've just realized that there is an icon for EndeavourOS in nerdfonts which you can call with `echo -e '\uf322'`. It looks very ... unspectacular, more like a cloud or a drop of water.

@romkatv Can the logo be integrated in the list of known icons?

**Comment by romkatv** [comment]
> @romkatv Can the logo be integrated in the list of known icons?

Sure, when https://github.com/romkatv/powerlevel10k/issues/2217 is done.
