### ISSUE TITLE
problem with light themes

### ISSUE THREAD

**Issue by mohammadne** [romkatv/powerlevel10k#1980]
Hi @romkatv ;
first of all thanks for your great effort.

I really think the 256 & 8 colors are statically coded for dark themes which looks ugly on light themes.
and I'm in search to make it dynamic to work great on both themes.

![Screen Shot 2022-08-12 at 5 15 29 PM](https://user-images.githubusercontent.com/51189292/184356782-7759f06f-da4a-423d-bfc5-3b3b429c22b7.png)

![Screen Shot 2022-08-12 at 5 15 47 PM](https://user-images.githubusercontent.com/51189292/184356807-421772d3-8de7-4797-ab30-91693d9cd67c.png)

as you can see the dark colors on `onedark` looks great but not on `onelight` theme.
I'm using iterm2 latest version.

## Suggestion: 
having 2 `.conf` file containing color values for dark and light themes and source them into `p10k.zsh` file and write colors there, this also make the plugin more neatly and separates the color logics into the actual config files.

thanks.

**Comment by romkatv** [comment]
There is no option that makes p10k look good with different backgrounds and base colors. You'll have to run `p10k configure` in the terminal you care about and choose what looks best.

One exception may be Lean with 8 colors. I believe it should look reasonably well anywhere. Lean with 256 colors might work too.

**Comment by mohammadne** [comment]
ok @romkatv ,
I've added a suggestion section, can I know your idea about it?

**Comment by romkatv** [comment]
If you intend to implement this in your own config, by all means. This isn't something I would put in powerlevel10k though.

In curious, why are you using dark and light terminals? Usually people use one or the other but not both.

**Comment by eddyg** [comment]
I also switch between light/dark terminal themes automatically (depending on day/night) using [this iTerm2 script](https://iterm2.com/python-api/examples/theme.html).

However, it's not necessary to have all the extra complexity of two P10K configs.

You just need _one_ P10K config file, but set it up so that it only uses the basic 16 colors, similar to the "Lean" theme with the "8 colors" option Roman mentioned (_or_, uses other colors that work OK in both dark/light themes). You use two different iTerm2 _color schemes_, each one optimized for a light or dark background, and assign each to a "Light" profile and a "Dark" profile in iTerm2.

When the current terminal's profile changes from Light to Dark (or vice versa), the color scheme updates, and any prompt elements using the 8 basic colors (plus the bright variants) update automatically.

For example, here's the _same_ P10K config with my personalized "Dark" and "Light" color schemes:
<img width="729" alt="Screenshot 2022-08-12 09 19 17@2x" src="https://user-images.githubusercontent.com/3235109/184362087-ee15c21d-419f-4c5f-bce7-6cc52c6908c1.png">

**Comment by romkatv** [comment]
Thanks for chiming in, Eddy. This is very helpful.

I'm closing this as I don't intend to do anything here.
