### ISSUE TITLE
Add screen session as optional prompt list element

### ISSUE THREAD

**Issue by mcandre** [romkatv/powerlevel10k#2022]
I would love an option to show the current `screen` session (the middle of a dot delimited string, unless blank) in my prompt.

**Comment by romkatv** [comment]
See `p10k help segment`.

**Comment by romkatv** [comment]
Add this to `~/.p10k.zsh`:

```zsh
function prompt_my_screen_session() {
  if [[ -n $STY ]]; then
    p10k segment -b yellow -f red -i 's' -t "${${STY#*.}%.*}"
  fi
}
```

Then add `my_screen_session` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

Change the values of `-b`, `-f` and `-i` as you like. See docs in `p10k help segment`.

**Comment by mcandre** [comment]
The default powerlevel10k configuration file is massive and difficult to navigate.

Either this kind of thing should be builtin and easier to toggle on/off, or else the default file should be damn near empty, minimalist.

**Comment by ccjmne** [comment]
I think that the fact we have so many segments built in and their configuration being readily available to the end user for tweaking is what contributes to the size of `p10k.zsh`. That and the fact it's littered with documentation!

If you don't want to mess with a large configuration file, as far as I can tell, the one thing that needs to be done in `p10k.zsh` is the addition of the hook to the array of either right or left prompt elements, both of which are virtually as near the top of `p10k.zsh` as possible—though admittedly, that's probably about line 30 by default because of the copious in-line documentation.

Everything else can be as simple as a single, standalone `zsh` function invoking `p10k segment`, which does provide comprehensive guidance through `p10k help segment`.

For reference, here's a (decommissioned) custom segment: https://github.com/ccjmne/dotfiles2025/commit/321f08b862b4ba9dbf6c0c1de2789df84e39f039

--

**I hope that you won't get discouraged by the configuration file being too large.** I don't mind it being this way; where the concept of "default" configuration that comes with user-managed overrides as you conceive it instead consists of *the one configuration file*, which by default ships with a ton of utilities and serves as its own documentation.

To address your final point, I actually think that the mere toggling of segments is still fairly straightforward. It would assume the segment already existing, however, and that depends on there being:
- desire and competence to maintain it in this repository (nobody here is lacking competence in general, but if it's a segment for a tool you don't use...)
- opinions in favour of that specific segment making it in: while any segment can be built in, not *every* segment can.

Well, your actual last point was that the default configuration should be "empty, minimalist", and I don't think that:
- everything needs to be minimalist (I adore the idea, but wouldn't educate the creator of tools that don't adhere to my ideals as to what the one design philosophy I want to box myself in is); and
- I don't know for sure that *adding an additional interface* that exposes far less information would be *more minimalist*.

But it'd certainly be more common and approachable—though you'd still likely want to delve under the hood whenever you have an itch to scratch anyways ;)

**Comment by mcandre** [comment]
Modern applications follow 0conf. Select practical defaults. Document how to customize and extend. An empty config file behaves the same as having no config file, applying the component's defaults without requiring tons and tons and tons of boilerplate.

The telegraf CLI has the same problem as powerlevel10k. It's not fun to troubleshoot a file hundreds or thousands of lines long, that really only contains a handful of customizations compared to the default behavior.

powerlevel10k's file is obnoxiously long to configure. Considering switching to spaceship instead.

Recommend moving the implementation into library, sourceable scripts as a first step. Then, move the default configuration into a dedicated script, which loads prior to and/or in place of an extant user configuration file.

**Comment by ccjmne** [comment]
I'm all with you about sane, practical defaults!

Regardless, what transpires in the rest of your message, to me, is that you're mostly sheepish about tweaking the large configuration file.
You're talking about the struggle with troubleshooting, which is possibly fair, provided that there is a pending issue in the code to begin with, or a behaviour otherwise irreconcilable with the documentation or ad-hoc support from the community or developers. I'm not certain it's applicable here.

You're stating that (verbatim): "powerlevel10k's configuration is obnoxiously long to configure".
I think you can just drop it anywhere, source it before initiating p10k's prompt and be done. The bits that are most personal (the actual layout and behaviour of the prompt) can be configured natively through a very discoverable tool—if you have no configuration, it'll help you get yours ready.

If you do want to configure something, you're making the case that you'd rather hop online to the corresponding Wiki or user documentation, figure out what the name of the variable is, and add its override to your barren configuration file; I like that I can just search the configuration file itself ;)

--

I understand your recommendation, and I think it's a brilliant (albeit obvious, as it's precisely what I had spelled out I thought you were suggesting behind "minimalism") solution if it helps you move past the mental block of using a sizeable configuration file whenever you need to tweak your prompt.

**You should know that you can choose to not source this configuration file *at all* and have precisely the experience you're talking about.**

Optionally, you can use the interactive wizard to get a personalised prompt that also sets up a lot of stuff that virtually everybody (I suppose) uses, but even then, you can choose to treat that as a default base configuration provided by the tool, which you'll never look at, and simply overwrite the handful of settings you want to change for yourself, directly in your `.zshrc`, or in any other form that you want: `p10k` is unopiniated in this way: it's your configuration.

I think I've outlined how you can implement that specific behaviour yourelf, but if it's unclear I'd be happy to actually help.

--

Just to finish with this topic: naively, I think I'd have also created something that looks precisely like what you have in mind. Now that I've seen something different, I chose to not fight against it but actually try to critically assess (for myself) its shortcomings and advantages, and all in all, I came out mostly thinking "huh, the obvious isn't necessarily the only viable".

Spaceship is certainly great, some of my colleagues use it and are enchanted. I considered using it as well, so seriously that I did switch to it over a week-end, only to realise the next monday morning that I wasn't ready to suffer the sluggishness that comes with any other zsh prompt that displays the Git status of a criminally large repository.

I don't want to alienate you, and I feel like I should stress that I'm merely a passerby: I'm in no way associated with this project or its maintainer, don't let my attitude (or the size of the configuration file) be the sole factors by which you decide to jump ship. Keep an open mind, good luck, and have fun—it's just a terminal prompt.

**Comment by mcandre** [comment]
Sheepish? I don't have time. Software is needlessly complex today.

**Comment by rwmitchell** [comment]
I think the problem with sane defaults  is in this world, sane is very subjective.

**Comment by mcandre** [comment]
Fair point.

"Consensus defaults" would suffice.
