### ISSUE TITLE
Missing color Directory on previously executed command

### ISSUE THREAD

**Issue by Amithkukar1** [romkatv/powerlevel10k#2041]
![Screenshot from 2022-10-01 14-18-31](https://user-images.githubusercontent.com/70800183/193402405-f24d1df7-bae1-43da-bbd8-e6cc3138c7cc.png)

**Comment by romkatv** [comment]
Run `p10k configure` and when asked whether you want to enable *Transient Prompt* answer No.

**Comment by Amithkukar1** [comment]
thank you

**Comment by romkatv** [comment]
You are welcome.

**Comment by Amithkukar1** [comment]
1) How can I have real-time  digital clock in terminal
2) How can I get that last login
![image (1)](https://user-images.githubusercontent.com/70800183/193403142-35b907cd-1c9e-4529-a4d9-25ea579ad443.png)
3) What does that base prompt mean

Thanks in advance

**Comment by romkatv** [comment]
> 1. How can I have real-time  digital clock in terminal

You can set `POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true`. I don't recommend this because zsh has several bugs that may be triggered by this. Try to configure your OS to display proper clock instead.

> 2. How can I get that last login
>    ![image (1)](https://user-images.githubusercontent.com/70800183/193403142-35b907cd-1c9e-4529-a4d9-25ea579ad443.png)

This is unrelated to powerlevel10k. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

> 3. What does that base prompt mean

Some kind of Python virtual environment. Maybe Conda, maybe something else.

**Comment by romkatv** [comment]
Also see https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style
