### ISSUE TITLE
Add a $ and # (for sudo) to command prompt for better look

### ISSUE THREAD

**Issue by tasinone** [romkatv/powerlevel10k#2071]
Can you add a $ sing and # for sudo mode at powerlevel10k? In this picture, you can see my terminal on the left side. And without a $ it kinda looks naked. So if you add a $ # in powerlevel10k or give us the option if anyone wants it or not while configuring then it will be better. As an example, I have added two images on the right side.
<a href="https://ibb.co/sC83fp9"><img src="https://i.ibb.co/dt8KTs4/github.png" alt="github" border="0"></a>

**Comment by romkatv** [comment]
1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX`.
3. Append `%(#.%F{yellow}#.%F{blue}\$)` to the value. It'll look like this but you might have a different number in there instead of 242:
   ```zsh
    typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%242F╰─%(#.%F{yellow}#.%F{blue}\$)'
   ```
4. Save.
5. Restart zsh with exec zsh.

See https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html for the explanation and other styling options.
