### ISSUE TITLE
2 errors when breaking via CTRL-C on Macos

### ISSUE THREAD

**Issue by ntwrkguru** [romkatv/powerlevel10k#2107]
Hello...I just installed p10k and it's beautiful, but... when breaking with CTRL-C, I see the following errors:

```
_p9k_restore_prompt:zle:2: No handler installed for fd 14
_p9k_restore_prompt:3: file descriptor 14 used by shell, not closed
```

macOS version: 12.6.1
zsh version: zsh 5.8.1 (x86_64-apple-darwin21.0)

Not sure what else you may need, but let me know.

**Comment by romkatv** [comment]
Can you reproduce this if you disable everything else (all plugins and plugin managers) and leave only powerlevel10k?

**Comment by romkatv** [comment]
Also, what are you breaking with CTRL-C?

**Comment by ntwrkguru** [comment]
> Also, what are you breaking with CTRL-C?

In this case, instead of holding CTRL-W to delete what was entered, I just used CTRL-C to break and return to the prompt.

> Can you reproduce this if you disable everything else (all plugins and plugin managers) and leave only powerlevel10k?

Hmm.. seems I can't reproduce it at all. I'll keep an eye out and report back if needed. I'll close this, but thanks for the INCREDIBLY fast response!

**Comment by romkatv** [comment]
> > Also, what are you breaking with CTRL-C?
> 
> In this case, instead of holding CTRL-W to delete what was entered, I just used CTRL-C to break and return to the prompt.

It's not a good idea to send an interrupt to zle. Press CTRL-G instead. CTRL-C aborts what the foreground process is currently doing (this is by design) and if it's doing something related to prompt, you'll abort that and usually end up with a broken shell.

An even better option is to simply clear the command line rather than aborting it. You can do this with CTRL-U.
