### ISSUE TITLE
long first command lag

### ISSUE THREAD

**Issue by ky0n** [romkatv/powerlevel10k#2160]
What might by the issue for the long first prompt lag? 
I run again through p10k configure, but the first-command-lag keeps being quite high.

zsh-bench output:
creates_tty=0
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=30.372
first_command_lag_ms=419.373
command_lag_ms=17.580
input_lag_ms=12.602
exit_time_ms=362.402

**Comment by romkatv** [comment]
The benchmark data shows first_prompt_lag_ms of 30 milliseconds. This is not long by any means. A typical display refreshes only twice during this period.

If you are concerned with first_command_lag_ms being relatively high, this is because your zshrc takes a long time to evaluate. 419ms isn't a lot though. It's unlikely that you'll finish typing a command in such a short time.

Can you explain what exactly is slow from the user's point of view?

**Comment by ky0n** [comment]
I think it's fine. Just starting a new tab in iTerm2 sometimes takes some time.
And sometimes, if I start typing immediately after opening a new tab, the text i input is not correctly displayed in the shell, instead there are question marks, then it will be resetted and the text i typed is gone, probably after the whole plugins of zsh are loaded.

**Comment by romkatv** [comment]
> I think it's fine. Just starting a new tab in iTerm2 sometimes takes some time.

This is normal after updating powerlevel10k.

> And sometimes, if I start typing immediately after opening a new tab, the text i input is not correctly displayed in the shell, instead there are question marks, then it will be resetted and the text i typed is gone, probably after the whole plugins of zsh are loaded.

If by question marks you mean something like `^[[A` (when pressing UP key), then this is normal.

**Comment by ky0n** [comment]
This is not what I meant, but I can't reproduce it right now.
