### ISSUE TITLE
How to debug prompt latency occurring in large directories?

### ISSUE THREAD

**Issue by SpanishPear** [romkatv/powerlevel10k#2222]
Hi!

First of all, thanks for all your work on this p10k!

I seem to be getting quite a slow prompt when in large projects. At first, I thought this was related to #1608 - but I'm still observing slow prompt latency when I've removed `vcs` from the left prompt. 

`$ ~/zsh-bench/zsh-bench`
```
==> benchmarking login shell of user spanishpear ...
creates_tty=0
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=0
first_prompt_lag_ms=48.931
first_command_lag_ms=997.920 
command_lag_ms=108.759
input_lag_ms=14.797
exit_time_ms=835.666 
```

Is this likely to be a personal configuration issue? If so, where could I start looking (Ventura 13.1, M1 Mac)

**Comment by romkatv** [comment]
Indeed, `command_lag_ms` and `first_command_lag_ms` are way too high. Here's what you can do:

1. Disable powerlevel10k and run the benchmark. If `command_lag_ms` stays high (let's say above 20), then you'll know the issue is not with powerlevel10k. You can try to narrow it down by continually disabling parts of your zsh config.
2. If disabling powerlevel10k brings `command_lag_ms` under 20ms, then you can re-enable powerlevel10k, generate a new `~/.p10k.zsh` with `p10k configure` and run the benchmark. If this gives you low `command_lag_ms`, it means the issue is with your `~/.p10k.zsh`. Review all manual changes that you've made and find out which of them makes things slow.

**Comment by SpanishPear** [comment]
That's extremely helpful - thanks! 

Managed to narrow it down to a bad plugin (git-prompt) I installed, but honestly have no idea why I installed it at the time.

Closing as resolved!
