### ISSUE TITLE
[feature request] Support persistent P10K settings

### ISSUE THREAD

**Issue by april** [romkatv/powerlevel10k#2224]
I do a _lot_ of tweaking of my `~/.p10k.zsh` file, way more tweaks than I can remember off the top of my head. Unfortunately, these get overwritten every time I run `p10k configure`, which I tend to do from time to time to shake things up or after I update my local repo.

Because they are so extensive, I have them pushed into a separate file that I then source from `~/.p10k.zsh`:

```zsh
# Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
# For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
# can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
# really need it.
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

# Load persistent p10k settings
if [ -f ~/.p10k.custom.zsh ]; then
  source ~/.p10k.custom.zsh
fi
```

```zsh
$ cat ~/.oh-my-zsh/custom/p10k.zsh
# Green prompt symbol if the last command succeeded.
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2

# Red prompt symbol if the last command failed.
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1

# Default prompt symbol.
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='$'

# and so on
```

oh-my-zsh already does this by sourcing everything in the `~/.oh-my-zsh/custom` directory, and it makes settings persistence a lot easier. It's not the _end_ of the world to have to add that source line every time I run `p10k configure`, but it would be nice if it natively supported something along these lines.

**Comment by romkatv** [comment]
Why not source the extra file from `~/.zshrc`?

**Comment by romkatv** [comment]
> * it also makes an FAQ entry more complicated (e.g. place in your `.zshrc` file but after these specific lines loading p10k instead of simply adding them to `~/.p10k.custom.zsh`)

I cannot add this FAQ entry anyway because what you are doing isn't guaranteed to work. If you update powerlevel10k and run `p10k configure`, it may generate a different config, on top of which your custom changes won't work as you expect. Likewise, if you run `p10k configure` without updating powerlevel10k and choose different options, your patch may also not work as you expect.

The reason why what you are doing is awkward is because it's brittle and essentially unsupported. Nevertheless, if you *want* to have your patch in a separate file, go ahead and place it anywhere you like and then source it form any file you like. The only file from which you cannot source it is `~/.p10k.zsh` because it's auto-generated. Any other file will do fine though.

**Comment by april** [comment]
Sure, the settings names might change, although IMO they are remarkably stable and I can't say I've noticed this method being particularly brittle in my years of use. It simply replaces manually changing them in the generated file with keeping them somewhere else that can be synced and source controlled easily, it doesn't guarantee that those tweaks will always work across powerlevel10k updates.

And yes, I understand that I can't place it in `~/.p10k.zsh`, because it's auto-generated. Hence opening the ticket, so that `p10k configure` would autogenerate a `~/.p10k.zsh` that included lines to source a custom file if it existed.

But it sounds like there's not interest for that, and that's okay. I appreciate the response either way. Thanks.  :)

**Comment by romkatv** [comment]
> And yes, I understand that I can't place it in `~/.p10k.zsh`, because it's auto-generated. Hence opening the issue, so that `p10k configure` would autogenerate a `~/.p10k.zsh` that included lines to source a custom file if it existed.

I cannot do this because it would implicitly endorse the usage that I provide no guarantees for. If *in practice* this patching works for you, go ahead and use it. For me to endorse it would require actually providing a guarantee, and I cannot do that.

> But it sounds like there's not interest for that, and that's okay.

That's not what I meant. I don't know how to support what you are doing in powerlevel10k. However, you don't seem to need this support because you can source your custom file from any other file you have. The one single file from which you cannot source your file is `~/.p10k.zsh` but this still leaves a vast number of your startup rc files that you have full control over.

**Comment by romkatv** [comment]
To clarify, powerlevel10k provides a guarantee that any *full* config (even if manually edited) will keep working after powerlevel10k is updated. powerlevel10k may become faster or to have some bugs fixed, but it won't break and won't require that you change your config after an upgrade.

This guarantee isn't enough for your usage though.

P.S.

The approach that most advanced users employ is 1) synchronize all of your dotfiles (including .zshrc and .p10k.zsh) across machines; 2) run `p10k configure` just once, pick the style that suits you, then edit `.p10k.zsh` as you like and never run `p10k configure` again. If you commit .p10k.zsh after it was generated and then again after making your own changes, you'll also have a diff that might prove useful in the future in the unlikely event that you'll want to switch style and re-apply your edits.

**Comment by april** [comment]
Sorry, to be clear — it's not a vast number of startup rc files. If it could be loaded in my startup rc files, that would be _much_ easier. It specifically has to be from a file loaded after:

```zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

Because powerlevel10k's `typeset` calls don't check to see if something has already been set, so setting in most places simply results in them being overwritten.

As such, it doesn't work with any of the usual startup rc files (such as those provided by oh-my-zsh), basically only with a manually edited `.zshrc`, as powerlevel10k is generally loaded last in the chain. I would love to sync `.zshrc` across machines, but while that works great for personal usage, it definitely doesn't work on personal and work machines.

Similarly, syncing `.p10k.zsh` does work (as long as I never run `p10k configure`), but it runs into similar brittleness issue in that it might not work on a machine with a newly installed version of powerlevel10k.

**Comment by romkatv** [comment]
You can source any file from .zshrc and from that you can source your patch. I wrote "vast" instead of "infinite" because the number of distinct file names is large but finite.

> Because powerlevel10k's `typeset` calls don't check to see if something has already been set [...]

There is no need to check because there is `unset` at the top of `~/.p10k.zsh`.

> I would love to sync `.zshrc` across machines, but while that works great for personal usage, it definitely doesn't work on personal and work machines.

Why not? Many sync their dotfiles across all machines.

How come you can sync `.p10k.zsh.custom` but not other files?

> Similarly, syncing `.p10k.zsh` does work (as long as I never run `p10k configure`), but it runs into similar brittleness issues in that it might not work on a machine with a newly installed version of powerlevel10k, requiring syncing the powerlevel10k repo across machines.

What do you mean by `.p10k.zsh` not working on a machine with a newly installed powerlevel10k? As I mentioned above, powerlevel10k guarantees backward compatibility, so your `.p10k.zsh` will work with all future versions of powerlevel10k.

**Comment by april** [comment]
I cannot sync because my work `.zshrc` contains all sorts of custom paths and various tools that load things into environmental variables, and those simply don't exist on my personal machine.

> What do you mean by .p10k.zsh not working on a machine with a newly installed powerlevel10k? As I mentioned above, powerlevel10k guarantees backward compatibility, so your .p10k.zsh will work with all future versions of powerlevel10k.

I guess I don't understand the brittleness concerns? If I make a change of:

```
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='$'
```

In a never-updated `.p10k.zsh`, with guaranteed backwards compatibility, how is that less brittle than having that same line in `.p10k.custom.zsh` and sourced at the bottom of `.p10k.zsh`? Not trying to argue and waste your time, I'm just confused.

Regardless, I guess I would say to go ahead and close the ticket. It is good to know that what I am doing is weird and unsupported, and the suggestion of moving it to `.zshrc` instead of trying to load from `.p10k.zsh` is a good one and more stable (even if `.zshrc` is a bit of a mess 😅)

Thanks again for the discussion, really appreciate the cordial back and forth, and it helped clarify to me why you would not want to do this.

**Comment by romkatv** [comment]
Suppose `p10k configure` generated the following config (just one line):

```zsh
POWERLEVEL9K_BACKGROUND=red
```

Here's how it looks:

![image](https://user-images.githubusercontent.com/1282067/225374090-dffc37d4-9ca2-4fe9-b5eb-905df8ec0da6.png)

Suppose you made this patch:

```zsh
POWERLEVEL9K_BACKGROUND=blue
```

The base config plus the patch make prompt look this way:

![image](https://user-images.githubusercontent.com/1282067/225374432-9b5fd888-2324-4cbc-a3ea-4975a2b909eb.png)

Then, after an upgrade, `p10k configure` generated this config:

```zsh
typeset -g POWERLEVEL9K_{CONTEXT,DIR,STATUS,HISTORY,TIME}_BACKGROUND=red
```

Prompt with this config looks the same as with the original `POWERLEVEL9K_BACKGROUND=red`. But here's the catch: **the patch no longer works**. It has no effect on prompt. The new patch that turns prompt blue would look like this:

```zsh
typeset -g POWERLEVEL9K_{CONTEXT,DIR,STATUS,HISTORY,TIME}_BACKGROUND=blue
```

This isn't a hypothetical change. I do make changes of this kind. For example, you probably have `typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3` in your config. When I added this parameter to the output of `p10k configure`, patches that used `POWERLEVEL9K_DIR_CLASSES` for styling broke. However, none of the full configs broke. In order to experience breakage, a user needs to use an old patch that they wrote together with a new config generated by `p10k configure`.

**Comment by april** [comment]
I understand that, but why wouldn't I have that exact same problem if I had fully versioned and kept my old .p10k.zsh, as you had suggested?

**Comment by romkatv** [comment]
The old .p10k.zsh plus the old patch would give the same prompt with any future version of powerlevel10k. However, a new .p10k.zsh with the old patch can do anything.

Imagine if instead of storing a patch in a separate file you actually stored it as a unified diff. Then, after generating a new version of .p10k.zsh, you attempted to apply this diff. In the hypothetical example I gave above, the diff would fail to apply (for a good reason!) and you would have to merge it manually. But if you simply sourced two files back-to-back, the merge conflict would get masked.

I understand that in practice this sort of patching where you simply source two files works most of the time and I'm not trying to dissuade you from using it. I'm explaining why I cannot add native support for this in powerlevel10k.

FWIW, my own dotfiles are fully synchronized across all machines. You can see the public portion of the said dotfiles on github. Here's .zshrc: https://github.com/romkatv/dotfiles-public/blob/master/.zshrc. You can notice at the bottom that it sources `.zshrc-private` if such a file exists. It exists on some of my machines and contains proprietary stuff. This file is also synchronized through git but the repo is private. There are other ways how to synchronize dotfiles across machines.
