### ISSUE TITLE
Powerlevel10k no longer resets prompt after loading?

### ISSUE THREAD

**Issue by dylanjm** [romkatv/powerlevel10k#223]
I use Zplugin and recently updated Powerlevel10k. Now when I open up iterm2, my prompt does not show up until after I hit `return` or run a command. I have narrowed this down to coming from Powerlevel10k, as I have rolled back Zplugin and updated each of my plugins one at a time until encountering the issue. I currently have this code in my `.zshrc`:

```zsh
zplugin ice wait'!' \
        atload'source ~/.p10k.zsh; _p9k_precmd' blockf lucid nocd
zplugin light romkatv/powerlevel10k
```

**Comment by romkatv** [comment]
Functions and parameters whose names start with `_p9k` or `__p9k` are internal. They may change or disappear without notice. Your prompt broke because `_p9k_precmd` has changed. One way to fix it is to read the source code of Powerlevel10k and find a way to do the same thing as before. This appears to work:

```zsh
zplugin ice wait'!' atload'
  source ~/.p10k.zsh
  zle() { unfunction zle; false }
  _p9k_precmd
' blockf lucid nocd
```

This first prompt doesn't have right prompt for some reason. I've no idea why.

Needless to say, this "solution" may break the next time you update Powerlevel10k and you'll have to come up with a new hack. If you'd rather avoid this hassle, don't use internal functions.

**Comment by romkatv** [comment]
> This first prompt doesn't have right prompt for some reason. I've no idea why.

I opened https://github.com/zdharma/zplugin/issues/167 for this.

**Comment by psprint** [comment]
I wonder why the solution has the `zle() { unfuction zle; false }` in it?

As for the changes in the project of whom precmd function user wants to call inside the `atload''` hook, then what often happens is that name of the hook changes, and one good method to get the name of the new one is to `echo $precmd_functions`.

**Comment by romkatv** [comment]
> I wonder why the solution has the `zle() { unfuction zle; false }` in it?

This is a hack, just like calling `precmd` hooks manually is hack. Once you start using hacks, your code tends to break, so you have to pile on more hacks to keep it working. Please don't take the hack above as an endorsement to use it. It is horrible and will break in the future without notice.

Calling `precmd` hooks manually from zle widgets is a hack because the environment isn't identical to the one where `precmd` hooks normally run. For example, `$status` and `$pipestatus` don't have correct values. `zle` without arguments succeeds while normally it fails. It is this latter difference that breaks powerlevel10k if you call its `precmd` hook manually. The hack above works around it.

> As for the changes in the project of whom `precmd` function user wants to call inside the `atload''` hook, then what often happens is that name of the hook changes, and one good method to get the name of the new one is to `echo $precmd_functions`.

I contend that it's not a good method.

If users want to use hacks and to call internal functions, it's their choice. What I deplore is when they open issues once inevitably their hacky and unsupported code breaks. I don't blame @dylanjm personally as I believe he wasn't aware his usage of Powerlevel10k was unsupported. The blame lies with the sources that list such hacks as if they were supported by developers who never signed up for it.
