### ISSUE TITLE
prompt color do not match on different terminals

### ISSUE THREAD

**Issue by GrooveWJH** [romkatv/powerlevel10k#2244]
macOS Ventura

**Tabby and Terminal use zsh with same config.**

**Screenshots:**

Tabby:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/68369010/228751361-52abcccc-ec85-4a72-a517-be82e4d7348a.png">

Terminal:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/68369010/228751604-c5552958-5d28-4703-ae65-ea5a25e3e08f.png">

The inconsistency of the color block colors on the terminal bothers me a lot.
Apparently, this is caused by different ways of configuring the colors used by different terminals, but I don't understand how to deal with it.

**Comment by romkatv** [comment]
> Terminal: <img alt="image" width="368" src="https://user-images.githubusercontent.com/68369010/228751604-c5552958-5d28-4703-ae65-ea5a25e3e08f.png">

There are two rendering issues visible on this screenshot:

1. The font height appears artificially increased, which causes a gap in the grey line at the very right and imperfect connection in the areas you've highlighted with green. You might be able to fix this by reducing *Line Spacing* under *Font* in the terminal settings.
2. Foreground and background colors don't look the same. This is the issue you seemed concerned with. Last time I looked at it, Apple Terminal didn't have a setting to turn this off. As far as I know, this is the only terminal that by default uses different background and foreground colors and does not allow you to make them the same. If you must use Apple Terminal, consider running `p10k configure` and choosing *Lean* style instead of *Rainbow*. Lean does not use background colors, so it does not suffer from this issue.

You should be able to see the problem on the output of the following command:

```zsh
print -P '%K{blue} %k%F{blue}█%f'
```

This command prints a space with blue background followed by █ (U+2588, known as Full Block) with blue foreground. It's supposed to look like this:

![image](https://user-images.githubusercontent.com/1282067/228779839-58a03f30-6483-4bc8-b8f5-240097b53d75.png)

Note that the two printed characters look exactly the same and are joined perfectly. In Apple Terminal this won't look the same.

**Comment by GrooveWJH** [comment]
Thanks for your answer. 
Then I wonder if it is possible to modify the color scheme of Apple Terminal to achieve such apperance

**Comment by romkatv** [comment]
I don't think it's possible: Apple Terminal allows you to choose only the foreground color and infers the background color from it by reducing brightness. Apple Terminal *intentionally* renders background and foreground colors differently. Apple apparently considers this a feature.
