### ISSUE TITLE
How to prevent prompt from changing with SSH?

### ISSUE THREAD

**Issue by hotsno** [romkatv/powerlevel10k#2262]
I'm wondering if there is a way to just entirely disable the prompt from doing anything special when I'm in an SSH session and have it work as normal?

Sorry if this is information is documented somewhere obvious, but I couldn't find it after some looking around.

**Comment by hotsno** [comment]
Ah, I think I may have actually been experiencing a bug. It seems like when I have a command that runs in my `~/.zshrc` which causes an error, powerlevel10k will not use the right configuration or something.

I'd still like to know the answer to the above, but now I see with ssh, the only new thing is the host name added on the right, which I think there is some documentation for in the README.

I can make a separate issue for the bug and give better steps to reproduce, but I don't have the time to right now.

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by hotsno** [comment]
@romkatv I'll make a separate issue about the bug when I get the chance to replicate it on my personal setup (I was experiencing it on my work laptop).

But I'm still wondering about my initial question in this issue.

**Comment by romkatv** [comment]
I don't understand the question, hence why I've asked you to rephrase it using the standard template.

**Comment by hotsno** [comment]
Oh, I thought you were referring to the bug.

After looking into it again I was able to figure out the answer to my own question. I didn't know what to call it when I initially tried looking into it but I guess what I wanted was to remove the "right prompt element" when I'm SSH'ed. I did so by commenting out `context` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(...)` in `~/.p10k.zsh`. Sorry to bother you.

**Comment by hotsno** [comment]
And also the bug doesn't seem to be a bug on p10k's end :)

It was happening when I was running a command on shell start in `~/.zshrc` which I then terminated with Ctrl-C. This was run before the line that sources `~/.p10k.zsh`, so the issue was that `~/.p10k.zsh` was never sourced. Fixed this by moving the sourcing line above the command I run on start.

**Comment by romkatv** [comment]
I'm glad you managed to resolve the issue(s).

FWIW, in my own config I've made prompt appear differently in SSH and locally.

Local prompt:

![image](https://user-images.githubusercontent.com/1282067/232859696-aa8209af-83b1-425f-a785-6b290f5702bd.png)

Remote prompt:

![image](https://user-images.githubusercontent.com/1282067/232859592-6bc128e6-3620-444b-9d02-b7a738f7d4a5.png)

Prompt in SSH shows the name of the machine (it always matches the argument I gave to the `ssh` command, which isn't necessarily the same as the hostname; in this case it's "california" because I typed `ssh california` to get there) and time (very useful when looking at logs because the time on the remote machine is often different from my local time). I don't need to see either of these things when working locally. In addition, the remote prompt has its first line highlighted. This makes it less likely that I get confused about where I am.
