### ISSUE TITLE
Instant prompt works but it takes time to have everything ready

### ISSUE THREAD

**Issue by Breigner01** [romkatv/powerlevel10k#2291]
So, I have no problems with instant prompt it works fine.
I just realized fairly recently that it takes time for everything to be ready, it takes a couple seconds to have auto complete and the rest of the prompt.
I don't think that it's related but I also see that the logo next to the battery percentage cannot be rendered and I just have the following:
![image](https://user-images.githubusercontent.com/55832366/236085450-7925f2d8-00d6-4f68-b63b-06d4172b2f6a.png)
I don't think it's related but since it appeared at the same time as it started taking time for everything to start, I cannot exclude the possibility that these are related or are caused by the same issue.

**Comment by romkatv** [comment]
For the icon, see https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render.

You can figure out what takes a lot of time to load by disabling parts of your .zshrc one by one. Common culprits include nvm, pyenv and various `eval` calls.

**Comment by h0adp0re** [comment]
The missing icon is caused by [a major upgrade](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) to Nerd Fonts. There is a translation table available here: https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287. But the changes must be done in p10k source because the icons are generated there. We as users could go through our `.p10k.zsh` to look for broken icons and replace them with suitable ones from https://www.nerdfonts.com/cheat-sheet.

**Comment by romkatv** [comment]
> The missing icon is caused by [a major upgrade](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) to Nerd Fonts.

Have you changed your terminal font? If so, run `p10k configure`.

**Comment by romkatv** [comment]
Edit: make sure you are on the latest version of powerlevel10k before running `p10k configure`.
