### ISSUE TITLE
Question: easier way to customize?

### ISSUE THREAD

**Issue by polothy** [romkatv/powerlevel10k#231]
I believe I'm following the recommended approach, I have a local copy of https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-lean.zsh and then modified it to customize it.

Recently, I updated p10k and I wanted to make sure my config was up-to-date as well.  To do that, I diffed my copy to the latest and copied changes over to my config.  While this worked, it'll be difficult over time.  Was wondering if I could do this sort of workflow for the config:

```shell
# Set my custom configs here, like colors, icons, etc.
source 'p10k-lean.zsh'
```

Thanks for any tips, cheers!

Great project, love how fast and useful my prompt is now!

**Comment by romkatv** [comment]
> Recently, I updated p10k

👍 

> and I wanted to make sure my config was up-to-date as well.

You don't need to do this. It's not even well-defined what it means for a config to be up-to-date. Powerlevel10k guarantees that all configs will keep working the same way forever even if you update Powerlevel10k proper to pick up performance improvements and bug fixes. If you are satisfied with the way your prompt looks, there is no reason to change your config.

I modify config templates frequently but these aren't necessarily improvements that you want to pick up. When changing config template, I make no regards for existing users or think of continuity in any sense. There can be a lot of churn precisely because there is no reason for the existing users to apply changes in the config template to their config. Config templates at any point in time codify my best attempt to serve new users or to offer something fresh to the existing users who are bored of their prompt and want to change it just for the sake of changes.

Think of other projects that have configs. Some of them come with config generators, others have config templates, most have nothing so that you start with a blank slate. Do you pull config updates from any of them? I guess not. Powerlevel10k config is no different.

**Comment by polothy** [comment]
> You don't need to do this.

Well, that's good hah! Was worried that they needed to stay in sync, but sounds like that is not the case.  Cheers and thanks for the quick reply.
