### ISSUE TITLE
Hiding entire prompt line, if it is empty

### ISSUE THREAD

**Issue by richard-kramer** [romkatv/powerlevel10k#2338]
Is there any way to hide an entire line of prompts if none of them render?

I've got the `vcs` and multiple other (mostly version manager) prompts on a second prompt line. But there are directories, where none of them show up, leading to an unnecessary empty line between the first (`os_icon`, `dir`, etc.) and third (`prompt_char`, etc.) one.

Is there any way to hide the entire line without checking some ominous state of each possible prompt (like in #504)?

Something like this:

```sh
function p10k-on-pre-prompt() {
  emulate -L zsh -o extended_glob
  if [[ "$PROMPT_LINE_2" != "" ]]; then
    p10k display 2=show
  else
    p10k display 2=hide
  fi
}
```

Where `$PROMPT_LINE_2` of course is some imaginary variable I came up with, which tells me if the line would be entirely empty or not.

**Comment by romkatv** [comment]
Powerlevel10k doesn't have such an option.

My personal advice is to use a two-line prompt with Lean style and transient prompt.

**Comment by romkatv** [comment]
I'm closing it because I don't intend to do anything here. You have 3 options (which you already know):

1. Use a two-line prompt. I'm yet to see a prompt so full of segments that two lines isn't enough.
2. Use your current config.
3. Rearrange segments in your current config so that you never have empty lines in it.
4. Do something similar to https://github.com/romkatv/powerlevel10k/issues/504.

There is no way to check whether a prompt segment is empty. Moreover, such a check is impossible even in theory because the content of a prompt segment can change at any moment.
