### ISSUE TITLE
VCS segment foreground color

### ISSUE THREAD

**Issue by GiDW** [romkatv/powerlevel10k#238]
I can not seem to set a different foreground color for the vcs segment. I am able to change the git icon's color but not the other parts of the vcs segment (branch icon, branch name). 

What are the correct variables to customize the foreground colors of the vcs segment?

I have tried:
```
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BRANCHFORMAT_FOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_BRANCH_FOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_BRANCHFOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_VCS_FOREGROUND='white'
```

The background color is correct but the foreground color stays the default green.

**Comment by romkatv** [comment]
> I can not seem to set a different foreground color for the vcs segment. I am able to change the git icon's color but not the other parts of the vcs segment (branch icon, branch name).
>
> What are the correct variables to customize the foreground colors of the vcs segment?
>
> I have tried:
>
> ```
> POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
> POWERLEVEL9K_VCS_CLEAN_BRANCHFORMAT_FOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_BRANCH_FOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_BRANCHFOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
> POWERLEVEL9K_VCS_FOREGROUND='white'
> ```

Out of these, only `POWERLEVEL9K_VCS_CLEAN_BRANCH_FOREGROUND` and `POWERLEVEL9K_VCS_CLEAN_BRANCHFOREGROUND` are incorrect. The rest will work as you expect.

![image](https://user-images.githubusercontent.com/1282067/65768996-ce768900-e132-11e9-81d9-109164ff2364.png)

Is it possible that you haven't listed all of your `POWERLEVEL9K` settings? There are many other settings, which, if set, will affect the content of your prompt. For example, `POWERLEVEL9K_VCS_CONTENT_EXPANSION='%1Fhello'` will turn the content of `vcs` prompt into red `hello` regardless of any other settings.

If your config has been generated by the configuration wizard, please read on. Otherwise please post the output of `typeset -m 'POWERLEVEL9K_*'`.

At the bottom of your `~/.zshrc` you should have these two lines:

```zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
```

If you heed the comment and open `~/.p10k.zsh`, you'll see that it defines `POWERLEVEL9K_VCS_CONTENT_EXPANSION`. The definition has plenty of comments to make it possible to customize the format of `vcs` prompt segment without being an expert in zsh. If your goal is to change colors, look for things like `%76F`. Changing `76` will change the color of the subsequent text.

If you prefer the prompt style with different background colors for different prompt segments, it might be easier to not run the configuration wizard and write your config manually from scratch.

**Comment by GiDW** [comment]
I did use the configuration wizard to create a config. My .zshrc looks like his:

```zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

ZLE_RPROMPT_INDENT=0

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    dir
    vcs
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    time
)

POWERLEVEL9K_DIR_FORGROUND='blue'
POWERLEVEL9K_DIR_BACKGROUND='236'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='blue'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'

POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='236'
POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''
```

Looks like I will need to create my configuration manually. 

Thank you for the clarification.

**Comment by krupeshanadkat-byjus** [comment]
Can anyone help me with this please? thanks

<img src="https://i.imgur.com/PkMBMFc.jpg" >

**Comment by romkatv** [comment]
@krupeshanadkat-byjus This:

```zsh
POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND=green
```

**Comment by rodrigopolo** [comment]
> I can not seem to set a different foreground color for the vcs segment. I am able to change the git icon's color but not the other parts of the vcs segment (branch icon, branch name).
> 
> What are the correct variables to customize the foreground colors of the vcs segment?
> 
> I have tried:
> 
> ```
> POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
> POWERLEVEL9K_VCS_CLEAN_BRANCHFORMAT_FOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_BRANCH_FOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_BRANCHFOREGROUND='white'
> POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
> POWERLEVEL9K_VCS_FOREGROUND='white'
> ```
> 
> The background color is correct but the foreground color stays the default green.

In the `.p10k.zsh` file you probably have the `typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'` set, so look for the `function my_git_formatter()` and there you can set the colors:

```sh
    # Styling for different parts of Git status.
    local      clean='%F{#fbf1c7}' # black foreground  %0F Git branch
    local   modified='%F{#fbf1c7}' # black foreground  %0F !1
    local       meta='%F{#ff0000}' # white foreground  %7F
    local  untracked='%F{#00ff00}' # black foreground  %0F
    local conflicted='%F{#0000ff}' # red foreground    %1F
```

**Comment by vac-kam** [comment]
@GiDW

To get the behavior you are seeking, you want to change this code in `~/.p10k.zsh`:
```zsh
    # Styling for different parts of Git status.
    local       meta='%7F' # white foreground
    local      clean='%0F' # black foreground
    local   modified='%0F' # black foreground
    local  untracked='%0F' # black foreground
    local conflicted='%1F' # red foreground
```
to something like this:
```zsh 
    # Set color overrides to empty values (prevents `POWERLEVEL9K_VCS_FOREGROUND` from being overwritten)
    local       meta=''
    local      clean=''
    local   modified=''
    local  untracked=''
    local conflicted=''
```
Optionally, you can set your desired colors there, instead of ditching the whole thing like I have.
