### ISSUE TITLE
disk_usage but remaining, and in units!

### ISSUE THREAD

**Issue by romanr** [romkatv/powerlevel10k#2436]
I searched p10k and p9k documentation and couldn't find anything about displaying disk remaining usage in actual MB/GB units rather than disk used in percent.
With modern terabyte sized drives, disk usage at 99% may be just fine to have all the time. On the other hand, having 99% all the time you would not see it approaching 100%.

Would be nice to have something like disk_remaining in numan readable format of course as `df -h` does.

Thank you.

**Comment by romkatv** [comment]
Disk usage prompt segment is primarily decorative, just like all other prompt segments that reflect the state of the machine rather than the current shell session. As such, I'm not keen on extending it. However, you can implement what you need via a custom prompt segment. Check out the output of `p10k help segment` and search for "example" in your `~/.p10k.zsh`.
