### ISSUE TITLE
The repo size is too big.

### ISSUE THREAD

**Issue by gapplef** [romkatv/powerlevel10k#245]
I use `Zplug` to manage Zsh plugin. Recently, I find the repo size of `powerlevel10k` is 157.5 MB due to the big `.git`, much larger than other plugins that are normally smaller than 1M.
Any reason for this problem?

**Comment by romkatv** [comment]
You can add `depth:1` to the `zplug` command. I've updated docs to recommend this.

```zsh
zplug romkatv/powerlevel10k, as:theme, depth:1
```

Since you already have powerlevel10k cloned, you'll need to prune it manually. This should do it:

```zsh
(
  emulate -L zsh
  setopt err_return
  cd ~/.zplug/repos/romkatv
  rm -rf powerlevel10k
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
)
```

The size of powerlevel10k will drop to 26M. Still much more than 1M but small enough to cause no inconvenience for most users. If you are severely space-constrained, you can manually delete files from `~/.zplug/repos/romkatv/powerlevel10k/gitstatus/bin` that you don't need. This might break updates by zplug so I wouldn't recommend it.
