### ISSUE TITLE
Any way to disable gitstatusd?

### ISSUE THREAD

**Issue by misuzu** [romkatv/powerlevel10k#246]
![](https://i.imgur.com/XjH9Les.png)
It's very annoing.

**Comment by romkatv** [comment]
`POWERLEVEL9K_DISABLE_GITSTATUS=true`

**Comment by misuzu** [comment]
@romkatv with ```POWERLEVEL9K_DISABLE_GITSTATUS=true```in ```.zshrc```  i'm getting ```gitstatus_query: command not found``` after every command.

**Comment by romkatv** [comment]
Ouch. That's a bug I've introduced last week. Thanks for reporting it! Fixed now.

**Comment by misuzu** [comment]
@romkatv it is working now, thank you!

**Comment by romkatv** [comment]
Note that your prompt will now be slower, especially when your current directory is a Git repository. The difference can be dramatic.

**Comment by exic** [comment]
Could it be that it isn't working again any more? Or is there a new setting / different way to set it? I need to disable gitstatusd because I have a `ulimit -u`  of 128 on a system (at least I think that that's the cause, because I get stuff like `fork: retry: Resource temporarily unavailable`) which is reached quite fast if I have more than 3 gitstatusd running. Probably because it's multithreaded and the threads count into that limit? I get 
```
ps -AL | grep -c gitstatus
33
```
with only one shell running.

As a workaround I can change `_p9k_declare -b POWERLEVEL9K_DISABLE_GITSTATUS 0` to `1` in `internal/p10k.zsh` – then gitstatusd doesn't start. Might also help for #823?

**Comment by romkatv** [comment]
> Could it be that it isn't working again any more?

Setting `POWERLEVEL9K_DISABLE_GITSTATUS=true` is still the way to disable gitstatus. Add it at the bottom of `~/.zshrc`.

**Comment by exic** [comment]
Thanks, setting it after loading the `~/.p10k.zsh` instead of before did it :see_no_evil:

**Comment by romkatv** [comment]
> Thanks, setting it after loading the `~/.p10k.zsh` instead of before did it 🙈

You can also put it in `~/.p10k.zsh`. That's where it belongs.

**Comment by romkatv** [comment]
By the way, if you don't need git status in prompt on that restricted machine, remove `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`. This will prevent gitstatusd from loading and will make your prompt fast. By comparison, if you set `POWERLEVEL9K_DISABLE_GITSTATUS=true` but keep `vcs` in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`, prompt will be slow.

**Comment by Groxx** [comment]
I currently have `export POWERLEVEL9K_DISABLE_GITSTATUS=true` set:
- at the beginning of my zshrc, before oh-my-zsh sets up p10k
- at the end of my zshrc, after omz
- and in a direnv .envrc in a mega-repository's folder that's causing problems with gitstatusd

none of which does anything.  should this still be working?

**Comment by romkatv** [comment]
@Groxx `POWERLEVEL9K_DISABLE_GITSTATUS` needs to be set in `~/.zshrc` anywhere. If you set it at the end, that would ensure that it's not unset by anything else. You don't need to export it. There is no point in setting it in `.envrc`.

> [...] in a mega-repository's folder that's causing problems with gitstatusd

Could you describe the problems? All problems I know of are fixable without disabling gitstatusd. If you disable gitstatusd, your prompt will have a noticeable lag *everywhere*, even in directories that aren't git repos. And in git repos the lag can be *massive*. In a mega-repository your shell may become virtually unusable.

> none of which does anything

The flag is meant to disable gitstatusd. Does it disable gitstatusd? You can verify with the following command:

```zsh
typeset -pm 'VCS_STATUS_*'
```

If it outputs anything, then you have gitstatusd. If it outputs nothing, you don't have gitstatusd.

> I still have a git status on my prompt and it still causes major performance issues in that repository. should this still be working?

Disabling gitstatusd doesn't remove git status from your prompt. It absolutely does make your prompt slow, especially in larger repositories.

If you want to remove git status from your prompt, open `~/.p10k.zsh`, search for `vcs` and remove the first hit.

However, as I mentioned above, if you can tell me which issues you are experiencing in the mega-repo while using gitstatusd, I might be able to offer a fix for that.

**Comment by Groxx** [comment]
>Disabling gitstatusd doesn't remove git status from your prompt. It absolutely does make your prompt slow, especially in larger repositories.

Aaah, that'd explain it.  It just stops using the daemon.  Yeah, my goal is to remove git from the prompt at all for this repo (but I love it elsewhere, p10k has overall been absolutely excellent).  I have not checked if it stopped using gitstatusd, but I assume it did.

Is there an easy-ish way to remove the git prompt entirely from this subfolder?  In the worst case I could probably set it up so I automatically start a new shell when I `cd` in, but I'd kinda prefer to not do that if possible.  Direnv is easy to set up for this, but I think it's too restrictive to allow that (which is probably a good thing most of the time).

> Could you describe the problems? All problems I know of are fixable without disabling gitstatusd.

Unfortunately not much concrete.  I noticed my CPU and disk going nuts for several minutes, and when I checked I saw ~ a dozen gitstatusd processes all using as much CPU as possible, all on that mega-repo.  I'm not sure if they were actually infinite-looping or just competing so heavily with each other that they were taking 100x longer than normal.  I may have had two or three terminal windows open in there, but I didn't even have that many terminal sessions _at all_ so I'm not sure why there were so many or what they were doing.

Normal `git status` checks in this repo take upwards of 5 seconds on a hot cache, and 20-ish or worse on cold, so we also have tried gitwatch and watchman... but both of those screw up routinely (missing edited files, or "phantom" edits that don't exist) so I disable them and just live with the latency.  So far I haven't seen gitstatusd produce any incorrect results, so I'm quite happy with that, and this is the first time I've seen it run so many hot processes.

**Comment by romkatv** [comment]
@Groxx What is the output of the following command when your current directory is within the problematic repo?

```zsh
git ls-files | wc -l
```

**Comment by Groxx** [comment]
350k files, 550k commits

**Comment by romkatv** [comment]
@Groxx There are two options. Chose the one you prefer.

## Option 1

Run this in your repo:

```zsh
git config --local bash.showUntrackedFiles false
git config --local bash.showDirtyState false
```

These settings only affect prompt. They'll disable the computation and the display of untracked files and staged, unstaged and conflicted changes. You'll need to run these commands every time you clone the repo.

The names of these config options start with "bash" because they were introduced in https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh. I've made gitstatusd respect the same options.

## Option 2

Alternatively, open `~/.p10k.zsh`, search for `POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY` and set its value to 100000. This option instructs gitstatusd to skip the computation of the number of unstaged, untracked and conflicted changes if there are more than 100k files in the repository's index.

I'd recommend going with option 2 because it'll work with all huge repos. Note that you'll still see the "cheap" information in your prompt: the branch name, the number of stashes, etc. You'll also see an indicator that tells you that some info is missing.

**Comment by Groxx** [comment]
I finally got around to testing these realistically / while doing a bunch of git changes and dev work, and: works great!  Thank you!  It takes ~1-2 seconds sometimes, but that's substantially better, and it seems to compete a lot less aggressively with other instances / load-heavy test/build work.

**Comment by romkatv** [comment]
@Groxx Thanks for the update. Which option did you end up using? Also, where do you store your git repo? HDD, SATA SSD, NVMe M.2?

**Comment by Groxx** [comment]
This would be a Mac NVMe from 2019.  So pretty darn fast overall, but the latest and greatest is faster by a good margin now.

I'm currently sticking with option 2 since there are a couple other mega-repos that I (very) rarely touch, and I'll almost certainly forget to set those git configs if I ever re-clone them for some reason.  Works well enough, and I do very much like that gitstatusd doesn't (seem to?) compete for lock files with other git commands.

**Comment by romkatv** [comment]
> I'm currently sticking with option 2

Good choice.

> Works well enough, and I do very much like that gitstatusd doesn't (seem to?) compete for lock files with other git commands.

Correct, gitstatusd doesn't lock git repos.

**Comment by romkatv** [comment]
@seodev-org What are you trying to say? I cannot make sense of your comment.
