### ISSUE TITLE
Update prompt from async custom segment?

### ISSUE THREAD

**Issue by davidparsson** [romkatv/powerlevel10k#2471]
I have been trying to implement my own asynchronous segment, and it all works fine, except the prompt is not updated when the async job is completed, only when a new prompt is rendered. I have read https://github.com/romkatv/powerlevel10k/issues/609 and https://github.com/romkatv/powerlevel10k/issues/503 but something seems to be missing.

I guess the relevant parts are the following:

```zsh
# Callback of the async job
function _my_async_segment_callback() {
  # Get result
  local return_values=(${(f)3})
  local working_directory=$return_values[1]
  local result=$return_values[2]
  # Store result
  _my_async_segment_result[$working_directory]=$result
  # Uptate prompt
  zle reset-prompt
  zle -R
}
```

```zsh
function prompt_my_async_segment() {
  _my_async_segment_compute

  local result="$_my_async_segment_result[$PWD]"

  local state="PRESENT"
  if [[ -z $result ]]; then
    state="ABSENT"
  fi
  
  p10k segment -s $state -f blue -c "$result" -t "async:$result"
}
```

The [full example can be found here](https://github.com/davidparsson/p10k-async-segment), which is an attempt at documenting this. It would be pretty sweet with some official documentation on how to do this though.

Thanks for a very nice and fast utility!

**Comment by romkatv** [comment]
What does your request consist of? To write better docs?

**Comment by davidparsson** [comment]
It was two-fold I guess, but I accidentally submitted my issue before it was completed. Sorry!

I have been trying to create an async custom segment, and having a minimal example of this would have helped me.

The other part of my issue was how to make my custom prompt update once the async callback completed, but I have found that my issue was related to single/double quotes.

For a future reader, single-quoting expressions and adding `-e` made the following work (although the `$state` needs to be reworked):

```zsh
function prompt_my_async_segment() {
  _my_async_segment_compute
  
  p10k segment -f blue -e -c '$_my_async_segment_result[$PWD]' -t '$_my_async_segment_result[$PWD]'
}
```

**Comment by romkatv** [comment]
The existing docs and the examples sufficed for you, right? Single quotes vs double quotes is a common mistake but it's too basic for p10k to teach this stuff.

**Comment by davidparsson** [comment]
Well, sure, but it too me (too many) hours to find out how to make it work properly, and it's really not that hard once it's clear how to do it.

I have made my point, and I will update my example and close this. Thanks!

**Comment by romkatv** [comment]
It's better to use `p10k display -r` instead of `zle reset-prompt` followed by `zle -R`.

**Comment by romkatv** [comment]
Yes, it would be nice to have a good example for your use case. It's a rare use case though.

**Comment by davidparsson** [comment]
Indeed, but I believe that this attracts power users.

Here are a few things I have not found answers to yet, that my ideal example would show:
1. Can I update state with asynchronous updates? How?
2. How should configuration defaults such as colors for different states be set? (I assume it's just a matter of declaring them, once states work, but I'm not sure.)
3. Can I use `_my_custom_segment_init` functions with my own segment? (I think not.)
4. Should I start my own async worker for my own segment? (I think so.)

**Comment by romkatv** [comment]
Powerlevel10k serves two types of users well: those who are satisfied with the config generated by `p10k configure` and those who can figure things out on their own. The former get nice out of the box experience and the latter get an incredible amount of power. Unfortunately, users in between—those who want to customize their prompt on top of the generated config but aren't very proficient in zsh—can sometimes suffer due to a lack of documentation and examples. I know it's a problem but it's not an easy one to solve and also not high on my priority list.

I'll try my best to answer your questions.

> * Can I update state with asynchronous updates? How?

Believe it or not, the answer can be derived from `p10k help segment`. Here's an example:

```zsh
function prompt_example() {
  p10k segment -s FOO -c '${(M)example_state:#FOO}' -et '$example_content' -i F -f red
  p10k segment -s BAR -c '${(M)example_state:#BAR}' -et '$example_content' -i B -f blue
}
```

If you add this prompt segment to your config, you can control what it displays by setting `example_content` and `example_state`. The latter can be set to "FOO" or "BAR" -- the two states supported by this prompt segment.

What happens here is that `prompt_example` always creates two segments but with mutually exclusive conditions that depend on the value of `example_state`.

> * How should configuration defaults such as colors for different states be set? (I assume it's just a matter of declaring them, once states work, but I'm not sure.)

The default foreground color is specified with `-f`. It can be overridden with `POWERLEVEL9K_<SEGMENT>_<STATE>_FOREGROUND`. I must be misunderstanding your question because I believe this answer is already obvious to you.

> * Can I use `_my_custom_segment_init` functions with my own segment? (I think not.)

No. The only API for custom segments that p10k provides is `function prompt_<SEGMENT>` with `p10k segment`.

> * Should I start my own async worker for my own segment? (I think so.)

You cannot use the async worker of p10k if that's what you are asking. This worker is actually really good, much better than zsh-async. Unfortunately, there is no public API for it.

**Comment by davidparsson** [comment]
Oh, right, creating multiple segments. That's clever!

Thanks a lot!

**Comment by davidparsson** [comment]
In the absence of a pull request enhancing the documentation, one can refer to [my async p10k plugin](https://github.com/davidparsson/p10k-ci-status/) for a complete but small enough example of asynchronous custom segments.
