### ISSUE TITLE
Theme mixes terminal-dependent Xterm-16 and terminal-independent Xterm-256 colors

### ISSUE THREAD

**Issue by geoelectric** [romkatv/powerlevel10k#2505]
I've been using P10K for awhile and really like it. But one thing that's seriously irked me, especially since I moved to gruvbox as my own theme, is that the Rainbow theme uses both Xterm 16 and Xterm 256 palette entries. I'm sure the others are similar.

Here's a simple example from my generated `~/.p10k.zsh` for the OS icon:

```
  # OS identifier color.
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7
```

The problem with this is that iTerm is in control of what 7 means, as the P10K docs call out for palette slots 0-15. 

> Colors are specified using numbers from 0 to 255. Colors from 0 to 15 look differently in different terminals. Many terminals also support customization of these colors through color palettes (a.k.a. color schemes, or themes). Colors from 16 to 255 always look the same.

Like a number of other color themes, gruvbox uses 0 & 7-15 for its palette flipping. So 7, which ostensibly is dark white, is actually dark brownish gray when the terminal is in light-background mode.

But 232 is an *absolute* request for "off-black." It's not palette-flipped because the terminal doesn't control it. As you yourself say above, it always looks the same.

So that results in this icon:

![Screenshot 2023-12-08 at 9 55 48 PM](https://github.com/romkatv/powerlevel10k/assets/314134/62028e2a-7b5e-4102-b2ef-2dccdaa4893e)

Had the theme used 0 for the foreground instead or used 251 for the background, it would've come out more correctly in gruvbox. The former would've palette flipped as expected and the latter would be an absolute combo that rendered the same in both modes. 

I did try to fix this for myself by mapping the traditional 0-15 colors to the rest of the 256 color palette and redefining every 0-15 element color for segments I use. It was proving a little annoying because it turns out almost the whole file is in 0-15, but I figured it was my issue, I should take care of it myself. But then I got to the git formatter colors, which I rely on daily but which aren't overridable without editing the generated file.

```
    # Styling for different parts of Git status.
    local       meta='%7F' # white foreground
    local      clean='%0F' # black foreground
    local   modified='%0F' # black foreground
    local  untracked='%0F' # black foreground
    local conflicted='%1F' # red foreground
```

The problem with those is that they're largely in the 0 & 7-15 palette-flipping portion of the gruvbox terminal-controlled color scheme, but their backgrounds are not.

```
 #####################################[ vcs: git status ]######################################
  # Version control background colors.
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=3
```

..and then there's the directory colors definition, which also mixes 16 and 256-color palettes side-by-side.

```
  ##################################[ dir: current directory ]##################################
  # Current directory background color.
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
  # Default current directory foreground color.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
```

So going from light to dark mode, I get one white-on-green combo that's readable, and one black-on-green combo that's drowned out by the non-flipping off-white directory foreground (254, above) beside it. Readability issues aside, it's just kind of annoying half my prompt is changing and half isn't.

![Screenshot 2023-12-08 at 10 35 08 PM](https://github.com/romkatv/powerlevel10k/assets/314134/91481b8b-9433-4ace-aa84-f571197209c8)

![Screenshot 2023-12-08 at 10 34 49 PM](https://github.com/romkatv/powerlevel10k/assets/314134/d1e0b7dd-b940-4450-93a4-214cde121e0a)

I think the point here is that while you can't be responsible for our terminal schemes, combining absolute colors with frequently-redefined (i.e. "relative") colors is likely to cause problems, just like any other situation where you're dealing with absolute vs. relative values.

The docs are pretty clear: 0-15 are controlled by the terminal and often look different, 16-255 always look the same.

So it would be much better if the themes were either completely 16-255 absolutes or 0-15 terminal-controlled. Given that there's a 256-color requirement on every theme but Lean anyway, the former would be far preferable.

**Comment by romkatv** [comment]
The configuration wizard offers only one style that is restricted to the basic colors: Lean with 8 colors. All other styles utilize at least 256 colors.

Moreover, two styles utilize both the low and the high colors. These are Rainbow and Pure original.

All other styles use only the high-numbered colors: Lean 256 colors, classic and Pure snazzy.

If you want Rainbow with 8 (or 16) colors, you'll need to manually edit `~/.p10k.zsh`.

**Comment by geoelectric** [comment]
Actually, what I want is 256 color Rainbow. You delivered 5% that and 95% 16 shifting colors. You should read my issue again, because you missed the point (or at least didn’t reply to it). You used terminal-defined colors for most of the theme but not all of it. There’s no way to keep it consistent. You should make it all 16-255 so it stays stable. I certainly hope you give more effort than this to fielding a well-documented issue I took an hour to write up for you. Cheers. On Dec 8, 2023, at 11:18 PM, Roman Perepelitsa ***@***.***> wrote:﻿
The configuration wizard offers only one style that is restricted to the basic colors: Lean with 8 colors. All other styles utilize at least 256 colors.
Moreover, two styles utilize both the low and the high colors. These are Rainbow and Pure original.
All other styles use only the high-numbered colors: Lean 256 colors, classic and Pure snazzy.
If you want Rainbow with 8 (or 16) colors, you'll need to manually edit ~/.p10k.zsh.

**Comment by romkatv** [comment]
Sorry, I was too brief in my response.

The configuration wizard provides several styles to choose from. I understand that your preferred style—Rainbow with only high-numbered colors—is missing. I agree that it would be better if there were more styles to choose from and if there was the style you personally want. Unfortunately, due to time constraints it's not something I can commit to implementing. As a workaround consider using Lean 256-colors. This is the style I use myself. Given my preference for Lean, you can see why this style has the two options that I believe you see as sensible (I certainly do): only low-numbered and only high-numbered colors.

**Comment by geoelectric** [comment]
That’s a good suggestion for more stable choice, and I apologize for my own frosty reply. I definitely shouldn’t be saying “you need” to do something. That’s rather counter to the point of OSS.

FWIW, I think Rainbow is a gorgeous theme. I just think it would benefit significantly from being tweaked into either an all 16-color palette so the terminal scheme color choice can control rendering, or all 256-color so the code can.

It’s strictly the split responsibility that causes an issue on light/dark palette-shifting terminals—as iTerm is by default as of the latest beta.

I wanted to call your attention to the overall issue with doing that in order to inform future theme work as well. Sticking to one or the other but not mixing both in any given theme would be a good idea. 

Thanks for your patient followup.

**Comment by romkatv** [comment]
We are on the same page. Everything you wrote makes perfect sense, I just don't have the bandwidth to work on this particular improvement.

Currently there is a separate config template for the [256-color lean](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-lean.zsh) and [8-color lean](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-lean-8colors.zsh) styles. These are large files with mostly identical content. Whenever I add a new prompt segment or a new parameter to an existing segment, I need to modify all config templates. If I were to add variations of the rainbow style within this framework, it would increase the amount of work I must do on every change. I'd very much like to avoid that. One alternative would be to change the rainbow style without splitting it into two but I'm afraid it would result in many users being upset. A better alternative would be to change the config templating scheme so that the number of config templates I need to maintain is `M + N` rather than `M * N` where `M` is the number of color schemes and `N` is the number of styles. That's a substantial amount of work. If I wanted to spend this much time on p10k development, I'd rather implement an alternative git backend to gitstatusd, which would resolve a significant number of issues people are having. In addition, suboptimal config created by the configuration wizard has a simple (albeit potentially time-consuming) workaround: edit the config by hand. Power users edit it by hand anyway, so it's not a major blocker.

I hope you can understand my perspective on this.

**Comment by geoelectric** [comment]
Yes, of course. Makes total sense to me. If you do take open source contributions, perhaps having the issue doc’d will invite a PR. That was more what I was going for. Thanks for the detailed explanation!

**Comment by romkatv** [comment]
The chance of receiving a PR addressing this issue that I would be comfortable merging is practically nil. I'm closing this as Won't Fix (sorry). Please don't let it discourage you from filing issues in the future.
