### ISSUE TITLE
Wrong arrow color

### ISSUE THREAD

**Issue by insureyang** [romkatv/powerlevel10k#2522]
When an incorrect instruction is entered, its arrow color is green, while the next correct instruction is red。

<img width="1002" alt="Snipaste_2024-01-02_20-43-08" src="https://github.com/romkatv/powerlevel10k/assets/64629972/f9d67084-007e-4657-af9c-9395a8565ea7">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

**Comment by rwmitchell** [comment]
Since you appear to be using MacOS, iterm2 with shell-integration puts a triangle on the command line with the color properly indicated.  For my prompt, I've added output a colored line after the command completes to indicate the exit status.

![image](https://github.com/romkatv/powerlevel10k/assets/15944841/9d1ae340-55b7-40a5-9f6f-cee270eec25d)
