### ISSUE TITLE
customize in a separate file

### ISSUE THREAD

**Issue by jotka** [romkatv/powerlevel10k#2549]
hi
Not really an issue, thanks for great software!.

I would like to customize (bold red context segment when I'm root :) ) the default config file (.p10k.zsh) in a separate file so it doesn't get overwrited when I do p10k configure.
What would be the best way to do it?

**Comment by rwmitchell** [comment]
I don't think there is an official way.

I make a new copy of .p10k.zsh as soon as I finish with ```p10k configure```.  These are my "gold" copies.  I compare the gold copies to check for any new changes/features since the last time I ran configure.

I also make a copy of .p10k.zsh after I finish editing .  If the gold copies didn't change, then I can just copy back in my custom version after running configure.  If the gold copies did change, then I edit from wherever is the easiest starting point.

**Comment by romkatv** [comment]
You can set `POWERLEVEL9_*` parameters in `.zshrc` after sourcing `~/.p10k.zsh`. These changes will sometimes work as you expect after `p10k configure` and sometimes they won't. In particular they may not work if you run `p10k configure` and select a different style from what you were using before. They also may not work if you upgrade powerlevel10k, run `p10k configure` and choose everything just as before. Moreover, it may not even be possible to make the same choices when you run `p10k configure` after an upgrade.

The official solution is to not run `p10k configure` after you choose a style to your liking. Simply keep the config.
