### ISSUE TITLE
MesloLGS breaks when turning on AtlasEngine

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#2557]
Greetings
I'm using rainbow theme with your patched MesloLGS NF font from Readme. The latest Windows Terminal update includes a new text rendering engine by default. And the prompt now looks like this:

![image](https://github.com/romkatv/powerlevel10k/assets/35394377/8ed1e8b2-acf7-4c98-9848-dc81c59b94ec)

I use a font size of 9px, if I make it 10 the problem disappears, but for me the font is too large. I tried downloading the original Nerd Font and there is no problem there either, but the prompt looks a little different and if I understand correctly, not all the glyphs are there.
Should I use the original Nerd Font, or can you update your own font?

upd The only font that looks similar to normal is MesloLGM NF, but even with that there is a problem.
![image](https://github.com/romkatv/powerlevel10k/assets/35394377/87f63998-b1aa-422f-9a4a-db005d787f34)

**Comment by romkatv** [comment]
Please take a look at the FAQ: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#sub-pixel-imperfections-around-powerline-symbols.

**Comment by Mystic8b** [comment]
> Please take a look at the FAQ: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#sub-pixel-imperfections-around-powerline-symbols.

So the problem is in the text rendering engine itself? Then I'll create an issue in the windows terminal repo. Thank you!

**Comment by romkatv** [comment]
You could say that, yes. Due to the way fonts work, it's not possible for a rendered to generate a perfect powerline without special-casting the powerline glyphs. If you run `p10k configure` and reach the screen with different head/tail styles, you should be able to see which of the powerline glyphs are special-cased by the rendered, if any. Those would be the ones that render perfectly no matter the font size. I believe the original Windows Terminal renderer special-cases all powerline glyphs used by the p10k configuration wizard, including the round ones that you are using. Perhaps the new engine does not do that yet.

**Comment by Mystic8b** [comment]
Thank you very much! I will fight MS😄
