### ISSUE TITLE
Feature Request: Discussion Forum

### ISSUE THREAD

**Issue by mayurankv** [romkatv/powerlevel10k#2565]
This is not a technical issue. I was curious about how to make the powerlevel10k prompt behave more like starship (since that is what I am used to) whilst getting the performance of powerlevel10k since I only use zsh. Unfortunately, finding information about how to do this can be relatively hard and so far has consisted of scrolling through bits and pieces of various other issues, most of which don't have a clear resolution since they are non-technical issues and I understand your focus is on fixing actual bugs. I think it would be very helpful to open up Discussions for this project (or some other forum alternative) as it would give users a space to discuss things like how to replicate other prompts or share snippets from useful configs which would make it easier for people to customise p10k, but also reduce the number of unnecessary issues raised.

Please let me know what you think!

**Comment by romkatv** [comment]
I hadn't enabled discussions earlier because I don't expect anything different out of them compared to issues. However, since I expect them to function exactly the same as issues, and not worse, there is no reason for me to *not* enable them, so I've enabled them now. Let's see how it goes. If you can create the first discussion, we can test drive it together.

**Comment by mayurankv** [comment]
Thanks, I've made a post. I hope it will consolidate more speculative theming questions outside of issues and potentially make it easier to reproduce non-default configurations for newcomers.
