### ISSUE TITLE
Using powerlevel10k in iTerm2: additional manual installation step necessary

### ISSUE THREAD

**Issue by workflowsguy** [romkatv/powerlevel10k#2579]
On macOS with iTerm2:

When during running `p10k configure`,  the "Lock" symbols are not displayed correctly, there may be an additional step required that is not mentioned in the [documentation](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#manual-font-installation):

in iTerm2, go to **Preferences → Profiles → Text**, set **Font** to MesloLGS NF, but also make sure that **Use a different font for non-ASCII text** is disabled.

Only after I unchecked this option did the symbols in `p10k configure` display correctly and additonal prompt configuration options become available.

**Comment by romkatv** [comment]
**Use a different font for non-ASCII text** is disabled by default though.

There are many non-default options that can break things. It would take too much space to cover all of them.

**Comment by rwmitchell** [comment]
Hmm.  Setting a different font for non-ascii text and then selecting a font that works properly allows me to then use any font, regardless of it having the proper glyphs.

**Comment by romkatv** [comment]
> Hmm. Setting a different font for non-ascii text and then selecting a font that works properly allows me to then use any font, regardless of it having the proper glyphs.

Yep. That's what this setting is for, although it's a crude solution because ASCII/non-ASCII isn't the right partitioning but in practice it's close to what you want.

I don't know about macOS but on Linux you can also do this on the level of the OS. That is, you can define a fallback font that will be used for glyphs missing in other fonts. This is of course better than ASCII/non-ASCII. Physically copying glyphs from one font to another (called *font patching*) is a viable alternative, which is often easier to achieve in practice and which works on all operating systems. This is in fact how MesloLGS NF is made: it's just Menlo (the font Apple used for the Terminal before switching to whatever they use now) with a bunch of glyphs added to it from other fonts. This patching is done by a script, which you can run with another font as a base. E.g., you can make a font with properly sized icons based on Hack, or any other monospace font. See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-was-the-recommended-font-created
