### ISSUE TITLE
_p9k_deschedule_redraw error after paste

### ISSUE THREAD

**Issue by petertimwalker** [romkatv/powerlevel10k#2584]
<img width="699" alt="Screenshot 2024-02-23 at 3 06 18 PM" src="https://github.com/romkatv/powerlevel10k/assets/108812366/7b9380e5-9bb2-4e41-a3b5-6f51f63a75d0">

# How to reproduce

Fresh install powerlevel10k

Typing anything after paste yields this 
```
_p9k_deschedule_redraw:zle:2: No handler installed for fd 18
_p9k_deschedule_redraw:3: file descriptor 18 used by shell, not closed
```

**Comment by romkatv** [comment]
It's almost certainly caused by a bug in one of the plugins you are using. 99% of the time it's zsh-autosuggestions. If you are using this plugin, you can either apply [this patch](https://github.com/zsh-users/zsh-autosuggestions/pull/753) or add `unset ZSH_AUTOSUGGEST_USE_ASYNC` at the very bottom of `.zshrc`.
