### ISSUE TITLE
git status when working with bare repos

### ISSUE THREAD

**Issue by kzshantonu** [romkatv/powerlevel10k#2585]
Would be nice to see git status when envs `GIT_WORK_TREE` and `GIT_DIR` are set

PS: love everything you've done

**Comment by romkatv** [comment]
`GIT_DIR` is respected but `GIT_WORK_TREE` is not. It shouldn't be a problem in practice because you can specify `core.worktree` in the git config of the repo.

```zsh
git --git-dir=/path/to/repo/.git config core.worktree /path/to/repo
```

Also note that bare repos aren't supported. This also shouldn't be a problem because you can set `core.bare` to false in the git config of the repo.

```zsh
git --git-dir=/path/to/repo/.git config bool core.bare false
```

Lastly, if the worktree is your home directory, see https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-is-git-status-from-homegit-not-displayed-in-prompt.
