### ISSUE TITLE
Issues with on-demand kubecontext segment gist

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#261]
Thought I'd branch out of #248 to keep that thread about `azure` segment.

I managed to reproduce the issue with `zsh-syntax-highlighting`, turns out the cause was hidden within prezto framework that I use, specifically [this block](https://github.com/sorin-ionescu/prezto/blob/2873885d37e362ae9be8ff4cb93ae36739ac0067/modules/environment/init.zsh#L27-L28).

Here's the minimal `.zshrc` needed to reproduce the issue:

```
source /tmp/colors-bug/powerlevel10k/powerlevel10k.zsh-theme
source /tmp/colors-bug/p10k-transient-kubecontext.zsh
source /tmp/colors-bug/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  kubecontext
  newline
  prompt_char
)
```

-----------

Here's an issue number two, I asked you earlier about recursive alias traversal (`kgp` -> `kg pod` -> `k get pod` -> `kubectl get pod`), however I stumbled upon a case where this breaks.

I happen to have the following alias:

```
alias rg='rg --hidden --follow --smart-case 2>/dev/null'
```

And once you type `rg` in terminal, it gets into an infinite loop.

The solution I think is to update the `while` loop to also check if the expanded string equals to the string you were trying to expand, in other words it would take `rg`, expand it to `rg --hidden --follow --smart-case 2>/dev/null`, then would take `rg` from there and expand it again to `rg --hidden --follow --smart-case 2>/dev/null, and at this point notice that expanded string equals the previous one and abort.

**Comment by romkatv** [comment]
> Here's the minimal `.zshrc` needed to reproduce the issue:
> 
> ```
> source /tmp/colors-bug/powerlevel10k/powerlevel10k.zsh-theme
> source /tmp/colors-bug/p10k-transient-kubecontext.zsh
> source /tmp/colors-bug/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> 
> autoload -Uz url-quote-magic
> zle -N self-insert url-quote-magic
> 
> typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
>   kubecontext
>   newline
>   prompt_char
> )
> ```

If you comment out `source /tmp/colors-bug/p10k-transient-kubecontext.zsh`, you still won't get syntax highlighting while typing. This is because typing calls `self-insert` widget, which was bound to `url-quote-magic` **after** zsh-syntax-highlighting was sourced. Since zsh-syntax-highlighting wraps widgets during sourcing (and not in a `precmd` hook like zsh-auto-suggestions), `self-insert` doesn't trigger highlighting.

Nevertheless, your code snippet was useful. Moving `source /tmp/colors-bug/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` to the bottom results in correct syntax highlighting if and only if `p10k-transient-kubecontext.zsh` is *not* sourced. Just what's needed to demonstrate the issue with the gist.

I've fixed this bug in the gist. Please update and try again.

> Here's an issue number two, I asked you earlier about recursive alias traversal (`kgp` -> `kg pod` -> `k get pod` -> `kubectl get pod`), however I stumbled upon a case where this breaks.

I've fixed this as well, although not the way you suggested. I think your suggestions will result in other types of bugs.

The new implementation is fairly robust but there is at least one edge case where it fails.

```zsh
alias -g nothing=
```

Typing `nothing kubectl` ideally should be handled the same way as plain `kubectl` but in the current gist implementation it's handled as `'' kubectl`. I think this is fine. Syntax highlighting also breaks on this code.

P.S.

That "magic" is crap. I'm appalled that prezto installs it. It changes your command line when you type or paste things, which can go unnoticed and is likely to be unexpected by most users. For example, suppose you want to clone powerlevel10k in the background.

```zsh
 2>/dev/null git clone https://github.com/romkatv/powerlevel10k.git&
```

If you attempt to type this, character-by-character, the actual command will be different, and it won't work. If you try to copy-paste it, it'll also be different.

I don't blame people who developed this "magic" or those who explicitly enable it for themselves, but installing it in prezto (and oh-my-zsh, too) for everyone by default? /smh

**Comment by maximbaz** [comment]
Glad you found my example useful, and thanks for the fast fixes - I confirm both issues do not reproduce anymore, even in the latest stable zsh.

> I've fixed this as well, although not the way you suggested. 

I think your approach is fine 👍 

> P.S. That "magic" is crap.

Hehehe, perhaps you are right, but it is what it is and we just have to support that 😄 

---

I'll close since all known issues are fixed for the moment, will reopen if I find something new!

P.S. Now that your gist becomes quite stable, I'm so much looking forward for it to be integrated in the core p10k and accessible in form of e.g. `AZURE_COMMAND` and `AZURE_LINGER_SECONDS` params! 🙂

**Comment by romkatv** [comment]
> Glad you found my example useful, and thanks for the fast fixes - I confirm both issues do not reproduce anymore, even in the latest stable zsh.

Thanks for the confirmation.

> > P.S. That "magic" is crap.
> 
> Hehehe, perhaps you are right, but it is what it is and we just have to support that 

Of course. It totally was a bug in the gist. You've bumped into it through magic but it could also be triggered by this:

```zsh
function my-self-insert() { zle .self-insert }
zle -N self-insert my-self-insert
```

Even if the bug was exposed *only* when magic was in use, I would still want to fix it or find a workaround. Perhaps I should come up with an unambiguous annotation for tangents and asides that have no consequences on the main thread. The post scriptum about magic was one of those. It should be treated as a rant against prezto (a project that I hold in very high esteem) and a personal advice to delete that part of the code from your own config. As prezto home page says, "It is highly recommended that you fork this project", which makes such edits easy.

In general, I'm highly motivated to make powerlevel10k better for users, even for those who have workflows, setups and aesthetic preferences different from mine. I hope you've already found out that it's not too difficult to convince me that some proposed changes would have positive effect even when I personally wouldn't benefit from them. I don't use azure, don't care about startup startup latency, and don't need to hide kubecontext (it sits in my right prompt together with other things that don't demand attention but are available when I want to look at them; sort of like a clock on a wall), and yet these are the things I've implemented thanks to your showing their usefulness to you and likely to other users.

> P.S. Now that your gist becomes quite stable, I'm so much looking forward for it to be integrated in the core p10k and accessible in form of e.g. `AZURE_COMMAND` and `AZURE_LINGER_SECONDS` params!

There is no rush, right? For now you can get the same behavior through user-defined configs.

**Comment by maximbaz** [comment]
> I hope you've already found out that it's not too difficult to convince me that some proposed changes would have positive effect even when I personally wouldn't benefit from them. I don't use azure, don't care about startup startup latency, and don't need to hide kubecontext (it sits in my right prompt together with other things that don't demand attention but are available when I want to look at them; sort of like a clock on a wall), and yet these are the things I've implemented thanks to your showing their usefulness to you and likely to other users.

Yes, and I'm very glad with the amount of help I'm getting from you, so once again thanks a lot for all your work! 😉 

> There is no rush, right? For now you can get the same behavior through user-defined configs.

Absolutely! I tried to extend your gist to support both azure and kubecontext but couldn't get that to work, but it's still not a big issue as I can rely on azure segment disappearing after 1h due to access token, so yeah it can definitely wait 😉

**Comment by romkatv** [comment]
> I tried to extend your gist to support both azure and kubecontext but couldn't get that to work

I've updated the gist. You now need to specify two parameters to make it work. Without them it'll have no effect. From the docs:

> The function is controlled by two parameters:
>
> - `TRANSIENT_PROMPT_KUBECONTEXT_CMD`: command pattern that triggers the display of `kubecontext`.
> - `TRANSIENT_PROMPT_AZURE_CMD`: command pattern that triggers the display of azure.
>
> Example configuration:
>
> ```zsh
> # Show kubecontext only when the current command is `kubectl` or `path/kubectl`.
> TRANSIENT_PROMPT_KUBECONTEXT_CMD='(*/|)kubectl'
>
> # Show azure only when the current command is `az`, `path/az`, `terraform`, or
> # `path/terraform`.
> TRANSIENT_PROMPT_AZURE_CMD='((*/|)az|(*/|)terraform)'
> ```

**Comment by maximbaz** [comment]
Wooow, thank you!

**Comment by maximbaz** [comment]
Found a small bug, but not sure how to fix it, maybe you can give me a hint.

Given these two aliases:

```
alias k=kubectl
alias k!=kubectl
```

The lines below correctly unwrap the first alias, but not the second.

```
  function _transient-prompt-segment-on-buf-change() {
    emulate -L zsh
    local cmd="${(Q)${(Az)BUFFER}[1]}"
    if (( $+aliases[$cmd] )); then
      if functions[_transient-prompt-segment-cmd]=${(q)cmd} 2>/dev/null; then
        cmd="${(Q)${(Az)functions[_transient-prompt-segment-cmd]}[1]}"
        unset 'functions[_transient-prompt-segment-cmd]'
      else
        cmd=
      fi
    fi
```

Is it some sort of unwanted shell expansion issue?

**Comment by romkatv** [comment]
> Given these two aliases:
> 
> ```
> alias k=kubectl
> alias k!=kubectl
> ```
> 
> The lines below correctly unwrap the first alias, but not the second.

Could you clarify what you do, what you expect and what you observe? Here's what I've tried.

1. Run `p10k configure` and generate a config with Lean style.
2. Run this:
```zsh
alias k!=kubectl
TRANSIENT_PROMPT_KUBECONTEXT_CMD='(*/|)kubectl'
eval "$(curl -fsSL 'https://gist.githubusercontent.com/romkatv/33f02f42245967072f8d00fc1db0f7fc/raw')"
```
3. Type `k!`, don't hit ENTER.

Expected: The current kubernetes context is displayed in the prompt.
Actual: The same as expected.

**Comment by maximbaz** [comment]
It seems to be again caused by some url magic inside prezto...

This is the minimal .zshrc that reproduces it for me:

```
source /tmp/powerlevel10k/powerlevel10k.zsh-theme # just cloned
source ~/.p10k.zsh # lean style default config
alias k=kubectl
alias k!=kubectl
TRANSIENT_PROMPT_KUBECONTEXT_CMD='(*/|)kubectl'
eval "$(curl -fsSL 'https://gist.githubusercontent.com/romkatv/33f02f42245967072f8d00fc1db0f7fc/raw')"

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic
```

If I comment the last line, then it works as expected for `k!`.

Let me know your thoughts...

**Comment by romkatv** [comment]
Couldn't reproduce. But then I remembered that you like enabling weird things and figured there is a chance you have `banghist` set. Lucky guess -- the problem indeed reproduces if I add `setopt banghist` to the config. Should be fixed now.

Thanks for reporting this!

**Comment by maximbaz** [comment]
> But then I remembered that you like enabling weird things

😂 😂 😂 

Only prezto! 😂 Apologies for bad report though, I was sure the above was the entire contents of my `.zshrc`, but seems I was wrong or I missed something. And as usual, thanks for solving the mystery!
