### ISSUE TITLE
Colorize prompt differently for Ctrl-C or Ctrl-G versus non-zero error code?

### ISSUE THREAD

**Issue by angelatlarge** [romkatv/powerlevel10k#2615]
Thank you for this project! Is there some way to colorize the prompt differently when command is terminated via Ctrl-C or command input is terminated via Ctrl-C or Ctrl-G? I like the red prompt on non-zero exit code, but don't want it when I abort the command input.

**Comment by romkatv** [comment]
There is no easy way to achieve this but you can do it with a bit of manual customization. It's not something I would recommend doing though. In all shells a command that exits due to SIGINT is considered to have exited with an error. Having errors shown in red is simpler than having only some errors shown in red.

**Comment by angelatlarge** [comment]
I guess Ctrl-G is interpreted essentially as SIGINT? I'll probably forego this, but if you are able to give me a pointer or two as to how to get started with distinguishing SIGINT from error return code in terms of prompt colorization, it might be helpful.

Thank you!

**Comment by romkatv** [comment]
Ctrl-C is handled by the terminal. When you press it, the terminal sends a signal (`INT`) to the foreground process group it controls. When zsh receives this signal, it aborts whatever it's been doing. If you have a non-trivial zsh config (using powerlevel10k, or oh-my-zsh, qualifies as non-trivial), `INT` can break your shell session in subtle ways. I never press Ctrl-C when using zsh because I know how difficult it is to write code that won't break when interrupted at a random point.

Ctrl-G is handled by zsh. By default it is bound to `send-break`. It does not have the downsides of Ctrl-C and is safe to press. However, I never press Ctrl-G because there is a better alternative: `kill-buffer`. By default, this widget is bound to `^X^K` in emacs keymap and unbound in other keymaps. You can rebind it like this:

```zsh
bindkey '^G' kill-buffer
```

If you still want to use Ctrl-G, and if you want it to affect prompt, you'll need to implement your own widget that sets a global parameter to indicate it was called and invokes `.send-break`. You can use the global parameter in prompt. It's worth repeating that `kill-buffer` is likely a better soltion.
