### ISSUE TITLE
Detect Linux console (VC) and fall back from non-functional features

### ISSUE THREAD

**Issue by WildPenquin** [romkatv/powerlevel10k#2723]
Hi,

Apologies if this has already been discussed somewhere (I'd be surprised if no-one has had this issue), I tried search but couldn't find any.

I really like this theme on my X.Org terminal emulators. However, sometimes (for minimalist sessions, setting up etc.) I'm using a plain Linux Console (a VC).

The Linux framebuffer console supports at maximum 256 glyphs with 16 colors or 512 glyphs with only 8 colors. Obviously, the fancy rainbow -prompt will break down (with question marks, no colors).

The framebuffer does use UTF-8 encoding but a limited character set, which can be changed.

Is there a ready-made, OOTB way to fall back to a simpler prompt?

Are there recommended character sets (FONTMAPs) to use, to get a  somewhat fancy prompt?

I could DIY by reading the TERM variable in my .zshrc.local, but I have a hunch I could be missing something, or if the theme does not currently handle this, it would not be that difficult to implement (I can see the messages about "very limited support" etc. in the README.md).

**Comment by romkatv** [comment]
Run `p10k configure` from a VC and from a graphical terminal emulator to generate two `~/.p10k.zsh` configs. `source` one of them from `~/.zshrc` conditionally. If you are using zsh4humans, this whole thing is automatic.

**Comment by ArchWand** [comment]
Leaving a comment here to help boost visibility. This solution didn't immediately occur to me since my previous theme directly handled the case of `$TERM` being `linux` by conditionally switching out the color palettes, using an 8 color palette when it detected that less than 256 colors were available, and using the 256 color palette otherwise; this led me to first read through #374. However, this solution makes more sense to me, and is altogether more flexible.

Once again, thank you for such an amazing tool!
