### ISSUE TITLE
How to add space after prompt character?

### ISSUE THREAD

**Issue by mathomp4** [romkatv/powerlevel10k#288]
Dear @romkatv,

Per your post on the `starship` issue, I decided to try out p10k today. Did a `p10k configure` and have a prompt. But, I'm wondering if you know how to add a space in the prompt? To wit my prompt looks like:
<img width="1082" alt="Screen Shot 2019-10-24 at 10 51 07 AM" src="https://user-images.githubusercontent.com/2982494/67497622-3c3ba500-f64c-11e9-9868-15b2c0027f4e.png">
I'd really like to have a space after the `>` character. Is this possible?

**Comment by romkatv** [comment]
There should be a space there by default. Something must be broken.

If you press `Ctrl+R`, or type `ls` followed by `TAB`, does your cursor change its position? If yes, things are definitely broken. Try the following, in order:

1. Type `ZLE_RPROMPT_INDENT=1`.
2. If using iTerm, verify that *Treat ambiguous-width characters as double width* is **not set** in properties.
3. Install the recommended font. If using iTerm2, `p10k configur` will offer to do it for you. If using another terminal, follow [these instructions](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k).
4. Follow [these instructions](https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-is-my-cursor-in-the-wrong-place).

Let me know which step fixes or if none do.

**Comment by mathomp4** [comment]
Ooh. That first one worked. Is it a safe thing to add to my `.zshrc`?

As for font, I think I'm using Hack Nerd Font because Meslo Nerd was a bit to narrow for me the last time I tried it. Maybe I picked the wrong one?

**Comment by mathomp4** [comment]
I just grabbed the font and it looks like Hack Nerd Font has bigger "those weird icons". Here is what my term looks like with each (and with ZLE_RPROMPT_INDENT=1).
MesloLGS NF:
<img width="1082" alt="Screen Shot 2019-10-24 at 11 13 59 AM" src="https://user-images.githubusercontent.com/2982494/67499700-84a89200-f64f-11e9-954c-22b29b13a0cd.png">
Hack Nerd Font:
<img width="1082" alt="Screen Shot 2019-10-24 at 11 13 35 AM" src="https://user-images.githubusercontent.com/2982494/67499743-92f6ae00-f64f-11e9-95d5-2481a9cded56.png">
My eyes aren't great, so bigger little icons are better. :smiley:

**Comment by romkatv** [comment]
> Ooh. That first one worked. Is it a safe thing to add to my `.zshrc`?

So the problem is that you are hitting a bug in `zsh` (not in powelevel10k but zsh proper). I've fixed it some time ago but your version doesn't have the fix yet. You can see the effects of this bug by typing `zsh -df` and then `PROMPT='>'; RPROMPT='<'; ZLE_RPROMPT_INDENT=0`. You'll notice that the cursor jumps when you press `Ctrl-R` or `ls` and `TAB`.

The default value of `ZLE_RPROMPT_INDENT` is unset. The fact that it was `0` for you implies that it was explicitly set to `0` by your `~/.zshrc`. You can either find that line and remove it (verify by typing `zsh` and then `echo $ZLE_RPROMPT_INDENT` -- must be empty) or add `unset ZLE_RPROMPT_INDENT` at the bottom of `~/.zshrc`. The former is better.

> As for font, I think I'm using Hack Nerd Font because Meslo Nerd was a bit to narrow for me the last time I tried it. Maybe I picked the wrong one?

The difference you are pointing out is not Hack vs Meslo but rather monospae vs non-monospace. In your Hack font some icons take more than one column. Remember that question in the configuration wizard where it asked about icon overlap? It wanted to know if your font is monospace.

In general, monospace fonts give much more consistent results because everything is the same width. With non-monospace fonts you have to add spaces after icons that may be too wide. The problem is that there is no way to know which icons are too wide and which aren't. So you end up with too much whitespace here and too much there. You can see that on the left side of your screen things are very tight, but on the right side there is too much space between the clock and the time.

In addition, the small size of icons in monospace fonts is better for productivity. These icons are almost meaningless, and if they are big, they are stealing too much attention from things that actually matter (text).

Nerd Fonts has a monospace and a non-monospace version for every font.

I usually recommend a monospace font, but it's your choice of course.

NOTE: After you switch to MesloLGS NF, you need to run `p10k configure`. It'll fix the whitespace.

**Comment by romkatv** [comment]
I believe this issue is resolved. Please reopen if it isn't.
