### ISSUE TITLE
add elements below cursor line using $terminfo

### ISSUE THREAD

**Issue by doronbehar** [romkatv/powerlevel10k#290]
I'm trying to migrate my old prompt setup to p10k, for the sake of performance. My old configuration had at the setup:

```zsh
terminfo_down_sc=$terminfo[cud1]$terminfo[cuu1]$terminfo[sc]$terminfo[cud1]
```

And then:

```zsh
function zle-keymap-select {
	case ${KEYMAP} in
		"vicmd")
			PS1_2="-- NORMAL --"
			;;
		"viins"|"main")
			PS1_2="-- INSERT --"
			;;
		"visual")
			PS1_2="-- VISUAL --"
			;;
	esac
	PS1="%{$terminfo_down_sc$PS1_2$terminfo[rc]%}$PS1_base"
	zle reset-prompt
}
```

While `$PS1_base` had all the left elements. This resulted in a prompt that looks like this:

![NUX-selection:2019 10 25-10:30:48](https://user-images.githubusercontent.com/10998835/67551908-731bc480-f6f9-11e9-8133-e5daf289a061.png)

Is there an elegant way of configuring an equivalent with p10k? Does it already provides wrappers for elements in a new line?

**Comment by romkatv** [comment]
Yes, it is possible to do the same thing, although maybe you won't need to.

p10k has a built-in segment called `prompt_char` that shows your current vi mode. In addition to normal, insert and visual it also shows override. In addition, it can indicate success/error of the last command through colors.

Here's basic configuration (copied from "classic" style template):

```zsh
# Green prompt symbol if the last command succeeded.
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=76
# Red prompt symbol if the last command failed.
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=196
# Default prompt symbol.
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
# Prompt symbol in command vi mode.
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
# Prompt symbol in visual vi mode.
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='Ⅴ'
# Prompt symbol in overwrite vi mode.
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
```

You can also show it without background, the same way "classic" does it.

P.S.

Aren't you going to end up with junk on your screen if you type `echo X`? I haven't tried it but it looks like you'll see `X- INSERT --` above your prompt?

There is no `visual` keymap in zsh, so I'm wondering how (and if) your prompt ever displays `-- VISUAL --`. There is visual mode, and it is possible to detect it, but you cannot do it by looking at `KEYMAP`.

**Comment by romkatv** [comment]
Here's how you can achieve the same thing you had before:

```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode user dir)
typeset -g POWERLEVEL9K_VI_INSERT_MODE_STRING='-- INSERT --'
typeset -g POWERLEVEL9K_VI_NORMAL_MODE_STRING='-- NORMAL --'
typeset -g POWERLEVEL9K_VI_VISUAL_MODE_STRING='-- VISUAL --'
typeset -g POWERLEVEL9K_VI_OVERWRITE_MODE_STRING='-- OVERWRITE --'
typeset -g POWERLEVEL9K_VI_MODE_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_VI_MODE_PREFIX="%{$terminfo[cud1]"
typeset -g POWERLEVEL9K_VI_MODE_SUFFIX=$'\r'"$terminfo[cuu1]%}"
typeset -g POWERLEVEL9K_VI_MODE_LEFT_SEGMENT_SEPARATOR=
typeset -g POWERLEVEL9K_VI_MODE_BACKGROUND=
typeset -g POWERLEVEL9K_VI_MODE_FOREGROUND=
```

It's hacky and will break in various cases. In addition to that issue with leftover junk I mentioned earlier, there will also be issues with multi-line commands. However, I believe this implementation will work in all cases in which your implementation worked. It has the advantage of *not* using `sc` and `cr`, which means that you can enable [instant prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-instant-prompt) -- a very useful feature.

I've written this down only because you asked. I don't recommend this and it's not a supported use of p10k.

**Comment by romkatv** [comment]
> I saw it commented in my `~/.p10k.zsh`

Several styles in the configuration wizard have it enabled. All lean styles and multi-line powerline styles without left frame, if I recall correctly.

> ... but I had no idea what will it do what it does.

That's definitely understandable. Comments above various `POWERLEVEL9K_PROMPT_CHAR_*` parameters hint at what it's about but it's not easy to make correct inference.

> Perhaps a more explanatory comment then `# prompt symbol` might be better.

Cannot put too many comments because people will stop reading them. What is needed is a proper online reference.

> I hope my first time user experience also mentioned in #169 is useful for you.

It is, thanks.

I'm aware that the lack of documentation is a pain for advanced users. Docs don't exist not because I think they are bad but because writing them is work that I haven't done.
