### ISSUE TITLE
Disable vcs_info for specific directories

### ISSUE THREAD

**Issue by seancmonahan** [romkatv/powerlevel10k#300]
Is there a way to exclude a specific directory from being checked by the VCS prompt element? I have keybase.io installed, and when I'm inside the `/keybase` directory (where keybase mounts its filesystem), the vcs plugin tries to access `/keybase/private/head`, which causes keybase.io to pop up an access denied notification.

As mentioned in #135, setting `zstyle ':vcs_info:*' disable-patterns "/keybase/private(|/*)"` doesn't seem to fix it. (Issue 135 was resolved by speeding up the git status so that the user didn't need to exclude a specific directory anymore.)

Cheers,
Sean

**Comment by romkatv** [comment]
Thanks for opening the issue.

I've done two things. First, I've changed [gitstatus](https://github.com/romkatv/gitstatus) so that it doesn't try to access `HEAD` in the current directory. Once you update powerlevel10k to the newest version the popup notification from keybase should disappear.

Second, I've added `POWERLEVEL9K_<segment>_DISABLED_DIR_PATTERN`. This parameter allows you to disable a prompt segment in any directory that matches a pattern. For example, if you have a Git repository in `/foo/bar` for which you don't want to see Git status in prompt, define the following parameter:

```zsh
POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN='/foo/bar(|/*)'
```

This can be useful even despite my gitstatus change because there are several other prompt segments in powerlevel10k that read files in the current directory.

While testing, I noticed that the popup also get triggered by [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). If you are using it (you should), you'll probably have to do something about it. The best solution in my opinion would be to disabled that useless popup but I don't know if it's possible (I don't use keybase).

**Comment by romkatv** [comment]
Timed out waiting for reaction. Reopen the issue if you are a human in possession of agency and still having issues.

**Comment by seancmonahan** [comment]
Thank you for the prompt response and fix --- it seems to be working great --- and for going above and beyond to add an entire new configuration parameter! (And sorry for the delay in testing this on my part. Didn't have a chance to test it over the weekend.)

And I'll take a look at `zsh-autosuggestions`. Thanks for the... suggestion :laughing:
