### ISSUE TITLE
Where does powerlevel10k gets POWERLEVEL9K_INSTALLATION_DIR from?

### ISSUE THREAD

**Issue by pr4bh4sh** [romkatv/powerlevel10k#303]
First of all thanks for making this, I had given up on the powerlevel9k because of the speed issue.

Now my issue, I'm trying to make the PWD path bold.  When I set  

` typeset -g POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true` in .pk10.zsh it only makes the text of pwd bold, not the whole path
\~/abcd/**efgh** vs **~/abcd/efgh**

It turns out that this is how it's implemented in powerlevel9k. (unless powerlever10k has reimplemented it). I can see that the logic to make it bold is implemented [here](https://github.com/Powerlevel9k/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L1001-L1017) 
Now if change the position of bld_on it should make the whole path bold but does not happens.

So I set the POWERLEVEL9K_INSTALLATION_DIR='/Users/myuser/powerlevel9k' and reload the .zshrc but no effect on the path.

This is my first attempt of customizing powerlevel(10/9)k so not sure if I'm doing something wrong.

**Comment by romkatv** [comment]
> Now my issue, I'm trying to make the PWD path bold.

There is no built-in support for this but you can achieve the same effect with the following combination of parameters:

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2048
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_DIR_PATH_SEPARATOR='%B/'
```

FWIW, if you run `p10k configure`, you'll get a much better better config. Instead of making the whole directory bold, powerlevel10k will make only important parts bold. See this case and read its description for more info:

[![asciicast](https://asciinema.org/a/258376.svg)](https://asciinema.org/a/258376)

> It turns out that this is how it's implemented in powerlevel9k. (unless powerlever10k has reimplemented it). 

All parameters that are recognized by powerlevel9k have the same effect in powerlevel10k. Implementation is different though.

> Now if change the position of bld_on it should make the whole path bold but does not happens.

You lost me there. Are you trying to edit the source code of powerlevel9k?

> So I set the POWERLEVEL9K_INSTALLATION_DIR='/Users/myuser/powerlevel9k' and reload the .zshrc but no effect on the path.

I don't understand what you are trying to achieve with this.

**Comment by pr4bh4sh** [comment]
Thanks for the quick response. setting those params worked.

I did set up the powerlevel10 with `p10k configure`. Highlighting the important parts bold(very good feature) not something I was interested in (simply because I wasn't aware of the feature) and my goad of making the dir path bold was for purely aesthetics. But surely I'll try that 👍 

> You lost me there. Are you trying to edit the source code of powerlevel9k?

Yes, I was hoping that it would achieve the goal.

> I don't understand what you are trying to achieve with this.

I was hoping that this would make the changes I made in powerlevel9k source load.

**Comment by romkatv** [comment]
> Yes, I was hoping that it would achieve the goal.

If you are using theme A, changing the source code of theme B won't affect your prompt. There is no symbiosis between p9k and p10k. They are as independent as any two separate themes can be. You can use either one or the other but not both at the same time.
