### ISSUE TITLE
[feature] Support Linux iproute2 command

### ISSUE THREAD

**Issue by si1kdd** [romkatv/powerlevel10k#305]
Hi, i just change my zsh theme from powerlevel9k to powerlevel10k,

However, on my Linux, i didn't install the **net-tools** (which contain ifconfig, netstat command etc.)

I found the p10k.zsh implementation is simply checking the local ip with **/sbin/ifconfig**,

https://github.com/romkatv/powerlevel10k/blob/47017e948e0e86eb56b9982ee41be28c44a849e6/internal/p10k.zsh#L3418-L3431

it only work on macOS, BSD series OS, and the Linux that install **net-tools**

I think you can check with the implementation of powerlevel9k,

https://github.com/Powerlevel9k/powerlevel9k/blob/3dafd79c41f8601b055e607ffefbfe3250c26040/functions/utilities.zsh#L380-L429

I would try to do a pull request at my free time,

Thank you.

**Comment by romkatv** [comment]
Thanks for opening the issue. I wasn't aware that some Linux installations are missing `ifconfig`.

> I found the p10k.zsh implementation is simply checking the local ip with `/sbin/ifconfig`

"Simply" isn't quite the right word because parsing the output of `ifconfig` is more difficult. Compare:

```text
❯ ifconfig
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.100.128.3  netmask 255.255.0.0  destination 10.100.128.3
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 2  bytes 184 (184.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 616 (616.0 B)
        TX errors 10  dropped 0 overruns 0  carrier 0  collisions 0

❯ ip -brief -4 a show
wg0              UNKNOWN        10.100.128.3/16
```

This also show why p10k isn't using the same implementation as p9k. The latter is broken. p9k is mistakenly looking at the operational link state instead of its administrative state. Operational state is unreliable with many drivers and is best ignored.

I could write another parser for `ip -4 a show` and use it if there is no `ifconfig` on the system. The output is similar enough to `ifconfig`, so it's not too much work.

```text
❯ ip -4 a show
18: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.100.128.3/16 scope global wg0
       valid_lft forever preferred_lft forever
```

Would that satisfy your needs?

**Comment by romkatv** [comment]
Timed out waiting for reaction. If you still care about this issue, please answer this question :point_down: and reopen.

> Would that satisfy your needs?

**Comment by si1kdd** [comment]
Sorry for the late reply,

Yes, i still care about this issue, if you could supply a implementation for non **net-tools** system,

It would be great !! 

Thank you.

**Comment by romkatv** [comment]
Done. Once you update powerlevel10k, prompt segments that parse network interfaces (`public_ip`, `vpn_ip` and `ip`) should work as long as you have `/sbin/ifconfig` OR `/sbin/ip`.

**Comment by si1kdd** [comment]
First of all, thank you,

However, i just find the different implementation of **ip** prompt between p9k and p10k .....

For example of the **ifconfig** output:

```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2  bytes 100 (100.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 100 (100.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.3  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::cf25:618d:7806:9aba  prefixlen 64  scopeid 0x20<link>
        ether f0:d5:bf:33:66:11  txqueuelen 1000  (Ethernet)
        RX packets 8206042  bytes 10364230453 (9.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1943918  bytes 346903565 (330.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

in p9k, the **ip** prompt segments would show address **192.168.0.3**
in p10k, always show the loop-back address -> **127.0.0.1** ...

I don't familiar with zsh script, but actually i want to show the non loop-back address version.

Is it possible to change 127.0.0.1 to 192.168.0.3 ??

**Comment by romkatv** [comment]
Prompt segment `ip` shows IP from a network interface whose name matches `$POWERLEVEL9K_IP_INTERFACE` regular expression. If there is more than one such interface, one of them is shown at random. The default value of `POWERLEVEL9K_IP_INTERFACE` is `.*`.

Assuming that you haven't defined `POWERLEVEL9K_IP_INTERFACE`, `ip` segment will show either IP from `lo` or from `wlp6s0` at random.

That's how it work in p10k. In p9k it's different because it has a bug that prevents it from seeing some interfaces. E.g., on my machine it's unable to see `wg0` (wireguard) and `lo` (loopback). Even if I explicitly set `POWERLEVEL9K_IP_INTERFACE=wg` or `POWERLEVEL9K_IP_INTERFACE=lo`, p9k won't show them as it'll mistakenly think that they are down.

It's possible that you've been relying on this bug in p9k to consistently choose `wlp6s0` despite there being two `UP` interfaces that match the regex. I do emulate some p9k bugs in p10k for the sake of backward compatibility but this bug is too egregious to enjoy such treatment.

Please define `POWERLEVEL9K_IP_INTERFACE` to match the interface from which you want to show IP address. Either like this:

```zsh
POWERLEVEL9K_IP_INTERFACE=wlp6s0
```

Or to match any interface at random that isn't `lo`:

```zsh
POWERLEVEL9K_IP_INTERFACE='([^l].*|.[^o].*|.|...+)'
```

**Comment by si1kdd** [comment]
Oh now i get it !
I will define the parameters.

Thank you for your information ! :smiley:

**Comment by romkatv** [comment]
You are very welcome.
