### ISSUE TITLE
Can't continue to scroll up in history after git status refresh

### ISSUE THREAD

**Issue by vibbix** [romkatv/powerlevel10k#306]
Given the time it takes for my repo to update its status, if i scroll up in my history while its background refreshing, upon the daemon updating the status bar I can no longer keep scrolling up.

**Comment by romkatv** [comment]
What terminal are you using?

What is the output of `uname -sm; typeset VCS_STATUS_INDEX_SIZE` while in that humongous repo?

**Comment by vibbix** [comment]
i am using iTerm2 on macOS Catalina with the latest ZSH.
`Darwin x86_64
VCS_STATUS_INDEX_SIZE=169509`

**Comment by romkatv** [comment]
Let's first establish that I understood the issue correctly.

When you hit ENTER while the current directory is within a *big git repo*, Git status in your prompt turns grey and stays that way for a long time. Eventually it gets redrawn with proper colors. If you start scrolling your terminal window up while Git status is grey, scrolling stops when Git status updates.

Is this correct? If so, there are two issues at play. The first is that iTerm2 scrolling breaks when prompt is updated. You'll need to report this to iTerm2. The second is that updating Git status takes unexpectedly long. It takes under 25ms on my machine for a Git repo of your size. Your machine may be slower but it should still take a fraction of a second. Something must be broken. If we can figure out what it is and fix it, then you won't have to report anything to iTerm2. Let's give it a try?

What machine are you using?

Please `cd` into the *big Git repo* and run the following command. Attach `/tmp/gitstatus.log` to this issue when the command completes.

```zsh
() {
  emulate -L zsh
  setopt err_return
  typeset -m 'ZSH_VERSION|ZSH_PATCHLEVEL'
  zsh --version
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -dfeic "
      time git status
      time git status
      time git describe --tags --exact-match || true
      time git describe --tags --exact-match || true
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 MY
      time yes | gitstatus_query -p MY
      time yes | gitstatus_query MY
      sleep 2
      time yes | gitstatus_query MY
      gitstatus_stop MY
      GITSTATUS_LOG_LEVEL=DEBUG
      gitstatus_start -s -1 -u -1 -c -1 -d -1 MY
      gitstatus_query -p MY
      gitstatus_query MY
      sleep 2
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
} &>/tmp/gitstatus.log
```

**Comment by vibbix** [comment]
2018 MacBook Pro with a Core i9 and 32Gb of RAM so hardware shouldn't be an issue. I have attached a scrubbed git status log. If that's too scrubbed, I can produce a better one via a DM probably.
[scrubbed_status.log](https://github.com/romkatv/powerlevel10k/files/3814872/scrubbed_status.log)

**Comment by vibbix** [comment]
Here's a GIF demonstrating this behavior in iTerm2
![issue](https://user-images.githubusercontent.com/1731900/68308025-25e50e80-007a-11ea-80df-35393f4ee07a.gif)

**Comment by romkatv** [comment]
> I have attached a scrubbed git status log. If that's too scrubbed, I can produce a better one via a DM probably.

Thanks! You scrubbed it just right. Everything I need for performance analysis is still there.

Powerlevel10k fetches Git info from the current repo on every prompt. The information it needs can be extracted with `git status` and `git describe --tags --exact-match`. Unlike other themes, Powerlevel10k doesn't actually call `git` but uses [gitstatus](https://github.com/romkatv/gitstatus) instead. When you reported that it took a very long time for Powerlevel10k to update prompt, my biggest concern was that gitstatus is doing something weird, which makes it slower than plain `git`.

The log file you've attached tells use the following:

- The first call to `git status` + `git describe --tags --exact-match` in your repo takes 3.078 seconds.
- The second call of the same takes 2.641 seconds. It's faster than the first call because of caches.
- The first `gitstatus_query` (this is the equivalent call from gitstatus) takes 1.519 seconds.
- The second `gitstatus_query` takes 0.538 seconds.

So `gitstatus_query` is 2 times faster on the first call and 5 times faster on the second. The latter number is much more important because you usually type several commands in the same repo.

5 times faster than `git` is within the expected range. On Linux with M2 SSD the difference is about 10x but on macOS it's usually smaller. It's also smaller with slower SSDs.

So whatever it is that makes your repo slow is affecting `git` as much as gitstatus. If you can figure out how to speed up the former, the latter will likely also get faster.

> Here's a GIF demonstrating this behavior in iTerm2

Thanks for the demo. I see that my description of the problem was incorrect. What you meant by "scrolling up" is likely calling `up-line-or-beginning-search`. I can tell you how to fix it if you can confirm that this is indeed the widget you are using.

What's the output of the following command?

```zsh
bindkey | grep -E '\^\[(\[|O)A'
```

I also noticed that you prompt is generally very slow. When the demo starts, you aren't in a git repo and yet prompt is extremely sluggish. Can you check whether the performance of your prompt improves if you use Powerlevel10k without any other plugins? The easiest way to check is to type the following command and see if it makes your prompt fast. The expected performance is as instant as you can imagine. No lag at all, not even a tiny amount. In large Git repos prompt might get rendered with a grey Git segment which updates asynchronously, but the initial prompt should still be instant. Is this what you get?

```zsh
(
  emulate -L zsh
  setopt no_unset err_return
  local tmp && tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k

    >$tmp/.zshrc echo "
      source ~/.p10k.zsh
      source ${(q)tmp}/powerlevel10k/powerlevel10k.zsh-theme"
    ZDOTDIR=$tmp zsh
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

**Comment by vibbix** [comment]
This is returned for bindkey:
```
"^[OA" up-line-or-beginning-search
"^[[A" up-line-or-history
```
It's possible that my `.zshrc` might be overwhelming it.  Specifically, i think the pyenv script is the one doing it. Of note, if I `ctrl-c` when the line is already updated, it evaluates instantly it seems. But when i press enter it redraws. And you are correct about performance, the lag is imperceptible with the new one, i can get iTerm to skip lines like this:
![image](https://user-images.githubusercontent.com/1731900/68311850-2a142a80-0080-11ea-9e95-3a26d5f379f8.png). When I ran your script, nothing like that happens.
for example running `/usr/bin/time /usr/local/bin/zsh -i -c exit` with your scripts return this consistently:
```
~/**scrubbed**/git ❯         0.05 real         0.02 user         0.02 sys                                                                                                                                                                                                                                                                                                    10:30:08
```
However, with my .zshrc I get this:
![image](https://user-images.githubusercontent.com/1731900/68312165-a60e7280-0080-11ea-8fae-4a76c27d08ce.png)
It seems to take longer when i'm inside a regular folder than it does in a git repo strangely too.

**Comment by vibbix** [comment]
My dotfiles are available here also: https://github.com/vibbix/dotfiles

**Comment by vibbix** [comment]
Performance issues were caused by pyenv it seems, commenting those out seemed to do the trick.
```
        0.20 real         0.09 user         0.10 sys
```
I still need to do some tuning overall to this.

**Comment by romkatv** [comment]
> This is returned for bindkey:
> 
> ```
> "^[OA" up-line-or-beginning-search
> "^[[A" up-line-or-history
> ```

As I thought, you are using `up-line-or-beginning-search`, which suffers from a bug in zsh (not in powerlevel10k but in zsh proper) that I've [fixed](https://github.com/zsh-users/zsh/commit/c5519372808d78519e1bac2db165d19a34534f74) back in April but there has been no zsh releases since then. You can either build zsh from head, or use a different widget in place of `up-line-or-beginning-search`. This widget in my opinion is the best for UP key but there are a few others that aren't much worse. You could try `history-beginning-search-backward-end`. The downside of this widget is that it breaks zsh-autosuggestions and cannot handle multi-line commands properly.

By the way, you've bound two different widgets to two versions of UP key. If somehow your terminal gets switched to raw mode (it seems like you normally stay in application mode), you'll start hitting the other binding.

> for example running `/usr/bin/time /usr/local/bin/zsh -i -c exit` with your scripts return this 

This doesn't measure anything useful. To measure prompt latency, use https://github.com/romkatv/zsh-prompt-benchmark.

To find what causes prompt lag, comment out everything in your config one by one. I see that you've identified the culprit, although I'm somewhat surprised because nvm doesn't cause prompt lag for me. What is the actual line in your config that makes the difference?

I also highly recommend updating powerlevel10k, running `p10k configure` and enabling *Instant Prompt* (this question is close to the end of the wizard). It'll reduce your zsh startup time down to zero (even if you load lots of plugins). Try opening tabs with your current config and then again after you enable Instant Prompt.

**Comment by romkatv** [comment]
Sorry, I mixed up nvm and pyenv. What's the pyenv line that causes prompt lag for you?

**Comment by vibbix** [comment]
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
This was the culprit. Building ZSH from source shouldn't be too bad, I wonder if its oh-my-zsh. I have yet to try out other frameworks like antigen, but i've been meaning to. I'll try out updating P10k & reconfiguring it out after I build from source.

**Comment by romkatv** [comment]
> ```
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

The first one is benign, you can keep it. The second is the culprit and you definitely should disable it. If you want to enable virtual environments automatically when you change your current directory, you can do this:

```zsh
eval "$(pyenv virtualenv-init -)"
# Run _pyenv_virtualenv_hook when current directory changes.
chpwd_functions+=(_pyenv_virtualenv_hook)
# Don't run _pyenv_virtualenv_hook on every command.
precmd_functions=(${(@)precmd_functions:#_pyenv_virtualenv_hook})
```

It'll add latency only when changing directories, which is also jarring but not as terribly as lag on every command.

> I wonder if its oh-my-zsh

What do you mean? Aren't all issues already explained? UP key was broken because of zsh bug and can be fixed by building zsh from head. Promt was slow because of pyenv/pyenv-virtualenv automatic activation on every command. What am I missing?

> I have yet to try out other frameworks like antigen, but i've been meaning to.

The final destination of this journey is the realization that all zsh frameworks and plugin managers are useless or harmful. If you have to try them all before you get there, so be it.

**Comment by romkatv** [comment]
Closing as I believe there is no issue with powerlevel10k. Please reopen if I'm mistaken.
