### ISSUE TITLE
DIR_CLASS_NAME_{BACKGROUND,FOREGROUND} config not being respected

### ISSUE THREAD

**Issue by brianjlandau** [romkatv/powerlevel10k#320]
* [This is my p10k.zsh](https://github.com/brianjlandau/dotfiles/blob/6379cb0d50c2c7cde535714540a39801bf39605a/p10k.zsh)
* [This is my zshrc](https://github.com/brianjlandau/dotfiles/blob/6379cb0d50c2c7cde535714540a39801bf39605a/zshrc)

`DIR` coloring doesn't seem to work right. I have classes set up for the standard dirs (`ETC`, `HOME`, `HOME_SUBFOLDER`, and `DEFAULT`). But it doesn't change to the correct background color when I `cd` into one of those directories. I also don't ever seem to get the `ANCHOR` coloring.

Any idea what I might be doing wrong with my config?

**Comment by romkatv** [comment]
> `DIR` coloring doesn't seem to work right. I have classes set up for the standard dirs (`ETC`, `HOME`, `HOME_SUBFOLDER`, and `DEFAULT`). But it doesn't change to the correct background color when I `cd` into one of those directories.

When I use your config, the foreground color and icons on the current directory change as expected. To make it easier to distinguish between different colors, I changed them like this:

```zsh
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=1
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND=2
typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND=3
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=5
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=6
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=7
```

Note that you have `POWERLEVEL9K_DIR_SHOW_WRITABLE=true`, which means that non-writable directories are styled with class `NOT_WRITABLE` and use icon `LOCK_ICON`. You might want to define colors for this class and set icon with `POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='icon'`, or set `POWERLEVEL9K_DIR_SHOW_WRITABLE=false`. Otherwise your `ETC` class will kick in only when you are root.

> I also don't ever seem to get the `ANCHOR` coloring.

Many `DIR` parameters work only with `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique`. `ANCHOR` parameters are among them.

If this doesn't answer your questions, please clarify what you expect to happen and what actually happens. Attach a screenshot to make it easier to understand.

**Comment by romkatv** [comment]
By the way, this parameter doesn't work the way I think you want it to work:

```zsh
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\ue0c2 '
```

If you are using a decent terminal (or the recommended font on any terminal), replacing that space with `\u2588` should fix the problem.

**Comment by brianjlandau** [comment]
Setting `POWERLEVEL9K_DIR_SHOW_WRITABLE=false` and `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` and everything worked as expected. Thanks!

I'm using [this font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf) and I get this with the space:

![Screen Shot 2019-11-10 at 4 15 14 PM](https://user-images.githubusercontent.com/3122/68552536-4d6b0c80-03d5-11ea-9bb2-bbdb1b270a21.jpg)

With `\u2588` I get this:
![Screen Shot 2019-11-10 at 4 18 26 PM](https://user-images.githubusercontent.com/3122/68552583-bce0fc00-03d5-11ea-8c81-6d595a7c58b4.jpg)

I think I like the space better but maybe I'm doing something else wrong if I shouldn't need the space.
