### ISSUE TITLE
p10k-on-post-prompt triggered on aborting completion menu

### ISSUE THREAD

**Issue by Syphdias** [romkatv/powerlevel10k#321]
Steps to reproduce:
1. Prepare:
```
# cd /tmp && curl -LsSO https://raw.githubusercontent.com/romkatv/powerlevel10k/7b3532de440f03a8d6577591828d7d3ccba122e0/config/p10k-lean.zsh
# autoload -U compinit && compinit
# zstyle ':completion:*' menu select
# source ~/.oh-my-zsh-custom/themes/powerlevel10k/powerlevel10k.zsh-theme
# function p10k-on-pre-prompt() { p10k display '1|2/right'=show '2/left/time'=hide; }
# function p10k-on-post-prompt() { p10k display '1|2/right'=hide '2/left/time'=show; }
# source /tmp/p10k-lean.zsh
```
2. type `grep --` followed by <tab><tab>
3. press `ctrl-c`

Result:
![image](https://user-images.githubusercontent.com/16988672/68586886-fa9d5d80-0485-11ea-8edf-f5f165bd3e01.png)

Expected result:
![image](https://user-images.githubusercontent.com/16988672/68586840-dc376200-0485-11ea-9fdb-a20e41201231.png)

I'm not sure if this can be fixed or is considered a bug at all...

**Comment by romkatv** [comment]
Damn. I'll try to find a workaround when I get some free time. Can be tricky though because I'm already dancing around memory corruption bugs in zsh. The current code avoids segfaulting zsh but almost any change in this area leads to crashes.

**Comment by romkatv** [comment]
Sent https://www.zsh.org/mla/workers//2019/msg00941.html. Fixing this bug would be nice but unfortunately not enough for the purpose of p10k. With any luck, someone out there already knows something about this bug and can educate me.

**Comment by Syphdias** [comment]
Good luck, then! :smile: 

> Fixing this bug would be nice but unfortunately not enough for the purpose of p10k

Especially since you strife to keep it quite compatible...

**Comment by romkatv** [comment]
This bug was driving me crazy. I've rolled a completely different implementation of transient prompt that doesn't have this issue. Unfortunately, it has another problem. Notifications about completed jobs don't come until you hit enter. Basically, zsh behaves as if you had `setopt no_notify`.

I've switched back to the original implementation and presevered until I found a solution. It's kinda crazy but works. There is still one problem where it triggers a bug in zsh that I've reported [here](https://www.zsh.org/mla/workers//2020/msg00024.html). This bug is less severe than the original problem and it triggers in fewer cases, so it's an improvement.
