### ISSUE TITLE
VCS Icon foregrounds incorrectly colored

### ISSUE THREAD

**Issue by iboyperson** [romkatv/powerlevel10k#33]
With the new addition of improved VCS theming I have noticed colors do not seem to be correctly set for the icons if my understanding of the new system is correct. Possibly assuming the color of the dominant foreground

Powerlevel Config: [Here](https://github.com/iboyperson/p9k-theme-pastel)
Applied like this: `zplugin ice lucid atinit"_pastel_init"; zplugin light romkatv/powerlevel10k`

For context:
`*`: Stash (Should be green)
`?`: Untracked (Should be red)
`!`: Unstaged (Should be yellow)

## Pre-new Theming
1: Just Stash 
![image](https://user-images.githubusercontent.com/10000914/54653769-0e203200-4a79-11e9-83fc-cc68692ff614.png)

2: Stash/Untracked
![image](https://user-images.githubusercontent.com/10000914/54653917-aa4a3900-4a79-11e9-97bc-8f1c5fae12ac.png)

3: Stash/Untracked/Unstaged
![image](https://user-images.githubusercontent.com/10000914/54649461-8e3d9c00-4a67-11e9-8e5c-ec3d38c4c62f.png)

## New Theming
1: Just Stash 
![image](https://user-images.githubusercontent.com/10000914/54653815-31e37800-4a79-11e9-875a-69415bba1b98.png)

2: Stash/Untracked
![image](https://user-images.githubusercontent.com/10000914/54653958-cbab2500-4a79-11e9-94f1-637a5ced571e.png)

3: Stash/Untracked/Unstaged
![image](https://user-images.githubusercontent.com/10000914/54649490-a8777a00-4a67-11e9-8d6c-90869e0ef19b.png)

**Comment by romkatv** [comment]
Your config is missing `-g` on `typeset` lines in `_pastel_config_vcs_p10k`. Should be like this:

```zsh
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKED_FOREGROUND="$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGED_FOREGROUND="$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGED_FOREGROUND="$__PASTEL_COLORS[green]"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGES_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGES_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASH_FOREGROUND="$POWERLEVEL9K_VCS_CLEAN_FOREGROUND"
    typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTION_FOREGROUND=001
```

**Comment by iboyperson** [comment]
Ah this fixes the issue. Apologies for the error on my end. Keep up the great work!

**Comment by romkatv** [comment]
I figured out a way to make the new styling options consistent with the existing styling options. Now they look like a natural extension of `POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND`. I documented them in https://github.com/romkatv/powerlevel10k/blob/master/README.md#extra-configuration (search for "when using gitstatus").

Unfortunately this means you'll have to change your config. This should give you the same prompt you have now, although I haven't tried it:

```zsh
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$__PASTEL_COLORS[brightgreen]"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$__PASTEL_COLORS[red]"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$__PASTEL_COLORS[yellow]"
POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND="$__PASTEL_COLORS[green]"
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_INCOMING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_OUTGOING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=001
```

I also recommend that you use these options both with p9k and p10k. This will make git prompt single-colored in p9k (the whole segment green when clean, yellow when modified, etc.) without individual coloring for `?` and `!`, but this is the only supported mode for p9k. It's not a good idea to embed `%F` tags where it's not explicitly allowed. Right now these tags cause weird artifacts such as white `3` in an otherwise green segment when your repo is 3 commits ahead, but it can also break in more spectacular ways in the future.

I'll also open an issue with p9k suggesting they implement the same extended styling options I have in p10k.

**Comment by romkatv** [comment]
> I'll also open an issue with p9k suggesting they implement the same extended styling options I have in p10k.

Opened https://github.com/bhilburn/powerlevel9k/issues/1222. Given that they haven't fixed any of the 9 bugs I reported and haven't implemented any of the 2 prior feature requests, this feature request is unlikely to see traction any time soon.
