### ISSUE TITLE
Transient prompt not working in desktop

### ISSUE THREAD

**Issue by FernandoGarcia** [romkatv/powerlevel10k#341]
Hi!

Firstly thanks for all your job!

Also thanks by add transient prompt feature. I have asked similar feature [here](https://github.com/Powerlevel9k/powerlevel9k/issues/1357#issuecomment-528063660).

I have configured a remote machine and desktop in the same way but the transient prompt is not working in local machine.

This behaviour is normal? It works only when using SSH?

I'm using Tilix for both machines.

See the result on terminal:

![transient](https://user-images.githubusercontent.com/2778501/69285164-02b87400-0bcf-11ea-91a2-97565e0d7153.png)
Best regards.

**Comment by romkatv** [comment]
> Also thanks by add transient prompt feature. I have asked similar feature [here](https://github.com/Powerlevel9k/powerlevel9k/issues/1357#issuecomment-528063660).

Yep, I remember that. I put it on the back burner for a while and eventually implemented something like the two prompts idea from that comment.

> I have configured a remote machine and desktop in the same way but the transient prompt is not working in local machine.

The most likely explanation is that you've enabled transient prompt on the remote machine but not on the local. Type `echo $POWERLEVEL9K_TRANSIENT_PROMPT` to confirm. To enable it locally, update powerlevel10k and then either type `p10k configure` or manually edit `~/.p10k.zsh`.

You might also want to update powerlevel10k on the remote machine and run `p10k configure` there. I've changed the default color of `os_icon` so that now it's black on white instead of white on black. White on black Ubuntu icon didn't look very nice.

**Comment by FernandoGarcia** [comment]
Hi!

Thanks for you reply.
It's working in local machine after close the terminal. 8)
But I didn't understand it. I sent the command `source ~/.zshrc` a few times before.

![pk10](https://user-images.githubusercontent.com/2778501/69287921-ace7ca00-0bd6-11ea-9323-6cda56d1bc14.png)

I'll upgrade the theme in remote machine.
Best regards.
