### ISSUE TITLE
[MAC] clear command [⌘+K] clear everything if the using 2 lines 

### ISSUE THREAD

**Issue by eltntawy** [romkatv/powerlevel10k#346]
Comand before ⌘+K

![Screenshot 2019-11-26 at 5 23 05 PM](https://user-images.githubusercontent.com/6157935/69652160-81029380-1071-11ea-848e-dc4a885a5d8c.png)

After ⌘+K
![Screenshot 2019-11-26 at 5 23 12 PM](https://user-images.githubusercontent.com/6157935/69652172-84961a80-1071-11ea-9ef9-1a1fea5f656d.png)

**Comment by romkatv** [comment]
What terminal are you using?

**Comment by mrwcjoughin** [comment]
@romkatv I have the same issue - I'm using the zsh that's built into macOS catalina

**Comment by romkatv** [comment]
@mrwcjoughin Thanks for letting me know which zsh version you are using. Which terminal are you using? It it Apple Terminal, iTerm, Hyper, something else?

**Comment by mrwcjoughin** [comment]
@romkatv thanks for the quick response! I am using iTerm2 Build 3.3.7

**Comment by romkatv** [comment]
I'm afraid there is nothing p10k can do to change the behavior of `⌘+K` in iTerm2. As far as I tell, the behavior you are observing is the intended behavior of iTerm2.

There are a few things you can do:

1. Use `Ctrl+L` instead of `⌘+K` (or type `clear`). This is likely what you want.
2. Try enabling shell integration in iTerm2: https://www.iterm2.com/documentation-shell-integration.html. I don't know if it'll help but it might.
3. Use a single-line prompt.
