### ISSUE TITLE
POWERLEVEL9K_SHORTEN_DIR_LENGTH option not applied properly

### ISSUE THREAD

**Issue by finalspy** [romkatv/powerlevel10k#351]
In powerlevel9k I use the following parameters :
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=''
```

For instance the path : 
`/home/user/Documents/Pro/Company/workspaces/docker-images/python/3.7`
is shortened into 
`~/Doc/Pr/C/w/d/p/3.7`
which is the shortest unique shortcut path to the directory.

But switching to powerlevel10k it ends up shortened into : 
`~/Doc/Pr/S/w/docker-images/p/3.7`
as if the - was avoiding the shortening to 1 character ...

**Comment by romkatv** [comment]
You can get the same behavior as in p9k by defining `POWERLEVEL9K_SHORTEN_FOLDER_MARKER=()`. The default value is not backward compatible with p9k because it's what the vast majority of users prefer.

Directory shortening is quite a bit more advanced in p10k. See https://asciinema.org/a/258376 and read its description for some of the features. If you run `p10k configure`, the resulting config will have reasonable options set. You can also read them here:

https://github.com/romkatv/powerlevel10k/blob/fdb90994c9ba7863b97621ab75f6e2bd7b9dc530/config/p10k-lean.zsh#L214-L310

**Comment by finalspy** [comment]
Thank you so much for the incredibly fast detailed and accurate answer !
Problem solved.
Great Job !
