### ISSUE TITLE
Shows old rust version

### ISSUE THREAD

**Issue by cubetastic33** [romkatv/powerlevel10k#365]
Even after I updated rust to version 1.39.0, rust prompt still shows 1.38.0. Here's a screenshot:
![image](https://user-images.githubusercontent.com/33519300/70259359-009c0b00-17b4-11ea-99e1-e614a586a877.png)
How do I fix this?

**Comment by romkatv** [comment]
Thanks for the report. I see that `rustc` is dynamically linked on Linux and its version is embedded in `/usr/lib/x86_64-linux-gnu/librustc_driver-*.so` rather than in `rustc` itself as I though when I wrote this code. Or maybe this has changed? I'll fix it when I get a free minute.

In the meantime you can get the proper version to show up in your prompt by nuking p10k cache and restarting zsh.

```zsh
rm -rf ~/.cache/p10k-* && exec zsh
```

**Comment by cubetastic33** [comment]
Ah, brilliant, that worked. Thanks a lot! I'm keeping this issue open as you haven't fixed it yet, though.

**Comment by romkatv** [comment]
Fixed. Thanks again for the bug report!
