### ISSUE TITLE
Not writable dir icon not applied

### ISSUE THREAD

**Issue by Bokoblin** [romkatv/powerlevel10k#367]
Hello,

As opposed to the other variables I have successfully tried, it seems that the following is not applied :
`POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION`
instead I get the exact glyph code shown : 
![image](https://user-images.githubusercontent.com/8015512/70392392-0b3ae800-19e0-11ea-977d-efdb54e71ec7.png)

Is it a bug on your side, or have I forgotten to enable something ?

---
I'm using the current master code of P10K with a file first configured using your built-in configure "wizard"

**Comment by romkatv** [comment]
If you set `POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='\uE0A0'`, prompt will show `\uE0A0` whenever the current directory isn't writable. I suppose this is what you are observing?

What you probably want is `$'\uE0A0'` rather than `'\uE0A0'`.

**Comment by Bokoblin** [comment]
@romkatv Thanks, it works. But, I'm wondering, why is the `$` needed this time, whereas with other variables like the prompt ones, there is no dollar and the icons are properly rendered?

**Comment by romkatv** [comment]
Different parameters undergo different expansions.

- `*_EXPANSION` parameters undergo single word expansions (namely, *parameter expansion*, *command substitution* and *arithmetic expansion*) followed by *prompt expansion*.
- Most other parameters undergo only C-escape-sequence expansion.
- There are a few special parameters that undergo a different set of expansions.

This may sound confusing but thankfully `~/.p10k.zsh` unambiguously specifies what you should put in every parameter. Here's what it has:

```zsh
# typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

This shows that the value of this parameter is the actual icon rather than a sequence of ASCII characters that will produce an icon after some sequence of expansions. Once you realize that `\uE0A0` is a sequence of 6 ASCII characters while $`\uE0A0` is a single character, everything falls into place.

In the ideal world `*_EXPANSION` parameters would behave just like the behave right now and all other parameters would get printed unexpanded. The reason powerlevel10k deviates from this ideal is backward compatibility with powerlevel9k. powerlevel9k performed C-escape-sequence expansion on many parameters essentially by accident and then users grew to rely on it.

**Comment by Bokoblin** [comment]
Thanks for the clarification

**Comment by horseinthesky** [comment]
Hello.
When I setup:
```
typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
```
I get `` icon before not writable directories (this is what I was expectiong)
```
 /usr
```
but it stops using colors I picked.

I've cheched:
```
echo $POWERLEVEL9K_DIR_DEFAULT_FOREGROUND
033
```
but it uses `grey23` color which is 237.

**Comment by romkatv** [comment]
Prompt segments in p10k can have *states*. When prompt segment `foo` is in state `BAR`, p10k resolves its foreground color by checking the existence of parameters in the following order:

1. `POWERLEVEL9K_FOO_BAR_FOREGROUND`
2. `POWERLEVEL9K_FOO_FOREGROUND`
3. `POWERLEVEL9K_FOREGROUND`

With default settings, `dir` can be in the following states:

- `ETC` -- when the current directory is `/etc` or a subdirectory of `/etc`.
- `HOME` -- when the current directory is the home directory.
- `HOME_SUBFOLDER` -- when the current directory is a subdirectory of the home directory.
- `DEFAULT` -- when the current directory is not one of the above.

With `POWERLEVEL9K_DIR_SHOW_WRITABLE=true`, `dir` can be in one extra state:

- `NOT_WRITABLE` -- when the current directory is not writable by the current user; this takes precedence over other states; for example, when the current directory is `/etc` and it's not writable, state is `NOT_WRITABLE`.

When `dir` is in state `NOT_WRITABLE`, p10k resolves its foreground color by checking the existence of parameters in the following order:

1. `POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND`
2. `POWERLEVEL9K_DIR_FOREGROUND`
3. `POWERLEVEL9K_FOREGROUND`

P.S.

In the future please open a new issue instead of commenting on closed loosely related issues. This doesn't imply you need to write longer descriptions or anything. The phrasing of your question was totally fine.

**Comment by horseinthesky** [comment]
Understood.
Didn't realize `NOt_WRITABLE` is another status. Setting up its color works perfectly fine. Thank you.
