### ISSUE TITLE
pyenv section behavior

### ISSUE THREAD

**Issue by leeallen337** [romkatv/powerlevel10k#372]
Is it possible to support the behavior found in [this issue that you provided a solution for related to `rbenv`](https://github.com/romkatv/powerlevel10k/issues/333#issuecomment-554957281) but for `pyenv`? I'm specifically referring to the source.

For example, I tried to add the following to my `.p10k.zsh`
```
typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local)
```
but it did not appear to work when I set `pyenv local 3.8.0` in a directory.

I'm really liking the theme so far! I'm coming from spaceship and this feels a lot faster!

**Comment by romkatv** [comment]
This is done. `POWERLEVEL9K_PYENV_SOURCES` will work as you expect once you update powerlevel10k and restart zsh.

**Comment by horseinthesky** [comment]
Hello.
Could you pls help me with this one?

I have
```
typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
```
But it only works with `local`. 

`typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false` says that it will hide python versions if `$(pyenv version-name) == $(pyenv global)` but they are always equal in global mode
```
❯ pyenv versions
  system
  2.7.16
* 3.6.9 (set by /home/horseinthesky/.pyenv/version)
  3.7.4
  3.8.0
❯ echo $(pyenv version-name)
3.6.9
❯ echo $(pyenv global)
3.6.9
```
so whenever I set `pyenv global <version>` it is always hidden.
Is there a bug or how can I make it show pyenv global version?

**Comment by romkatv** [comment]
> I have
> 
> ```
> typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
> typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
> ```

With these settings `pyenv` prompt segment will be hidden if and only if:

1. Python doesn't come from one of these sources: `shell`, `local`, `global`. More specifically, this means that `set by` in the output of `pyenv version` does not refer to `PYENV_VERSION`, to `.python-version` or `.pyenv/version`.
***OR***
2. The output of `pyenv version-name` is identical to `pyenv global`.

Note that (1) is always false because `(shell local global)` is the full set of possible sources.

> But it only works with `local`.

Can you describe the conditions under which the above logic is violated?

> `typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false` says that it will hide python versions if `$(pyenv version-name) == $(pyenv global)` but they are always equal in global mode

If `pyenv version` says `set by /home/horseinthesky/.pyenv/version`, then the output of `pyenv version-name` will be identical to `pyenv global`.

> so whenever I set `pyenv global <version>` it is always hidden.

This isn't correct. After you call `pyenv global <version>` the output of `pyenv version-name` isn't necessarily identical to `pyenv global`. With the configuration parameters you've quoted above `pyenv` segment is hidden only when they are identical.

```zsh
$ pyenv local 3.7.3
$ pyenv global 3.7.2
$ pyenv version-name
> 3.7.3
$ pyenv global
> 3.7.2
```

Here `pyenv` prompt segment will be shown.

> Is there a bug?

There can always be a bug but there is no evidence of one in your post.

> how can I make it show pyenv global version?

Are you looking for `POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true`? If not, please describe under which conditions you want `pyenv` to be shown/hidden.

**Comment by horseinthesky** [comment]
I want to see pyenv version in any case when it is different from the system one i.e. when setting it up via `pyenv local` or `pyenv global`.
I prefer to keep
```
POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
```
to hide `system`.

**Comment by romkatv** [comment]
`system` is just one python version, similar to 3.7.3. It can come from any source. For example:

```shell
$ pyenv local system
$ pyenv version
> system (set by /my/project/.python-version)
```

Here the source of python is `local` and the version is `system`.

Do I understand it correctly that you want to see the current python version if and only if it's not equal to `system`?

**Comment by horseinthesky** [comment]
> system is just one python version, similar to 3.7.3. It can come from any source.
Yes, I know that.

> Do I understand it correctly that you want to see the current python version if and only if it's not equal to system?
That is correct.

**Comment by romkatv** [comment]
> > Do I understand it correctly that you want to see the current python version if and only if it's not equal to system?
> That is correct.

You can achieve it with these parameters:

```zsh
typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
# Hide pyenv segment if its content is "system".
typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT:#system}'
typeset -g POWERLEVEL9K_PYENV_VISUAL_IDENTIFIER_EXPANSION='${${P9K_CONTENT:#system}:+$P9K_VISUAL_IDENTIFIER}'
```

**Comment by horseinthesky** [comment]
This works as I expected. Thank you very much.
It looks a little bit tricky. Could you explain how these EXPANSIONs work? I see plenty of them in config examples.

**Comment by romkatv** [comment]
See `man zshexpn` or the same thing online: http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion.

> `${name:#pattern}`
> 
> If the *pattern* matches the value of *name*, then substitute the empty string; otherwise, just substitute the value of *name*.
> 
> `${name:+word}`
> 
> If *name* is non-null, then substitute *word*; otherwise substitute nothing.
>
