### ISSUE TITLE
Feature request. Let p10k inherit colors from terminal theme

### ISSUE THREAD

**Issue by securisec** [romkatv/powerlevel10k#374]
I have to say, i have tested a whole bunch of zsh prompts, and p10k is by far the most extensible and fast. But one thing that is really annoying is theming it. There are just too many variables that control too many sections of the prompt, and trying to find them is really difficult specially when playing with color codes one by one. 

Is it possible to make a feature request so that p10k inherits the colors from the terminal itself?

**Comment by romkatv** [comment]
> I have to say, i have tested a whole bunch of zsh prompts, and p10k is by far the most extensible and fast.

Thanks!

> There are just too many variables that control too many sections of the prompt, and trying to find them is really difficult specially when playing with color codes one by one.

Finding all variables that specify colors is fairly easy. Search with regex `COLOR=|FOREGROUND=|BACKGROUND=|%[0-9]+F`. If you want colors to follow your terminal theme, you'll need to restrict the config to colors from 0 to 7. Depending on your terminal and theme, you might also be able to use colors 8 through 15.

I can add an extra screen to the wizard that asks whether to use fixed colors (colors above 15 usually don't get affected by terminal themes) or to follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style, harder for classic, and a lot of work for rainbow.

Would this help? Which style are you using?

Note that you might still want to edit colors manually because you may prefer different colors for some segments than the ones I would assign.

**Comment by romkatv** [comment]
> Would this help? Which style are you using?

Friendly ping.

**Comment by securisec** [comment]
Ah, sorry for the late response. Hmm.. i think i prefer the later solution as it can automatically pick up the colors that are being set to the terminal. But i think I would like to make a counter suggestion. Maybe there is room for a `.p10k-theme` file that can be used to populate the color fields? and for true color terms, hex color codes would be really great to have too i think. Just a suggestion. One of the neatest things I like about p10k is its potability and extendability, so this suggestion makes theming extensible.

**Comment by romkatv** [comment]
> i think i prefer the later solution

What do you mean by the latter solution?

I would really appreciate if you could answer two questions I've posted above:

1. Would this help? (This refers to the previous paragraph where I explain that I can add an extra question to the configuration wizard.)
2. Which style are you using?

> But i think I would like to make a counter suggestion. Maybe there is room for a `.p10k-theme` file that can be used to populate the color fields? and for true color terms, hex color codes would be really great to have too i think.

Sorry, I don't understand this. Could you clarify?

**Comment by securisec** [comment]
>follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style, harder for classic, and a lot of work for rainbow.

I prefer this option. This way, if i change the theme of the terminal, p10k changes automatically. 

> Which style are you using?

I change styles quite frequently, but usually gruvbox or panda. 

The last part is having a custom theme file which can be used to control colors, order of prompt elements etc. Similar to starship.toml in the starship project. What this allows one to do is make really custom designs and share within the community. This way, if I want to share my p10k config with someone, I am not sharing the entire p10k file, but just my p10k theme file. Does that make more sense?

**Comment by romkatv** [comment]
> > follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style, harder for classic, and a lot of work for rainbow.
> 
> I prefer this option. This way, if i change the theme of the terminal, p10k changes automatically.

Got it.

> I change styles quite frequently, but usually gruvbox or panda.

When you run `p10k configure`, one of the first screens asks you to pick style. There are several options: lean, classic, rainbow and pure. Which one do you use?

> The last part is having a custom theme file which can be used to control colors, order of prompt elements etc. Similar to starship.toml in the starship project. What this allows one to do is make really custom designs and share within the community.

That's `~/.p10k.zsh`. This file defines how your prompt looks like.

> This way, if I want to share my p10k config with someone, I am not sharing the entire p10k file, but just my p10k theme file. Does that make more sense?

I don't understand this part. Do you want to share a part of your config? Is there an equivalent to sharing a part of your config in any other theme? For example, you mentioned starship. Does it have partial configs?

**Comment by securisec** [comment]
> When you run p10k configure, one of the first screens asks you to pick style. There are several options: lean, classic, rainbow and pure. Which one do you use?

I use lean. I agree that p10k does prompt for it, but it doesnt prompt for things like order of [prompt elements](https://starship.rs/config/#prompt). 

> That's ~/.p10k.zsh. This file defines how your prompt looks like.

Yes I agree. But sometimes, like as in my previous feature request to you, i might have a custom function in my p10k.zsh file like check for direnv. Well, if i want to share my p10k.zsh setup, the next person willl get that function also which they may not need. This is just an example. 

So if there was something like `.p10k.theme`, then I dont have to share my internal functions. 

>  Do you want to share a part of your config? 

Yes, so in the case of [starship](https://starship.rs/config/#prompt) everything is controlled by a `starship.toml` file for customization, while starship itself will use most other things from .zshrc itself. So in my case, when I am swithcing machines, i just share the starship.toml file between machines, and i get my themes, promopt element order etc, while zsh and custom stuff remains machine specific.

> Does it have partial configs?
^^

**Comment by romkatv** [comment]
> I use lean.

Got it.

> I agree that p10k does prompt for it, but it doesnt prompt for things like order of [prompt elements](https://starship.rs/config/#prompt).

Do you mean that configuration wizard doesn't ask you to choose the order of prompt segments? This is true. Is this a problem? Is this related to the current issue? Note that starship doesn't have a configuration wizard to begin with. You define prompt segment order by editing a config file, just like with powerlevel10k.

> Yes, so in the case of [starship](https://starship.rs/config/#prompt) everything is controlled by a `starship.toml` file for customization

`starship.toml` defines the whole prompt. If you share it, you are sharing the whole prompt. `~/.p10k.zsh` defines the whole prompt. If you share it, you are sharing the whole prompt. Seems the same.

I think you are suggesting that the configuration wizard should be generating multiple files instead of one file, and these multiple files should all contribute different aspects to prompt. One file defines the order of prompt segment, another file defines which segments are visible, yet another file defines colors, still another file defines connections between prompt segments, etc. There is some merit in this but it's much more complex than having a single file. If there was any other theme that was already doing this, I could use it for inspiration. As far as I can tell, starship is using a single file to define everything related to prompt. There is a very good reason for this.

P.S.

There is builtin `direnv` prompt segment in p10k.

**Comment by securisec** [comment]
> There is builtin direnv prompt segment in p10k.

Yes, i think you added it after i posted a question about it here. 

Thanks for the discussion. What you say makes sense. 

> follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style, harder for classic, and a lot of work for rainbow.

I think this would be a great feature to have.

**Comment by romkatv** [comment]
Thanks, I'll add another question to the configuration wizard. Initially only for lean style because it's the easiest to implement. Might take a few days as I'm swamped with other commitments.

**Comment by michaelpj** [comment]
Perhaps something that would make the colors easier to configure without having more sweeping changes would be to define a bunch of "palette" variables at the top which were then used for each of the individual color settings.

e.g. at the moment `virtualenv`, `anaconda`, and `pyenv` all use the same color (38), but if I wanted to change that I'd have to go through and change all three. If instead there was `POWERLEVEL_10k_FG_OPTION_1` or something then I could change it in one place.

Then I think @securisec could have his `.p10k.theme` by just writing a zsh file that set all of the palette variables and nothing else.

**Comment by romkatv** [comment]
> Perhaps something that would make the colors easier to configure without having more sweeping changes would be to define a bunch of "palette" variables at the top which were then used for each of the individual color settings.

Indirection makes configs much more difficult to edit for most users. 

> Then I think @securisec could have his .p10k.theme by just writing a zsh file that set all of the palette variables and nothing else.

This would define a new API for which I would have to maintain backward compatibility. It's not a bad thing if the API makes so much sense that it's hard to envision that it would ever have to change. `POWERLEVEL_10k_FG_OPTION_1` isn't it though.

**Comment by michaelpj** [comment]
> Indirection makes configs much more difficult to edit for most users.

Well, this particular user considered editing the colors for the theme, realised that they were spread out all over the config file, and despaired of ever creating an alternative consistent set. I'd have been much more likely to do it if it was all in one place. But that's just me :)

Perhaps put it a different way: as a user I want to configure the *set* of colors that the prompt uses, and I typically care much less about which color any individual element uses, hence why a palette is nice. (Same way most terminal themes work.)

> This would define a new API for which I would have to maintain backward compatibility.

Does it? I wouldn't have expected you to be on the hook for this any more than you are for someone doing the same thing with other internal variables in `.p10k.zsh` and distributing that. If people want to hack around they can, but merely defining some variables doesn't commit you to an API!

**Comment by romkatv** [comment]
>  I want to configure the set of colors that the prompt uses, and I typically care much less about which color any individual element uses.

https://github.com/romkatv/powerlevel10k/issues/374#issuecomment-566729840 would work for you, right? I took your first comment to implied that it wouldn't.

> Does it?

Either it's an API or the same "theme file" cannot be used with different versions of p10k. If you write a theme file and cannot give it to anyone or even expect it to work once you upgrade p10k, then it's not very useful.

> on the hook

I guarantee backward compatibility for all configs. That is, once you create a config that sets a bunch of `POWERLEVEL9K` parameters, you can use it with any future version of p10k and you'll get the same prompt.

**Comment by michaelpj** [comment]
> #374 (comment) would work for you, right? I took your first comment to implied that it wouldn't.

I *would* like that, since it would let me configure my palette somewhere else (namely the terminal theme), but presumably it would also limit the set of colors used quite a bit.

So I was digressing and suggesting a feature that would help users who want to configure the color scheme (not necessarily using the terminal one). It would help this particular issue in that it would be much easier for people to "help themselves" by setting the palette to only use the colors set by the terminal.

> I guarantee backward compatibility for all configs.

Impressive. Then I can see why you're reluctant to add more variables.

**Comment by romkatv** [comment]
> I was digressing and suggesting a feature that would help users who want to configure the color scheme (not necessarily using the terminal one).

I'm all for helping users to achieve their goals but I have to thing of *all* users.

You'd like the config to have a new option for setting the color of all segments related to python. The other day I received a feature request to add a new option to the config to specify that whenever Git branch is "master", an icon should be displayed instead. Today someone asked for an option to always display username@hostname. Yesterday it was an option to disable Git branch shortening.

Adding all these options would make the config immense. There would also be countless interactions between the options. Paradoxically, every option *must be at the top of the config* or the user asking for it wouldn't be able to find the option even if it existed.

**Comment by michaelpj** [comment]
> You'd like the config to have a new option for setting the color of all segments related to python.

No, I definitely don't want that! The python thing was just an example because they happen to all use the same color.

I want options for a *palette*. Here's a screenshot of the theme editor for Konsole:

![Edit Colour Scheme — Konsole_001](https://user-images.githubusercontent.com/1699466/72441043-e33e6180-37a1-11ea-8014-80df7f63080f.png)

It just sets out a bunch of colors that work together, not what specific thing they're used for. So it *should* be pretty generic. The idea of a color palette for something that uses a lot of colors is a pretty old idea.

Perhaps it would be easiest if I just made a PR to show you what I have in mind.

**Comment by romkatv** [comment]
> I want options for a palette. Here's a screenshot of the theme editor for Konsole:

If Konsole already has a UI you want, why would you need another UI for the same thing in p10k?

**Comment by securisec** [comment]
> > I want options for a palette. Here's a screenshot of the theme editor for Konsole:
> 
> If Konsole already has a UI you want, why would you need another UI for the same thing in p10k?

I think what @michaelpj is saying is he wants to use the same base colors in p10k as what is showing in his screenshot. So he would like to have a base color to base color mapping option in p10k. I think this is the same solution idea we discussed also.

**Comment by romkatv** [comment]
> So he would like to have a base color to base color mapping option in p10k.

What's that? Can you give an example how it would look like?

**Comment by eddyg** [comment]
Are you familiar with the [Base16](https://github.com/chriskempson/base16) project?

I think having a p10k "theme" that is _compatible_ with the Base16 concept (that is, only uses the base 16 colors) instead of using random colors from the standard 256-color terminal palette (which often look bad depending on your terminal theme) would nicely solve the problem of having a "consistent" theme.

**Comment by securisec** [comment]
> > So he would like to have a base color to base color mapping option in p10k.
> 
> What's that? Can you give an example how it would look like?

For example, [here](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L1047) we can see the hard coded value of `003` for yellow. What he is saying is to adopt that value of colors like yellow, red, green, blue, cyan, magenta etc from the base values that he has set for his terminal. 

For further example: 
![image](https://user-images.githubusercontent.com/22226823/72442532-b32f9800-377a-11ea-909c-f71aa1d80c53.png)

Here, the base value for my terminal for yellow is `ffb76b`. So instead of yellow being hardcoded to `003`, it would be nice if it could inherit from `ffb76b`

**Comment by securisec** [comment]
I think thats what he means by consistent theme.

**Comment by romkatv** [comment]
> Are you familiar with the [Base16](https://github.com/chriskempson/base16) project?

Yes.

> I think having a p10k "theme" that is _compatible_ with the Base16 concept (that is, only uses the base 16 colors) instead of using random colors from the standard 256-color terminal palette (which often look bad depending on your terminal theme) would nicely solve the problem of having a "consistent" theme.

Is this https://github.com/romkatv/powerlevel10k/issues/374#issuecomment-566729840? If yes, I agree it would be useful.

@michaelpj is saying that something else would be useful. I'm trying to understand what it is.

> For example, [here](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L1047) we can see the hard coded value of `003` for yellow. What he is saying is to adopt that value of colors like yellow, red, green, blue, cyan, magenta etc from the base values that he has set for his terminal.

That's exactly what `yellow` and `3` do. They use the color configured by your terminal. You can try it like this:

```zsh
print -P '%F{yellow}TEST %F{3}TEST%f'
```

Now try changing your terminal color scheme. You'll notice that the color of `TEST` changes. Also note that both `TEST` words are always printed with the same color.

**Comment by securisec** [comment]
Right, i am not disputing the value of yellow here, or how to change the color of yellow text being printed on the console. What I am saying is it would be good if p10k defaulted to the user defined value of yellow for its prompt elements instead of the true value of yellow.

**Comment by romkatv** [comment]
> Right, i am not disputing the value of yellow here, or how to change the color of yellow text being printed on the console. What I am saying is it would be good if p10k defaulted to the user defined value of yellow for its prompt elements instead of the true value of yellow.



> > Are you familiar with the [Base16](https://github.com/chriskempson/base16) project?
> 
> Yes.
> 
> > I think having a p10k "theme" that is _compatible_ with the Base16 concept (that is, only uses the base 16 colors) instead of using random colors from the standard 256-color terminal palette (which often look bad depending on your terminal theme) would nicely solve the problem of having a "consistent" theme.
> 
> Is this [#374 (comment)](https://github.com/romkatv/powerlevel10k/issues/374#issuecomment-566729840)? If yes, I agree it would be useful.
> 
> @michaelpj is saying that something else would be useful. I'm trying to understand what it is.
> 
> > For example, [here](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L1047) we can see the hard coded value of `003` for yellow. What he is saying is to adopt that value of colors like yellow, red, green, blue, cyan, magenta etc from the base values that he has set for his terminal.
> 
> That's exactly what `yellow` and `3` do. They use the color configured by your terminal. You can try it like this:
> 
> ```shell
> print -P '%F{yellow}TEST %F{3}TEST%f'
> ```
> 
> Now try changing your terminal color scheme. You'll notice that the color of `TEST` changes. Also note that both `TEST` words are always printed with the same color.

**Comment by romkatv** [comment]
> Right, i am not disputing the value of yellow here, or how to change the color of yellow text being printed on the console. What I am saying is it would be good if p10k defaulted to the user defined value of yellow for its prompt elements instead of the true value of yellow.

Are you saying that [#374 (comment)](https://github.com/romkatv/powerlevel10k/issues/374#issuecomment-566729840) would be useful? If yes, I agree.

@michaelpj is saying that something else would be useful. I'm trying to understand what it is.

**Comment by securisec** [comment]
> follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style,

Yes, this would be ideal.

**Comment by romkatv** [comment]
> > follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style,
> 
> Yes, this would be ideal.

Thanks for clarifying. I think everyone here agrees this would be useful. I still don't know what @michaelpj means though.

**Comment by securisec** [comment]
> > > follow the terminal theme (colors 0 to 7). This would be fairly easy to do for lean style,
> > 
> > 
> > Yes, this would be ideal.
> 
> Thanks for clarifying. I think everyone here agrees this would be useful. I still don't know what @michaelpj means though.

I have a feeling he is saying the same thing, but in a different way.

**Comment by eddyg** [comment]
For what it's worth, this is the quick-and-dirty way I check the readability of all the colors currently defined in the p10k theme:

```
grep -E '(FORE|BACK)GROUND=\d' .p10k.zsh | while read -r l; do [[ $l =~ '=([0-9]+)' ]] && print -P $l "%$match[1]F\u2588\u2588 text%f"; done
```

(It's not ideal because it doesn't show actual foreground/background color combinations, but I've still found it helpful. I'm sure Roman could come up with some sweet zsh code to do it better!)

**Comment by romkatv** [comment]
> I have a feeling he is saying the same thing, but in a different way.

I asked. Here's the reply: https://github.com/romkatv/powerlevel10k/issues/374#issuecomment-574647995. I understood it to mean that having an option to restrict Lean to 8 colors would be nice but he would love to have something else. After that several people jumped in trying to explain what that something else is.

**Comment by eddyg** [comment]
I jumped in to mention the extended palette of Base16 only because I find the "base 8" colors a little _too_ restrictive. Base16 actually generates 22 colors, which include _shades_ of a color, and those are very suitable for status lines:

![Screenshot Airline](http://i.imgur.com/wRQceUR.png)

**Comment by romkatv** [comment]
> I jumped in to mention the extended palette of Base16 only because I find the "base 8" colors a little _too_ restrictive.

I agree that having a 22-color option would also be useful but it's much more niche. The number of p10k users who employ base16 color schemes but at the same time don't want to manually set colors for all prompt segments is likely tiny.

**Comment by securisec** [comment]
> The number of p10k users who employ base16 color schemes but at the same time don't want to manually set colors for all prompt segments is likely tiny.

Agreed. Vote on Lean 7.

**Comment by michaelpj** [comment]
Okay, the screenshot clearly didn't help :sweat_smile:  What I was trying to point out is that the theme is defined in terms of a palette of generically defined colors that work together.

A palette for p10k would probably involve more colors than that.

What does this look like in practice? Just some variables:
```
POWERLEVEL_10K_COLOR_FG_1=...
POWERLEVEL_10K_COLOR_FG_2=...
...
```
What do they mean? It's just like in Konsole: it's a set of colors that work well together that will be used by p10k.

Why have this? It means that I can pick a set of colors that go together, but I *don't* have to go through every prompt section individually and pick colors for them. The current p10k approach is like if Konsole listed a color for every element.

Just using colors 0-7 would achieve this indirectly, because by picking the palette in your terminal theme configuration, you would implicitly pick the palette for p10k (since it would be the same). But p10k could also define its own palette that had more colors. 

This would make it easy for people to configure the palette in p10k, but not via the terminal theme. But it would make it easy to use the terminal scheme if you want to, by doing e.g.
```
POWERLEVEL_10K_COLOR_FG_1=1
```
to pick a mapping from the p10k palette to the terminal colors.

**Comment by romkatv** [comment]
Got it. Thanks for the explanation.

The advantage of having these extra variables is not zero but also not very large. It'll allow you to iterate over color parameters by pressing DOWN key while currently you need to iterate by pressing on the "search next" key after starting the search for regex `COLOR|FOREGROUND|BACKGROUND|foreground`. The current setup has a big advantage that you'll actually know what each parameter means when you are changing it.

**Comment by romkatv** [comment]
I've added an extra screen that allows you to choose between 256-color and 8-color flavors of Lean style.

![image](https://user-images.githubusercontent.com/1282067/72449472-058fa980-37b9-11ea-9ded-c13c32593f76.png)

Please give it a try and report back whether it works for you.

**Comment by romkatv** [comment]
There is one major loss when using the 8-color flavor of Lean. You no longer can distinguish between 3 kinds of directory segments. Regular, anchor and shortened segments are all plain blue. This is because all colors in the 8-color palette are very different, so using something like blue/cyan/magenta would make directory look like a Christmas tree.

**Comment by michaelpj** [comment]
> The advantage of having these extra variables is not zero but also not very large. It'll allow you to iterate over color parameters by pressing DOWN key while currently you need to iterate by pressing on the "search next" key after starting the search for regex COLOR|FOREGROUND|BACKGROUND|foreground. The current setup has a big advantage that you'll actually know what each parameter means when you are changing it.

Tastes differ :) I'd find it more maintainable - one outcome of this is that I'm likely just going to edit my own `p10k.zsh` file to have a palette. Which works for me, though it's tedious work I'd like to save others.

**Comment by romkatv** [comment]
> though it's tedious work I'd like to save others.

I also want to save others work. I just don't want to save work for one person while piling up extra work to a thousand others.

**Comment by romkatv** [comment]
@michaelpj After sleeping on it I realized there is a good chance I still didn't understand what you were asking for. So I'll try again to describe what I think you want to see.

You want to have the following parameters at the top of `~/.p10k.zsh`:

```zsh
POWERLEVEL_10K_COLOR_FG_1="6"
POWERLEVEL_10K_COLOR_BG_1=""
POWERLEVEL_10K_COLOR_FG_2="#fbe890"
POWERLEVEL_10K_COLOR_BG_2="""#a0421c"
...
POWERLEVEL_10K_COLOR_FG_86="#a0421c"
POWERLEVEL_10K_COLOR_BG_86=""
POWERLEVEL_10K_COLOR_FG_87="#947743"
POWERLEVEL_10K_COLOR_BG_87="208"
...

There is one `FG` and one `BG` parameter for every piece of colored text. The number 87 is approximate. It's in the right ballpark though.

Please correct me if I'm wrong (I very likely am).

**Comment by michaelpj** [comment]
No, there would be one parameter for every *distinct* colour used. Pieces of colored text that use the same color can use the same variable. P10K currently uses some number of distinct colors (certainly not 87!), this amounts to a list of those.

So a simple way to create the current palette would be to extract every distinct color literal to a variable. (This maybe isn't quite right - if you happened to use the same color for a foreground and a background element you might want to distinguish them.)

Again I want to emphasise that I'm not making this idea up: this is a pretty standard way that applications expose the set of colors that they use for customization, *without* requiring the user to customize every element individually. (Random set of examples I found when poking around: Wordpress, Google slides, MS Office, Konsole, Tableau, the [solarized theme](https://ethanschoonover.com/solarized/) is defined as a palette, etc. etc.)

**Comment by romkatv** [comment]
> No, there would be one parameter for every _distinct_ colour used. Pieces of colored text that use the same color can use the same variable. P10K currently uses some number of distinct colors (certainly not 87!), this amounts to a list of those.

Where the current configs use the same color for two different things, it's almost always a coincidence. For example, `❯` and Git branch both use color 76. It just happened. Would you want a separate parameter for each, or a single parameter that controls both of these elements?

> Again I want to emphasise that I'm not making this idea up: this is a pretty standard way that applications expose the set of colors that they use for customization, _without_ requiring the user to customize every element individually.

Do I understand it correctly that your suggestions hinges on the assumption that the number of distinct colors that p10k prompt *can* use is much lower than the *total number of text elements* in it?

**Comment by michaelpj** [comment]
> Where the current configs use the same color for two different things, it's almost always a coincidence. For example, ❯ and Git branch both use color 76. It just happened. Would you want a separate parameter for each, or a single parameter that controls both of these elements?

Same parameter. You say it's a coincidence... but you didn't just pick those at random, you picked something that looked nice. Perhaps you weren't consciously thinking about the contrast with the color of nearby elements, but I suspect that things do actually work out that way.

Take, for example, the colors used for the parts of the directory. They're all shades of blue, with different weight corresponding to emphasis. Changing those to similarly emphasized shades of green would retain the logic of the palette.

There *is* a theory here, which is that if an application uses a palette of colors that go well together, you can usually replace them with a similar palette and it will look okay. This is not obviously true, but I think it's borne out in practice. 

> Do I understand it correctly that your suggestion hinges on the assumption that the number of distinct colors that p10k prompt can use is much lower than the total number of text elements in it?

Yes, I would guess that that's the case. 

There's another theory here, which is that applications generally look good with a relatively small set of colors that work well together (and perhaps shades of those). Given that P10K looks nice, I guess it has a reasonable palette. However, I'm using the `lean` version which uses fairly few colors, perhaps I would find the rainbow version overwhelming ;)  

It might also be interesting just to see how big a palette you actually use. I'm not suggesting you spend ages on color design, but if it turns out that the palette is really big it might be interesting to experiment with shrinking it.

**Comment by romkatv** [comment]
> Same parameter. You say it's a coincidence... but you didn't just pick those at random, you picked something that looked nice. Perhaps you weren't consciously thinking about the contrast with the color of nearby elements, but I suspect that things do actually work out that way.

Trust me, there is no underlying reason why these two colors are the same.

Also, in different config files (e.g., classic vs rainbow) the clusters are different. In one config two prompt segments can be the same color while in another they are different.

> Take, for example, the colors used for the parts of the directory. They're all shades of blue, with different weight corresponding to emphasis. Changing those to similarly emphasized shades of green would retain the logic of the palette.

How should these parameters look like so that you are able to switch from shades of blue to shades of green?

> There _is_ a theory here, which is that if an application uses a palette of colors that go well together, you can usually replace them with a similar palette and it will look okay. This is not obviously true, but I think it's borne out in practice.

Was I wrong in assuming that you are asking to simply add extra parameters to the file? It seems like you are asking for a visual redesign of the config?

> > Do I understand it correctly that your suggestion hinges on the assumption that the number of distinct colors that p10k prompt can use is much lower than the total number of text elements in it?
> 
> Yes, I would guess that that's the case.

If you are OK with different prompt elements being rendered with the same small set of colors, then the 8 color version of Lean should satisfy you, right? Have you tried it?

There are several ways I can parse your suggestion and I don't know which one is right. In one interpretation the 8 color version should satisfy you 100% and you don't actually want extra parameters. That is, if you believe that my clustering of prompt elements is meaningful, then you can use the config that uses just 8 clusters whose colors you can change through a nice UI provided by your terminal. No extra parameters needed. Prompt will use the same color scheme as everything else in your terminal.

In another interpretation the extra parameters don't help you at all (2 * 87 parameters).

In the third interpretation you are asking for something that I don't know how to provide (allow the user to change the directory colors from shades of blue to shades of grey).

> Given that P10K looks nice

Thanks!

> I'm using the `lean` version which uses fairly few colors, perhaps I would find the rainbow version overwhelming ;)

Rainbow uses fewer distinct colors. Almost everything is from the 8 color pallet. It looks overwhelming because of its use of background colors.

> It might also be interesting just to see how big a palette you actually use. I'm not suggesting you spend ages on color design, but if it turns out that the palette is really big it might be interesting to experiment with shrinking it.

It's big. Colors are pretty much random. I've no interest in experimenting in either shrinking or expanding it. Users who care about colors can edit them. If someone finds it in their good soul to contribute back a patch that improves the default colors, I'd be grateful.

**Comment by michaelpj** [comment]
> In one config two prompt segments can be the same color while in another they are different.

That's fine - the assignments to elements can be different even if the palette they draw colors from is the same.

> How should these parameters look like so that you are able to switch from shades of blue to shades of green?

There would be, say:
```
POWERLEVEL10K_FG_1=... # blue
POWERLEVEL10K_FG_2=... # bold blue
...
POWERLEVEL9K_DIR_FOREGROUND=$POWERLEVEL10K_FG_1
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$POWERLEVEL10K_FG_2
```
Then you would change those to green and bold green. Which would also change other things that use those colors, since all the colorings for prompt segments would just use the variables.

You could also give people a hint if one of them has a use, e.g. maybe `POWERLEVEL10K_FG_2` should be called `POWERLEVEL10K_FG_1_INTENSE`.

> If you are OK with different prompt elements being rendered with the same small set of colors, then the 8 color version of Lean should satisfy you, right? Have you tried it?

Not yet! I probably will use that and it will likely satisfy my needs, *and* it requires less configuration since it just uses the terminal palette. My suggestion here is mostly trying to be helpful for people who use the versions with a larger palette.

> Rainbow uses fewer distinct colors. Almost everything is from the 8 color pallet.

Nice. All I'm suggesting is to define the palette up front so people can see/tweak it.

> It's big. Colors are pretty much random. I've no interest in experimenting in either shrinking or expanding it. Users who care about colors can edit them. If someone finds it in their good soul to contribute back a patch that improves the default colors, I'd be grateful.

FWIW I think this sort of contribution would be much more likely if you had a defined palette. That's the sort of thing someone can look at and say "I'm a color designer, here's a suggestion that will improve the contrast of these two colors".

**Comment by romkatv** [comment]
> FWIW I think this sort of contribution would be much more likely if you had a defined palette. That's the sort of thing someone can look at and say "I'm a color designer, here's a suggestion that will improve the contrast of these two colors".

These are all the way I know of how to allow people to define a palette.

1.  Provide parameters with meaningful names such as `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND`.
1.1 Group them together with other parameters that control the appearance of the prompt segment.
1.2 Put all these parameters at the top.
2. Provide parameters with meaningless names such as `POWERLEVEL10K_FG_12`.
2.1. Use one parameter per prompt element.
2.2. Randomly cluster prompt elements so that only 8 (or 16, or 22) colors are used.

1.1 is the current state. Do you think 1.2 would be an improvement? (FWIW, I don't think it would be.)

You said 2.1 would be bad. 2.2 would be nice if the assignment wasn't random but it is. I'm not a designer so random is all I can do. Note that given the random assignment I'm removing a lot of freedom from potential visual designers who might want to define a color palette.

**Comment by eddyg** [comment]
Personally I would prefer 2.1, with a max of 22 colors: `POWERLEVEL10K_THEME_[0-21]`. These 22 colors could be defined all in one place, making it easy to merge to a newly-regenerated `.p10k.zsh` (or, they could even be sourced from a separate `.p10k.colors` file). Each prompt segment would then define a foreground/background color from one of these theme color variables.

Another option to consider:

The [Base16 Styling Guidelines](http://chriskempson.com/projects/base16/) defines how colors should be used for syntax highlighting from a limited palette of colors. You could take a similar approach for "prompt segments": a color for cloud computing elements, a color for version control elements, there could be a couple colors for virtual environments (since there are so many and people may use more than one), a color for status items, a color for system information, etc.

I haven't fully come up with a "mapping, but I'm thinking something like this:

POWERLEVEL9K_THEME_DIR_FOREGROUND=4
POWERLEVEL9K_THEME_VCS_FOREGROUND=14
POWERLEVEL9K_THEME_CLOUD_COMPUTING_FOREGROUND=10
POWERLEVEL9K_THEME_VIRTUAL_ENV_1_FOREGROUND=9
POWERLEVEL9K_THEME_VIRTUAL_ENV_2_FOREGROUND=11
POWERLEVEL9K_THEME_SHOW_ON_COMMAND_FOREGROUND=13
POWERLEVEL9K_THEME_STATUS_FOREGROUND=3           _(clock, execution time, etc.)_
POWERLEVEL9K_THEME_SYSTEM_INFO_FOREGROUND=5    _(user@host, etc.)_
POWERLEVEL9K_THEME_DECORATION_FOREGROUND=8     _(used for things like gap char, icons)_
POWERLEVEL9K_THEME_SUCCESS_FOREGROUND=2
POWERLEVEL9K_THEME_ERROR_FOREGROUND=1
etc.

then instead of each prompt segment having a "random color", each foreground/background gets assigned an appropriate "theme group variable". Users are still free to change the color group to a different group (e.g. make the AWS segment use the VIRTUAL_ENV_2 color), or, they can use a specific color number just like they can now. And for things like the different parts of the current/shortened directory, you could try using **bold** or underline attributes instead of a different shades of color so it is compatible with more themes.

There could be a few color group options to choose from during configuration, including one that restricts the colors to 0-15, so the prompt dynamically updates based on the terminal theme.

I do re-run 'p10k configure' occasionally to check out new features/additions, but afterwards, I have to manually go through and make all my color changes. (I understand I don't ever need to run `p10k configure` again, but like I said, I do it to see all of Roman's latest additions/changes to the `.p10k.zsh` file.) Either of these approaches would make that it easier, while still allowing "power users" who wanted maximum customizability to be able to specify foreground/background colors on a segment-by-segment basis.

**Comment by romkatv** [comment]
Everyone, thanks for you feedback and suggestions. For the sake of saving everyone's time I'm going to close this issue. Finding a perfect solution to this problem is beyond my capabilities. I hope the 8-color variant of lean will prove useful at least to some of you. (It's unfortunate that no one has provided any feedback on it despite it being requested by so many.)

**Comment by michaelpj** [comment]
I'm intending to provide feedback on the new lean style - I just have cycles for writing issues but not fiddling with my shell at the moment :) thanks for your work!

**Comment by romkatv** [comment]
> I believe this can be solved fairly simply and is an important feature.

You don't have to convince me. Go ahead an act on your believes. Click fork and implement it. Shouldn't take long for a fairly simple change.

**Comment by romkatv** [comment]
> I am willing to implement the feature, but am not too familiar with the codebase. Will this entail significant change to the config wizard to have it properly write .p10k.zsh in the new format?

I don't know.

> If you can refer me to the relevant code or provide some suggestions/docs as to how to best modify the wizard it will expedite the process.

I don't know how to implement this. My suggestion that *you* implement it was just a common sense conclusion following from your own assessment of the important and difficulty of this problem. I didn't mean to imply that I encourage you to change code, or that I would like to receive a PR, or that I'll merge it.

**Comment by benorgera** [comment]
> You don't have to convince me. Go ahead and act on your beliefs. Click fork and implement it. Shouldn't take long for a fairly simple change.

> I didn't mean to imply that I encourage you to change code, or that I would like to receive a PR, or that I'll merge it.

This sort of sentiment is the bane of open source. You have users looking for a feature and people willing to contribute, but because you started the project you’d rather respond sarcastically than consider constructive suggestions.  Configuring color independent of functionality is theoretically simple. It’s a glorified find and replace. The config wizard makes it more difficult. If you don't know how to do it, you're simple. If I can't contribute to the project, the least I can do is contribute this https://www.bosley.com/

**Comment by Wizhi** [comment]
@romkatv I know this is an old issue, but as someone discovering this amazing project in the future, I'd just like to say thank you a lot for the 8-bit variant of Lean, it fits my niche, rather minimalistic and base16 needs perfectly from what I can tell. :)

**Comment by romkatv** [comment]
@Wizhi Thanks :hugs:

**Comment by romkatv** [comment]
> Could we get a classic version of this?

In theory, yes. In practice it's not something I'm going to implement. If you send a clean PR, I'll merge it.

**Comment by ShiromMakkad** [comment]
Fair enough, I don't have the time to do that right now either
