### ISSUE TITLE
Create releases/tags for packaging

### ISSUE THREAD

**Issue by mweinelt** [romkatv/powerlevel10k#392]
Hi,

I'm packaging p10k for NixOS and we would much prefer packaging released tags than pinning a random version from master. While one can easily monitor releases the same cannot be said for a whole upstream git history. Also there is the point of compatibility between p10k and gitstatus versions, that might break once in a while. I'm pretty sure other package maintainers feel the same way.

Would you mind considering doing releases once in a while? This affects p10k and gitstatus (& your libgit2 fork). 

P.S.: What is the chance of your libgit2 changes going upstream? I didn't find an answer to this question anywhere.

**Comment by romkatv** [comment]
> Would you mind considering doing releases once in a while? This affects p10k and gitstatus (& your libgit2 fork).

Please let me know what you want me to do to make your job easier.

> P.S.: What is the chance of your libgit2 changes going upstream?

Virtually zero.

**Comment by crunchtime-ali** [comment]
@romkatv I think manual GitHub release / tags (v0.1, v0.2, etc.) will suffice. You can also get GitHub notifications on releases now on GitHub which is my primary source of update information for favourite projects. 

![image](https://user-images.githubusercontent.com/7140800/71550816-3a3deb80-29d9-11ea-9236-3b09af22f1c5.png)

You can cut a new release based on features or also time-based (every month e.g.)
Along with that a short changelog would be awesome. There are plenty of tools ([like this one](https://github.com/github-changelog-generator/github-changelog-generator) which can help you put together these changelogs.

**Comment by romkatv** [comment]
I've created a release. Is that good enough? I won't be publishing changelogs between "releases" because these tags are artificial. In practice `master` is still a rolling release branch with each commit being a release.

Good enough?

**Comment by mweinelt** [comment]
My primary concern is that new releases should be made at least when compatibility between p10k and gitstatusd would break.

**Comment by romkatv** [comment]
I'm not sure I'm following. Are you going to rely on github having read/write consistency across different repositories? Could you explain how you are going to use the release tags that you want added to p10k?

P.S.

In the meantime I've removed the release tag as it's unclear to me whether it actually helps you.

**Comment by mweinelt** [comment]
Both p10k and gitstatusd are being developed in a rolling release fashion. If you'd use gitstatusd from mid 2019 and a recent p10k version that would not work, I've accidentally tried that. The two versions are therefore incompatible. Tags would be helpful to indicate breaking changes like this. Like saying that a fictional p10k release 0.1 requires gitstatusd >= 0.1.

**Comment by romkatv** [comment]
> Both p10k and gitstatusd are being developed in a rolling release fashion. If you'd use gitstatusd from mid 2019 and a recent p10k version that would not work, I've accidentally tried that.

There are two constraints:

1. `gitstatus.plugin.zsh` must match `gitstatusd`. There is no stable API between them. If you build `gitstatusd` from the same commit in gitstatus repo from which you've got `gitstatus.plugin.zsh`, it'll work.
2. Powerlevel10k needs `gitstatus.plugin.zsh` that isn't too old. The one that is bundled with powerlevel10k will always work, but you cannot easily find out from which commit in the gitstatus repo I've copied it from.

(1) is a solved problem but (2) isn't. Will it help you if I add a file to powerlevel10k that will always contain the commit from gitstatus repo from which I've copied `gitstatus.plugin.zsh`? Basically, like a submodule in git. To use powerlevel10k you'll do this:

1. Checkout master.
2. Read `gitstatus.gitref` file. (The actual format is TBD.)
3. Checkout gitstatus at the specified commit.
4. Build gitstatusd.
5. This gitstatusd can be used with powerlevel10k.

I can do the same to record the dependency between gitstatus and libgit2.

N.B. Storing gitstatus as a Git submodule would be ideal but that ship has sailed. If I replace the existing `gitstatus` directory in powerlevel10k with a submodule, users will break when they `git pull`. If I add the submodule *in addition* to the `gitstatus` directory, then users who pull submodules recursively will have their repo size double.

**Comment by romkatv** [comment]
Friendly ping. I don't intend to d anything until I know what will work for you.

**Comment by mweinelt** [comment]
I'll get back to you in a few days, busy with other things currently.

**Comment by maximbaz** [comment]
> I won't be publishing changelogs between "releases" because these tags are artificial. In practice master is still a rolling release branch with each commit being a release.

@romkatv I would actually be very excited if you had releases with changelogs!

- Why releases: right now I simply don't know when to update p10k, it happens randomly, whenever I remember it, and then I go on fixing occasional breaks because I don't know what to expect from the update (like today my custom-made `nnn` segment broke, because turns out it was implemented in p10k directly - which is nice!). Just like @crunchtime-ali I also monitor releases of my favorite projects on Internet, so if I would receive occasional emails `p10k has new release x.y.z, this is what is new`, I would be updating a lot more often!
- Why changelogs: commits on `master` provide too much granularity, and there might be some internal changes which don't impact me as a user, it would be very helpful if you had some sort of changelog "from user perspective", something like `new segments: xx, yy, zz; improvements: xx, yy, zz` would be valuable. Particularly news about new segments, which I must monitor so that I know to update my config file. I actually think spaceship did quite a good job at describing releases 🙂 

Releases with changelogs also build up excitement around the community, because it's very easy to see continuous progress and improvements (again, just look at [spaceship releases page](https://github.com/denysdovhan/spaceship-prompt/releases)).

I obviously don't want you spend all your time making releases when you could be using this time to deliver even more of your awesome commits, there is also a danger of doing very infrequent releases (I would even argue it does more harm than good, because some people would not update, and would wait for the next release), but I think it should be possible to find a good middle ground. If I managed to give you some new perspective on this topic, do consider it 😉

**Comment by romkatv** [comment]
Thanks, @maximbaz. I appreciate your thoughts on this.

Let me first address more specific points.

> like today my custom-made `nnn` segment broke, because turns out it was implemented in p10k directly - which is nice

Don't define things with names that can conceivably be taken over by other projects. p10k is being more conscious about name pollution than other projects, so it's easy to guess what could or could not collide with p10k in the future. If you need to define a prompt segment, give it your name as a prefix. I also use `my` for this purpose.

> right now I simply don't know when to update p10k

You use prezto, right? And I suppose you update it? When you do, p10k gets updated as well.

I update p10k in prezto regularly (see [my PRs](https://github.com/sorin-ionescu/prezto/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aromkatv+)) and I write a short release log when I do. Here's [the latest](https://github.com/sorin-ionescu/prezto/pull/1784):

> - New features:
>   - Show On Command -- Display prompt segments conditional on the command being typed. Demo:
>     ![demo](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/show-on-command.gif)
>   - `p10k display` -- Quickly hide or show different parts of prompt.
>   - `p10k-on-*` hooks -- Get notified about prompt-related events.
> - New prompt segments:
>   - google_app_cred -- Google Application Credentials.
>   - luaenv -- Lua version from https://github.com/cehoffman/luaen.
>   - jenv -- Java version from https://github.com/jenv/jenv.
>   - plenv -- Perl version from https://github.com/tokuhirom/plenv.
>   - nnn -- Shell indicator for https://github.com/jarun/nnn.
> - Important fixes:
>   - Ctrl-C no longer shortens prompt when used to terminate a zle widget with transient prompt enabled.
>   - Don't print warnings in instant prompt when OMZ is updating.
>   - rust_version now properly recognized rustup overrides.
> - Smoother rendering when using transient prompt.
> - New style in `p10k configure`: Lean restricted to 8 colors.

It's not *too difficult* for me to create a release in p10k at the same time and use the same notes. I don't think it'll help @mweinelt. I'm not sure it'll help you (@maximbaz) because you get p10k from prezto (I suppose?).

Now to more general themes.

(I've written a long treatise here and then wisely deleted it.)

**Comment by maximbaz** [comment]
> You use prezto, right? And I suppose you update it? When you do, p10k gets updated as well.

I personally don't use third-party things from prezto, but fetch them directly (it's quite easy to do via antigen). So p10k I get from your repo, so it's very easy for example to test a branch like `reactive`.

Prezto itself also doesn't have releases, so I update it in the same fashion - whenever I remember to do that. But I think I use a relatively small subset of prezto features, so I don't really expect any major changes or new features.

Your project on the other hand is evolving very fast, new features appear often, new segments, I would definitely value to have a simple way to get summary of recent changes to stay up to date, and give you some feedback of course if things don't work as intended 😉 

> I update p10k in prezto regularly (see my PRs) and I write a short release log when I do. Here's the latest:
> It's not too difficult for me to create a release in p10k at the same time and use the same notes. I'm not sure it'll help you (@maximbaz) 

Wow, that kind of summary is *exactly* what I am looking for! It would help me greatly if this exact message was posted in this repo as a release, which I can subscribe to via emails 😉  

(I'm about to go now in prezto PRs history, find all your recent PRs and get up-to-date with what changed in p10k since I installed it and initially configured 😄 )

**Comment by romkatv** [comment]
> > It's not too difficult for me to create a release in p10k at the same time and use the same notes. I'm not sure it'll help you (@maximbaz)
> 
> Wow, that kind of summary is _exactly_ what I am looking for! It would help me greatly if this exact message was posted in this repo as a release, which I can subscribe to via emails 😉

Alright, I've created 1.0 just now and will in the future create releases at the same time I'm updating p10k in prezto.

**Comment by mweinelt** [comment]
Good enough for me, thank you.

I'll likely bump gitstatusd at the same time I bump p10k.

**Comment by mweinelt** [comment]
I'll just pick the version at the time of the p10k release and hope that's fine. Is that a reasonable strategy?

**Comment by romkatv** [comment]
> I'll just pick the version at the time of the p10k release and hope that's fine. Is that a reasonable strategy?

I cannot comment on reasonableness of this choice. I suppose you know as well as I do its pros and cons.

I'm willing to do what you need, you just need to tell me. If "do nothing" is good enough, I certainly can comply. I can also specify exact dependencies, including commits, in release notes. I've mentioned other options above.

**Comment by mweinelt** [comment]
In that case please mention the commit you are updating gitstatusd to in commits like https://github.com/romkatv/powerlevel10k/commit/c21961b53c137253020aeffca2b132fdd6bcb116.

**Comment by romkatv** [comment]
> In that case please mention the commit you are updating gitstatusd to in commits like [c21961b](https://github.com/romkatv/powerlevel10k/commit/c21961b53c137253020aeffca2b132fdd6bcb116).

Sounds good. Will do that. Closing the issue.

**Comment by maximbaz** [comment]
Just wanted to say once again: thanks for all your work on p10k, and thanks for making releases with release notes, very helpful! ❤️

**Comment by mweinelt** [comment]
Indeed, thank you very much for creating p10k and doing releases. This helps alot!

**Comment by romkatv** [comment]
@maximbaz @mweinelt Thanks for confirming that what I'm doing is working for you.

**Comment by romkatv** [comment]
@mweinelt Heads up: This change in v1.3.0 is probably relevant to you:

> - gitstatus:
>   - `make` now produces `usrbin/gitstatusd` instead of `./gitstatusd`.

**Comment by mweinelt** [comment]
Heads up: The build time dependency for libgit2 defined in the v1.3.0 release notes seems to old:

> https://github.com/romkatv/libgit2/tree/75be63625a0de418ec3551306362ee1e21034039

and results in

```
src/index.cc: In member function 'size_t gitstatus::Index::InitDirs(git_index*)':
src/index.cc:350:36: error: 'git_index_get_byindex_no_sort' was not declared in this scope; did you mean 'git_index_get_byindex'?
  350 |     const git_index_entry* entry = git_index_get_byindex_no_sort(index, i);
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    git_index_get_byindex
make: *** [Makefile:27: obj/index.o] Error 1
```

I guess I need https://github.com/romkatv/libgit2/commit/c52ffd4b01d4d11366d27264fe405c88fd426eab for that, but I bumped our package to use https://github.com/romkatv/libgit2/commit/bb77509f4436901f3958e30272026f63d2247d7d and that looks good.

**Comment by romkatv** [comment]
> Heads up: The build time dependency for libgit2 defined in the v1.3.0 release notes seems to old:
> 
> > https://github.com/romkatv/libgit2/tree/75be63625a0de418ec3551306362ee1e21034039

Thanks for the report. I've messed up libgit2 reference in the release notes for 1.3.0. Fixed. I've updated my release checklist to avoid making the same mistake in the future.

**Comment by romkatv** [comment]
@mweinelt I'm curious, why do you build gitstatusd from source? Are there any issues with the official binaries or is it a policy of some sort?

**Comment by mweinelt** [comment]
Because in NixOS libraries are elsewhere in the system. I'd either need to patch some paths using `pachelf`, which I'm not too familiar with, or build from source, which is what I'm capable of doing.

```
❯ file ./gitstatusd-linux-x86_64
./gitstatusd-linux-x86_64: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=da65233268891b668fea96a277c77bac35722bd0, stripped
❯ ldd ./gitstatusd-linux-x86_64
	linux-vdso.so.1 (0x00007ffc9cbeb000)
	libpthread.so.0 => /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libpthread.so.0 (0x00007fc3a244a000)
	libc.so.6 => /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6 (0x00007fc3a228b000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib64/ld-linux-x86-64.so.2 (0x00007fc3a28b3000)
❯ ./gitstatusd-linux-x86_64
zsh: no such file or directory: ./gitstatusd-linux-x86_64
```

**Comment by romkatv** [comment]
@mweinelt Are you getting these results with the latest version of gitstatus/powerlevel10k?

**Comment by romkatv** [comment]
To add to my previous comment. `gitstatusd-linux-x86_64` used to depend on libc but it doesn't anymore. However, on systems without libc powerlevel10k and standalone gitstatus have been using `gitstatusd-linux-x86_64-static` since a very long time. This binary is statically linked, so it works on nixos just fine. (Nowadays `gitstatusd-linux-x86_64` is statically linked, so `gitstatusd-linux-x86_64-static` is just a shit that calls it.)

**Comment by mweinelt** [comment]
Yes, that happens on 

```
commit eab09f893802d46d0cdd78c3c2cfeab52b768826 (HEAD -> master, origin/master, origin/HEAD)
Author: romkatv <roman.perepelitsa@gmail.com>
Date:   Sun Mar 29 18:50:34 2020 +0200

    remove special error message for 32-bit arm and intel; these are now supported
```

**Comment by romkatv** [comment]
Oh god. I've posted my comment right after breaking all gitstatusd binaries... Fixing ASAP.

I think you've answered my question though. You've been building gitstatusd from source because you believed that powerlevel10k doesn't work out of the box, right? It has worked out of the box on NixOS since Jun 7, 2019. (It'll work once again as soon as I fix my mess.)

**Comment by romkatv** [comment]
> Oh god. I've posted my comment right after breaking all gitstatusd binaries... Fixing ASAP.

OK, turns out it isn't so bad. Only one binary is dynamically linked against my intentions. Still, it stings that I've missed it.

Fixed. Please update and try again.

**Comment by mweinelt** [comment]
Yep, that works. Thanks!

**Comment by romkatv** [comment]
> Yep, that works. Thanks!

Awesome! Does it mean you no longer need the "Build time dependencies" section in releases? Powerlevel10k package in nix can just download the main source archive (e.g., https://github.com/romkatv/powerlevel10k/archive/v1.4.0.tar.gz) and extract it, right? No patching or building necessary. The same goes for gitstatus package.

**Comment by mweinelt** [comment]
Well, there's several reason binary releases are frowned upon by NixOS when the source is actually available.

- Building from source allows us to have a Git reference, which makes it easier to review changes to the code
- It also allows the enduser to be sure of what they actually get in terms of the source that was checked out and is currently running
- The build recipe can be overloaded by endusers if they like to do that, quite like the way we lean on the original `libgit2` expression to build your fork: https://github.com/NixOS/nixpkgs/blob/1ab2e9ef3f2a023ee126ed2028f1be886f72b198/pkgs/applications/version-management/git-and-tools/gitstatus/romkatv_libgit2.nix#L3

Is there any particular concern you have with building from source? I'll try as best as I can to watch out for changes to gitstatusd and libgit2 makeflags.

**Comment by romkatv** [comment]
> Is there any particular concern you have with building from source? I'll try as best as I can to watch out for changes to gitstatusd and libgit2 makeflags.

No, I just want to understand your usage better.

I'm currently in the process of restructuring gitstatus, so build instructions will likely change. I wanted to know in advance whether I still need to communicate these changes to you. I understand the answer is Yes.

**Comment by maximbaz** [comment]
FWIW in Arch we also prefer building from sources whenever possible, mostly for the same reasons, but also to make sure that no app uses potentially outdated and vulnerable dependency (i.e. avoid statically linked binaries), and to align on how all apps are compiled across distro (stripping binaries, using certain optimization flags, using some security flags, etc).

Having said that, I can see that our own p10k package does not currently compile `gitstatus` from sources, we might want to adjust that, cc @shibumi.

**Comment by shibumi** [comment]
@maximbaz we should probably build a single gitstatus package and let powerlevel10k depend on it.

**Comment by romkatv** [comment]
@shibumi The bindings between Zsh and gitstatusd are currently an implementation detail. This makes decoupling of gitstatusd from powerlevel10k quite difficult. It's more practical to treat powerlevel10k as having an instant of gitstatus (with gitstatusd) as its own implementation detail.

**Comment by romkatv** [comment]
@mweinelt @shibumi Heads up, powerlevel10k has new packaging instructions: https://github.com/romkatv/powerlevel10k/#how-to-package-powerlevel10k-for-distribution. Please give it a try and let me know whether it works.

This should be much simpler than the current package definition in Nix. It should also allow Arch to painlessly package Powerlevel10k (and gitstatus, if you want to).

**Comment by cridemichel** [comment]
Dear Roman
I saw that after latest "git pull" gitstatus binaries have been 
removed from powerlevel10k git directory which is located 
in my .oh-my-zsh fold, should I have to compile them?

best C.

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
No. Did you get any error messages?

**Comment by cridemichel** [comment]
no everything’s fine but I wonder what
gitstatus executable I am using right now…
just curiosity


Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
@cridemichel This change was long in the making.

From [gitstatus release notes](https://github.com/romkatv/gitstatus/releases/tag/v1.0.0):

> - gitstatusd binaries are no longer in the repository. You can find them in releases from now on. Zsh and Bash bindings will download them automatically.

From [powerlevel10k release notes](https://github.com/romkatv/powerlevel10k/releases/tag/v1.8.0):

> - Powerlevel10k Git repository no longer stores gitstatusd binaries. Instead, appropriate binaries are downloaded automatically when necessary.

**Comment by cridemichel** [comment]
Dear Roman,
I installed powerlevel10k manually by checking it out
under .oh-my-zsh/custom/themes/
and gitstatus binaries are not there anymore. How can I 
download them automatically? 
I also ran p10k configure but still nothing…

thank for your help

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
Dear Cristiano,

The absence of gitstatusd binaries under `~/.oh-my-zsh/custom/themes/powerlevel10k` is expected.

If you are experiencing problems using powerlevel10k (error messages, incorrect prompt, slow prompt, etc.), please open an issue.

**Comment by cridemichel** [comment]
ok but what’s the name of the binary file which I am actually using
for the git prompt and where I can possibly find it?

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
The binary is in here:

```zsh
ls "${GITSTATUS_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/gitstatus}"
```

May I ask what you are trying to achieve? Why do you have an interest in gitstatusd?

**Comment by cridemichel** [comment]
nothing special, just knowing where binaries are located :-)

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
You can answer such questions with `ps`:

```zsh
ps -o comm | grep -E '^/.*/gitstatusd.*'
```
