### ISSUE TITLE
[feature] is there already a function to add a segment to the prompt during runtime?

### ISSUE THREAD

**Issue by jayree** [romkatv/powerlevel10k#416]
I really like p10k and as I'm working on an additional segment I'm currently wondering if there is already a function which is doing something like this:
```zsh
  local segment=$1
  local at=$2
  [[ -n "$segment" ]] || return 1
  [[ -n "$at" ]] || return 1
  if [[ ! " ${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]} " =~ " $segment " ]]; then
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[$at,0]=$segment
    (( ! $+functions[p10k] )) || p10k reload
    return 0
  fi
```

I've tried already to use this:
```zsh
p10k display '*/right/time'=show
```
but this only works if 'time' is commented out in the `~/.p10k.zsh` file, so a segment can be hided or shown, but not added.

**Comment by romkatv** [comment]
There is no such function. What you've written is the way to do it.

P.S.

Simpler and faster check for the presence of a segment:

```zsh
if (( ! POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[(Ie)$segment] )); then
  ...
fi
```

This find the position of an element within the array instead of concatenating all elements of the array and then using regex match of the string.

Better check for `at`:

```zsh
[[ $at == <1-> ]] || return 1
```

It verifies that `at` is a positive integer.
