### ISSUE TITLE
Hide RPROMPT from previous commands

### ISSUE THREAD

**Issue by rochdev** [romkatv/powerlevel10k#417]
When I press the return key, I would like the RPROMPT of the previous command to disappear. This is mostly because of the bug on resize in zsh that doesn't seem to be fixable. I put mostly information relevant to the current command in the RPROMPT and I would rather have it disappear in past commands instead of the current broken behavior from zsh.

Is this currently possible? Otherwise I can always try to make a PR to add a variable for it. Should it be named transient rprompt? It's very similar but not exactly the same functionality, so let me know if that would be confusing.

**Comment by Aloxaf** [comment]
Is option `TRANSIENT_RPROMPT` what you want?
```man
TRANSIENT_RPROMPT
       Remove  any  right  prompt from display when accepting a command line.  This may be useful with terminals with
       other cut/paste methods.
```

**Comment by romkatv** [comment]
> When I press the return key, I would like the RPROMPT of the previous command to disappear.

That sounds like `setopt transient_rprompt`.

> This is mostly because of the bug on resize in zsh that doesn't seem to be fixable.

There are several mitigation options:

1. Use [this patch](https://github.com/romkatv/zsh/commit/75f3e06f8723fc96ea288ca05a4e0867d6a9681a).
2. Configure your terminal to not reflow text on resize. Not all terminals support this.
3. Make sure your **current** prompt does not span to the right edge of the screen. That is, there is no right prompt and left prompt isn't very long. **It doesn't matter how previous prompts look like.**

Note that `setopt transient_rprompt` or any kind of transient prompt is not on the list. It doesn't help here.

It's really helpful to see what happens in slow motion with a simple prompt. Here are a few examples.

```zsh
PROMPT=$'$(sleep 1)> ' RPROMPT='<' /bin/zsh -df --prompt_subst
```

(`sleep 1` makes it easier to see what's going on.)

Once prompt appears, type `reset && print -l {1..3}` and hit ENTER. Then ESC-ENTER. This is the screen:

```text
1
2
3
>                          <
█
```

Now shrink the terminal window and note how left prompt got duplicated.

```text
1
2
3
> 
>              <
█
```
 Make the terminal window wider. We now have a complete mess.

```text
1
2
3
>                >     > 
>                          <
█
```

Similar results with the following prompt (here you don't have to press ESC-ENTER to get the mess):

```zsh
PROMPT=$'$(sleep 1)X${(pl.$((COLUMNS-2))..-.)}\n> ' /bin/zsh -df --prompt_subst
```

Note how in both cases there are no long lines before the current prompt and yet resizing the terminal produces mess.

**Comment by romkatv** [comment]
I should also mention that you can manually control how prompt changes when it gets retired. `POWERLEVEL9K_TRANSIENT_PROMPT` is syntax sugar for a specific prompt truncation logic but you can do pretty much anything there. For example, if you want to hide right prompt, `setopt transient_rprompt` won't work for multi-line prompts (`RPROMPT` is only on the last line; everything else is `PROMPT`). But you can do it like this:

```zsh
# Called by p10k right before the current prompt is retired.
function p10k-on-post-prompt() {
  # Hide right prompt and gap from all prompt lines.
  p10k display '*/(right|right_frame|gap)'=hide
}

# Called by p10k right before a new prompt is rendered.
function p10k-on-pre-prompt() {
  # Unhide what was hidden by p10k-on-post-prompt earlier.
  p10k display '*/(right|right_frame|gap)'=show
}

# Disable preset prompt retirement logic.
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
```

**Comment by rochdev** [comment]
Thanks for the prompt answer (pun intended).

I assumed that `RPROMPT` was valid on every line, but it seems that this is not the case. As you said, this means there is really no way to address the issue without patching zsh which I'm not willing to do.

As a side note, do you have a PR for the zsh fix? I read somewhere that you were told the fix could theoretically break some themes, but I want to argue with them that right now all themes are broken.

Since the original request is covered by your last snippet, I will go ahead and close this issue.

**Comment by romkatv** [comment]
> Thanks for the prompt answer (pun intended).
> 
> I assumed that `RPROMPT` was valid on every line, but it seems that this is not the case.

I'll clarify just in case there is misunderstanding. `RPROMPT` in zsh cannot occupy multiple lines but `PROMPT` can. Basically, when prompt is rendered, everything before the cursor is `PROMPT`, and everything after the cursor is `RPROMPT`. When your p10k prompt looks like this:

```text
~/foo/bar master       minikube
❯ █                    10:50:42
```

`RPROMPT` is `10:50:42`, while `PROMPT` is `~/foo/bar master       minikube\n❯ ` (that `\n` is newline).

`setopt transient_rprompt` removes `RPROMPT` when prompt is retired. In the example above it would leave this prompt:

```text
~/foo/bar master       minikube
❯
```

I should also repeat that transient prompt does not and cannot fix rendering issues on terminal resize. Even if you change the code of zsh so that the whole prompt is cleared when it's retired, the issue will remain. I've attempted to demonstrate this in my previous comment where the only long line is the one that belong to the *current* prompt and yet resizing the terminal causes visual artifacts. Rendering breaks when the number of lines between the start of the prompt and the cursor changes as the result of terminal resizing. The content before the start of the current prompt is irrelevant.

> As you said, this means there is really no way to address the issue without patching zsh which I'm not willing to do.

Correct. For the reference, here's how you can build zsh without this bug:

Build zsh and install it as `/usr/local/bin/zsh`:

```zsh
(
  emulate -L zsh
  setopt err_return
  # replace the next 2 lines if using non-debian based OS
  sudo apt update
  sudo apt install -y git build-essential libncurses-dev gcc autoconf man yodl
  zsh_dir="$(mktemp -d)"
  {
    git clone https://github.com/romkatv/zsh -b fix-winchanged $zsh_dir
    cd $zsh_dir
    ./Util/preconfig
    ./configure
    sudo make -j 20 install
  } always {
    sudo rm -rf $zsh_dir
  }
)
```

(Your original `zsh` is still available as `/bin/zsh` and `/usr/bin/zsh`.)

Add `/usr/loca/bin/zsh` to the list of login shells:

```zsh
grep -qE '^/usr/local/bin/zsh$' /etc/shells || sudo tee -a /etc/shells <<</usr/local/bin/zsh >/dev/null
```

Make `/usr/local/bin/zsh` your login shell:

```zsh
chsh -s /usr/local/bin/zsh
```

> As a side note, do you have a PR for the zsh fix?

Patches for zsh are sent to zsh-workers@zsh.org. Here's the thread: https://www.zsh.org/mla/workers//2019/msg00561.html.

> I read somewhere that you were told the fix could theoretically break some themes

Correct.

> but I want to argue with them that right now all themes are broken.

I appreciate your support but I would caution against this.

**Comment by rochdev** [comment]
Thanks for the thorough clarification. Interestingly, I just did some tests with only a longer PROMPT with Powerlevel10k and another theme and while the same issue exists for Powerlevel10k when the window is resized smaller than the line even without RPROMPT, the other theme seems to handle it properly. Are there some other factors that can cause this difference?

**Comment by romkatv** [comment]
Please do my previous reply and try out the commands I've written down.

**Comment by rochdev** [comment]
I'm not sure I understand what you mean, since I already ran any command that is relevant to me. Even then, with mostly the default settings and an almost identical theme, I'm not sure to understand why one theme would have the issue and not the other. Doesn't that mean it's possible to avoid the issue in Powerlevel10k as well in some cases?

**Comment by romkatv** [comment]
> I'm not sure to understand why one theme would have the issue and not the other.

Keep trying. Use simple prompt with `sleep 1` in it and build the precise model in your head for predicting what will happen when the terminal window is resized. Read this sentence a few more times:

> Rendering breaks when the number of lines between the start of the prompt and the cursor changes as the result of terminal resizing.

If it's still unclear, post a question on zsh-users@zsh.org.

**Comment by rochdev** [comment]
Sure, I mean it makes perfect sense. I just don't get why it wouldn't glitch for the other theme. But it's also a more rigid theme so maybe they found a way that is specific to that specific prompt structure.

**Comment by rochdev** [comment]
Nevermind the above, I was able to replicate it with the other theme as well, it's just a bit more difficult because it renders more lazily (which is both good and bad as it also means it's less responsive).

Thanks @romkatv for all the help!

**Comment by romkatv** [comment]
> [...] maybe they found a way that is specific to that specific prompt structure.

I'm 100% positive that whenever the number of lines between the start of the prompt and the cursor changes as the result of terminal resizing, zsh renders prompt on the wrong line. If rendering happens higher than it should, terminal content gets erased. If it happens lower than it should, parts of the previous prompt that were meant to be deleted will remain. Zsh scripts have no way around this. The severity of incorrect rendering wholly depends on the content of prompt. If prompt stats with an empty line (e.g., if you enable "sparse" and "transient prompt" options in `p10k configure`), then it's not as bad because it's the empty line that will get duplicated.
