### ISSUE TITLE
prompt_char command not found

### ISSUE THREAD

**Issue by horseinthesky** [romkatv/powerlevel10k#424]
Hello.
I'm sorry. Couldn't find the answer.

I've added this:
```
  POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=142
  # Red prompt symbol if the last command failed.
  POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=167
  # Default prompt symbol.
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  # Prompt symbol in command vi mode.
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  # Prompt symbol in visual vi mode.
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='Ⅴ'
  # Prompt symbol in overwrite vi mode.
  POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
```
to `.zshrc` but it tells me:
```
/home/horseinthesky/.zshrc:338: command not found: POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=142
/home/horseinthesky/.zshrc:340: command not found: POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=167
/home/horseinthesky/.zshrc:342: command not found: POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION=❯
/home/horseinthesky/.zshrc:344: command not found: POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION=❮
/home/horseinthesky/.zshrc:346: command not found: POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION=Ⅴ
/home/horseinthesky/.zshrc:348: command not found: POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION=▶
```
every time I enter the prompt.

And it seems it is ignoring color settings:
![image](https://user-images.githubusercontent.com/19948672/72669924-be1f4c80-3a48-11ea-9c96-1bf03724046c.png)

This is my left segments:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_host custom_user dir_writable dir virtualenv pyenv newline prompt_char)
```

**Comment by romkatv** [comment]
> ```zsh
> POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=142
> ```

Try copy-pasting this command into an interactive zsh session. You'll see the same error. The problem is that it's missing `typeset` in front.

**Comment by horseinthesky** [comment]
Yes. This works.
But I still have one whitespace begore and one after the prompt char + background which I didn't set up.
Could you pls tell what this `typeset -g` do exactly? All my other settings from 9K do not have this prefix.

**Comment by romkatv** [comment]
> Yes. This works.
> But I still have one whitespace begore and one after the prompt char + background which I didn't set up.

`prompt_char` is a prompt segment like any other. Like all segments, it has default background color and surrounding spaces.

I recommend copying these parameters and then changing bits and pieces if something doesn't work the way you want:

https://github.com/romkatv/powerlevel10k/blob/3391739b550f855416444ce6d44a913fa80b2d3b/config/p10k-classic.zsh#L212-L234

This is generally an effective way to configure advances features:

1. Run `p10k configure`.
2. Play with the prompt.
3. Look at `~/.p10k.zsh` and copy things you like into your own prompt.

Examples of things that are incredibly useful but virtually impossible to discover otherwise:

1. [Responsive directory truncation](https://asciinema.org/a/258376).
2. [Instant prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-instant-prompt).
3. [Transient prompt](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif).
4. [Show on command](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/show-on-command.gif).

It would be awesome if there was documentation for this stuff but unfortunately there isn't, so configs generated by `p10k configure` is the only substitute.

> Could you pls tell what this `typeset -g` do exactly?

`typeset` is a reserved word in zsh (there is also a builtin with the same name). It sets parameters. `-g` makes the parameters global.

> All my other settings from 9K do not have this prefix.

This:

```zsh
typeset -g a{1,2,3,4}b=x
```

becomes this after brace expansion:

``zsh
typeset -g a1b=x a2b=x a3b=x a4b=x
```

which is equivalent to this (assuming none of these parameters were declared as local earlier):

```zsh
a1b=x
a2b=x
a3b=x
a4b=x
```

This isn't a powerlevel10k feature, it's just zsh. See `typeset` in `man zshbuiltins`.

So instead of this:

```zsh
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=142
```

You can write this:

```zsh
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=142
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=142
POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=142
POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND=142
```

The effect is the same. Powerlevel10k won't be able to tell a difference.

**Comment by horseinthesky** [comment]
Thank you very much for such a detailed answer. Keep playing with `p10k configure`.
