### ISSUE TITLE
Select text with mouse

### ISSUE THREAD

**Issue by farshidhss** [romkatv/powerlevel10k#438]
Hi! After I have updated my powerline10K and did a configure, I can no longer select the text using mouse. I can select if I hold down option(alt) key but I prefer to be able to select the text same as before. Is there any settings that I should set?

**Comment by romkatv** [comment]
Are you sure this issue is caused by powerlevel10k? Please double-check that:

1. With powerlevel10k enabled you cannot select text with mouse.
2. With powerlevel10k disabled you can select text with mouse.

Make sure that the only difference between the two setups is that in one of them you are using powerlevel10k, while in another setup you are not using powerlevel10k.

If you can confirm this, please attach the two versions of `~/.zshrc` that you've tested. Also let me know which operating systems you are using and which terminal.

**Comment by farshidhss** [comment]
I tried it and problem exists when p10k is disabled too. My two version that I tested are attached.
[with_p10k.zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4112033/with_p10k.zshrc.txt)
[without_p10k.zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4112034/without_p10k.zshrc.txt)

**Comment by romkatv** [comment]
> Also let me know which operating systems you are using and which terminal.

Please :point_up:

**Comment by farshidhss** [comment]
Ah sorry, I'm on Mac 10.15.2 Catalina, and using iterm2 3.3.7

**Comment by romkatv** [comment]
The two attached files (`with_p10k.zshrc.txt` and `without_p10k.zshrc.txt`) are identical.

**Comment by farshidhss** [comment]
ah my bad, for disabling p10k I simply commented out the last two lines:
`# source ~/powerlevel10k/powerlevel10k.zsh-theme
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh`

**Comment by romkatv** [comment]
Cannot reproduce.

What exactly happens when you try to select text with mouse while using powerlevel10k?

Have you changed anything in iTerm2 preferences?

What is the output of `/usr/libexec/PlistBuddy -c Print ~/Library/Preferences/com.googlecode.iterm2.plist`?

**Comment by farshidhss** [comment]
It's quite strange, from the menu I chose Session->Reset and it fixed the problem. Many thanks for your help.

**Comment by romkatv** [comment]
I'm glad this issue got resolved. FWIW, there is nothing in powerlevel10k that should in any way affect how mouse selection works, so I have no idea what was the root cause.
