### ISSUE TITLE
Fonts installed but arrows not showing in prompt

### ISSUE THREAD

**Issue by elie222** [romkatv/powerlevel10k#441]
My prompt looks as follows:

![image](https://user-images.githubusercontent.com/3090527/73143004-ba6d7480-409d-11ea-94eb-6ed3513e266d.png)

On OS X. Using iTerm 2. Updated preferences:

![image](https://user-images.githubusercontent.com/3090527/73143015-e4bf3200-409d-11ea-8fc6-01bd903cd6c8.png)

Any idea what's going wrong?

**Comment by elie222** [comment]
This may be related. When I run `config` I don't see any of the symbols. I answer no to all the questions but it doesn't do anything to fix it.

**Comment by romkatv** [comment]
Please describe what you believe is wrong on the screenshot.

**Comment by romkatv** [comment]
> This may be related. When I run `config` I don't see any of the symbols. I answer no to all the questions but it doesn't do anything to fix it.

Try restarting iTerm2 (the whole terminal, not just zsh) and running `p10k configure` afterwards.

**Comment by elie222** [comment]
> > This may be related. When I run `config` I don't see any of the symbols. I answer no to all the questions but it doesn't do anything to fix it.
> 
> Try restarting iTerm2 (the whole terminal, not just zsh) and running `p10k configure` afterwards.

This fixed both problems. Thanks

Got a whole different set of questions when running configure once the font issue was fixed.

**Comment by romkatv** [comment]
Here's what I think happened. Please let me know if this matches your recollection.

When the configuration wizard ran for the first time, it asked you whether to install the recommended font. You agreed (good choice). After installing the font, wizard presented you with this screen:

![image](https://user-images.githubusercontent.com/1282067/73163916-2f1dce80-40f1-11ea-8d32-0b01219bd302.png)

There is no way to exit this screen other than by pressing `Y`. If you press any other key, it'll say "It's important to restart iTerm2 for the changes to take effect" and ask for confirmation once again.

![image](https://user-images.githubusercontent.com/1282067/73163967-46f55280-40f1-11ea-8f03-2e4aafeff4ba.png)

In the past, the wizard would simply print "Please restart iTerm2 for the changes to take effect" and exit, but so many users were missing this message that I added essentially a non-dismissible modal dialog. This has cut down on the number of issues similar to this by a lot. If you exit this dialog and then run `p10k configure` *without restarting iTerm2*, the wizard will not offer to install the font because it will see that the font is already installed. However, iTerm2 is still using the old font, so you won't see custom glyphs such as the diamond, the lock, etc. Once you tell the wizard that glyphs don't render properly, it won't offer prompt styles that use them. If it did, you would end up with broken prompt.

Does this sound like what happened? Knowing the answer would allow me to make proper adjustments in the code to avoid pitfalls like this in the future.

**Comment by elie222** [comment]
No, it didn’t. I didn’t see either of those screens.

Best,
Eliezer

**Comment by romkatv** [comment]
> No, it didn’t. I didn’t see either of those screens.

Did you see the screen that asks whether you want the recommended font to be installed? If yes, did you agree to install it?

I added the modal dialog following the font installation on Dec 17, 2019. Prior to this date powerlevel10k was simply printing a message asking to restart iTerm2. Is it possible that your version of powerlevel10k is older than that?

**Comment by elie222** [comment]
I downloaded powerlevel10k for the first time yesterday. I didn't see any of those messages. Only the questions where I could see the symbols (which I couldn't) and then it just moved on like all was okay.

Best,
Eliezer

**Comment by romkatv** [comment]
The screenshot of iTerm2 settings that you've posted in https://github.com/romkatv/powerlevel10k/issues/441#issue-555299107 shows MesloLGS NF font. How did you install it?

**Comment by elie222** [comment]
I believe I downloaded the fonts and add them to font book. I also switched the iTerm2 settings to use that font.

(I was playing with a bunch of fonts yesterday so I don't remember exactly how I added each font.)

Best,
Eliezer

**Comment by romkatv** [comment]
This is very surprising. When you change font manually through iTerm2 settings, the font is applied immediately without restarting iTerm2. Given that your restarting iTerm2 had effect on fonts (you couldn't see the diamond before restart but could see it after restart), it suggests that MesloLGS NF was previously installed by the powerlevel10k configuration wizard rather than manually. Another possibility is that iTerm2 has a bug that prevents font changes through settings to be applied immediately without restart.

Either way, I think we should wrap it up here. Thanks for you help getting to the bottom of this issue.

**Comment by slackwing** [comment]
> Does this sound like what happened? Knowing the answer would allow me to make proper adjustments in the code to avoid pitfalls like this in the future.

This is exactly what happened to me, so you have one data point. (More specifically, I issued an `exit` command to close the iTerm2 window not realizing this doesn't restart iTerm2. I'm relatively new to Macs.)

**Comment by romkatv** [comment]
> This is exactly what happened to me, so you have one data point. (More specifically, I issued an `exit` command to close the iTerm2 window not realizing this doesn't restart iTerm2. I'm relatively new to Macs.)

If you are relatively new to Macs, I would suggest doing what the instructions says rather than doing something else.
