### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by shurik** [romkatv/powerlevel10k#459]
Hello,

I used to use Fira Code as my terminal font. It has ligatures. Is it possible to add ligatures to the font that ships with Powerlevel10K?

**Comment by romkatv** [comment]
The font that ships with p10k is simply a font that looks fairly good, has all conceivable glyphs built-in, and has been verified to work everywhere (plus a few manual edits, but those a minor). You are free to use any font you like. Just make sure to run `p10k configure` after changing terminal font so that powerlevel10k can adjust to the capabilities of your font.

**Comment by shurik** [comment]
Excellent. I should have realized that p10k configuration step that displays icons and asks if I can see them was detecting font features. Thank you for clarifying and for the work you've done building this.

**Comment by romkatv** [comment]
> Thank you for clarifying and for the work you've done building this.

Glad to be of service 😁
