### ISSUE TITLE
Abbreviating dir?

### ISSUE THREAD

**Issue by jovalle** [romkatv/powerlevel10k#482]
`dir` appears to display absolute directory path. This can get quite long when neck-deep in a project. Right prompt elements are then sacrificed in favor of `dir` which we can all agree is relatively insignificant in many cases. Are there plans to support `PROMPT_DIRTRIM` or something similar? How can we abbreviate the `dir`, to 2 levels for example, in zsh?

**Comment by romkatv** [comment]
> `dir` appears to display absolute directory path.

You can configure it this way but it's not the default.

Have you used `p10k configure` to generate your config? Does you directory behave [like this](https://github.com/romkatv/powerlevel10k/blob/master/README.md#current-directory-that-just-works)?

**Comment by jovalle** [comment]
Shortly after posting I noticed the truncation feature. Truncated levels are nice but there's still a sizable min length. Imagine PROMPT_DIRTRIM + truncation. :)

Default size terminal:
![Screenshot from 2020-02-09 22-52-07](https://user-images.githubusercontent.com/47045210/74119819-0684e280-4b8f-11ea-83d8-1dd3fef6fe51.png)
Resized to fit:
![Screenshot from 2020-02-09 22-58-23](https://user-images.githubusercontent.com/47045210/74119991-b78b7d00-4b8f-11ea-9bda-d62ff6a034d5.png)

Notice Right elements are first to go. Would seek Left elements to have similar behavior, lesser priority in some cases or some form of word wrapping?

**Comment by jovalle** [comment]
Since kubectl element only appears when typing kubectl, perhaps it can temporarily overlap any elements, specifically Left elements?

**Comment by romkatv** [comment]
It's technically possible to implement shortening/hiding priorities for segments but it's quite a bit of work and the demand for this feature is low.

If you lose right prompt often, consider running `p10k configure` and disabling decorative elements.

From the FAQ:

> If you value horizontal space or prefer minimalist aesthetics, disable *current time* and use *few icons*. The extra icons enabled by the *many icons* option primarily serve decorative function. Informative icons, such as background job indicator, will be shown either way.

Disabling left frame and *fluent mode* (`on` and `at`) will save a bit more space. In the screenshot you would recover about half of screen real estate without losing information.

You can also customize how kubernetes context is displayed so that it both takes less space and gets easier to recognize in prompt. The relevant configuration options and documentation are in your `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/d37cf22a9ccdf5134247ac3200f80c18f9209321/config/p10k-lean.zsh#L931-L1008

**Comment by romkatv** [comment]
> Shortly after posting I noticed the truncation feature.

Closing then.

**Comment by jovalle** [comment]
@romkatv, fair enough. Will look to optimize on my end and perhaps contribute once I figure out zsh. Thanks for taking the time and building this theme. It's generally been a godsend.
