### ISSUE TITLE
Prompt character (pure) not showing in urxvt

### ISSUE THREAD

**Issue by vaskark** [romkatv/powerlevel10k#483]
I'm currently using the pure version of p10k in urxvt and the prompt character (>) does not show up. It _is_ rendered in other terminals like st and kitty. I've gone into ~/.p10k.zsh and changed the character to `\u+F641` (from the mdi section of my nerd font) and it works. But the next time I run `p10k configure` this will be overwritten again and I'll be back to having the same problem.

Any advice?
Thanks.

**Comment by romkatv** [comment]
> Any advice?

I don't use urxvt myself so I wouldn't know how to fix it. Ask on urxvt forums? The problem isn't specific to powerlevel10k. You can reproduce it with a simple `echo` or `cat` command to test whether the character is displayed or not.

Here, try these. Once you get them to work in urxvt (I know it's possible), your problem is solved.

```zsh
echo -e '\u276F'
echo '❯`
```

**Comment by romkatv** [comment]
Just in case. I suppose you've already tried this? https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by vaskark** [comment]
@romkatv 

I installed the recommended fonts and the prompt character is back.
Many thanks.
