### ISSUE TITLE
Home icon not used anymore

### ISSUE THREAD

**Issue by weilbith** [romkatv/powerlevel10k#49]
I have set the options `POWERLEVEL9K_HOME_ICON="\uf07b"` and `POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=""`. But what I get is the closed folder icon and a `~`. I assume both not to be there. How do I make my old configuration working again?

This is my configuration regarding the `dir` segment:
```sh
### Dir Segment
#### Short Path
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_SHORTEN_DELIMITER=".."

#### Colors
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="239"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="15"

POWERLEVEL9K_DIR_HOME_BACKGROUND="239"
POWERLEVEL9K_DIR_HOME_FOREGROUND="15"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="239"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="15"

#### Icons & Separators
POWERLEVEL9K_HOME_ICON="\uf07b"
POWERLEVEL9K_DIR_PATH_SEPARATOR_ICON="\uE0BB"
POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon 'DIR_PATH_SEPARATOR_ICON') "
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=""
```

**Comment by romkatv** [comment]
> I have set the options POWERLEVEL9K_HOME_ICON="\uf07b"

That's a closed folder icon. You can see it by typing `echo $'\uf07b'`. This icon will be shown wherever you are in your home folder.

> POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=""

This setting will remove `~/` prefix from your path if it there is such prefix. Thus, when you are in `~/foo`, you'll see `foo`. When you are in your home folder, you'll still see `~` because an empty path is confusing.

Does this help?

**Comment by weilbith** [comment]
Oh damn this is embarassing. Wtf I've done here. Thank you!!!
