### ISSUE TITLE
Running `emulate -L zsh` before sourcing p10k changes `EXTENDED_GLOB`

### ISSUE THREAD

**Issue by infokiller** [romkatv/powerlevel10k#496]
This is probably just a lack of understanding zsh on my part, but here goes.
I noticed that if I source `powerlevel10k.zsh-theme` in a function with `emulate -L zsh` at the top, the `EXTENDED_GLOB` option is set from to false (if it was set to true).
Minimal zshrc to reproduce:

```zsh 
P10K_DIR='/tmp/powerlevel10k'
if [[ ! -d "${P10K_DIR}" ]]; then
  git clone https://github.com/romkatv/powerlevel10k "${P10K_DIR}"
fi

source "${P10K_DIR}/config/p10k-lean.zsh"

setopt EXTENDED_GLOB
# Will print "extendedglob          on"
set -o | grep extendedglob

() {
  emulate -L zsh
  source "${P10K_DIR}/powerlevel10k.zsh-theme"
}

# Will print "extendedglob          off"
set -o | grep extendedglob
```

My zsh version:
```zsh
❯ zsh --version
zsh 5.7.1 (x86_64-pc-linux-gnu)
```

Is this working as intended?

**Comment by romkatv** [comment]
> Is this working as intended?

Unfortunately, yes.

`powerlevel10k.zsh-theme` needs to unset `prompt_sp` and `prompt_cr` if instant prompt is active or set them if it's inactive. These options must have proper values before the first `precmd`.

When `powerlevel10k.zsh-theme` is sourced with `local_options`, it has two choices:

1. Unset `local_options` and set correct options. This is what's currently being done and it has the side effect you observe. To work around this side effect, you can add `setopt local_options` after sourcing `powerlevel10k.zsh-theme`.
2. Do nothing. This may result in incorrect `prompt_sp` and `prompt_cr` options. If instant prompt is active, it'll even print a scary warning with instructions how to fix the problem.

I don't have a strong preference between these choices. Both are imperfect but both also have solutions/workarounds when their imperfections show up.

Since you've opened an issue due to the current choice, I went ahead and switched from (1) to (2). If someone complains about the warnings, I'll revert back to (1) as it had been working fine for a long time.

P.S.

Why do you source `powerlevel10k.zsh-theme` from a function with `local_options`? It's not bad, I just want to learn your use case.

**Comment by infokiller** [comment]
Thanks for the detailed explanation!
My use case doesn't require me to source p10k from a function that uses local_options. The reason I hit this issue is that I recently added `emulate -L zsh` to all the functions that don't set or depend on global options, because from what I understood this is good practice in zsh. Seems like I was over-aggressive in doing it.

**Comment by romkatv** [comment]
> The reason I hit this issue is that I recently added `emulate -L zsh` to all the functions that don't set or depend on global options, because from what I understood this is good practice in zsh. Seems like I was over-aggressive in doing it.

It *is* a good practice. You need to know which options are in effect at any point where Zsh code is being evaluated. `emulate -L zsh` is one way to do it.

By the way, you can test options like this:

```zsh
[[ -o extended_glob ]] && echo "extended_glob is on"
```

There is also `options` associative array:

```zsh
echo "extended_glob is $options[extended_glob]"
```

**Comment by infokiller** [comment]
Cool, thanks for the tips!
