### ISSUE TITLE
git prompt stuck with old info

### ISSUE THREAD

**Issue by tdclaritum** [romkatv/powerlevel10k#512]
At some point the git prompt will stuck with old info and doesn't update to the current branch. On the left side of the image the git prompt is grey and is showing older branch (not the current one). The right side shows up to date info.

To reproduce it you need to checkout a branch and after this try to merge with another branch. There should be conflicts that required manual fix - do not fix them. After this step just abort the merge process 

Steps to reproduce:
```
> git checkout MY_BRANCH
> git merge OTHER_BRNACH
> # There should be conflicts, so still in the merge process 
> # At this point the git status become grey
> git merge --abort
> # git status is still grey; EXPECTED: to be green as before
> git checkout OTHER_BRANCH
> # git status keep showing MY_BRANCH in grey; EXPECTED: to show OTHER_BRANCH and to be green
```

I'm on commit fc404a2d8a7899ada22c19548f5560274f811307 a bit out of date

![image](https://user-images.githubusercontent.com/60884107/74834008-7f640700-5312-11ea-9046-a68e0b123736.png)

**Comment by romkatv** [comment]
> I'm on commit [fc404a2](https://github.com/romkatv/powerlevel10k/commit/fc404a2d8a7899ada22c19548f5560274f811307) a bit out of date

Have you tried it with the latest version of powerlevel10k?

**Comment by tdclaritum** [comment]
Thank you for the fast reply. I just have upgraded to the latest master and everything works correctly with it.
I will close this ticket and if it happens again will try on a clean git repo like you have suggested.

**Comment by romkatv** [comment]
Glad it's working for you.

When you encounter an issue, please update. It might already be fixed. Powerlevel10k doesn't break backward compatibility with configs, so updates are painless. They'll only fix bugs and occasionally make your prompt faster. There are also many new features but they won't be turned on automatically. If you want to turn them on, run `p10k configure`. Since it's been a while since you've last update powerlevel10k, you might want to scroll through https://github.com/romkatv/powerlevel10k#features.
