### ISSUE TITLE
Init script enabling completion loaded only once

### ISSUE THREAD

**Issue by OCamlPro-mattiasdrp** [romkatv/powerlevel10k#516]
**Describe the bug**

I installed opam and it added a line in my .zshrc for terminal completion. As long as I don't have this theme enabled the completion works at each terminal start up. As soon as I enable this them, the init script it is executed only at the first startup and if I close and start my terminal the completion doesn't work unless I source my .zshrc.

If I comment the line:
`# ZSH_THEME=powerlevel10k/powerlevel10k`
and uncomment the line:
`ZSH_THEME="robbyrussell"`

My script will be loaded at each startup and the completion will always work

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Install opam by running the following command: `sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)`
2. `opam init` (may take some time but it's easy to delete it afterwards, just `rm -rf .opam`)
3. The following line should be present in your .zshrc:
`test -r ~/.opam/opam-init/init.zsh && . ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true`
If not, add it manually at the end of the file
4. Close terminal, start it. When writing `opam` then hitting tab you should have this:

![image](https://user-images.githubusercontent.com/5543639/74952916-3dfe5500-5401-11ea-9a2d-eca49bcfc0b1.png)

5. Everytime you close and open the terminal the completion will work
6. Install powerlevel10k and change your theme to it
7. Close and open terminal multiple times trying to complete with tab after `opam` it will give you the files in your directory instead of the possible commands
8. If you run `source .zshrc` the completion will work again

**Expected behavior**
Completing should show the possible subcommands. Enabling theme

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 19.10
 - Latest ohmyzsh Update?: Yes/No
 - ZSH Version: 5.7.1

**Comment by romkatv** [comment]
Powerlevel10k doesn't do anything with completions or opam, so filing an issue against either oh-my-zsh (it supposedly calls compinit and stuff) or opam (it supposedly provides completions) is more appropriate.

Try moving the opam line in `~/.zshrc` the top/bottom of the file. Maybe it'll help.

**Comment by OCamlPro-mattiasdrp** [comment]
I already tried moving it to the top and it didn't help. And this behaviour happens only when enabling the theme so I know it's just a theme but it doesn't explain why it behaves like this.

**Comment by romkatv** [comment]
Alright, I've created a VM with Ubuntu 19.04 on DigitalOcean and reproduced this problem. The culprit is a bug in `~/.opam/opam-init/init.zsh`. This script doesn't install completions if file descriptor 0 is not a tty. This check makes no sense. If they are trying to save time, they should be checking whether shell is interactive.

Bad:

```zsh
[ -t 0]
```

Good:

```zsh
[[ -o interactive ]]
```

You can work around this bug by redirecting file descriptor 0 when sourcing `~/.opam/opam-init/init.zsh`.

```zsh
test -r ~/.opam/opam-init/init.zsh && . ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null <$TTY || true
```

*NOTE*: There is `<$TTY` close to the end of the command.

You can also replace this weird-looking contraption with normal Zsh code:

```zsh
[[ ! -r ~/.opam/opam-init/init.zsh ]] || source ~/.opam/opam-init/init.zsh <$TTY
```

Note that this script installs completions in unorthodox ways, so it must be called *after* `compinit`. In your config `compinit` is called by Oh My Zsh when you `source $ZSH/oh-my-zsh.sh`, so you need to have the opam line after that.

Why is opam's bug makes itself known only when you are using Powerlevel10k? Because of [instant prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-enable-instant-prompt):

> When instant prompt is enabled, for the duration of Zsh initialization standard input is redirected to `/dev/null`...

For the reference, here's the complete command that installs everything on a fresh Ubununtu 19.10. When zsh prompt shows up, `opam` completions work correctly.

```zsh
ssh -t root@xxx.xxx.xxx.xxx '
set -Eeuo pipefail
apt update
apt install -y git curl zsh make m4 gcc unzip bubblewrap
git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)" <<<""
opam init <<<""
>~/.zshrc cat <<\END
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
ZSH=~/.oh-my-zsh
ZSH_CUSTOM=$ZSH/custom
ZSH_THEME=powerlevel10k/powerlevel10k
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
source $ZSH/oh-my-zsh.sh
[[ ! -r ~/.opam/opam-init/init.zsh ]] || source ~/.opam/opam-init/init.zsh <$TTY
END
exec zsh -i'
```

**Comment by OCamlPro-mattiasdrp** [comment]
Thanks a lot, will tell them to modify their script ;-)
