### ISSUE TITLE
direnv isn't working

### ISSUE THREAD

**Issue by jtrees** [romkatv/powerlevel10k#523]
Not sure if I'm doing something wrong here but adding `direnv` to my prompt has no effect.

#### My setup

- pure theme
- direnv 2.15.0

#### Notes

`direnv` is working fine. I have the following line in my `.zshrc`:

```sh
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook zsh)"
```

Adding the respective segment to my `p10k.zsh` has no effect though, regardless of whether I'm in a dir with an `.envrc` or not.

Here is an example of me trying it on the right side. It doesn't work on the left for me either though.

```sh
# Right prompt segments.
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  # =========================[ Line #1 ]=========================
  direnv
  time                      # current time
  # =========================[ Line #2 ]=========================
  newline                   # \n
)
```

**Comment by romkatv** [comment]
Pure style is an emulation of Pure theme. Pure has no icons next to segments, so icons are turned off globally in your config. You can find the following line in `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=           # no segment icons
```

So you don't get to see a segment icon for `direnv`. Since `direnv` has no content other than the icon, you see nothing.

While you can modify a config based on Pure style to achieve what you want, it's much better to use Lean style instead. This style isn't intentionally crippled to match limited functionality of Pure. It's better out of the box and it's meant to be easily customized.

**Comment by jtrees** [comment]
Thanks! Got it working and will consider switching to lean style.

**Comment by romkatv** [comment]
> will consider switching to lean style.

It's easier than it sounds. You can configure it in the configuration wizard to look quite similar to Pure. Also this might be helpful: https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-the-best-prompt-style-in-the-configuration-wizard.
