### ISSUE TITLE
Installing fonts doesn't enable all glyphs

### ISSUE THREAD

**Issue by cinnamennen** [romkatv/powerlevel10k#526]
*Might be related to #525*

When trying to run `p10k configure` in iTerm, none of the glyphs are appearing. Checking the box in iTerm `Use built-in Powerline glyphs` makes the diamond appear (albeit larger than I'm guessing it should be), but the other checks fail. `MesloLGS NF` is showing as the selected font in iTerm, and FontBook is indicating that the fonts are successfully installed. 

Running on:
* Catalina 10.15.3
* iTerm 3.3.9
* zsh 5.8

**Comment by romkatv** [comment]
Doesn't sound related. Usually you get this effect if you don't restart iTerm2 after installing MesloLGS NF through the configuration wizard.

Try the following:

1. Manually change font in iTerm2 settings to `Monaco`.
2. Update powerlevel10k to the latest version.
3. Restart Zsh (note that `source ~/.zshrc` does **not** restart Zsh).
4. Run `p10k configure`.
5. Agree to install font.
6. **Restart iTerm2.**

**Comment by cinnamennen** [comment]
https://imgur.com/a/5ebl2Uz

**Comment by romkatv** [comment]
Thanks for that Gif. It removes some paranoia although not all of it.

Can you try to debug it a little bit on your own? It's incredibly inefficient to perform simple checks by my writing instructions, your executing them, my not trusting that you executed them correctly, your posting a Gif showing that you did, my not trusting that `zinit update` actually updates anything, etc.

- Does the font appear in the font book?
- Does it say it has 6406 glyphs?
- Does it work in other apps?
- Does bold font work in iTerm2? Italic? Bold-Italic?
- Does any Nerd Font work in iTerm2?
- Does it work if you manually switch to Monaco and then manually to Meslo?
- Does it work if you disable session restoration in iTerm2?
- Do ascii characters actually look like Meslo when the font in iTerm2 is set to Meslo?
- Does it work on another machine?

These are just some ideas of what you could investigate. Since I cannot reproduce this, I have nothing to go on.

**Comment by romkatv** [comment]
> Do ascii characters actually look like Meslo when the font in iTerm2 is set to Meslo?

Answering my own question: In your Gif the font is always Monaco, even at the very end. So the problem is not that some glyphs from Meslo are not displayed, but that iTerm2 uses Monaco instead of Meslo.

I don't know why that happens but I think it might be fixed by opening iTerm2 settings changing font to something that is neither Meslo nor Monaco, restarting iTerm2, opening iTerm2 settings again and changing font to Meslo.

**Comment by cinnamennen** [comment]
You're correct about the font not "actually" installing. After having iterm quit for a while and coming back to it, it just...worked? the font was installed and glyphs were working. Guessing something bad on iterms end?

**Comment by romkatv** [comment]
> Guessing something bad on iterms end?

Dunno. All my attempts to reproduce this have failed.

But I'm glad it's finally working for you.

**Comment by shawnthompson** [comment]
I'm having this problem too.

Running:

* MacMini M1
* MacOS 11.4
* iTerm2 3.4.8
* Oh My ZSH: Pulled latest 2021-05-27
* zsh 5.8 (x86_64-apple-darwin20.0)

The font is installed in my Font book with all the glyphs there. I've tried changing the font in iTerm2 to something else and running the install a few times and I get the same results as @cinnamennen.

I see the diamond but not the lock (\UF023).

The lock is there in my Font Book.

![image](https://user-images.githubusercontent.com/2575266/119837893-f7838a00-bed0-11eb-8119-d27a6edf901c.png)

MacOS 11 has really locked the system down, should the font be install on the system and not per user?

**Comment by shawnthompson** [comment]
I just installed it with no failure on my MacBook Pro Intel running the same MacOS and everything.
