### ISSUE TITLE
Consider using font with ligatures

### ISSUE THREAD

**Issue by aserrallerios** [romkatv/powerlevel10k#530]
Just switched to p10k and it's amazing, but I miss my ligatures. Do you recommend any particular font 100% compatible with p10k with ligatures? Could Meslo possibly be modified with ligatures?

**Comment by romkatv** [comment]
Powerlevel10k should work with any font supported by your terminal. Just make sure to run `p10k configure` after changing fonts.

This font is the closest to the one that powerlevel10k recommends but with ligatures:

- [Meslo LG S Regular Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf).
- [Meslo LG S Bold Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Bold/complete/Meslo%20LG%20S%20Bold%20Nerd%20Font%20Complete.ttf).
- [Meslo LG S Italic Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Italic/complete/Meslo%20LG%20S%20Italic%20Nerd%20Font%20Complete.ttf).
- [Meslo LG S Bold Italic Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Bold-Italic/complete/Meslo%20LG%20S%20Bold%20Italic%20Nerd%20Font%20Complete.ttf).

Install following [the same instructions](https://github.com/romkatv/powerlevel10k#manual-font-installation) as for the recommended font except that the font family is `MesloLGS Nerd Font` instead of `MesloLGS NF`.

The biggest downside of this font (and all other Nerd Fonts with ligatures) is that it's not monospace. Some glyphs from this font are wider than a single column, so they overlap whatever goes to their right. Powerlevel10k inserts extra spaces where necessary to avoid this (that's the reason the configuration wizard asks your whether icons overlap or not) but it's not perfect because those oversized glyphs aren't two columns wide but something like 1.1-1.8 columns wide (depending on a glyph). So spacing may look a bit inconsistent.

Try it, see if you like it. If not, try a different font.

**Comment by jramiresbrito** [comment]
Installed the Meslo LG family but the ligatures still not work. Any changes on this?

**Comment by romkatv** [comment]
> I've installed the Meslo LG family but the ligatures still not working. Any changes on this?

The issue must be either with the terminal or the font. You might have better luck asking for help elsewhere provided that neither the terminal nor the font come from powerlevel10k.

**Comment by nulman** [comment]
@jramiresbrito Did you ever figure out the ligature thing?

**Comment by Francesco146** [comment]
They don't work for me either, I think the font doesn't support them

**Comment by romkatv** [comment]
> They don't work for me either, I think the font doesn't support them

If by "the font" you mean MesloLGS NF, then yes, it doesn't have ligatures. It's a monospace font.

**Comment by Francesco146** [comment]
> > They don't work for me either, I think the font doesn't support them
> 
> If by "the font" you mean MesloLGS NF, then yes, it doesn't have ligatures. It's a monospace font.

I was referring to the font with the ligatures that you linked long ago. as for other people, i installed it but the ligatures seems not to work

**Comment by romkatv** [comment]
I don't use the font myself. I pointed to it because it comes from the same project and its documentation says it has ligatures. As I mentioned above, this isn't even tangentially related to powerlevel10k.
