### ISSUE TITLE
Add custom icon at the start of the line.

### ISSUE THREAD

**Issue by lednhatkhanh** [romkatv/powerlevel10k#533]
Sorry if this is a bad question because I'm new to this theme and the docs overwhelmed me.

So I used `spaceship` before moving to this theme and I had this config in `spaceship`:

```
SPACESHIP_CHAR_SYMBOL='🦁 '
``` 

This will display a lion icon at the start of the line, how can I add something like this in `powerlevel10k`? Thank you.

**Comment by romkatv** [comment]
Could you post a screenshot of your current powerlevel10k prompt? (Note: you can paste images from clipboard or drag-and-drop image files to the edit box on github.)

**Comment by lednhatkhanh** [comment]
![image](https://user-images.githubusercontent.com/9303093/75531184-8f809280-5a46-11ea-866e-7db1ce4e2db7.png)

This is my current prompt together with the config, how can I change the angle icon to the lion icon and still keep the 2 line prompt? Thank you.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and search for `❯` in it. Change the value accordingly.

Before you do that, I highly recommend running `p10k configure` and selecting *Lean* style instead of *Pure*. It looks similar but is much better on many levels. Pure style exists only to make old time Pure Zsh Theme users feel at home.

**Comment by lednhatkhanh** [comment]
Thank you, feels like home now!

**Comment by romkatv** [comment]
Welcome home :wink:
