### ISSUE TITLE
Icon does not fit

### ISSUE THREAD

**Issue by lestofante** [romkatv/powerlevel10k#547]
When i run the configure my icon does NOT fit int the "X" (see screenshot).
I press "N", but looks like nothing happen and the icon still are truncated.

Monospace font will fix, but I really like the bigger icon

![image](https://user-images.githubusercontent.com/1166173/75931372-171a3700-5e75-11ea-9fca-f0dc27c6225a.png)

edit: looks like I have the opposite issue of https://github.com/romkatv/powerlevel10k/issues/180

**Comment by romkatv** [comment]
Which terminal are you using? Is it konsole perchance?

Which icons are truncated? Please attach a screenshot.

**Comment by lestofante** [comment]
Yes I am using konsole; the screenshot is attached at the first post, it is
visible for me, if you confirm is missing for you I'll try to reupload it.

**Comment by romkatv** [comment]
When you choose "there is overlap" in the configuration wizard, which icons in prompt get cut off? Please post a screenshot of prompt.

**Comment by lestofante** [comment]
Yes, the screenshot in the first post is literally taken from that
configuration step. Do you see it?
I tried both Y and N and nothing seems to change.

**Comment by romkatv** [comment]
> Yes, the screenshot in the first post is literally taken from that configuration step. Do you see it?

Yes, I see it.

> I tried both Y and N and nothing seems to change.

Please see my previous comment and please provide the information I've asked for.

**Comment by lestofante** [comment]
The icon is cut off is the distribution logo (Arch in this specific case), all he other icons look good, even if some are double size wide.

![Screenshot_20200306_171620](https://user-images.githubusercontent.com/1166173/76101399-a9821e00-5fce-11ea-8335-3ca82cb9d3fc.png)

**Comment by romkatv** [comment]
Thank you for the screenshot.

This issue is caused by a bug in Konsole that gets triggered when using non-monospace fonts. This is the only terminal with this particular bug. There are several things you can do to mitigate it:

1. Switch to another terminal.
2. Switch to a monospace font.
3. Fix the bug in Konsole.
4. Convince someone else to fix the bug in Konsole.
5. Open `~/.p10k.zsh` and comment out `os_icon`.
6. Open `~/.p10k.zsh` and change `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` as follows (this will add an extra space after the icon):
```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='%B${P9K_CONTENT} '
```
6. Open `~/.p10k.zsh` and change `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` as follows (this will make the icon non-bold):
```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${P9K_CONTENT} '
```

Each of these options in isolation is enough to fix the issue. There is no need to implement more than one option.

Please let me know whether any of these options work for you.

**Comment by lestofante** [comment]
Thanks,
tested both option 6 and 7, both work correctly.  
In case anyone else need it, option 6.  looks better.

I reported the issue to Konsole bug tracker, as I could not find anything about it. https://bugs.kde.org/show_bug.cgi?id=418553

**Comment by romkatv** [comment]
I think I've seen this reported before.

FWIW, your description isn't enough to reproduce the problem. Here's how you can reproduce from any shell and without any dependencies:

```zsh
echo -e '\0357\0214\0203\033[31m '
```

This assumes that the font used by the terminal has an oversized glyph for U+F303. Any other oversized glyph will do.

**Comment by lestofante** [comment]
thanks, I added it.  
  
The search function of bugzilla is quite terrible, i spent like 20minute digging into search term and filtering issue before giving up. If it is duplicate hopefully a kind soul will tag it.

Have a nice weekend!

**Comment by romkatv** [comment]
> Have a nice weekend!

Thanks! Have a great weekend yourself 🎉
