### ISSUE TITLE
Inconsistent behaviour and missing symbols

### ISSUE THREAD

**Issue by debo** [romkatv/powerlevel10k#551]
Hi there as per subject and as you can see in the following picture

![Screenshot 2020-03-06 at 09 14 26](https://user-images.githubusercontent.com/493257/76070009-c47f6e80-5f8b-11ea-92f8-bd8d48210bc1.png)

My icon/symbols seem to change depending by the folder where I'm in and I can't explain myself why, unless, just thinking about it now, one represents GitHub and the other one GitHub EE. Beyond that I also have issues with the missing symbols. I tried all possible POWERLEVEL9K_MODE values documented in the configuration file as well as the one described [here](https://github.com/Powerlevel9k/powerlevel9k#vcs-symbols) but I don't seem to be able to show the awesome complete symbols. I'm sure I'm missing something possibly obvious but what?

I also had a look [here](https://github.com/romkatv/powerlevel10k#does-powerlevel10k-always-render-exactly-the-same-prompt-as-powerlevel9k-given-the-same-config) and follow the suggestion but it makes it slightly worse.

Any help will be really appreciated, thanks.

**Comment by romkatv** [comment]
> My icon/symbols seem to change depending by the folder where I'm

The screenshot at the bottom shows GitHub logo. This means the remote of your current branch is pointing to github.com. You can see the url of the remote with `git config --get remote.origin.url`.

The screenshot at the top shows `git` icon. This means that either there is no remote for the current branch or it's not pointing to github, gitlab or bitbucket. Type `git config --get remote.origin.url` to see where the remote is pointing to.

There are no missing symbols on your screenshots.

Relevant FAQs:

- [What do different symbols in Git status mean?](
    #what-do-different-symbols-in-git-status-mean)
- [How do I change the format of Git status?](#how-do-i-change-the-format-of-git-status)

In general, please refer to Powerlevel10k documentation instead of Powerlevel9k.

**Comment by debo** [comment]
Hi @romkatv thanks for the prompt reply. So ok as I thought the different icon is because one repo points to GitHub and the other points to GitHub Enterprise.

As per the other, I know about the status meaning, however, a colleague of mine who has powerlevel10k installed on this machine has his prompt should the same symbols glyphs shown in the powerlevel9k documentation hence why I was referring to their documentation as well. Do you have an idea of why that would be the case? Thanks a lot for your help.

**Comment by romkatv** [comment]
You can use powerlevel10k with a config for powerlevel9k. Your colleague is likely doing that. You can ask them for their config (ask them to execute `typeset -pm 'POWERLEVEL9K_*'` and send you the output) and use it in place of `~/.p10k.zsh`. If you go this route, you should refer to powerlevel9k documentation. I don't recommend this approach because powerlevel9k configs are restricted to the functionality of powerlevel9k -- a small subset of what powerlevel10k can do. Basically, you'll get a fast powerlevel9k and nothing more.

You can also follow the FAQ I linked to earlier: [How do I change the format of Git status?](#how-do-i-change-the-format-of-git-status). Here's what it says:

> To change the format of Git status, open `~/.p10k.zsh`, search for `my_git_formatter` and edit its
source code.

For example, here's how that exclamation mark comes about:

```zsh
# !42 if have unstaged changes.
(( VCS_STATUS_NUM_UNSTAGED )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
```

You can replace `!` with anything else. For example, you can replace it with the exclamation mark in a circle, like in the screenshot you've posted above.

```zsh
(( VCS_STATUS_NUM_UNSTAGED )) && res+=" ${modified}"$'\uF06A'"${VCS_STATUS_NUM_UNSTAGED}"
```

You can find unicode code points for various circled symbols by going to https://www.nerdfonts.com/cheat-sheet and searching for "circle". Note that circled explanation mark, question mark, plus and arrows may be significantly harder to distinguish than their uncircled variants. If your goal is productivity, it's better to keep the existing Git format.

**Comment by debo** [comment]
Ha! Thanks a lot, that's super useful, I just needed that cheat-sheet then. Thanks thanks thanks.

**Comment by romkatv** [comment]
By the way, you might want to check out how Git status looks in *Lean* style before you start manually customizing.

Closing as I believe you questions have been answered. Please reopen or open another issue if anything doesn't work the way you like.

**Comment by dgdosen** [comment]
FYI - I tried using the unicode substitutions - and the prompt would get repeated in an endless loop...

**Comment by romkatv** [comment]
@dgdosen I don't know what Unicode substitutions are. If you experience problems using or configuring powerlevel10k, please open an issue.

**Comment by dgdosen** [comment]
Nope - I just edited my previous comment.  Want me to throw it in a pull request to the readme?

**Comment by romkatv** [comment]
> FYI - I tried using the unicode substitutions - and the prompt would get repeated in an endless loop...

Could you provide a few more details about what hasn't worked for you? I see that you've reacted with thumbs-down to https://github.com/romkatv/powerlevel10k/issues/551#issuecomment-595695843. What in that comment was not up to your expectations?

> Here's an example of a couple edits that work for me:
> 
> ```
> (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}`echo -e '\uf01a'` ${VCS_STATUS_COMMITS_BEHIND}"
> (( VCS_STATUS_STASHES        )) && res+=" ${clean}`echo -e '\uf01c'` ${VCS_STATUS_STASHES}"
> ```

I highly recommend using `$'\uf01a'` instead of `echo -e '\uf01a'`. It is simpler, shorter and faster.

```zsh
(( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}"$'\uf01a'" ${VCS_STATUS_COMMITS_BEHIND}"
(( VCS_STATUS_STASHES        )) && res+=" ${clean}"$'\uf01c'" ${VCS_STATUS_STASHES}"
```

> I just like the fatter glyphs more than text. It's easier to tell the difference between say, incoming commits and unstaged changes.

No harm in that.

> Want me to throw it in a pull request to the readme?

What would you like to be changed in the readme?

**Comment by dgdosen** [comment]
I voted down because using that suggested unicode replacement didn't work for me... It only works if I use back tics and an echo command - does the other form of string interpolation work for you?

**Comment by romkatv** [comment]
> I voted down because using that suggested unicode replacement didn't work for me...

I'm sorry to hear that.

I'm not aware of any zsh version where that syntax wouldn't work. Would you mind literally copy-pasting that code and trying it? I realize that the instructions aren't very exact, so I'll try to clarify them.

1. Run `p10k configure` and select prompt options that you like.
2. Open `~/.p10k.zsh` in a text editor.
3. Search for the following line:
```zsh
(( VCS_STATUS_NUM_UNSTAGED )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
```
4. Delete that line and put this in its place:
```zsh
(( VCS_STATUS_NUM_UNSTAGED )) && res+=" ${modified}"$'\uF06A'"${VCS_STATUS_NUM_UNSTAGED}"
```
5. Save `~/.p10k.zsh` and exit the text editor.
6. Type `exec zsh`.

> does the other form of string interpolation work for you?

Of course. I'm sure it'll work for you too. Just make sure to copy-paste the code. Trying to type it by hand often leads to errors.

**Comment by romkatv** [comment]
@dgdosen Friendly ping.

User support is time confusing. Issues with clear resolutions are valuable assets as they allow future users to help themselves. To the best of my knowledge, your comment incorrectly states that the resolution on this issue doesn't work and suggests an inferior alternative. It has turned an asset into a liability. I'd appreciate if you work with me to reconcile this problem.
