### ISSUE TITLE
Color render issue

### ISSUE THREAD

**Issue by GeekArthur** [romkatv/powerlevel10k#558]
As the GIF shows below, the color render doesn't work well if I press enter key quickly, I have to press enter key slowly to make it work, seems like the new color (yellow) is rendered on top of the background color (grey) every time, wonder if we have some workarounds to fix this or probably do some configurations to eliminate the background color?

![Kapture 2020-03-09 at 12 33 37](https://user-images.githubusercontent.com/15131537/76236034-6d370380-6202-11ea-8fe2-1f3d5bd46052.gif)

**Comment by romkatv** [comment]
This is working as expected. I've added an entry to the FAQ: https://github.com/romkatv/powerlevel10k#why-does-git-status-sometimes-appear-grey-and-then-gets-colored-after-a-short-period-of-time.

**Comment by romkatv** [comment]
Just to confirm that Git status is slow. Could post the output of the following command?

```zsh
time ( repeat 10; do git describe --tags --exact-match; git status; done ) &>/dev/null
```

**Comment by GeekArthur** [comment]
```
( repeat 10; do; git describe --tags --exact-match; git status; done; ) &>   1.51s user 18.34s system 324% cpu 6.114 total
```
@romkatv I think should be git status slowness issue, repeatedly run the group of git commands takes ~ 6s

**Comment by romkatv** [comment]
Thanks for the benchmark results.

So powerlevel10k is indeed working as expected. Blocking prompt for 600ms after every command would be quite awful, so powerlevel10k turns on asynchronous mode for Git status. Grey color is an indication for you so that you know that information may be stale. (It's actually possible to disable this greying-out logic through configuration changes but it's not a good idea as you'll have no idea whether data in prompt is up-to-date or not.)

**Comment by GeekArthur** [comment]
@romkatv That makes sense, thanks for your explanation!
