### ISSUE TITLE
idea: show execution time of the currently running command

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#564]
This is just an idea, I don't know if it's even possible, but want to hear your perspective 🙂 

I use transient prompt and I like it this way, but as a result I cannot know how long the currently running command is already running. I will know the total execution time after the command finishes, but while it's running I'm completely blind.

I can think of two ways to do this, but feel free to come up with something cleverer 🙂 

1. Maybe transient prompt can treat the prompt of the currently running unfinished command specially, and let it keep the time of when the command was started (so that I can scroll myself up, and see when the command started, and calculate the run time myself).

2. While command is running, show at the very bottom a line "Execution time: 5s", which would always stay in the bottom, below all output that is currently being produced, and it would update every second.

```
$ i=0; while (( i < 10 )); do (( i++ )); echo "tick: $i"; sleep 1s; done
tick: 1
tick: 2
tick: 3
Execution time: 3s
```

```
$ i=0; while (( i < 10 )); do (( i++ )); echo "tick: $i"; sleep 1s; done
tick: 1
tick: 2
tick: 3
tick: 4
Execution time: 4s
```

```
$ i=0; while (( i < 10 )); do (( i++ )); echo "tick: $i"; sleep 1s; done
tick: 1
tick: 2
tick: 3
tick: 4
tick: 5
Execution time: 5s
```

**Comment by romkatv** [comment]
> Maybe transient prompt can treat the prompt of the currently running unfinished command specially...

This is not possible. The moment you type `some-command` and hit ENTER, `some-command` takes over. It can do absolutely anything with the terminal. Think of commands such as `vim`, `tmux` or `less`. When the command completes, it's impossible to find and/or modify the previous prompt. The last chance to modify prompt is in `preexec` -- right before `some-command` starts executing. That's where transient prompt currently kicks in. There is a bit more info in the FAQ: https://github.com/romkatv/powerlevel10k/blob/master/README.md#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them.

What you can do is display the start time of every command in transient prompt.

Like this:

```zsh
13:50:17 ❯ foo
13:52:43 ❯ bar
█
```

Or like this:

```zsh
❯ foo               13:50:17
❯ bar               13:52:43
█
```

Here `bar` is still running. By seeing the start time in the last prompt you'll be able to calculate for how long the command has been running.

I believe you already know how to configure transient prompt this way. Let me know if not.

Alternatively (or in addition) you can display the start time of a command in the terminal title.

```zsh
# When a command is running, display it in the terminal title.
function _z4h-set-term-title-preexec() {
  emulate -L zsh
  print -rn -- $'\e]0;'${(%):-%*: }${(V)1}$'\a' >$TTY
}
# When no command is running, display the current directory in the terminal title.
function _z4h-set-term-title-precmd() {
  emulate -L zsh
  print -rn -- $'\e]0;'${(V%):-"%~"}$'\a' >$TTY
}
autoload -Uz add-zsh-hook
add-zsh-hook preexec _z4h-set-term-title-preexec
add-zsh-hook precmd _z4h-set-term-title-precmd
_z4h-set-term-title-precmd
```

I've copied these lines from [zsh4humans](https://github.com/romkatv/zsh4humans/blob/master/.zshrc) and added `${(%):-%*: }`.

> While command is running, show at the very bottom a line "Execution time: 5s"

This isn't possible in general. Think again of commands such as `vim`, `tmux` or `less` that take over the whole terminal rather than append characters at the end.

**Comment by maximbaz** [comment]
Thanks! Your explanation makes sense, and I actually like the idea with terminal title very much!

**Comment by billywitherspoon** [comment]
More explanation of a possible solution [here](https://github.com/romkatv/powerlevel10k/issues/917#issuecomment-664791542)
