### ISSUE TITLE
[question] last commit message near git branch name

### ISSUE THREAD

**Issue by k03mad** [romkatv/powerlevel10k#578]
Hello,

I've tried to find some variable with current branch commit message, but fails.

So I've just added after this line:
https://github.com/romkatv/powerlevel10k/blob/758affe574a9006fd45dd9c6470d9340a2876dda/config/p10k-lean.zsh#L404
```bash
res+=" ($(git log --oneline --format=%B -n 1 HEAD | head -n 1))"
```

Seems it is not legit, although it works :)
Which is the correct way?

**Comment by romkatv** [comment]
That should work. You can make it a bit faster by using the following method for retrieving last commit's subject:

```zsh
git log -n1 --format=%s
```

And to use it:

```zsh
local commit_subj
if commit_subj=$(git log -n1 --format=%s 2>/dev/null); then
  if [[ -n $commit_subj ]]; then
    res+=" ${meta}(${commit_subj//\%/%%})"
  else
    res+=" ${meta}[no message]"
  fi
fi
```

You'll definitely want to escape percents like in the code snippet above. Setting colors is also a good idea. Otherwise commit message will be printed with the color of the last element added to `res`. Could be great, yellow, red, etc. Quite confusing.

You might want to change the presentation of empty commit subjects. Tweaking colors could also lead to better results. E.g., you might want to drop the parentheses, or display the message and the parentheses in different colors.

Note that this will slow down prompt quite a bit. On Linux you should expect slowdown somewhere between 20% and 50%. On other systems the slowdown will be higher. This is solely due to invoking `git`. The formatting code runs instantly in comparison.

**Comment by k03mad** [comment]
Thank you! Works like a charm

**Comment by romkatv** [comment]
Thanks for the confirmation!
