### ISSUE TITLE
Cancel autocomplete menus with Escape key

### ISSUE THREAD

**Issue by areographe** [romkatv/powerlevel10k#593]
just switched to p10k and everything is working perfectly. just one thing: when using autocomplete or autocomplete search (ctrl+R), sometimes i want to just cancel it and get an empty prompt again.

i have
```
bindkey '\e' send-break
```
in my .zshrc, which works, but i was wondering if there is a cleaner way to achieve this. cheers

**Comment by romkatv** [comment]
Do you believe the answer to this question is dependent on the use of powerlevel10k? If so, why?

The following answer doesn't depend on powerlevel10k. By default Ctrl-G is bound to `send-break`, so you can terminate zsh widgets with that. You can also use Ctrl-C. Binding the Esc key is unusual because many standard keybindings start with Esc. The binding for Esc will make it more difficult to use those other bindings (you must be quick or your command line will disappear in the void!) and will also introduce a delay when you do want to use just Esc with no followup keys.

**Comment by areographe** [comment]
that's fair enough, this is not actually related to my use of p10k after all! my apologies for taking up your time. keep up the good work. thanks
