### ISSUE TITLE
feature request: make configure reuse last configuration

### ISSUE THREAD

**Issue by clog-rocks** [romkatv/powerlevel10k#612]
After updating `p10k` I want to see if configuration file generated by `p10k configure` has changed. Be it adding new options, new segments or other improvements. But I don't want to change my general configuration: lean or not, no. of colors, etc.

`.p10k.zsh` already contains answers given by user. Could there be less interactive mode, say `p10k configure --reuse` or `p10k configure --no-interactive` which would use answers stored in existing configuration file.

What are your thoughts @romkatv ?

Also, sometimes `configure` asks if font should be updated. Is there a way to check if there is an updated font version available?

Thanks!

**Comment by romkatv** [comment]
The list of options and even the meaning of answers in the configuration wizard can change when you update powerlevel10k. Your favorite style may disappear or get renamed. This makes it difficult to transfer your previous choices.

> Also, sometimes `configure` asks if font should be updated.

This happens when your current font isn't `MesloLGS NF` or when I genuinely push a new version of this font. The latter has happened only once so far. I don't intend to update the font often.

**Comment by romkatv** [comment]
I don't think I'll work on this in the near future, so I'll close the issue.

**Comment by clog-rocks** [comment]
Thanks for your answers, it makes sense.
