### ISSUE TITLE
Instant prompt for custom prompt element reports incorrect screen size in first run

### ISSUE THREAD

**Issue by hktonylee** [romkatv/powerlevel10k#614]
# Problem
If I make some custom element for the prompt, and when the instant prompt is enabled, I cannot get the correct screen size by using `tput cols` in the first run.

Example code:

```zsh
prompt_my_separator() {
  local length=$(($(tput cols) - 4))
  local text=$(yes '─' | head -$length | tr -d '\n')
  p10k segment -t " $text"
}

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  my_separator
  newline
  dir
  vcs
)
```

`tput cols` will always report 80 when first run. But it becomes correct after first run.

**Comment by romkatv** [comment]
Try putting `tput cols` at the very top of your `~/.zshrc` and open a new terminal. What do you see?

**Comment by romkatv** [comment]
If you want to have a line above prompt, you can do it with these parameters:

```zsh
typeset -g POWERLEVEL9K_SHOW_RULER=true
typeset -g POWERLEVEL9K_RULER_CHAR='─'
typeset -g POWERLEVEL9K_RULER_FOREGROUND=240
```

This will be 1000+ times faster and will respect `POWERLEVEL9K_TRANSIENT_PROMPT=always` if you set it.

You can also try these alternative values for `POWERLEVEL9K_RULER_CHAR`: `'·'` or `'▁'`.

Note that ruler isn't very popular in powerlevel10k because *prompt connection* serves the same need while saving a line. Try running `p10k configure`, selecting two-line prompt and seeing how different prompt connections look like.

**Comment by hktonylee** [comment]
> `tput cols`

It is 160 :)

**Comment by hktonylee** [comment]
> If you want to have a line above prompt, you can do it with these parameters:
> 
> ```shell
> typeset -g POWERLEVEL9K_SHOW_RULER=true
> typeset -g POWERLEVEL9K_RULER_CHAR='─'
> typeset -g POWERLEVEL9K_RULER_FOREGROUND=240
> ```
> 
> This will be 1000+ times faster and will respect `POWERLEVEL9K_TRANSIENT_PROMPT=always` if you set it.
> 
> You can also try these alternative values for `POWERLEVEL9K_RULER_CHAR`: `'·'` or `'▁'`.
> 
> Note that ruler isn't very popular in powerlevel10k because _prompt connection_ serves the same need while saving a line. Try running `p10k configure`, selecting two-line prompt and seeing how different prompt connections look like.

Thanks for your suggestion! Actually it works flawlessly :) This already fixes my problem. Please resolve this issue if you think there is no need to solve this `tput cols` problem.

**Comment by romkatv** [comment]
Glad to hear it's working for you. Powerlevel10k has no means of affecting `tput`. It's not even a zsh builtin, it's an external command. If `tput` gives you incorrect value in some circumstances, it's almost certainly a bug in the terminal you are using. This wouldn't be something out of the ordinary. All terminals based on VTE (this is *so many* terminals!) or term.js have bugs of this sort. Powerlevel10k has implements several workarounds for these bugs so that it can find out the right terminal dimensions even when things like `tput` lie. That's why the built-in ruler works.
