### ISSUE TITLE
Different prompt in MC

### ISSUE THREAD

**Issue by maver1ck** [romkatv/powerlevel10k#619]
Hi,
Is it possible to set different prompt in mc ?

Right now it looks ugly. Right elements are moved to left.

![image](https://user-images.githubusercontent.com/4006010/78836895-492e3400-79f3-11ea-87f9-8d7be926f362.png)

**Comment by romkatv** [comment]
> Is it possible to set different prompt in mc ?

I really don't know. If you know how to do that, please send a PR.

**Comment by maver1ck** [comment]
@romkatv 
Why you close this issue ?
It's not solved. And I think this is kind of bug where prompt is buggy in mc.

**Comment by maver1ck** [comment]
Workaround for this is (at the end of .zshrc)
```
if ps $PPID |grep mc; then                                                                                                                                                 typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()                                                                                                                   fi   
```

**Comment by romkatv** [comment]
> @romkatv
> Why you close this issue ?

This issue is not specific to powerlevel10k. If mc cannot display right prompt in zsh, you might want to open an issue against mc.

I've closed this issue because I don't intend to work it. I only keep open issues for things I plan to do.

> It's not solved. And I think this is kind of bug where prompt is buggy in mc.

It's fair to say that mc doesn't work well with zsh with right prompt. Whether it's a bug in zsh or mc, I cannot tell.
