### ISSUE TITLE
Gitstatus - commits behind the remote

### ISSUE THREAD

**Issue by schmas** [romkatv/powerlevel10k#653]
Hi,

This is more a doubt then an issue.

Should gitstatus show if there are commits at remote branch if are not in my local branch without doing an `git fetch`? I think that used to do that.

Example:
I enter a directory that is a git repo on a branch.
I know that there are new commits at that remote branch.
But the status at my powerlevel10k doesn't change.
Only after I do a `git fetch` it shows a green `⇣1`.

If I'm not mistaken, it used to show a blue `⇣1`, I didn't need to do a fetch.

There is any configuration to enable/check that?
I've enabled the `GITSTATUS_ENABLE_LOGGING=1` but there isn't any error.

Thank you.

**Comment by romkatv** [comment]
> If I'm not mistaken, it used to show a blue `⇣1`, I didn't need to do a fetch.

No, there has never been a feature like that in powerlevel10k. To my knowledge, the only Zsh theme that does this is Pure.

This feature doesn't belong in a theme. If you want to automatically call `git fetch` in the background, you can do this separately. You have the freedom to decide what exactly to fetch, how often and when. Powerlevel10k will display info but it's not its job to produce the info in the first place.

**Comment by schmas** [comment]
Thanks. You are right.
Before using powerlevel10k I was using `sindresorhus/pure` which as you mention has a feature like that and was really helpful.

Thanks for the reply.

**Comment by wadkar** [comment]
Ah, yes - I heavily used pure and now I see similar prompt but p10k doesn't "autofetch". Any suggestions/links on how to `git fetch` "reasonably regularly"?

**Comment by romkatv** [comment]
@wadkar Are you asking for guidance on the usage of `git fetch`? It's not the best place for it. You can `git fetch` as often as you like. If you want it to happen when you `cd` into a repo, or every 5 minutes, or whatever, go ahead and do it. The job of prompt is to show state, not to change it.

**Comment by wadkar** [comment]
I am sorry @romkatv - I didn't mean to ask you for supporting this in `p10k`. I was wondering if @schmas or anyone else figured a way that plays nicely with git_status. Or do we just make a copy pasta from `[sindresorhus/pure](https://github.com/sindresorhus/pure/blob/c42bd354943ba4cf2da3ecf493fca4fef0b2722c/pure.zsh#L296)` repository.

Thank you for making it pretty clear that `git_status` does not and probably will never support async git fetch so our prompts will magically do a `git fetch` in the background and change the prompt on pressing enter. Those who want that functionality can switch back to the original pure prompt. Do I have that right?

**Comment by romkatv** [comment]
> Thank you for making it pretty clear that `git_status` does not and probably will never support async git fetch so our prompts will magically do a `git fetch` in the background and change the prompt on pressing enter.

If by `git_status` you mean Powerlevel10k, then yes, you can rest assured that Powerlevel10k is not going to change the state of your Git repositories.

> Those who want that functionality can switch back to the original pure prompt. Do I have that right?

No, you don't have it right. I'm surprised my words could even be interpreted that way.

If you want to invoke `git fetch` every time you press enter, just implement that. It's only a few lines of zsh and this logic is orthogonal to prompt. If you want `git fetch` every 5 minutes, or every time you `cd`, or once a day for all your repos, or more frequent for small repos than for bigger ones, you can do that too. If you want this functionality but don't know how to implement it, ask someone for help. This isn't something you should expect your prompt to do because prompt's job is to *show* state, not to *change* it. I know that Pure does it but if I thought that Pure was perfect I'd be using it myself.

**Comment by wadkar** [comment]
Ah, perhaps I did misunderstood you. My apologies in that case.

I have played with basics of `zle_` functions and I can ask in #zsh for help. The trick, as you rightfully alluded to in your comment, is the "reasonably regularly" part I mentioned in my first comment in this thread. There is no one answer, let alone a right answer to it. So it's best not to go down that rabbit hole. Even [GitHub Desktop users](https://github.com/desktop/desktop/issues/1128#issuecomment-628668920) are asking to disable this feature it seems.

**Comment by romkatv** [comment]
My personal opinion is that it’s best to never issue `git fetch` in the background. I don’t think I’ve ever worked on a project where automatic fetching  would have been useful. This isn’t to say you should not do it.

**Comment by wadkar** [comment]
Re: project where automatic fetching is useful

It's useful, for example when you're running scripts, say ansible playbooks, and your colleagues have fixed things on remote. If you aren't prompted by your prompt (haha) that you're not up to date with your colleagues remote work, you run the risk of running outdated scripts and breaking things.

Yes, yes, I know the answer is to add a custom zle_/background task that'll fetch that repo in the background. And yes, I agree - p10k isn't suited for it. But it might be useful, perhaps for the sake of posterity, to provide future generations a quick example of such functionality.

Personally, I believe this is a classic "it depends" Software Engineering (ambiguous requirements to be precise) issue and no one solution exists. We can simply provide bunch of tricks that people can choose and apply for their use case.

**Comment by romkatv** [comment]
> It's useful, for example when you're running scripts, say ansible playbooks, and your colleagues have fixed things on remote.

If your way of finding out about changes is via shell prompt, then you'll only know the scripts have changed if you `cd` into the scripts directory. Wouldn't you want to know regardless of whether you `cd` or not? What if you run these scripts without `cd`? Wouldn't it be better to run a cron job that polls the repo and notifies you via some OS mechanism (banner of some sort) or perhaps email? Or, alternatively, add "git fetch every 5 minutes" logic to the scripts themselves so that they alert you when you are running stale scripts? (This assumes you are running them interactively.) What exactly you implement depends on requirements but it's hard to see any requirements that would suggest doing what Pure does.

> But it might be useful, perhaps for the sake of posterity, to provide future generations a quick example of such functionality.

Then go ahead and implement it. (I don't think it would be useful but you don't need to convince me.)

> Personally, I believe this is a classic "it depends" Software Engineering

I'm not seeing it yet.
