### ISSUE TITLE
Can't show live time

### ISSUE THREAD

**Issue by subnut** [romkatv/powerlevel10k#666]
Heya'll. Great work!! Only one small issue.....
I am trying to get a live clock in my prompt. Something like [this](https://askubuntu.com/a/360172)
I currently am using p10k from oh-my-zsh

I have tried doing it with some other oh-my-zsh theme installed, and it works. Curiously, `PROMPT="%D[%H:%M:%S]$PROMPT"` seems to change the prompt in other themes, but seems to do NOTHING in case of powerlevel10k..... `echo $PROMPT` gives the same output before and after running the above code. It seems as if p10k is refreshing the $PROMPT in some way. Is my hypothesis correct?

Also... any tips about how i can achieve the live clock in a two-lined prompt? (see my prompt below. it's double-lined) I would absolutely LOVE it 😍

Thanks for your help guys. Great work, btw..... making the terminals of us n00bs beautiful. Thanks again.

My prompt..... 
![image](https://user-images.githubusercontent.com/56714626/80344185-c7f4ef00-8884-11ea-85cc-dcd25949f93f.png)

**Comment by romkatv** [comment]
To make current time in powerlevel10k update in real time, add the following parameter to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true
```

This parameter is experimental because it has unwanted side effects that are impossible to eliminate. The solution from https://askubuntu.com/a/360172 has *even more* unwanted side effects.

In general, it's much better to enable clock in your OS or Desktop Environment. Current time isn't a property of zsh session (unlike current directory, presence of background jobs or status of the last command), so it doesn't make sense to put it in prompt.

**Comment by subnut** [comment]
Wow!! Really didn't expect such a fast reply!!
Thanks. It works just as I wanted!

BTW, just curious... 
> This parameter is experimental because it has unwanted side effects that are impossible to eliminate. 
what kind of side-effects?

>The solution from https://askubuntu.com/a/360172 has **even more** unwanted side effects.
This makes me even more curious...... how so?

Thanks again for your solution. You really are awesome!

**Comment by romkatv** [comment]
> what kind of side-effects?

Various. None will delete your files, they are just annoying. I'm sorry that I don't elaborate further. I'm very busy.

> This makes me even more curious...... how so?

Ditto.

> Is it correct? Just curious.

If you use powerlevel10k to set your prompt, then powerlevel10k sets your prompt.
