### ISSUE TITLE
second line of prompt shows as space in 10k vs right-triangle in 9k

### ISSUE THREAD

**Issue by mr-salty** [romkatv/powerlevel10k#67]
I have `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs newline background_jobs root_indicator)`

in 9k, this always shows a right-triangle on the second line, but in 10k it only shows up if the background_jobs or root_indicator elements are present:

(10k on left, 9k on right)

![10k](https://user-images.githubusercontent.com/7683836/57507492-f7ee5f80-72cc-11e9-9a1e-e37594f6350e.png)

**Comment by romkatv** [comment]
Thanks for the high-quality bug report.

I've fixed this issue in https://github.com/romkatv/powerlevel10k/commit/154bc2e1ff9a435f8686962d5a8e88e6e63ff453.

Powerlevel10k aims for compatibility with Powerlevel9k except where Powerlevel9k does something nonsensical that is likely a bug. This seems to be the case with the handling of empty lines of left prompt. Consider the following configuration:

```zsh
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline background_jobs newline dir_writable)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
```

Powerlevel9k:

![p9k](https://user-images.githubusercontent.com/1282067/57516204-9225c600-7314-11e9-8261-02ece1e76395.png)

Powerlevel10k before the fix:

![p10k-before](https://user-images.githubusercontent.com/1282067/57516216-9651e380-7314-11e9-91b0-eb64edfc0582.png)

Powerlevel10k after the fix:

![p10k-after](https://user-images.githubusercontent.com/1282067/57516222-994cd400-7314-11e9-91a0-37e0b0a7e6f4.png)

Powerlevel10k after the fix is the only version that renders prompt consistently in this case. It's also  fairly close to the behavior of Powerlevel9k, so I believe this was the original intention of its developers. However, there is always a chance someone is relying on the current behavior. If there are many such users, I'll have to come up with another solution when they complain.

I'll open an issue against Powerlevel9k so that they can fix it too.

**Comment by romkatv** [comment]
For the reference, here's the issue I opened against Powerlevel9k: https://github.com/bhilburn/powerlevel9k/issues/1266.
