### ISSUE TITLE
Remove pattern from current working directory

### ISSUE THREAD

**Issue by kovasap** [romkatv/powerlevel10k#676]
I'm interested in removing/replacing a current working directory segment with either nothing, ellipses, or a custom segment.  For example, if my working directory is `/path/to/my/code/repo`, i would like my prompt to display `.../repo` or `<my custom path>/repo` or just `repo`.  Is this possible?

**Comment by romkatv** [comment]
Add the following definition to `~/.zshrc`:

```zsh
hash -d repo=/path/to/my/code/repo
```

Now prompt will display `~repo/blah` when you are in `/path/to/my/code/repo/blah`. In addition, things like `ls ~repo` and `cd ~repo/<TAB>` will work.

Depending on your real directory structure you might want to add `hash -d c=/path/to/my/code` instead of the alias above. You might also want to add more than one alias.

In addition or instead of `hash -d` you can open `~/.p10k.zsh`, search for `POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER` and change its value to `first` or `last`. You must be on the latest version of powerlevel10k for this to work. See docs for this parameter [here](https://github.com/romkatv/powerlevel10k/blob/7c4b0f36c0b5d3dc1049115ecca192463c19278d/config/p10k-classic.zsh#L245-L250).

**Comment by kovasap** [comment]
That works, thanks!

**Comment by romkatv** [comment]
Thanks for the confirmation!

**Comment by kpal99** [comment]
Hi, My directory structure is quite complex. Right now, `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` is set. 
So, the prompt takes a lot of time to highlight the parts of directory, which it will eventually use to shorten directory path preserving uniqueness (I guess). 
I used hashes in zshrc to remedy that 
```
hash -d repo=/path/to/my/code/repo
hash -d rfoobar=/foo/to/my/code/bar
```
When I am doing `cd ~repo` the prompt is showing `> ~repo`
but when I am doing `cd ~foobar` the prompt is expanding to full directory path and doing all the highlight. 
I want hashes to be in the prompt and not find uniqueness in underlying directory structure until the hash. 
Is there something wrong in my way of implementing hashes? Any help in the matter would be highly appreciated.

**Comment by romkatv** [comment]
Please open a separate issue.

**Comment by kpal99** [comment]
Opened the new issue.
