### ISSUE TITLE
Powerlevel10k does not pick up changed variables 

### ISSUE THREAD

**Issue by benjaminbauer** [romkatv/powerlevel10k#69]
Hi all,

I am using two functions, light and dark, to toggle the themeing of my shell/vim etc. In this function I also want to change the theme of powerlevel10k from light to dark (or the opposite). What I do is `export POWERLEVEL_9K_COLOR_SCHEME='light'` and unset it again in my "dark" function. After that I  source the zsh-theme file again, but that does not change anything, because `_P9K_INITIALIZED` is still set.

What I tried: `unset _P9K_INITIALIZED`, but that gives me an additional "wrapping" sign every time I call it: `╭─╭─╭─╭─╭─╭─╭─INSERT ~ `. What can I do to get the behavior I want?

Thanks so much in advance for your help and in general for this cool speedup of 9k!

**Comment by romkatv** [comment]
> What I tried: unset `_P9K_INITIALIZED`

Changing internal variables (those that start with `_`) is not a good idea. Even if it works now, it may break tomorrow.

> What can I do to get the behavior I want?

Change your `~/.zshrc` like this:

```zsh
: ${POWERLEVEL9K_COLOR_SCHEME:=light}
```

(This assumes that you want light theme by default when you open your terminal. Replace `light` with `dark` if you want dark by default.)

Define theme switching functions like this:

```zsh
function dark light() {
  export POWERLEVEL9K_COLOR_SCHEME=$0
  exec zsh
}
```

In general, `exec zsh` works better than `source ~/.zshrc`.

**Comment by benjaminbauer** [comment]
Hi @romkatv, thanks for the immediate help! Can you explain to me what the leading colon in `: ${POWERLEVEL9K_COLOR_SCHEME:=light}` does? Also, does the call `exec zsh` spawn a shell inside the shell?

**Comment by romkatv** [comment]
> Can you explain to me what the leading colon in `: ${POWERLEVEL9K_COLOR_SCHEME:=light}` does?

`${POWERLEVEL9K_COLOR_SCHEME:=light}` assigns  `POWERLEVEL9K_COLOR_SCHEME=light` if `POWERLEVEL9K_COLOR_SCHEME` is unset of empty. Otherwise it does nothing.

`:` is a ZSH builtin that takes any number of arguments and does nothing. Since we are using `${POWERLEVEL9K_COLOR_SCHEME:=light}` for its side effects (namely, for conditional assignment) but don't need the value of this expansion, we can use `:` to ignore it.

Here's an example:

```zsh
: ${FOO:=ls}
```

This is equivalent to the following:

```zsh
FOO=${FOO:-ls}
```

Now, suppose we didn't use `:`.

```zsh
${FOO:=ls}
```

Equivalent code:

```zsh
FOO=${FOO:-ls}
$FOO
```

The last line will invoke `ls` if `FOO` wasn't set to begin with.

> Also, does the call `exec zsh` spawn a shell inside the shell?

It does not. You can try calling `exec zsh` a few times and verifying that you still have the same number of `zsh` processes. In addition, `exec zsh` doesn't change the PID of the process.
