### ISSUE TITLE
don't git status specific directories

### ISSUE THREAD

**Issue by delanym** [romkatv/powerlevel10k#714]
I use sshfs to mount remote repos. When 10k prompt does a git status it takes an age. It would be helpful to set 10k to ignore locations and/or filesystems of type fuse.sshfs

**Comment by romkatv** [comment]
There are several options. I suggest trying them in the specified order. They progressively disable more and more parts of `vcs` prompt segment.

Go to the repo and run this command:

```zsh
git config --local bash.showUntrackedFiles false
```

Restart `zsh`. If it's still too slow, run another command:

```zsh
git config --local bash.showDirtyState false
```

Restart `zsh`. If it's still too slow, revert these changes:

```zsh
git config --local --unset bash.showUntrackedFiles
git config --local --unset bash.showDirtyState
```

Open `~/.p10k.zsh` and search for `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN`. If your config is new enough, you'll see this:

```zsh
# Don't show Git status in prompt for repositories whose workdir matches this pattern.
# For example, if set to '~', the Git repository at $HOME/.git will be ignored.
# Multiple patterns can be combined with '|': '~(|/foo)|/bar/baz/*'.
typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
```

Change this parameter as suggested in the comments. If you don't have this parameter, add it.

Restart `zsh`. If it's still too slow, revert your changes, open `~/.p10k.zsh` and add this:

```zsh
typeset -g POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN='(/some/dir|/another/dir)(|/*)'
```

**Comment by delanym** [comment]
Thanks, I took the last option for now as I still want to see untracked/dirtystate when i'm in a server shell.
Hmm, look what I found https://www.presslabs.com/docs/code/gitfs/usage/

**Comment by romkatv** [comment]
> Hmm, look what I found https://www.presslabs.com/docs/code/gitfs/usage/

Could you give me a hint how this is relevant? What do you expect me to understand from the link?

**Comment by delanym** [comment]
Well git is its own fs. So when I have time i might look into using a more integrated approach than sshfs. Im guessing it would allow more efficient git status lookup.
Then you might consider integrating into p10k? I don't know how that would work—I saw this today.

**Comment by romkatv** [comment]
> Then you might consider integrating into p10k?

Integrate how? What would you like to work that doesn't work now?

**Comment by albertnetymk** [comment]
I encountered sth similar. Since I can't change the git configs in that repo, I used both `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN` and `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`. The former alone is not enough. I wonder what's the diff btw those two options? IOW, what features are disabled?

**Comment by romkatv** [comment]
> I encountered sth similar.

What have you encountered?

> I used both `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN` and `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`.

What have you set them to?

> The former alone is not enough.

Not enough in what sense?

> I wonder what's the diff btw those two options? IOW, what features are disabled?

`POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN` removes Git status from prompt when the current directory matches the specified pattern.

`POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN` removes Git status from prompt when the repository's working directory matches the specified pattern.

**Comment by albertnetymk** [comment]
After using sshfs to mount a remote git repo, and `fusermount -u` always says the device is busy.

I set both to `~/project/remote_git`, the mount point for my remote repo.

`fusermount -u` still says the device is busy, when I only use `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN`. If I use both, I can successfully unmount the repo.

Thank you for the explanation of those two vars. I think I understand `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`: if I don't `cd` into that directory, gitstatusd is not triggered, but I still don't get the other var, what do you mean by "repository's working directory"?

**Comment by romkatv** [comment]
> After using sshfs to mount a remote git repo, and `fusermount -u` always says the device is busy.

When you `cd` into a directory that doesn't match `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN` that is a subdirectory of a Git repository, Powerlevel10k opens the repository and keeps it open for an hour.

> I set both to `~/project/remote_git`, the mount point for my remote repo.

That means you won't see Git status in prompt when your current directory is `~/project/remote_git` but you'll still see it when your current directory is a subdirectory of `~/project/remote_git`. Is that what you want?

> `fusermount -u` still says the device is busy, when I only use `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN`.

This is expected. In order to retrieve the working directory of a git repository, the repository needs to be opened.

> I think I understand `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`: if I don't `cd` into that directory, gitstatusd is not triggered

I don't understand this sentence. When your current directory matches `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`, Git status in prompt is not computed. The repository is not opened either because there is no reason to open it.

> but I still don't get the other var, what do you mean by "repository's working directory"?

Every non-bare Git repository has a working directory. You can use `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN` to avoid displaying Git status in prompt for any Git repository whose working directory matches the specified pattern. I don't know how to make this any clearer.

**Comment by albertnetymk** [comment]
> Powerlevel10k opens the repository and keeps it open for an hour.

Sounds right; I didn't wait that long before killing the process.

> That means you won't see Git status in prompt when your current directory is ~/project/remote_git but you'll still see it when your current directory is a subdirectory of ~/project/remote_git. Is that what you want?

I see; `~/project/remote_git(|/*)` is probably more accurate in my case since I don't want Powerlevel10k to access anything in that remote repo. (Not showing repo info on the prompt is fine.)

> This is expected. In order to retrieve the working directory of a git repository, the repository needs to be opened.

I see; `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN` is probably what I need, since I want to forbid all access to remote repo.

> I don't understand this sentence...

I was trying to express the same view: if the current directory is `POWERLEVEL9K_VCS_DISABLED_DIR_PATTERN`, no repo info is presented on the prompt.

> Every non-bare Git repository has a working directory. 

I see; I didn't associate this term to git.

Thank you for the explanation, and this elegant & handy theme.

**Comment by romkatv** [comment]
> > Every non-bare Git repository has a working directory.
> 
> I see; I didn't associate this term to git.

This is partially my fault. Git used to use the term "working directory" as a synonym for "working tree" but the former has been rooted out. See, for example, [this commit](https://github.com/git/git/commit/2a0e6cdedab306eccbd297c051035c13d0266343). I should've used `WORKTREE` instead of `WORKDIR` in the parameter name in Powerlevel10k and "working tree" in comments and descriptions.
