### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by sandro-git** [romkatv/powerlevel10k#74]
hello,

it doesn't work for me i'm using iterm2. i try to remove zsh_theme line and other stuff on readme but nothing helps. i'm using Oh-my-zsh to. can you help me ?

**Comment by romkatv** [comment]
Sure, let's dig into this.

When you say it doesn't work, what do you mean? What are you doing and what are you seeing as the result?

Please attach your `~/.zshrc`.

**Comment by sandro-git** [comment]
sorry i was pretty tired. here is some screen shot and my ~/.zshrc file
<img width="563" alt="Screenshot at Jun 01 15-40-16" src="https://user-images.githubusercontent.com/17152022/58749240-d889c300-8483-11e9-9098-7180adc21d86.png">
<img width="564" alt="Screenshot at Jun 01 15-40-59" src="https://user-images.githubusercontent.com/17152022/58749241-d9225980-8483-11e9-9057-69ef0a9975ff.png">
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/3243807/zshrc.txt)

**Comment by romkatv** [comment]
Thanks for the screenshots and the configs. The culprit is https://github.com/robbyrussell/oh-my-zsh/blob/6af58f492f8c5219e27f74cf6378e92834d1b3e5/plugins/common-aliases/common-aliases.plugin.zsh#L28.

```zsh
alias -g M="| most"
```

It breaks any code that uses unquoted `M`. For example:

```zsh
echo M

if [[ M == M ]]; then
  echo "All is well"
else
  echo "The world is on fire"
fi
```

This works for me (and for most users out there) but you'll get something unexpected from the first line and `zsh: parse error near` from the rest.

I've added extra quotes in powerlevel10k to defend against these aliases. Please update powerlevel10k and let me know if it works now.

P.S.

Thanks for the bug report!

**Comment by sandro-git** [comment]
It work just fine thank you. you do a awesome job. i just stared you project

**Comment by romkatv** [comment]
Thanks for the confirmation!

**Comment by romkatv** [comment]
I've also submitted a more general fix for this problem so that global aliases won't break Powerlevel10k in the future.
