### ISSUE TITLE
p10k-instant-prompt-output filling /tmp

### ISSUE THREAD

**Issue by DiegoGuidaF** [romkatv/powerlevel10k#770]
Hi,

I have been using the instant prompt feature for a bit now without problems.
Recently I have been testing a script which due to an error and debugging flags had a huge output via console. It seems this output was sent to the file:
/tmp/p10k-instant-prompt-output-diego-6427
Thus filling it and with it my ram (which resulted in all kinds of errors).

I have now noticed that all my session output goes to this file, I am currently using sway and launching it via the **.zlogin** file like this:
```
# This file is sourced AFTER zshrc
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec launch_sway.sh
fi
```
Where **launch_sway.sh** is:
```
#!/bin/bash
sway 2>sway.log
```

The contents of the **/tmp/p10k-instant-prompt-output-diego-6427** are:
```
[2020-05-27 16:31:23.918] [info] Resources files: /home/diego/.config/waybar/config, /home/diego/.config/waybar/style.css
[2020-05-27 16:31:23.946] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[2020-05-27 16:31:24.143] [warning] Requested width: 0 exceeds the minimum width: 1920 required by the modules
```
Which is consistent with the output of the `sway 2>sway.log` command.

I do understand that it is expected for me to manage the whole output of the `sway` command instead of just the errors and that is my fault. However I do not understand why this is redirected to the **/tmp/p10k-instant-prompt-output-diego-6427** file, is this expected? I see many users could be seeing their ram usage increase unexpectedly due to this.

**Comment by romkatv** [comment]
Please describe all steps necessary to reproduce the problem. Try to remove everything irrelevant. If systemd is not necessary to reproduce, don’t mention it. The same goes for sway, etc.

**Comment by DiegoGuidaF** [comment]
Okey, it can be reproduced by adding
`exec yes` at the end of the .zshrc file:

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

exec yes
```

**Comment by romkatv** [comment]
Thanks for the config. Could you also describe what the issue with that config is?

**Comment by romkatv** [comment]
If you enable instant prompt, put `exec yes` in `~/.zshrc` and start interactive zsh, you'll get no output to the terminal and a temporary file in `${TMPDIR:-/tmp}` will be growing in size very fast. If this is surprising to you, please read https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-enable-instant-prompt.

If `exec yes` in `~/.zshrc` isn't something you actually care about, you might benefit from the latest changes I've made.

- Instant prompt will no longer activate when you run `zsh -ic cmd`, `zsh -i script` or `zsh -x`.
- If an interactive zsh session with instant prompt terminates before it gets to the first prompt (e.g., through `exit` in `~/.zshrc`), captured console output will be printed and the temporary file deleted.

There is no reliable way to hook `exec yes`, so that one will still work as before.

**Comment by DiegoGuidaF** [comment]
Okey, I understand this is a consequence of the instant prompt and care should be taken with any output scripts launched from terminal.
Thing is I didn't expect it to happen on an script launched from .zlogin and also that the output would be filling my /tmp for the whole session.

I will be more careful while using the instant prompt, since it is clear enough on the documentation that it should be used with care :)

Thank you!

**Comment by romkatv** [comment]
FWIW, putting `exec whatever` in `.zlogin` is kind of crazy. You attempt to login and your shell turns into something else. No more shell for you...

If you really want this, use `.zprofile` instead. It's also crazy but at least you won't evaluate `.zshrc` before killing shell.

A proper solution is to start sway through systemd. Since you have systemd, might as well use it.

**Comment by DiegoGuidaF** [comment]
> FWIW, putting `exec whatever` in `.zlogin` is kind of crazy. You attempt to login and your shell turns into something else. No more shell for you...
> 
> If you really want this, use `.zprofile` instead. It's also crazy but at least you won't evaluate `.zshrc` before killing shell.
> 
> A proper solution is to start sway through systemd. Since you have systemd, might as well use it.

Starting Sway via .zlogin is suggested by themselvs https://github.com/swaywm/sway/wiki#login-managers.
However you make a valid point, I will check into starting it via systemd, thank you.
