### ISSUE TITLE
Arrows not aligned properly 

### ISSUE THREAD

**Issue by Henryws** [romkatv/powerlevel10k#781]
I'm using alacritty with the recommended fonts but I can't seem to figure this out:
![screenshot](https://user-images.githubusercontent.com/58742515/83354455-5b0ac400-a31e-11ea-9d8a-cec99328a1ff.png)
The arrow after the Ubuntu logo is to high up and same for the prompt head. Can someone help? Thanks

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#sub-pixel-imperfections-around-powerline-symbols

**Comment by Henryws** [comment]
no, I tried those things and nothing works, don't close an issue until the OP figures out the problem

**Comment by romkatv** [comment]
> no, I tried those things and nothing works

Have you tried this?

> Try a different terminal.

---

> don't close an issue until the OP figures out the problem

lol

**Comment by Henryws** [comment]
yes, it happens in other terminals

**Comment by romkatv** [comment]
> yes, it happens in other terminals

That's implausible. If it did, I'm inclined to believe you would've mentioned it in the OP and maybe posted screenshots.

If you are on Linux, try GNOME terminal or anything else based on VTE (Tilix, Guake, etc.). These are the best terminals at rendering and all around. Much better than Alacritty. That said, almost any terminal on Linux is better than Alacritty.

If you are on macOS, try iTerm2.

If you are on Windows, try Windows Terminal.

**Comment by Henryws** [comment]
So is it a problem with my config? Or is alacritty just not going to work?

**Comment by romkatv** [comment]
Alacritty is generally bad at rendering. It aligns text poorly and makes rendering jerky. If you try anything VTE, you'll immediately notice how much snappier zsh feels and how much more pleasant it's too look at.

Some of these issues can be alleviated by tweaking the config. I recall I made alacritty rendering not completely awful by tweaking the config to shift all text by one pixel and increasing font size. I wasn't able to find any workaround for its jerky rendering, which is very noticeable if you enable transient prompt.

If you are really dedicated to alacritty, you can even manually edit some font so that it looks OK in alacritty. The edited font will look bad everywhere else though.

It's much more practical to just use a better terminal. Alacritty has no practical advantages over VTE.
