### ISSUE TITLE
VCS prompt segment won't show anything if local branch is behind or ahead of remote repository.

### ISSUE THREAD

**Issue by AitBits** [romkatv/powerlevel10k#787]
Hi, as the title says vcs segment doesn't show anything when local repo is behind or ahead of remote one.

I noticed this when doing git fetch on powerlevel10k repo to update it.
As soon as I git fetch and local branch is behind by one or more commits, it stops showing.
It comes back when I git pull to bring it up-to-date.
Same thing when it's ahead of remote.

Please let me know if you need whatever information on this matter.

**Comment by romkatv** [comment]
Please describe all steps necessary to reproduce this issue.

**Comment by AitBits** [comment]
That was a quick reply.
I just found out that this only happens in powerlevel10k repo and not others, not sure what makes difference.

Anyways, here you go,

1. be in a powerlevel10k repo

2. touch blah

3. git add blah

4. git commit -m "blah"

After this, vcs segment disappears.

Or, for the opposite case,

1. be in a outdated powerlevel10k repo

2. git fetch

And there, vcs segment disappears.

**Comment by romkatv** [comment]
I've reproduced this on a repository cloned with `--depth=1`. Will debug later when I get more free time.

**Comment by mike-pittelko** [comment]
Any progress on this?

**Comment by romkatv** [comment]
No progress and no ETA.

**Comment by mike-pittelko** [comment]
Any information I can provide? - I can reproduce this on a number of repos, many are full clones, most are the origin repos.

**Comment by romkatv** [comment]
> Any information I can provide? - I can reproduce this on a number of repos

I can reproduce this myself, see my comment above. I don't need additional information.

I'm not working on this issue and I don't expect to work on it any time soon. Maybe I'll eventually get to fixing it, maybe not. Hence no progress and no ETA.

If you want this get fixed, consider fixing it.

---

@AitBits Oh, I just realized that you are commenting on an unrelated issue instead of opening a new one. The log you've posted don't have anything to do with this issue. See the description: "VCS prompt segment won't show anything if local branch is behind or ahead of remote repository." This does not sound like the issue you are having, does it?

Your repos have "link" extensions. gitstatus doesn't understand it, so it refuses to open such repos. I'm unable to find any documentation for this extension. Can you point me to it? If yes, please open another issue, copy the log message and post info about "link" extension.

**Comment by mike-pittelko** [comment]
will do.

**Comment by romkatv** [comment]
Fixed.

**Comment by mario-amazing** [comment]
@romkatv 
Could you tell me why I can't see VCS segment?
With almost default p10k configure
<img width="601" alt="image" src="https://user-images.githubusercontent.com/9537753/186787109-58ef1bbd-7ae4-4cbf-a0bd-83c9eb544877.png">

**Comment by romkatv** [comment]
> Could you tell me why I can't see VCS segment?

Perhaps, if you open an issue an describe what you do, what you expect, and what you observe.
