### ISSUE TITLE
user & host prompt elements

### ISSUE THREAD

**Issue by tumd** [romkatv/powerlevel10k#790]
Hi!

First of all, thank you for all your great work on p10k!

I'm trying to to setup my prompt with different looks for `user` and `host` and thus using these elements instead of the `context` element.
However, trying to customize these doesn't seem to work in the same manner as `context`.

For example, it doesn't seem that setting `POWERLEVEL9K_USER_TEMPLATE` to something other than `'%n'` does anything at all. I tried to make this bold with `'%B%n'`.

Also the `host` element seem to add an empty space in front of it, that I can't figure out how to remove with bellow configs;
```
POWERLEVEL9K_{HOST,SSH}_ICON=''
POWERLEVEL9K_HOST_TEMPLATE='@%m'
```

Apart from these two possible bugs, I would love if the `user` & `host`-elements getting support for the same "states" as the `context`-element. I.e. `REMOTE,REMOTE_SUDO,ROOT`.

**Comment by romkatv** [comment]
> I'm trying to to setup my prompt with different looks for `user` and `host` and thus using these elements instead of the `context` element.

You can embed formatting within `POWERLEVEL9K_CONTEXT_TEMPLATE` and the like.

```zsh
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%F{red}\uF007 %n%f %F{blue}%m%f'
```

> For example, it doesn't seem that setting `POWERLEVEL9K_USER_TEMPLATE` to something other than `'%n'` does anything at all.

`POWERLEVEL9K_USER_TEMPLATE` is used only when you are root. This logic makes no sense but that's how it was in Powerlevel9k so I kept it. I don't want to break backward compatibility here because I don't find `user` prompt segment useful at all.

> Also the `host` element seem to add an empty space in front of it, that I can't figure out how to remove with bellow configs;
> 
> ```
> POWERLEVEL9K_{HOST,SSH}_ICON=''
> POWERLEVEL9K_HOST_TEMPLATE='@%m'
> ```

I don't see any spaces with this setup. Maybe you are referring to the usual space between prompt segments? You can remove it either by using `host_joined` or with separator override just for `user` (I'd post the parameter name if you showed your config).

> Apart from these two possible bugs

This is working as intended.

> I would love if the `user` & `host`-elements getting support for the same "states" as the `context`-element. I.e. `REMOTE,REMOTE_SUDO,ROOT`.

Not happening. I'd suggest using `context`, getting by with `user` and `host` or defining your own segments. The latter is really easy for such simple segments. You can refer to `P9K_SSH` to write conditional logic for ssh connections.

```zsh
function prompt_my_context() {
  if (( P9K_SSH )); then
    # in ssh
    p10k segment -t '%F{red}%n%f %F{blue}%m%f'
  elif (( EUID || UID )); then
    # privileged
    ...
  else
    # other
    ..
  fi
}
```

Craft conditions as you like. See `p10k help segment`.

**Comment by tumd** [comment]
You are of course right, and the `context`-element is absolutely the way to go.
Thank you for the informative and fast answer!
