### ISSUE TITLE
musl binary of gitstatus is not present

### ISSUE THREAD

**Issue by dimon222** [romkatv/powerlevel10k#81]
First of all, I absolutely fell in love with this theme.
However, I noticed that due to its nature of being plugged into prezto as "git submodule" and its reliance on custom libgit2 implementation sadly made it unusable on default Alpine Linux (musl based distro). Basically, binary of `gitstatus` just doesn't run.

I was able to compile binary manually on Alpine, and it actually even works, but I'm curious, is there anything can be done to make it through or maybe even improved? I have alpine package implementation (obviously with necessary build.zsh run) for patched gitstatus that I could theoretically push to https://github.com/alpinelinux/aports but sadly its not exactly same thing as actually making sure prezto and others use this global binary.

**Comment by romkatv** [comment]
I added a statically-linked gitstatusd binary for linux-x86_64. It's linked against musl because statically linking against glibc would require making non-trivial changes to libgit2. The new binary is used when glibc isn't available. This binary actually works everywhere but it increases prompt latency by 50% so I'm using it only if there is no better option. I was surprised that musl is so much slower in gitstatusd, especially considering that gitstatusd spends over 90% of CPU time in kernel. I haven't profiled it because it's a pain to recompile all my C++ dev tools for musl.

Unfortunately, on Alpine Linux this binary is terribly slow. This slowdown seems specific to Alpine as the same binary is fast everywhere else, including NixOS that also uses musl libc.

After hours of debugging I figure out that git is broken on Alpine and my binary is correct. I opened https://bugs.alpinelinux.org/issues/10542. Perhaps you know what's up? Also, do you have the same git bug on your system? You can check by running the following commands:

```zsh
mkdir /tmp/repo
cd /tmp/repo
git init
touch x
git add x
git ls-files --debug -- x
```

If `mtime` ends with `:0`, git is broken.

Depending on the source and nature of this bug I might add a workaround but at this point I don't have enough understanding of the problem to proceed further.

**Comment by romkatv** [comment]
Could you confirm that powerlevel10k now works for you out of the box, without having to build your own gitstatusd binary?

Could you send me the output of the following command?

```zsh
(
  emulate zsh && setopt xtrace err_exit
  stat --version
  git --version
  mkdir /tmp/repo
  cd /tmp/repo
  git init
  touch x
  stat x
  git add x
  git ls-files --debug -- x
)
```

**Comment by dimon222** [comment]
I've checked with latest powerlevel10k, works fine now.

Also, don't know specifics about fractional seconds, might be just a bug of git build with some of their git musl patches.
I ran your commands. Yes, they both show `:0`

```
+./test.sh:5> stat --version
stat (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Michael Meskes.
+./test.sh:6> git --version
git version 2.20.1
+./test.sh:7> mkdir /tmp/repo
+./test.sh:8> cd /tmp/repo
+./test.sh:9> git init
Initialized empty Git repository in /tmp/repo/.git/
+./test.sh:10> touch x
+./test.sh:11> stat x
  File: x
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fd03h/64771d    Inode: 196         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-06-09 08:53:02.692239167 -0500
Modify: 2019-06-09 08:53:02.692239167 -0500
Change: 2019-06-09 08:53:02.692239167 -0500
 Birth: -
+./test.sh:12> git add x
+./test.sh:13> git ls-files --debug -- x
x
  ctime: 1560088382:0
  mtime: 1560088382:0
  dev: 64771    ino: 196
  uid: 0        gid: 0
  size: 0       flags: 0
```

**Comment by romkatv** [comment]
Thanks for the confirmation. This is as I feared. I believe all Alpine Linux packages built against musl libc see invalid data when they call `stat()`. The underlying syscall returns correct data and then musl corrupts it. Packages built against glibc are not affected. Neither are binaries build against musl by the users themselves. Your `/bin/stat` comes from coreutils. It's GNU code based on glibc, so it works. Git is from an Alpine package built against musl. Broken.

This can lead to problems, most likely related to performance. As I mentioned above, I started digging into it because I noticed that gitstatusd was super slow on Alpine Linux. This isn't surprising when different binaries get different results when they `stat()` the same file.

I implemented a workaround for this bug in libgit2 and gitstatusd. I rebuilt the variant of gitstatusd binary that gets picked up on Alpine. Once you update powerlevel10k, your git prompt will be as fast as on other distributions.

Thank you for opening the issue and for providing valuable support in debugging.
