### ISSUE TITLE
Git tag icon not displaying

### ISSUE THREAD

**Issue by HackAttack** [romkatv/powerlevel10k#811]
9k

<img width="1260" alt="Screen Shot 2020-06-09 at 4 43 29 PM" src="https://user-images.githubusercontent.com/1222646/84211547-6f626580-aa70-11ea-9bea-60c1d66b5e2a.png">

10k

<img width="1302" alt="Screen Shot 2020-06-09 at 4 45 13 PM" src="https://user-images.githubusercontent.com/1222646/84211624-a0db3100-aa70-11ea-9bbe-250cf4f6dcff.png">

Is this opt-in somehow?

**Comment by HackAttack** [comment]
Same with VCS_STASH_ICON

**Comment by romkatv** [comment]
Comparisons between p9k and p10k make sense only when you use both themes with a p9k config. I you use p9k with one config and p10k with another, there is no expectation that you'll get the same results.

Configs produced by `p10k configure` use different Git status format by default. I'm not tied with backward compatibility here, so I can choose what I believe is best. Plain `+` is much easier to read than the circled plus used by p9k, so I go with that. It's usually important to me to know that I'm in detached head, so `#` is rendered in different font to avoid confusion with your being in a branch. For the description of the default Git status format see https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean.

This is customizable, so if you like to have the same icons that p9k uses you can do that. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status. And of course you can also delete `~/.p10k.zsh` and continue using your old p9k config.

**Comment by romkatv** [comment]
> Ah now I see, I was confused about when to expect the same behavior. Thanks.

Just to clarify, Powerlevel10k implements a superset of functionality of Powerlevel9k. In other words, it's backward compatible with Powerlevel9k.

Think of it as C++ and C. You can compile C programs with a C++ compiler but you cannot compile C++ programs with a C compiler. Likewise, you can use Powerlevel9k configs with Powerlevel10k but you cannot use Powerlevel10k configs with Powerlevel9k.

In addition, different configs produce different prompts. Otherwise there would be no point in having configs at all.
