### ISSUE TITLE
Add support for Julia to asdf

### ISSUE THREAD

**Issue by noahgaertner** [romkatv/powerlevel10k#817]
Currently, ASDF per-language configuration support (icons, upglob, etc. ) only supports a limited subset of languages. Ideally, support would be extended to most languages with a significant userbase (a good starting point, in my opinion, would be supporting the languages [starship does](https://starship.rs/config/)) , but this feature request in particular is about adding this functionality to [Julia](https://julialang.org/),

**Comment by noahgaertner** [comment]
Okay, so I just tried to copy one of the other language's config and change the language name to julia and reconfigure it that way and that worked fine, so since the any asdf language is already supported, it would be nice to make it clearer to the end user that it is by stating that in the block comment above the asdf section, but I'll be closing this issue nevertheless.

**Comment by romkatv** [comment]
As you've discovered, powerlevel10k supports all asdf tools out of the box. However, it doesn't know which icons to display and which color to use unless you define the respective parameters. I've added these parameters for Julia.

> a good starting point, in my opinion, would be supporting the languages [starship does](https://starship.rs/config/)

What makes it a good starting point?

**Comment by noahgaertner** [comment]
> 
> > a good starting point, in my opinion, would be supporting the languages [starship does](https://starship.rs/config/)
> 
> What makes it a good starting point?
I'm fairly certain the original feature request for asdf support referenced it's inclusion in starship, but beyond that it's the other major theme that supports in-console language versioning, so achieving feature parity with it makes sense to me.

**Comment by romkatv** [comment]
> I'm fairly certain the original feature request for asdf support referenced it's inclusion in starship, but beyond that it's the other major theme that supports in-console language versioning, so achieving feature parity with it makes sense to me.

I was hoping you'd point me to some kind of guideline that Starship follows to determine which languages receive first-class support. If they don't have it, there is no reason why their list is any better than the one in Powerlevel10k. I include languages when someone asks for them, and it seems like Starship does the same. Having more languages on the list isn't necessarily better because it makes documentation and configs larger.

As to the value of feature parity, it's unclear how useful it is. Starship isn't a popular zsh theme to begin with. It might be in top 10 but definitely not in top 5. Perhaps it's popular among Fish and Bash users; I wouldn't know.
