### ISSUE TITLE
Configure command not asking to configure separators

### ISSUE THREAD

**Issue by TheNoNinja** [romkatv/powerlevel10k#830]
I have a clean install of arch with zsh, oh-my-zsh, and powerlevel10k. I also have installed the recomended fonts and all nerd fonts. But when I run the configure command it does not ask me to setup the separators. I have searched far and wide to find a solution but I haven't found somebody else with the same problem. Is there something I am missing? Thanks in advance!

**Comment by romkatv** [comment]
It’s not very clear what the problem is. You expect the configuration wizard to ask you something but it doesn’t? What is it that you expect? Why do you expect it?

Have you seen this? https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by TheNoNinja** [comment]
That did the trick.

I had UTF-8 selected but I never ran `locale-gen` -_-

I have spend way to much time googeling and pulling my hair out on this one. Thanks so much!
