### ISSUE TITLE
POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true makes gitstatus fail initialization

### ISSUE THREAD

**Issue by mundry** [romkatv/powerlevel10k#838]
Hey,

following up from #837 

I set `typeset -g POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true` and on the next zsh start I get:
```
[powerlevel10k] fetching gitstatusd
[ERROR]: gitstatus failed to initialize
```

Setting `GITSTATUS_LOG_LEVEL=DEBUG` reports this error:
```
+_gitstatus_daemon_p9k_:82> HOME=/home/username /home/username/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.0.0 -s -1 -u -1 -d -1 -c -1 -m -1 e -v DEBUG -t 16
unexpected positional argument: e
```

`zsh`: v5.7.1

Looks like the argument for `POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS` is not constructed properly.

**Comment by romkatv** [comment]
Thanks for the report. Apparently I broke it in gitstatus months ago. Now we know no one is using `-e` and three other flags.

It’s a simple fix in gitstatus, so I’ve applied it from my phone. Merging it to powerlevel10k requires access to my dev machine in order to run `git subtree pull`. I’ll be able to do that in 12 hours or so. In the meantime you can apply the fix locally in your clone of powerlevel10k (see the link to the commit above) or just wait.

**Comment by mundry** [comment]
Thanks for the fast fix.
I applied it manually and it works now.

**Comment by romkatv** [comment]
I've merged https://github.com/romkatv/gitstatus/commit/0f5402c8686a593cd21b95ade28a154dd51749bb to powerlevel10k. Closing as fixed.
