### ISSUE TITLE
"`RPROMPT`" overflows into next line

### ISSUE THREAD

**Issue by Syphdias** [romkatv/powerlevel10k#84]
Not sure if this will be a bug report or feature request...
Config is mostly `purepower` but with my own spin that is probably not relevant. The important bit being `POWERLEVEL9K_PROMPT_ON_NEWLINE=true` and `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false`.

If the sum of both `PROMPT` and "`RPROMPT`" get too long it flows into the next line. This is different from the behavior if the native(*) `RPROMPT` is used.
![image](https://user-images.githubusercontent.com/16988672/59152774-947e5b80-8a4b-11e9-8a26-512e27307141.png)

I think there could be two approaches:
1. Hide "`RPROMPT`" if it would overflow (or just the first segment, then the next, if you want to go crazy)
2. Commit to the overflow and right align it again like it happens if `PROMPT` is too like. Like this:
![image](https://user-images.githubusercontent.com/16988672/59152785-c1cb0980-8a4b-11e9-8e9b-e3900af1ddfc.png)

*native being two cases:
- if `RPROMPT` on same line as `PROMPT`: hide
- if `RPROMPT` on line above `PROMPT`: take precedence and overlap `PROMPT`

**Comment by romkatv** [comment]
This is a marvelous bug! I tip my hat to you for finding and reporting it.

I've fixed it in https://github.com/romkatv/powerlevel10k/commit/2f379690f334037df509bdfe42e117164977b4f3. Hopefully didn't break anything.

I tried to make it behave just like the native RPROMPT. There is one corner case where left prompt fits exactly within a line and right prompt is shorter than left prompt. There are two options here: do not display right prompt or display it on a new line below left prompt. I went with the latter as it seems more consistent with native RPROMPT, although doing the former would also be fine IMO.

If you decide to test this, keep in mind the off-by-one bug in all ZSH versions between 5.5 and 5.7.1 (both bounds inclusive). The bug causes ZSH to underestimate the position of the cursor when prompt overflows to the next line. You can see it by starting ZSH with `PROMPT="${(l.500..-.)}>" zsh -df` and then hitting `ctrl+r`. You'll notice that the cursor jumps back by as many characters as the number of times prompt has wrapped around. Hitting `ls<tab>` will not only move the cursor but also change prompt content.

Thus, if you are using one of the broken ZSH versions and your left prompt wraps around, p10k will misbehave. I could add a workaround but it doesn't seem worth it. If enough people complain, I might change my mind.

> if `RPROMPT` on line above `PROMPT`: take precedence and overlap `PROMPT`

There is no legal way to put `RPROMPT` on the line above cursor. Powerlevel9k does it by hiding cursor control commands in `%{..%}` which violates the requirement that "the string within the braces should not change the cursor position." This leads causes issues:
- https://github.com/bhilburn/powerlevel9k/issues/1267
- https://github.com/bhilburn/powerlevel9k/issues/1291
- https://github.com/bhilburn/powerlevel9k/issues/1305

So our only guide w.r.t. consistency is RPROMPT that goes on the same line as cursor. Since ZSH hides RPROMPT when it doesn't fit, I did the same in p10k.

**Comment by romkatv** [comment]
Could you confirm whether p10k now works as you expect?

**Comment by Syphdias** [comment]
Sorry, for the dalay. Nice job it looks much better!

> There are two options here: do not display right prompt or display it on a new line below left prompt. I went with the latter as it seems more consistent with native RPROMPT, although doing the former would also be fine IMO.

Agreed. It's probably a rare case if you are not testing it explicitly.

> Hitting `ls<tab>` will not only move the cursor but also change prompt content.

A marvelous bug. As I understand it only triggers if `ZLE_RPROMPT_INDENT=0`. As discussed in another thread, I use `ZLE_RPROMPT_INDENT=1` in which case all cases seem to behave just fine.
I tried `0` nonetheless and it seems only to break if the left side overflows (for documentation sake):
![image](https://user-images.githubusercontent.com/16988672/59187647-2da99100-8b76-11e9-983f-66b840a781ae.png)

Again, not an issue for me; especially since it will get fixed in a future zsh release.

**Comment by romkatv** [comment]
Thanks for verifying!

> As I understand it only triggers if `ZLE_RPROMPT_INDENT=0`.

Unfortunately, no. You are thinking of a different bug. If you are still using zsh 5.7.1, type the following command and then hit `ctrl+r`.

```zsh
PROMPT="${(l.500..-.)}>" zsh -df
```

**Comment by Syphdias** [comment]
Yes, still on 5.7.1. (I need to set `bindkey "^R" history-incremental-search-backward` first btw). Yes the cursor does jump back. I don't experience that with an overflowing p10k prompt though. So I don't see how it is relevant.

So since you talked about another bug, I'll leave it to you if you want fix the `ZLE_RPROMPT_INDENT=0` behavior.

> You are thinking of a different bug

I'm losing count of zsh bugs :sweat_smile:

**Comment by romkatv** [comment]
> Yes, still on 5.7.1. (I need to set bindkey "^R" history-incremental-search-backward first btw). Yes the cursor does jump back. I don't experience that with an overflowing p10k prompt though. So I don't see how it is relevant.

If left prompt overflows, your prompt will break. This is true whether you are using p10k or not.

> So since you talked about another bug, I'll leave it to you if you want fix the ZLE_RPROMPT_INDENT=0 behavior.

Do you mean the last screenshot you posted? It's not caused by `ZLE_RPROMPT_INDENT=0`. This is the result of left prompt overflowing. Try the following.

1. Load p10k.
2. Set `ZLE_RPROMPT_INDENT=1`.
3. Make sure your left prompt wraps around at least twice, meaning that it spans at least 3 lines.
4. Observe broken prompt.

**Comment by Syphdias** [comment]
Oh I see, it just happens earlier if I use a lower numbers for `ZLE_RPROMPT_INDENT`
![image](https://user-images.githubusercontent.com/16988672/59191127-ec69af00-8b7e-11e9-94cc-3743ddd489d3.png)

**Comment by romkatv** [comment]
That's right. Every time left prompt wraps around, ZSH underestimates the position of the cursor by 1. As a result, right prompt will be drawn 1 character to the right of the correct position. With `ZLE_RPROMPT_INDENT=1` and one wraparound it's hard to notice the problem because right prompt doesn't overflow yet. But it's in the wrong position nonetheless -- there is no space after it.

**Comment by Syphdias** [comment]
Thanks for taking the time to explain it!
