### ISSUE TITLE
An extra powreline?

### ISSUE THREAD

**Issue by agentlewis** [romkatv/powerlevel10k#877]
Hey @romkatv, firstly big thanks for the amazing repo you have made - I love it.

So I am having a bit of a funny problem. I am getting a shadow powerline above the rainbow one I configure.

I have debugged it somewhat and believe it is being created by oh-my-zsh somehow.

I have installed your custom oh-my-zsh theme, installed via zplug and manually and it all ends up the same:

![image](https://user-images.githubusercontent.com/1431991/87219739-0002cd00-c3b2-11ea-970a-87b21e962d48.png)

You can see my [.zshrc file here](https://github.com/agentlewis/dotfiles-osx/blob/master/.zshrc) 

I thought it may hove something to do with the instant prompt as it takes about 2 seconds to appear. But I tried turning it off to no avail.

I imagine this there is just something basic I am doing wrong - your directions would be much appreciated :)

**Comment by romkatv** [comment]
You are loading 3 themes. You must load only one.

1. You are loading Pure theme with these lines.
```zsh
# PURE PROMPT
autoload -U promptinit; promptinit
prompt pure
```
2. You are loading Powerlevel10k via Oh My Zsh. This line does it:
```zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
```
3. You are once again loading Powerlevel10k but this time by manually sourcing it.
```zsh
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
```

The first thing you need to do is to remove the lines identified in (1) so that Pure is not loaded.

Then you need to decide how you want Powerlevel10k loaded. If you want it loaded via Oh My Zsh, then remove the line from (3). If you want it loaded manually, then remove the line from (2).

**Comment by agentlewis** [comment]
Oh man 😱 what a muppet I am.

Thanks for the assist - I just got myself confuzzled.

Ps your instructions read so clearly so I knew I must have done something obviously wrong.

Thanks
D

**Comment by agentlewis** [comment]
sorted - thanks mate!
D

**Comment by romkatv** [comment]
You are very welcome. Glad it's working for you now.
