### ISSUE TITLE
Little sideways triangle |> inserted before every line.

### ISSUE THREAD

**Issue by getsec** [romkatv/powerlevel10k#892]
I'm sorry if this is a little ambiguous. But for some reason, every newline in my terminal has this weird 
 blue arrow / triangle. This isnt game breaking or anything, but to be honest, It's a little annoying. Any Ideas?

Using Iterm2 and ZSH.

![image](https://user-images.githubusercontent.com/13003926/87463690-703e6800-c5d7-11ea-8bab-8bdd37a51a90.png)

**Comment by romkatv** [comment]
That triangle is painted by iTerm2. This is a part of [iTerm2 Shell Integration](https://www.iterm2.com/documentation-shell-integration.html). If you don't like it, uninstall iTerm2 Shell Integration. However, I would recommend keeping it because it's in fact very useful. There is a setting in iTerm2 preferences to disable the display of those triangles, so you can get rid of them without disable shell integration.
