### ISSUE TITLE
Character position twisted

### ISSUE THREAD

**Issue by soaringk** [romkatv/powerlevel10k#895]
## Current Behavior
The characters shifted somehow when I press the Tab to complete the command.
<img width="89" alt="Screen Shot 2020-07-16 at 4 32 31 PM" src="https://user-images.githubusercontent.com/42689402/87647464-f5658080-c781-11ea-9c71-e565e493d4b1.png">

And it also happens when I try to move my cursor.
<img width="147" alt="Screen Shot 2020-07-16 at 4 31 36 PM" src="https://user-images.githubusercontent.com/42689402/87647151-d36bfe00-c781-11ea-80e9-a7f37ecae73e.png">

Another weird behavior is that the cursor will quickly fall back one position after finishing initialization.
<img width="86" alt="Screen Shot 2020-07-16 at 4 36 00 PM" src="https://user-images.githubusercontent.com/42689402/87648670-715fc880-c782-11ea-925a-882c3725cb13.png">

## Steps to Reproduce:
1. download prezto and follow the instruction
2. change `zstyle ':prezto:module:prompt' theme` to `powerlevel10k`

## Context (Environment):
OS: macOS Catalina 10.15.5
Terminal: iTerm2, Terminal.app
manager: prezto

## Detailed Description
This happens when I updated the powerlevel10k to the latest version.
I tried to record the screen using [terminalizer](https://github.com/faressoft/terminalizer), but it work smoothly in the rendered gif... I've no idea.  

Did anyone get this problem?

**Comment by romkatv** [comment]
1. What is the output of `typeset -p TERM`?
2. Have you tried following https://github.com/romkatv/powerlevel10k/blob/master/README.md#cursor-is-in-the-wrong-place ?

**Comment by soaringk** [comment]
> * What is the output of `typeset -p TERM`?
> * Have you tried following https://github.com/romkatv/powerlevel10k/blob/master/README.md#cursor-is-in-the-wrong-place ?

Thanks, I solved it by run `p10k configure` after installing the recommended font.

**Comment by soaringk** [comment]
Well, this is probably caused by the `ip`, because when I uncomment this element, the same problem occurs again.

I also tried to restore the backup and comment this element. Problem solved.

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
print -r -- ${icons[NETWORK_ICON]}
```

**Comment by soaringk** [comment]
\uF877

**Comment by romkatv** [comment]
> 1. What is the output of `typeset -p TERM`?
> 2. Have you tried following https://github.com/romkatv/powerlevel10k/blob/master/README.md#cursor-is-in-the-wrong-place ?

:point_up:

**Comment by soaringk** [comment]
Thanks, I observe this:
```
+-------------------------------------------------------------------------------------------------------------------------------------+
| ❯                                                                                          ⇣12.17 B/s ⇡9.31 B/s 192.168.65.3   ─╯ |
+-------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by romkatv** [comment]
If you want to show how it looks, you'll need to post screenshots. Posting just text doesn't work because my browser can render it differently from your terminal. Note that you don't need to censor the IP because it's on a private network.

If prompt is shorter/longer than the frame, you can find out which symbol is causing issues by copy-pasting a part of the prompt.

Also please follow the guide I linked above and try what it suggests. E.g., verify that you don't have the awful iTerm2 option to display ambiguous characters as double width turned on.

**Comment by soaringk** [comment]
Thanks for reply.
I didn't turn on the 'Ambiguous characters are double-width' on iTerm2.

I found out the last character was considered as double width
<img width="126" alt="Screen Shot 2020-07-16 at 7 44 17 PM" src="https://user-images.githubusercontent.com/42689402/87667367-cb6d8780-c79c-11ea-898c-f1e4b7d83e5e.png">

However, when I tried copy and pasting the character one by one, I found this.
<img width="957" alt="Screen Shot 2020-07-16 at 9 04 30 PM" src="https://user-images.githubusercontent.com/42689402/87674054-0d4ffb00-c7a8-11ea-8fde-a731b38548bd.png">

I also tried the same thing in a docker image I built a while ago.
<img width="956" alt="Screen Shot 2020-07-16 at 9 01 11 PM" src="https://user-images.githubusercontent.com/42689402/87674147-2f497d80-c7a8-11ea-8882-9cae4c9dc0ed.png">






> ```shell
> print -r -- ${icons[NETWORK_ICON]}
> ```

As for this, in container 
<img width="269" alt="Screen Shot 2020-07-16 at 9 06 49 PM" src="https://user-images.githubusercontent.com/42689402/87674209-4ab48880-c7a8-11ea-8294-67e9af042566.png">

**Comment by romkatv** [comment]
So the problem is that your terminal incorrectly displays `\uF877` as a zero-width character. This character is from Private Use Area, so it must be displayed as single width. This is the same macOS low-level bug as in https://github.com/romkatv/powerlevel10k/issues/241. You can follow the same instructions as in https://github.com/romkatv/powerlevel10k/issues/241#issuecomment-537176093 to verify this (simply replace `F878` with `F877`).

I'll need to change the default icon used by `ip` segment. It's unfortunately that I don't know which range of characters is affected by this macOS bug, so it's not clear which icon is safe to use as a replacement. Perhaps `\uF50D`? Can you verify that your prompt gets fixed if you add the following parameter to `~/.p10k.zsh`?

```zsh
typeset -g POWERLEVEL9K_NETWORK_ICON='\uF50D'
```

**Comment by romkatv** [comment]
By the way, https://github.com/romkatv/powerlevel10k/blob/master/README.md#if-the-prompt-line-is-shorter-than-the-frame-and-is-mangled already describes your case. I wonder what could be made clearer so that you could identify it yourself.

**Comment by soaringk** [comment]
> ```shell
> typeset -g POWERLEVEL9K_NETWORK_ICON='\uF50D'
> ```

<img width="181" alt="Screen Shot 2020-07-16 at 9 31 09 PM" src="https://user-images.githubusercontent.com/42689402/87676848-adf3ea00-c7ab-11ea-9926-226d15412f10.png">

> By the way, https://github.com/romkatv/powerlevel10k/blob/master/README.md#if-the-prompt-line-is-shorter-than-the-frame-and-is-mangled already describes your case. I wonder what could be made clearer so that you could identify it yourself.

Sorry, I didn't know much about the encoding. I checked #241 and this is the result.
<img width="197" alt="Screen Shot 2020-07-16 at 9 34 05 PM" src="https://user-images.githubusercontent.com/42689402/87677218-15aa3500-c7ac-11ea-841a-1598f546ae5c.png">

So I thought this is caused by:
> This can also happen if prompt contains glyphs designated as "wide" in the Unicode standard and your terminal incorrectly displays them as non-wide. Terminals suffering from this limitation include Konsole, Hyper and the integrated VSCode Terminal. The solution is to use a different terminal or remove all wide glyphs from prompt.

instead of a macOS low-level bug.

**Comment by soaringk** [comment]
Maybe provide an example like `typeset -g POWERLEVEL9K_NETWORK_ICON='\uF50D'` could be helpful? It would be more straightforward if users can just see it themselves.

**Comment by romkatv** [comment]
> Maybe provide an example like `typeset -g POWERLEVEL9K_NETWORK_ICON='\uF50D'` could be helpful? It would be more straightforward if users can just see the difference themselves.

I don't understand. Let's forget that I've asked this question.

I've replaced the default icon. Since you are using prezto, you won't pick up this fix until the next powerlevel10k release. You can keep `POWERLEVEL9K_NETWORK_ICON` in your config until then. Once you get the new version of powerlevel10k, you can remove this parameter.

**Comment by soaringk** [comment]
Thank you for your reply.
