### ISSUE TITLE
Custom gitstatusd binary location

### ISSUE THREAD

**Issue by keyb0ardninja** [romkatv/powerlevel10k#905]
Currently (as per this [comment](https://github.com/romkatv/powerlevel10k/issues/747#issuecomment-631872243)):

> When gitstatus initializes, it looks for the appropriate `gitstatusd` binary in `${GITSTATUS_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/gitstatus}`. If not found, it downloads the binary and stores it in the same directory.

I mount a `tmpfs` partition (RAM) to my `~/.cache` directory. This means the `~/.cache` directory is cleared after every reboot.

Is it possible to point the `gitstatusd` binary to a different location?

**Comment by romkatv** [comment]
> @romkatv I mount a `tmpfs` partition (RAM) to my `~/.cache` directory.

That's not a very good idea. `XDG_CACHE_HOME`, which defaults to `~/.cache`, is meant for *persistent* cache data. This is in contrast to `$TMPDIR`, which defaults to `/tmp` and may be cleared on reboot.

> Is it possible to point the `gitstatusd` binary to a different location?

You can set `GITSTATUS_CACHE_DIR`. However, it would be etter to make `XDG_CACHE_HOME` persistent because gitstatus is likely not the only app you have that suffers from the cache being nuked on reboots. At the minimum it'll slow down Powerlevel10k, too.

**Comment by keyb0ardninja** [comment]
> You can set `GITSTATUS_CACHE_DIR`

Thanks!
