### ISSUE TITLE
prompt heads on Mac Terminal using incorrect/pale color

### ISSUE THREAD

**Issue by eeweegh** [romkatv/powerlevel10k#906]
I've seen this mentioned by a few other people, and usually reasoned away with 'use iTerm2', but I'm a Terminal fan, so I tried to understand what was going on, and hack my way around it. Feel free to close this issue if you consider it irrelevant, but if you see a more elegant way to achieve the same thing, please let me know.
I am new to the p10k code, so if my approach seems crude, please forgive (and correct) me. I've lost some sleep over this, and thought it was best to share here.

This is the problem (see the pale left head on the 3rd and 4th line, and the right head on the 4th line). Note that you don't see it on the time or the duration segment, because the status segment is actually taking the hit as the first in the right prompt.
![Screenshot 2020-07-22 at 15 04 12](https://user-images.githubusercontent.com/23082161/88179775-aeb5d180-cc2c-11ea-965a-4824a27f533f.png)
This is how it's supposed to look:
![Screenshot 2020-07-22 at 15 07 35](https://user-images.githubusercontent.com/23082161/88180114-28e65600-cc2d-11ea-80f2-00b7d79717a2.png)

This is what I did to make it work (adding explicit background directives, based on https://apple.stackexchange.com/questions/282911/prevent-mac-terminal-brightening-font-color-with-no-background).
I realise this is a hack that suits my particular terminal background color, but maybe it could be extended into something like support for POWERLEVEL9K_{LEFT_PROMPT_LAST,RIGHT_PROMPT_FIRST}_SEGMENT_BACKGROUND

```
diff --git a/internal/p10k.zsh b/internal/p10k.zsh
index 6e2fc05..a5eaae0 100644
--- a/internal/p10k.zsh
+++ b/internal/p10k.zsh
@@ -637,7 +637,7 @@ _p9k_left_prompt_segment() {
 
     _p9k_get_icon $1 LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL $sep
     _p9k_escape $_p9k__ret
-    local end_sep_=$_p9k__ret
+    local end_sep_="%K{0\}$_p9k__ret"
 
     _p9k_get_icon $1 WHITESPACE_BETWEEN_LEFT_SEGMENTS ' '
     local space=$_p9k__ret
@@ -869,7 +869,7 @@ _p9k_right_prompt_segment() {
 
     _p9k_get_icon $1 RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL $sep
     local start_sep=$_p9k__ret
-    [[ -n $start_sep ]] && start_sep="%b%k%F{$bg_color}$start_sep"
+    [[ -n $start_sep ]] && start_sep="%b%K{0}%F{$bg_color}$start_sep"
 
     _p9k_get_icon $1 RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL
     _p9k_escape $_p9k__ret

```

**Comment by romkatv** [comment]
Thanks for posting this. It might help others in the future.

The underlying problem is a bug in Apple Terminal.

Your patch works around the bug but it will produce incorrect results on every terminal with `0` background not being identical to no background. This includes the majority of terminals. Here's how you can check whether this patch will break prompt on a terminal:

```zsh
print -P '%K{0}    %k'
```

If you can see the output of this command, the patch will break prompt. If you don't see the output, the patch is a no-op for all terminals except Apple Terminal.

> usually reasoned away with 'use iTerm2'

These are reasonable responses when someone asks what to do about bugs in their terminal -- use another terminal. On macOS there are two decent terminals: iTerm2 and Kitty.

**Comment by eeweegh** [comment]
OK - thanks for prompt (pun intended) reaction!
