### ISSUE TITLE
Git status bar showing wrong info about commits

### ISSUE THREAD

**Issue by simonlucalandi** [romkatv/powerlevel10k#915]
Running git status I see that my local master is 1 commit ahead of remote, but the status bar shows 1413 commits..

![image](https://user-images.githubusercontent.com/2782202/88477902-26913e00-cf44-11ea-99ba-3a7301b8a78e.png)

I get the same issue (wrong number of ahead commits) in all git repo that I use.

Is there anything that I'm doing wrong?

**Comment by romkatv** [comment]
- Does it show 1413 in all repos or is the number different in different repos?
- Can you reproduce this in a repo created with `git clone https://github.com/romkatv/powerlevel10k`?
- What do you get in a repo created with `git init`?
- Do you export any environment variables show names start with `GIT`?
- Do you have a global git config? What's in it?
- Add `GITSTATUS_LOG_LEVEL=DEBUG` to `¬/.zshrc`, type `exec zsh` and then look at `cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`. Any clues there?

**Comment by simonlucalandi** [comment]
>     * Does it show 1413 in all repos or is the number different in different repos?
> 
No, the number is different for each repo, and increase at each commit.

>     * Can you reproduce this in a repo created with `git clone https://github.com/romkatv/powerlevel10k`?
> 
Nope. I cloned the repo, changed a file and committed, and the status bars shows 1 commit ahead of remote.

>     * Do you export any environment variables show names start with `GIT`?
> 
No, `export | grep GIT` shows nothing

>     * Do you have a global git config? What's in it?
>
just the  [user] section, 

```
[user]
        email = xxxxx@xxxx
        name = Simonluca Landi
```
 
>     * Add `GITSTATUS_LOG_LEVEL=DEBUG` to `¬/.zshrc`, type `exec zsh` and then look at `cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`. Any clues there?

From what i can see, nothing special here.

I strongly suspect that this issue is related to the naming of the remote branch, that is `remotes/origin/master` and not `origin/master` 

```
❯ git status
On branch master
Your branch is up to date with 'remotes/origin/master'.

nothing to commit, working tree clean

```

**Comment by romkatv** [comment]
Can you post complete instructions how to reproduce? Which commands do I need to run to create a Git repo that would result in an invalid Git status prompt?

(My guess is that the number you are seeing is the total number of commits.)

**Comment by simonlucalandi** [comment]
Now I sure that the issue is related to the remote branch named as "remotes/origin/master", because of a "weird" list of command that I issued on my local copy of the repo, that i finally managed to reproduce:

```
cd /tmp
git clone git@github.com:simonlucalandi/test.git
cd test
git checkout -b origin/master
git checkout --track origin/master
git checkout master
```
git status now shows "remotes/origin/master"

```
git status

On branch master
Your branch is up to date with 'remotes/origin/master'.

nothing to commit, working tree clean

```
now add/modify a file, commit and push

```
git add -A
git commit -m"added some files"
git push
```

the status bar now will show 1 commit ahead.
Add/modify more files, commit and push, and the status bar will show 2 commits ahead.

Btw, I made a clean clone of the repo from the remote github, referenced as "origin/master"

```
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

and now the status bar shows the correct info, so feel free to close the issue, due to my weird tracking of the "remote" repo.

**Comment by romkatv** [comment]
Thanks for the reproduction instructions. Here's a simplified and annotated version:

```zsh
git clone git@github.com:simonlucalandi/test.git
cd test
git reset --hard 'HEAD^'
```

Here's what `git status` says at this point:

```text
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

Powerlevel10k agrees with this and shows `master ⇣1`.

Now the crucial part: create a local branch named `origin/master`.

```zsh
git branch origin/master
```

Nothing has changed about branch `master` or remote `origin`. However, now reference `origin/master` is ambiguous. It can either mean `refs/heads/origin/master` or `refs/remotes/origin/master`. Powerlevel10k (incorrectly) applies the first interpretation while `git status` (correctly) applies the second.

`git status` output (note that it now refers to the remote as `remotes/origin/master`; the remote hasn't changed but it cannot be referred to as `origin/master` because it would be ambiguous):

```text
On branch master
Your branch is behind 'remotes/origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

Powerlevel10k: `master` (note that `⇣1` is gone because Powerlevel10k incorrectly thinks that `refs/heads/origin/master` is the tracking remote).

I've fixed this in https://github.com/romkatv/gitstatus/commit/c2e03bc50503cbc8536a4d32adb50f18ee0e1871 and eventually the fix will make its way into Powerlevel10k. I'm not rushing the release because I understand that you've created local branch `origin/master` by mistake without intending to do so. If you have repos exhibiting this issue, delete the ambiguously named branches.

```zsh
git branch -d origin/master
```
