### ISSUE TITLE
is it possible to truncate the same as fish shell (all directories truncated apart from the current directory) ?

### ISSUE THREAD

**Issue by 5c0tt-b0t** [romkatv/powerlevel10k#918]
Thank you so much for this, its incredible!!
I was wondering if you can truncate all but current directory and if so, would you be kind enough to let me know the values / possibly add it in the readme.
Thank you again!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_DIR_MAX_LENGTH`, set its value to `0` and restart zsh with `exec zsh`. This isn't exactly what you are asking for but it has a nice advantage that directory shortening is lossless -- you can recover the whole directory by copying it to the command line and pressing <kbd>Tab</kbd>.

If this is too verbose for you, set `POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=last` in addition or instead of the previous change. This will remove prefix of any Git repository or similar.

If this is still too verbose for your taste, set `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last`. This will give you what you are asking for -- the last segment only. This is a good choice if you are used to it.
