### ISSUE TITLE
Random b after custom segment text, and where do I find icons?

### ISSUE THREAD

**Issue by matthesinator** [romkatv/powerlevel10k#924]
Hi!

I'm trying to create a custom segment using this code:

        typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
            # =========================[ Line #1 ]=========================
            home_usage
            status                  # exit code of the last command

        [...]

        function` prompt_home_usage() {
		disk_usage=`df /home |awk "NR==2" |awk '{print$5}'`
		p10k segment -i "⭐" -t '%F{green}68%'
        }

but somehow there's always a ["b" after the text](https://imgur.com/cz6cO2P). How can I fix that? Thanks!

On a side-note: How/Where do I find icons like 'LOCK_ICON' shown in `p10k segment help`

**Comment by romkatv** [comment]
Since the text of the segment undergoes prompt `prompt_percent` expansion, you need to escape `%`.

Replace this:

```zsh
p10k segment -i "⭐" -t '%F{green}68%'
```

With this:

```zsh
p10k segment -i "⭐" -f green -t '68%%'
```

You can use `LOCK_ICON` like this:

```zsh
p10k segment -r -i LOCK_ICON
```

Note `-r`. See `p10k help segment` for the explanation.

You can see all symbolic icon names with `get_icon_names`.

Note that the custom segment you've added is very-very slow. It'll slow down prompt by 100% or so. This may be OK because powerlevel10k leaves some room for inefficient customizations but if you add a couple extra slow segments like that you'll notice prompt lag.

**Comment by matthesinator** [comment]
Thanks you!

You say it's very slow, how would I make it faster? Any pointers?

**Comment by romkatv** [comment]
You can make it faster by using zsh instead awk to process the output of df.
