### ISSUE TITLE
vsc settings not applying out of the box

### ISSUE THREAD

**Issue by ajetli** [romkatv/powerlevel10k#926]
I recently tried switching over from using Oh-My-Zsh to PowerLevel10k and I noticed that after running the default setup instructions `p10k configure`, I'm not able to see any git branch, status, other other git indicators on the LHS of my terminal despite having `vcs` configured to show up on the LHS:

```
  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # os_icon                 # os identifier
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )

...
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
     ...
```

Other segments seem to show up fine (e.g. dir, prompt_char, virtualenv, time, etc)

I wasn't using any "fancy custom zsh" settings before going through the setup doc here: https://github.com/romkatv/powerlevel10k#oh-my-zsh. I just used Oh-My-Zsh to set up a zsh theme for iTerm2.

The strange part is that very infrequently I do see the git branch name and status codes but they seem to disappear after I run some commands on the terminal (git pull, status, etc) (see below screenshot). So far I've uninstalled & re-installed p10k, restarted my laptop, and tried going through `p10k configure` a couple times with different settings. Let me know if there's any suggestions on what else I could try (or additional info I could provide), since I wasn't seeing this issue happening for other users after searching for a while.

![p10k_git_issue](https://user-images.githubusercontent.com/3355746/89109670-1d96e580-d3f8-11ea-854c-1a8d44125000.png)

**Comment by romkatv** [comment]
Add `GITSTATUS_LOG_LEVEL=DEBUG` to `~/.zshrc`, restart zsh with `exec zsh`, get to a point where Git status isn't showing in prompt when it should be and look at `tail -50 -- $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`. What does it say?

My guess is that says that your repo is using extensions that gitstatusd doesn't recognize. Uber's repo must be big, so perhaps split index, which involves "link" extension? Or something else?

**Comment by ajetli** [comment]
Thank you for the speedy response! This is happening both on our monorepo + some micro-repos that I'm working with. And yeah from the debug trace it seems like an error is being printed out related to "link" extension but I'm unsure what it means:

![p10k_issue_2](https://user-images.githubusercontent.com/3355746/89110792-25a85280-d403-11ea-87c2-af0af2019fed.png)

Any idea on workarounds for this? Appreciate your help.

**Comment by ajetli** [comment]
Confirmed that changing `--split-index=false` for my default git config seems to get rid of this issue! I'll see what other implications this would have on git performance when working locally. If I ever need to add it back as "true" does p10k not support this git configuration setting?

**Comment by romkatv** [comment]
"link" extension is used by [split index](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresplitIndex). [libgit2](https://libgit2.org/) cannot handle repos with split index enabled, and since gitstatusd relies on libgit2 for some of its features it cannot handle split index either.

There are a few things you can do:

1. Add support for split index to libgit2. Once done, I can add support to gitstatusd.
2. Disable split index on your local repos. This will slow down operations that write to the index. On a modern machine this is not noticeable for an index with 1M files but it may be too slow for your monorepo.
3. Disable gitstatusd with `POWERLEVEL9K_DISABLE_GITSTATUS=true`. This will make your prompt much slower and likely unusable when in the monorepo.

I've an item on my TODO list to add a decent fallback based on `git` command that would be automatically used when gitstatusd cannot open the repo. It's not very high on my priority list and I'm not working on it.

**Comment by ajetli** [comment]
Thanks for your help
