### ISSUE TITLE
How to add script for segment?

### ISSUE THREAD

**Issue by rediffusion** [romkatv/powerlevel10k#934]
Aloha! 🙂

 I have this **script**:

```
zsh_internet_signal(){
  local color
  local symbol="\uf7ba"
  if ifconfig en0 | grep inactive &> /dev/null; then
  color="%F{red}"
  else
  color="%F{blue}"
  fi
  echo -n "%{$color%}$symbol "
}
```

 I wonder how can I use it? Maybe I should add segment like this `custom_internet_signal` in a file called "**.p10k.zsh**" right here:
> POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=

 Please respond, cheers!

**Comment by romkatv** [comment]
I wouldn't recommend using this script because it'll make your prompt slow. If you want to an indicator when `en0` network interface is up, use `ip` segment.

1. Run `p10k configure` and select prompt style.
2. Open `~/.p10k.zsh` in a text editor.
3. Search for `# ip` and uncomment this line.
4. Search for `POWERLEVEL9K_IP_INTERFACE` and set the value to `en0`.

By default this segment is quite verbose. You can customize how it looks by changing `POWERLEVEL9K_IP_CONTENT_EXPANSION`. There are comments above this parameter that should help. If you set this parameter to an empty string, you'll only see an icon whenever `en0` is up.
