### ISSUE TITLE
Multiple options for single element type

### ISSUE THREAD

**Issue by o0-o** [romkatv/powerlevel10k#947]
Currently, options are applied globally per element. Is it possible to apply them individually?

For instance, if I want 2 time elements, one with the date and one with the time, is there any way to achieve this?

I can also imagine graying out old prompts so that only the current prompt is brightly colored.

I believe I can achieve this by copying the native time element code into a custom element and changing the parameter names, but just want to see if there's a built-in solution that I have overlooked.

**Comment by romkatv** [comment]
There is no builtin solution to this. I've a low priority item on my TODO list to support element tags, which would allow you to add `time:foo` and `time:bar` to `POWERLEVEL9K_{LEFT,RIGHT}_PROMPT_ELEMENTS` and then customize via `POWERLEVEL9K_TIME_FOO_*`, etc. I'm unlikely to ever implement this because `POWERLEVEL9K_*` parameters are already unreadable as they are. If I ever get around to adding support for customization via `zstyle`, this would be much easier since `zstyle` naturally supports hierarchical parameters.
