### ISSUE TITLE
Colors in Windows Terminal Look Bad

### ISSUE THREAD

**Issue by SturmB** [romkatv/powerlevel10k#960]
I've finally upgraded to WSL2 and, along with it, Windows Terminal (from my old wsltty/Cmder setup). I started from scratch with a new Ubuntu 20.04 installation.

Setting up Windows Terminal was easy enough, using the color schemes found at https://atomcorp.github.io/themes/.

When I have P10k running, however, the colors look incorrect. With the "BlueBerryPie" theme from the above link, the "Rainbow" prompt style looks like this:

![WindowsTerminal_YtAwy6q5DC](https://user-images.githubusercontent.com/6216224/90668745-88c92000-e21e-11ea-83b8-86f29b480db2.png)

I've highlighted the areas that don't look right. In wsltty, this isn't an issue. (I'm using a different color theme there, of course, because wsltty uses a completely different format for defining color themes.)

What do I need to do to fix these color issues?

**Comment by romkatv** [comment]
The issue with the right prompt is caused by a long-standing bug in Windows Terminal. A workaround is to not use segments with black background.

The issue on the left is caused by color 4 (blue) being being rendered with a different hue when it’s used as background or foreground. If Windows Terminal allows specifying these colors independently, you need to set them to the same value.

A more robust solution that will allow you to sidestep countless terminal bugs and will make your prompt look better is to use Lean prompt style.

**Comment by SturmB** [comment]
I think Microsoft may have updated Windows Terminal in the last few days, because now the colors look fine. No change on my part.

![WindowsTerminal_XJJ6ZbePHM](https://user-images.githubusercontent.com/6216224/91725374-a70f1400-eb6c-11ea-98f5-10a4dc664fec.png)

¯\_(ツ)_/¯

**Comment by romkatv** [comment]
I confirm that this bug in Windows Terminal has been fixed.
