### ISSUE TITLE
Add in Tony Lambiris' modifications?

### ISSUE THREAD

**Issue by Hebgbs** [romkatv/powerlevel10k#99]
From bhilburn's config showcase I encountered Tony's config which, aside from being _stupid_ complicated with the use of zplug, showed off a novel idea that I don't believe is implemented in bhilburn's work, or your own as I am using the same lines he has for this and it simply isn't working.

The mod in question adds in prompt separators which allow for custom icons to be used at the ends of prompts. The code in question;

```
P9K_LEFT_SEGMENT_SEPARATOR_ICON='▓▒░'
P9K_RIGHT_SEGMENT_SEPARATOR_ICON='░▒▓'
```

The result is what's shown here:
https://github.com/tonylambiris/dotfiles/raw/799a7fa53358a849c656cf27b07c5ebdfafa8d15/7F2ANZ.png

Any way this can be added as a p10k experimental feature? There are a multitude of other uses for this aside from fancy gradient fade effects. This would help me define _no_ ending to a segment whatsoever if I am ending with a clear background, since I'm either dumb and don't know how to make the entire prompt on either side clear, or I don't know how to make the separator of a specific segment clear.

Not that it matters, I'll ask about my issues in P9K Gitter but if the prompt separator icons were included I could just define to have no "Separator" for prompts that end with a segment which has a clear background.

**Comment by romkatv** [comment]
`P9K` configuration variables are used by the unstable development branch of Powerlevel9k called `next`. Powerlevel10k and the stable branch of Powerlevel9k use `POWERLEVEL9K` instead. However, just replacing `P9K` with `POWERLEVEL9K` isn't enough to port this config as there are several options that have different names in powerlevel9k/next.

I went through the Tony's config and ported all options one by one. Here's the resulting [Powerlevel10k config with Tony Lambiris's style](https://gist.github.com/romkatv/3e1c685ec83170ecb33267d5c7d3fe3f). Let me know whether it works for you. Make sure to use the latest version of Powerlevel10k.

@tonylambiris Is the attribution in that gist appropriate? Let me know if you want it changed or removed.

**Comment by romkatv** [comment]
Closing based on the resolution in https://gist.github.com/romkatv/3e1c685ec83170ecb33267d5c7d3fe3f.

**Comment by tonylambiris** [comment]
Looks fine to me, thanks for liking my theme! I haven't been as up-to-date as I'd like to with my zshrc settings, so hopefully it wasn't too much of a pain to port all the bits you wanted.

Cheers!

**Comment by romkatv** [comment]
> Looks fine to me, thanks for liking my theme!

Cheers :smile:

> I haven't been as up-to-date as I'd like to with my zshrc settings, so hopefully it wasn't too much of a pain to port all the bits you wanted.

No pain at all. The ported config yield prompt exactly identical to yours but 10+ times faster thanks to Powerlevel10k.

**Comment by tonylambiris** [comment]
@omkatv oh righteous, I'll have to check that out. Is the major difference due to zplug stuff? May be time to start monitoring what zsh/zplug is doing behind the scenes because I do notice it takes a minute to initialize (even after caching).

Thanks again, will be giving powerlevel10k a spin this weekend! :)

**Comment by romkatv** [comment]
@tonylambiris 

> Is the major difference due to zplug stuff?

No, it's Powerlevel10k being faster than Powerlevel9k.

> I do notice it takes a minute to initialize (even after caching).

Powerlevel10k is also relative slow to load but it's still [3 times faster](https://github.com/romkatv/powerlevel10k/#is-powerlevel10k-fast-to-load) than powerlevel9k/next that you are using right now.

When I say that Powerlevel10k is fast I mean prompt latency. It's the delay you get after every command you type. If you press and hold enter, Powerlevel9k cannot keep up. Powerlevel10k can, with any config you throw at it.

Powerlevel10k is backward compatible with powerlevel9k/master, so everyone on powerlevel9k/master can trivially replace their theme without changing any configuration options and they'll get the same prompt as before but much faster. I had to "port" your config because you are using options in the style of powerlevel9k/next that don't work with powerlevel9k/master and by extension don't work with Powerlevel10k. This porting mostly involved renaming `s/P9K/POWERLEVEL9K/`, plus using a few features from Powerlevel10k that don't exist in powerlevel9k/master.

If you want to try it, replace this line in your `~/.zshrc`:

```zsh
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme, from:github, at:next, as:theme
```

with this:

```zsh
zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme
```

And copy the content of [file-p10k-tony-lambiris-zsh](https://gist.github.com/romkatv/3e1c685ec83170ecb33267d5c7d3fe3f#file-p10k-tony-lambiris-zsh) into it.

**Comment by Syphdias** [comment]
> This porting mostly involved renaming `s/P9K/POWERLEVEL9K/`, plus using a few features from Powerlevel10k that don't exist in powerlevel9k/master.

Yep, but there are also some changes in naming consistency which can be found here: https://github.com/bhilburn/powerlevel9k/blob/next/powerlevel9k.zsh-theme#L84-L170
For example the variables for the `dir` segment:
```zsh
  # dir segment
  'P9K_HOME_ICON'                     'P9K_DIR_HOME_ICON'
  'P9K_HOME_SUB_ICON'                 'P9K_DIR_HOME_SUBFOLDER_ICON'
  'P9K_FOLDER_ICON'                   'P9K_DIR_DEFAULT_ICON'
  'P9K_LOCK_ICON'                     'P9K_DIR_NOT_WRITABLE_ICON'
  'P9K_ETC_ICON'                      'P9K_DIR_ETC_ICON'
  'P9K_SHORTEN_DIR_LENGTH'            'P9K_DIR_SHORTEN_LENGTH'
  'P9K_SHORTEN_STRATEGY'              'P9K_DIR_SHORTEN_STRATEGY'
  'P9K_SHORTEN_DELIMITER'             'P9K_DIR_SHORTEN_DELIMITER'
  'P9K_SHORTEN_FOLDER_MARKER'         'P9K_DIR_SHORTEN_FOLDER_MARKER'
  'P9K_HOME_FOLDER_ABBREVIATION'      'P9K_DIR_HOME_FOLDER_ABBREVIATION'
```

**Comment by romkatv** [comment]
Heads up that I've deleted `POWERLEVEL9K_RIGHT_SEGMENT_END_SEPARATOR` option. I'd originally implemented it for symmetry with `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR` but it makes little sense for right prompt. If you are using it, you'll need to switch to `POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL`. You'll get a warning if you forget.

You should also replace `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR` with `POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL`. The former is added unconditionally after the last left prompt line. People who don't enable `POWERLEVEL9K_PROMPT_ON_NEWLINE` use this parameter to set their prompt symbol. `POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL`, on the other hand, overrides the last delimiter of every left prompt line. This is a perfect fit for Tony-styled prompt.

I've updated https://gist.github.com/romkatv/3e1c685ec83170ecb33267d5c7d3fe3f with these changes. I've also simplified this config so that it's really short now. For example, you can now use `POWERLEVEL9K_BACKGROUND=239` to set the default background for all prompts. Or `POWERLEVEL9K_DIR_FOREGROUND=158` to set background for `dir` prompt. It's no longer necessary to enumerate all states as in `typeset POWERLEVEL9K_DIR_{DEFAULT,HOME,HOME_SUBFOLDER,ETC}_FOREGROUND=158`.
